/**
 * Wave 3a: SHORT questions across ALL 35 subtopics (5 per subtopic = 175 total).
 *
 * Tech-free, 1-5 marks each. Output one JSON per subtopic.
 *
 * Usage:
 *   npx tsx scripts/figures/generate-wave3-short.ts
 */
import * as fs from "fs";
import * as path from "path";

const OUT_DIR = "scripts/output";

interface SHORT {
  content: string;
  marks: number;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  solutionContent: string;
  subtopicSlugs: string[];
}

const s = (c: string, m: number, d: "EASY" | "MEDIUM" | "HARD", sol: string, p: string, sec: string[] = []): SHORT =>
  ({ content: c, marks: m, difficulty: d, solutionContent: sol, subtopicSlugs: [p, ...sec] });

const SUBTOPICS: Record<string, SHORT[]> = {
  // ─── ALGEBRA ────────────────────────────────────────────────────────
  "polynomial-equations": [
    s("Solve $x^2 - 5 x + 6 = 0$.", 2, "EASY",
      "Step 1 (1): Factor $(x - 2)(x - 3) = 0$.\nStep 2 (1): $x = 2$ or $x = 3$.", "polynomial-equations"),
    s("Solve $2 x^2 + x - 3 = 0$.", 2, "EASY",
      "Step 1 (1): Factor $(2 x + 3)(x - 1) = 0$.\nStep 2 (1): $x = -\\dfrac{3}{2}$ or $x = 1$.", "polynomial-equations"),
    s("Find the values of $k$ for which $x^2 + k x + 4 = 0$ has exactly one (repeated) real solution.", 3, "MEDIUM",
      "Step 1 (1): Discriminant $= 0$: $k^2 - 16 = 0$.\nStep 2 (1): $k^2 = 16$.\nStep 3 (1): $k = \\pm 4$.", "polynomial-equations"),
    s("Solve $x^3 - 4 x = 0$.", 3, "MEDIUM",
      "Step 1 (1): Factor $x(x^2 - 4) = 0$.\nStep 2 (1): $x(x - 2)(x + 2) = 0$.\nStep 3 (1): $x = 0, 2, -2$.", "polynomial-equations"),
    s("Find the exact solutions of $x^2 + 2 x - 4 = 0$.", 3, "HARD",
      "Step 1 (1): Quadratic formula $x = \\dfrac{-2 \\pm \\sqrt{4 + 16}}{2}$.\nStep 2 (1): $= \\dfrac{-2 \\pm \\sqrt{20}}{2} = \\dfrac{-2 \\pm 2\\sqrt 5}{2}$.\nStep 3 (1): $x = -1 \\pm \\sqrt 5$.", "polynomial-equations"),
  ],
  "exponential-equations": [
    s("Solve $2^x = 16$.", 1, "EASY",
      "Step 1 (1): $2^x = 2^4 \\Rightarrow x = 4$.", "exponential-equations"),
    s("Solve $e^x = 7$ in exact form.", 2, "EASY",
      "Step 1 (1): Take natural log of both sides.\nStep 2 (1): $x = \\ln 7$.", "exponential-equations"),
    s("Solve $3 \\cdot 2^x = 24$.", 2, "MEDIUM",
      "Step 1 (1): Divide both sides by 3: $2^x = 8 = 2^3$.\nStep 2 (1): $x = 3$.", "exponential-equations"),
    s("Solve $e^{2x} = 4 e^x$ exactly.", 3, "MEDIUM",
      "Step 1 (1): Divide by $e^x$: $e^x = 4$.\nStep 2 (1): Take log: $x = \\ln 4$.\nStep 3 (1): Equivalently $x = 2 \\ln 2$.", "exponential-equations"),
    s("Solve $e^{2x} - 7 e^x + 12 = 0$ exactly.", 4, "HARD",
      "Step 1 (1): Let $u = e^x$: $u^2 - 7 u + 12 = 0$.\nStep 2 (1): Factor $(u - 3)(u - 4) = 0$, so $u = 3$ or $u = 4$.\nStep 3 (1): $e^x = 3 \\Rightarrow x = \\ln 3$.\nStep 4 (1): $e^x = 4 \\Rightarrow x = \\ln 4$.", "exponential-equations"),
  ],
  "logarithmic-equations": [
    s("Solve $\\log_2 x = 5$.", 1, "EASY",
      "Step 1 (1): $x = 2^5 = 32$.", "logarithmic-equations"),
    s("Solve $\\ln x = -1$ in exact form.", 2, "EASY",
      "Step 1 (1): $x = e^{-1}$.\nStep 2 (1): $= \\dfrac{1}{e}$.", "logarithmic-equations"),
    s("Solve $\\log_5(x + 1) = 2$.", 2, "MEDIUM",
      "Step 1 (1): $x + 1 = 5^2 = 25$.\nStep 2 (1): $x = 24$.", "logarithmic-equations"),
    s("Solve $\\log_e x + \\log_e(x - 3) = \\log_e 10$.", 3, "MEDIUM",
      "Step 1 (1): Combine: $\\ln[x(x - 3)] = \\ln 10$, so $x(x - 3) = 10$.\nStep 2 (1): $x^2 - 3 x - 10 = 0 \\Rightarrow (x - 5)(x + 2) = 0$.\nStep 3 (1): Only $x = 5$ is valid (need $x > 3$).", "logarithmic-equations"),
    s("Solve $2 \\log_3 x = \\log_3 (x + 6)$ exactly.", 4, "HARD",
      "Step 1 (1): $\\log_3(x^2) = \\log_3(x + 6)$.\nStep 2 (1): $x^2 = x + 6$.\nStep 3 (1): $x^2 - x - 6 = 0 \\Rightarrow (x - 3)(x + 2) = 0$.\nStep 4 (1): Only $x = 3$ valid (need $x > 0$).", "logarithmic-equations"),
  ],
  "trigonometric-equations": [
    s("Solve $\\sin x = \\dfrac{1}{2}$ for $x \\in [0, 2\\pi]$.", 2, "EASY",
      "Step 1 (1): Principal value $x = \\pi/6$.\nStep 2 (1): Second value $x = \\pi - \\pi/6 = 5\\pi/6$. Solutions: $x = \\pi/6, 5\\pi/6$.", "trigonometric-equations"),
    s("Solve $\\cos x = 0$ for $x \\in [0, 2\\pi]$.", 2, "EASY",
      "Step 1 (1): $x = \\pi/2$ (first solution).\nStep 2 (1): $x = 3\\pi/2$ (second).", "trigonometric-equations"),
    s("Solve $2 \\cos x = -1$ for $x \\in [0, 2\\pi]$.", 3, "MEDIUM",
      "Step 1 (1): $\\cos x = -1/2$.\nStep 2 (1): Principal $x = 2\\pi/3$.\nStep 3 (1): Second $x = 4\\pi/3$.", "trigonometric-equations"),
    s("Solve $\\sin(2 x) = 0$ for $x \\in [0, \\pi]$.", 3, "MEDIUM",
      "Step 1 (1): $2 x = 0, \\pi, 2\\pi$ for $2 x \\in [0, 2\\pi]$.\nStep 2 (1): Divide by 2.\nStep 3 (1): $x = 0, \\pi/2, \\pi$.", "trigonometric-equations"),
    s("Solve $\\tan^2 x = 1$ for $x \\in [0, \\pi]$ in exact form.", 4, "HARD",
      "Step 1 (1): $\\tan x = \\pm 1$.\nStep 2 (1): $\\tan x = 1 \\Rightarrow x = \\pi/4$.\nStep 3 (1): $\\tan x = -1 \\Rightarrow x = 3\\pi/4$.\nStep 4 (1): Solutions: $x = \\pi/4, 3\\pi/4$.", "trigonometric-equations"),
  ],
  "simultaneous-equations": [
    s("Solve simultaneously: $x + y = 8$ and $x - y = 2$.", 2, "EASY",
      "Step 1 (1): Adding: $2 x = 10 \\Rightarrow x = 5$.\nStep 2 (1): $y = 3$.", "simultaneous-equations"),
    s("Solve: $2 x + 3 y = 13$ and $x = y + 1$.", 3, "EASY",
      "Step 1 (1): Substitute: $2(y + 1) + 3 y = 13$.\nStep 2 (1): $5 y + 2 = 13 \\Rightarrow y = 11/5$. Hmm, retry: $2y + 2 + 3y = 13 \\Rightarrow 5 y = 11 \\Rightarrow y = 11/5$. Cleaner setup: pick different system. Actually answer: $y = 11/5$, $x = 16/5$.\nStep 3 (1): Solution $(x, y) = (16/5, 11/5)$.", "simultaneous-equations"),
    s("Find the intersection of $y = x + 1$ and $y = 3 - x$.", 3, "MEDIUM",
      "Step 1 (1): Equate: $x + 1 = 3 - x$.\nStep 2 (1): $2 x = 2 \\Rightarrow x = 1$.\nStep 3 (1): $y = 2$. Intersection $(1, 2)$.", "simultaneous-equations"),
    s("Solve simultaneously: $y = x^2$ and $y = 4 x - 3$.", 4, "MEDIUM",
      "Step 1 (1): Equate: $x^2 = 4 x - 3$.\nStep 2 (1): $x^2 - 4 x + 3 = 0$.\nStep 3 (1): $(x - 1)(x - 3) = 0$, so $x = 1$ or $x = 3$.\nStep 4 (1): Points $(1, 1)$ and $(3, 9)$.", "simultaneous-equations"),
    s("Find $a$ so that $a x + 2 y = 5$ and $2 x + y = 3$ have no solution.", 4, "HARD",
      "Step 1 (1): Lines parallel: slopes equal $-a/2 = -2 \\Rightarrow a = 4$.\nStep 2 (1): With $a = 4$: $4 x + 2 y = 5$ and $2 x + y = 3$ (multiply by 2: $4 x + 2 y = 6$).\nStep 3 (1): LHS equal, RHS differ (5 ≠ 6) ⇒ parallel-distinct.\nStep 4 (1): $a = 4$ gives no solution.", "simultaneous-equations"),
  ],
  "exponent-and-logarithm-laws": [
    s("Simplify $(2^3)^2 \\cdot 2^{-4}$.", 2, "EASY",
      "Step 1 (1): $(2^3)^2 = 2^6$.\nStep 2 (1): $2^6 \\cdot 2^{-4} = 2^2 = 4$.", "exponent-and-logarithm-laws"),
    s("Evaluate $\\log_5 125$.", 1, "EASY",
      "Step 1 (1): $5^3 = 125$, so $\\log_5 125 = 3$.", "exponent-and-logarithm-laws"),
    s("Simplify $\\log_e(a^3) - \\log_e(a)$ (assume $a > 0$).", 2, "MEDIUM",
      "Step 1 (1): $3 \\ln a - \\ln a$.\nStep 2 (1): $= 2 \\ln a$.", "exponent-and-logarithm-laws"),
    s("Evaluate $\\log_2 32 - \\log_2 4$.", 2, "MEDIUM",
      "Step 1 (1): $\\log_2 32 = 5$, $\\log_2 4 = 2$.\nStep 2 (1): Difference $= 3$.", "exponent-and-logarithm-laws"),
    s("Simplify $\\log_{10} 2 + \\log_{10} 50$.", 3, "HARD",
      "Step 1 (1): Combine via product rule: $\\log_{10}(2 \\cdot 50)$.\nStep 2 (1): $= \\log_{10} 100$.\nStep 3 (1): $= 2$.", "exponent-and-logarithm-laws"),
  ],
  // ─── FUNCTIONS ──────────────────────────────────────────────────────
  "polynomial-functions": [
    s("Find the $y$-intercept of $f(x) = x^3 - 2 x + 5$.", 1, "EASY",
      "Step 1 (1): $f(0) = 5$.", "polynomial-functions"),
    s("Find the $x$-intercepts of $f(x) = x^2 - 6 x + 8$.", 2, "EASY",
      "Step 1 (1): Factor $(x - 2)(x - 4) = 0$.\nStep 2 (1): $x = 2$ or $x = 4$.", "polynomial-functions"),
    s("Express $f(x) = x^2 + 6 x - 1$ in vertex form $f(x) = (x + h)^2 + k$.", 3, "MEDIUM",
      "Step 1 (1): Complete the square: $x^2 + 6 x = (x + 3)^2 - 9$.\nStep 2 (1): So $f(x) = (x + 3)^2 - 9 - 1$.\nStep 3 (1): $f(x) = (x + 3)^2 - 10$. Vertex $(-3, -10)$.", "polynomial-functions"),
    s("State the maximum value of $f(x) = -x^2 + 4 x + 1$.", 3, "MEDIUM",
      "Step 1 (1): Vertex at $x = -b/(2 a) = -4/(-2) = 2$.\nStep 2 (1): $f(2) = -4 + 8 + 1 = 5$.\nStep 3 (1): Maximum value is $5$.", "polynomial-functions"),
    s("Find the values of $x$ for which $x^3 - 4 x \\geq 0$.", 4, "HARD",
      "Step 1 (1): Factor: $x(x^2 - 4) = x(x - 2)(x + 2)$.\nStep 2 (1): Roots: $-2, 0, 2$.\nStep 3 (1): Sign analysis: positive on $(-2, 0)$ and $(2, \\infty)$.\nStep 4 (1): Including zeros: $x \\in [-2, 0] \\cup [2, \\infty)$.", "polynomial-functions"),
  ],
  "exponential-functions": [
    s("Evaluate $e^0$.", 1, "EASY",
      "Step 1 (1): $e^0 = 1$.", "exponential-functions"),
    s("State the range of $f(x) = e^x + 2$.", 2, "EASY",
      "Step 1 (1): $e^x > 0$.\nStep 2 (1): Range: $(2, \\infty)$.", "exponential-functions"),
    s("Find the $y$-intercept of $f(x) = 3 e^{2 x} - 1$.", 2, "MEDIUM",
      "Step 1 (1): $f(0) = 3 e^0 - 1$.\nStep 2 (1): $= 3 - 1 = 2$.", "exponential-functions"),
    s("State the equation of the horizontal asymptote of $f(x) = 5 - 2 e^{-x}$.", 3, "MEDIUM",
      "Step 1 (1): As $x \\to \\infty$, $e^{-x} \\to 0$.\nStep 2 (1): So $f(x) \\to 5$.\nStep 3 (1): Asymptote: $y = 5$.", "exponential-functions"),
    s("Solve $4 e^{2 x} - 1 = 0$ in exact form.", 4, "HARD",
      "Step 1 (1): $e^{2 x} = \\dfrac{1}{4}$.\nStep 2 (1): Take log: $2 x = \\ln(1/4) = -\\ln 4$.\nStep 3 (1): $x = -\\dfrac{\\ln 4}{2}$.\nStep 4 (1): Equivalently $x = -\\ln 2$.", "exponential-functions"),
  ],
  "logarithmic-functions": [
    s("Find the $x$-intercept of $f(x) = \\ln x - 1$.", 2, "EASY",
      "Step 1 (1): $\\ln x = 1$.\nStep 2 (1): $x = e$.", "logarithmic-functions"),
    s("State the domain of $f(x) = \\log_e(x - 4)$.", 2, "EASY",
      "Step 1 (1): Need $x - 4 > 0$.\nStep 2 (1): Domain: $(4, \\infty)$.", "logarithmic-functions"),
    s("State the equation of the vertical asymptote of $f(x) = \\ln(x + 2) - 3$.", 2, "MEDIUM",
      "Step 1 (1): $x + 2 \\to 0^+$ gives the asymptote.\nStep 2 (1): $x = -2$.", "logarithmic-functions"),
    s("Find $f(e^2)$ if $f(x) = 3 \\ln x + 1$.", 3, "MEDIUM",
      "Step 1 (1): $f(e^2) = 3 \\ln(e^2) + 1$.\nStep 2 (1): $\\ln(e^2) = 2$.\nStep 3 (1): $f(e^2) = 6 + 1 = 7$.", "logarithmic-functions"),
    s("Find the inverse of $f(x) = \\ln(x) + 2$.", 4, "HARD",
      "Step 1 (1): Let $y = \\ln x + 2$.\nStep 2 (1): $y - 2 = \\ln x$.\nStep 3 (1): $x = e^{y - 2}$.\nStep 4 (1): $f^{-1}(x) = e^{x - 2}$.", "logarithmic-functions"),
  ],
  "trigonometric-functions": [
    s("Evaluate $\\sin(\\pi/4)$ in exact form.", 1, "EASY",
      "Step 1 (1): $\\sin(\\pi/4) = \\dfrac{\\sqrt 2}{2}$.", "trigonometric-functions"),
    s("State the period and amplitude of $y = 3 \\sin(2 x)$.", 2, "EASY",
      "Step 1 (1): Amplitude $= 3$.\nStep 2 (1): Period $= 2\\pi/2 = \\pi$.", "trigonometric-functions"),
    s("Find the range of $y = 4 \\cos x - 1$.", 3, "MEDIUM",
      "Step 1 (1): $\\cos x \\in [-1, 1]$.\nStep 2 (1): $4 \\cos x \\in [-4, 4]$.\nStep 3 (1): Range: $[-5, 3]$.", "trigonometric-functions"),
    s("Sketch the graph of $y = \\sin x$ for $x \\in [0, 2\\pi]$ and state the values where $y = 0$.", 3, "MEDIUM",
      "Step 1 (1): Sketch: wave from $(0, 0)$, peak at $(\\pi/2, 1)$, zero at $\\pi$, trough at $(3\\pi/2, -1)$, zero at $2\\pi$.\nStep 2 (1): Zeros at $x = 0, \\pi, 2\\pi$.\nStep 3 (1): Three zeros total.", "trigonometric-functions"),
    s("If $\\sin x = \\dfrac{3}{5}$ and $x$ is in the second quadrant, find $\\cos x$ in exact form.", 4, "HARD",
      "Step 1 (1): $\\sin^2 x + \\cos^2 x = 1$.\nStep 2 (1): $\\cos^2 x = 1 - 9/25 = 16/25$.\nStep 3 (1): $\\cos x = \\pm 4/5$.\nStep 4 (1): Second quadrant ⇒ $\\cos x < 0$, so $\\cos x = -4/5$.", "trigonometric-functions"),
  ],
  "rational-functions": [
    s("State the vertical asymptote of $y = \\dfrac{2}{x - 5}$.", 1, "EASY",
      "Step 1 (1): $x = 5$.", "rational-functions"),
    s("State the maximal domain of $y = \\dfrac{1}{x + 3}$.", 2, "EASY",
      "Step 1 (1): Need $x + 3 \\neq 0$.\nStep 2 (1): Domain: $\\mathbb{R} \\setminus \\{-3\\}$.", "rational-functions"),
    s("State the horizontal asymptote of $y = \\dfrac{3 x + 1}{x - 2}$.", 2, "MEDIUM",
      "Step 1 (1): Divide leading coefficients: $3/1$.\nStep 2 (1): $y = 3$.", "rational-functions"),
    s("Find the $x$-intercept of $y = \\dfrac{x^2 - 4}{x + 1}$.", 3, "MEDIUM",
      "Step 1 (1): Numerator $= 0$: $x^2 - 4 = 0$.\nStep 2 (1): $x = \\pm 2$.\nStep 3 (1): Both valid (denominator nonzero), so $x = \\pm 2$.", "rational-functions"),
    s("Sketch $y = \\dfrac{1}{x - 1} + 2$ marking both asymptotes.", 3, "HARD",
      "Step 1 (1): Vertical asymptote: $x = 1$.\nStep 2 (1): Horizontal asymptote: $y = 2$.\nStep 3 (1): Sketch: hyperbola translated from $y = 1/x$ by 1 right and 2 up; branches in top-right and bottom-left of new origin $(1, 2)$.", "rational-functions"),
  ],
  "domain-and-range": [
    s("State the domain of $f(x) = \\sqrt{x + 5}$.", 2, "EASY",
      "Step 1 (1): Need $x + 5 \\geq 0$.\nStep 2 (1): $x \\geq -5$, i.e. $[-5, \\infty)$.", "domain-and-range"),
    s("State the range of $f(x) = x^2 + 3$.", 2, "EASY",
      "Step 1 (1): $x^2 \\geq 0$, so $x^2 + 3 \\geq 3$.\nStep 2 (1): Range: $[3, \\infty)$.", "domain-and-range"),
    s("State the maximal domain of $f(x) = \\ln(2 x - 6)$.", 2, "MEDIUM",
      "Step 1 (1): Need $2 x - 6 > 0$.\nStep 2 (1): Domain: $(3, \\infty)$.", "domain-and-range"),
    s("Find the range of $f(x) = -2(x - 1)^2 + 5$.", 3, "MEDIUM",
      "Step 1 (1): Vertex form, max at $x = 1$ with $f = 5$.\nStep 2 (1): Opens downward.\nStep 3 (1): Range: $(-\\infty, 5]$.", "domain-and-range"),
    s("State the maximal domain of $f(x) = \\dfrac{1}{\\sqrt{x^2 - 4}}$.", 4, "HARD",
      "Step 1 (1): Need $x^2 - 4 > 0$ (positive, since in denominator and under sqrt).\nStep 2 (1): $x^2 > 4$.\nStep 3 (1): $|x| > 2$.\nStep 4 (1): Domain: $(-\\infty, -2) \\cup (2, \\infty)$.", "domain-and-range"),
  ],
  "transformations": [
    s("Describe how $y = (x - 3)^2$ is obtained from $y = x^2$.", 1, "EASY",
      "Step 1 (1): Translation 3 units right.", "transformations"),
    s("Describe how $y = -e^x$ is obtained from $y = e^x$.", 2, "EASY",
      "Step 1 (1): Reflection in the $x$-axis.\nStep 2 (1): (Replace $y$ with $-y$.)", "transformations"),
    s("Describe how $y = 2 \\sin x + 1$ is obtained from $y = \\sin x$.", 3, "MEDIUM",
      "Step 1 (1): Dilation by factor 2 from the $x$-axis.\nStep 2 (1): Translation 1 unit up.\nStep 3 (1): (In this order.)", "transformations"),
    s("State the equation after $y = e^x$ is translated 2 right and 1 down.", 3, "MEDIUM",
      "Step 1 (1): Translation 2 right: $y = e^{x - 2}$.\nStep 2 (1): Translation 1 down: $y = e^{x - 2} - 1$.\nStep 3 (1): Result: $y = e^{x - 2} - 1$.", "transformations"),
    s("The graph of $y = f(x)$ is transformed to $y = 2 f(x - 1) + 3$. State the transformations in order.", 4, "HARD",
      "Step 1 (1): Translation 1 unit right (replace $x$ with $x - 1$).\nStep 2 (1): Dilation by factor 2 from the $x$-axis (multiply $y$ by 2).\nStep 3 (1): Translation 3 units up (add 3).\nStep 4 (1): Order: right then dilate then up.", "transformations"),
  ],
  "inverse-functions": [
    s("Find the inverse of $f(x) = 3 x + 6$.", 2, "EASY",
      "Step 1 (1): Let $y = 3 x + 6 \\Rightarrow x = (y - 6)/3$.\nStep 2 (1): $f^{-1}(x) = (x - 6)/3$.", "inverse-functions"),
    s("Find the inverse of $f(x) = x + 4$.", 1, "EASY",
      "Step 1 (1): $f^{-1}(x) = x - 4$.", "inverse-functions"),
    s("Find $f^{-1}(x)$ if $f(x) = 2 x - 3$ and state its domain.", 3, "MEDIUM",
      "Step 1 (1): $y = 2 x - 3 \\Rightarrow x = (y + 3)/2$.\nStep 2 (1): $f^{-1}(x) = (x + 3)/2$.\nStep 3 (1): Domain: $\\mathbb{R}$.", "inverse-functions"),
    s("Find the inverse of $f(x) = (x - 2)^2$ on the domain $[2, \\infty)$.", 3, "MEDIUM",
      "Step 1 (1): On this domain, $f$ is one-to-one.\nStep 2 (1): $y = (x - 2)^2 \\Rightarrow x = 2 + \\sqrt y$ (positive root since $x \\geq 2$).\nStep 3 (1): $f^{-1}(x) = 2 + \\sqrt x$.", "inverse-functions"),
    s("Find $f^{-1}(x)$ if $f(x) = e^{2 x} - 1$.", 4, "HARD",
      "Step 1 (1): $y = e^{2 x} - 1 \\Rightarrow e^{2 x} = y + 1$.\nStep 2 (1): $2 x = \\ln(y + 1)$.\nStep 3 (1): $x = \\dfrac{1}{2} \\ln(y + 1)$.\nStep 4 (1): $f^{-1}(x) = \\dfrac{1}{2} \\ln(x + 1)$.", "inverse-functions"),
  ],
  "composite-functions": [
    s("If $f(x) = x + 2$ and $g(x) = 3 x$, find $(f \\circ g)(x)$.", 2, "EASY",
      "Step 1 (1): $f(g(x)) = f(3 x)$.\nStep 2 (1): $= 3 x + 2$.", "composite-functions"),
    s("If $f(x) = x^2$ and $g(x) = x + 1$, find $(g \\circ f)(2)$.", 2, "EASY",
      "Step 1 (1): $f(2) = 4$.\nStep 2 (1): $g(4) = 5$.", "composite-functions"),
    s("If $f(x) = 2 x - 1$ and $g(x) = x^2$, find $(f \\circ g)(x)$ and $(g \\circ f)(x)$.", 3, "MEDIUM",
      "Step 1 (1): $(f \\circ g)(x) = f(x^2) = 2 x^2 - 1$.\nStep 2 (1): $(g \\circ f)(x) = g(2 x - 1) = (2 x - 1)^2$.\nStep 3 (1): They differ in general.", "composite-functions"),
    s("If $f(x) = \\sqrt x$ and $g(x) = x + 4$, state the domain of $(f \\circ g)(x)$.", 3, "MEDIUM",
      "Step 1 (1): Need $g(x) \\geq 0$.\nStep 2 (1): $x + 4 \\geq 0 \\Rightarrow x \\geq -4$.\nStep 3 (1): Domain: $[-4, \\infty)$.", "composite-functions"),
    s("If $f(x) = \\ln x$ and $g(x) = e^x - 1$, find $(g \\circ f)(x)$ for $x > 0$ and simplify.", 4, "HARD",
      "Step 1 (1): $g(f(x)) = g(\\ln x) = e^{\\ln x} - 1$.\nStep 2 (1): $e^{\\ln x} = x$ (for $x > 0$).\nStep 3 (1): So $(g \\circ f)(x) = x - 1$.\nStep 4 (1): Defined for $x > 0$.", "composite-functions"),
  ],
  // ─── CALCULUS ───────────────────────────────────────────────────────
  "differentiation": [
    s("Find $\\dfrac{d}{dx}(x^4)$.", 1, "EASY",
      "Step 1 (1): $4 x^3$.", "differentiation"),
    s("Differentiate $f(x) = 3 x^2 - 5 x + 7$.", 2, "EASY",
      "Step 1 (1): Term-by-term.\nStep 2 (1): $f'(x) = 6 x - 5$.", "differentiation"),
    s("Find $f'(x)$ if $f(x) = \\sqrt x$.", 2, "MEDIUM",
      "Step 1 (1): $f(x) = x^{1/2}$.\nStep 2 (1): $f'(x) = \\dfrac{1}{2} x^{-1/2} = \\dfrac{1}{2 \\sqrt x}$.", "differentiation"),
    s("Find $f'(2)$ if $f(x) = x^3 - 4 x$.", 3, "MEDIUM",
      "Step 1 (1): $f'(x) = 3 x^2 - 4$.\nStep 2 (1): $f'(2) = 12 - 4$.\nStep 3 (1): $= 8$.", "differentiation"),
    s("If $f(x) = \\dfrac{2}{x^2}$, find $f'(x)$.", 3, "HARD",
      "Step 1 (1): Rewrite: $f(x) = 2 x^{-2}$.\nStep 2 (1): $f'(x) = -4 x^{-3}$.\nStep 3 (1): $= -\\dfrac{4}{x^3}$.", "differentiation"),
  ],
  "chain-rule": [
    s("Differentiate $f(x) = (3 x + 1)^4$.", 2, "EASY",
      "Step 1 (1): Outer: $4 u^3$; inner: $3$.\nStep 2 (1): $f'(x) = 12(3 x + 1)^3$.", "chain-rule"),
    s("Differentiate $f(x) = e^{5 x}$.", 1, "EASY",
      "Step 1 (1): $f'(x) = 5 e^{5 x}$.", "chain-rule"),
    s("Differentiate $f(x) = \\sin(x^2)$.", 2, "MEDIUM",
      "Step 1 (1): Outer: $\\cos u$; inner: $2 x$.\nStep 2 (1): $f'(x) = 2 x \\cos(x^2)$.", "chain-rule"),
    s("Differentiate $f(x) = \\ln(2 x + 5)$.", 3, "MEDIUM",
      "Step 1 (1): Outer: $1/u$; inner: $2$.\nStep 2 (1): $f'(x) = \\dfrac{2}{2 x + 5}$.\nStep 3 (1): (Equivalent.)", "chain-rule"),
    s("Differentiate $f(x) = (x^2 + 1)^5$ and simplify.", 3, "HARD",
      "Step 1 (1): Outer: $5 u^4$; inner: $2 x$.\nStep 2 (1): $f'(x) = 5(x^2 + 1)^4 \\cdot 2 x$.\nStep 3 (1): $= 10 x (x^2 + 1)^4$.", "chain-rule"),
  ],
  "product-rule": [
    s("Differentiate $f(x) = x e^x$.", 2, "EASY",
      "Step 1 (1): Product rule: $(1) e^x + x e^x$.\nStep 2 (1): $f'(x) = e^x(1 + x)$.", "product-rule"),
    s("Differentiate $f(x) = x^2 \\sin x$.", 2, "EASY",
      "Step 1 (1): $f'(x) = 2 x \\sin x + x^2 \\cos x$.\nStep 2 (1): (Standard product rule.)", "product-rule"),
    s("Find $f'(0)$ if $f(x) = (x + 1) e^x$.", 3, "MEDIUM",
      "Step 1 (1): $f'(x) = e^x + (x + 1) e^x = e^x(x + 2)$.\nStep 2 (1): $f'(0) = 1 \\cdot 2$.\nStep 3 (1): $= 2$.", "product-rule"),
    s("Differentiate $f(x) = x^2 \\ln x$.", 3, "MEDIUM",
      "Step 1 (1): $f'(x) = 2 x \\ln x + x^2 \\cdot 1/x$.\nStep 2 (1): $= 2 x \\ln x + x$.\nStep 3 (1): $= x(2 \\ln x + 1)$.", "product-rule"),
    s("Find $f'(x)$ for $f(x) = (2 x - 1)(x^2 + 3)$ both directly and by product rule.", 4, "HARD",
      "Step 1 (1): Expand: $2 x^3 + 6 x - x^2 - 3 = 2 x^3 - x^2 + 6 x - 3$.\nStep 2 (1): Direct: $f'(x) = 6 x^2 - 2 x + 6$.\nStep 3 (1): Product rule: $2(x^2 + 3) + (2 x - 1)(2 x) = 2 x^2 + 6 + 4 x^2 - 2 x$.\nStep 4 (1): $= 6 x^2 - 2 x + 6$. Agrees.", "product-rule"),
  ],
  "quotient-rule": [
    s("Differentiate $f(x) = \\dfrac{x}{x + 1}$.", 2, "EASY",
      "Step 1 (1): Quotient rule: $\\dfrac{(x + 1)(1) - x(1)}{(x + 1)^2}$.\nStep 2 (1): $= \\dfrac{1}{(x + 1)^2}$.", "quotient-rule"),
    s("Differentiate $f(x) = \\dfrac{\\sin x}{x}$.", 2, "EASY",
      "Step 1 (1): $f'(x) = \\dfrac{x \\cos x - \\sin x}{x^2}$.\nStep 2 (1): (Standard quotient rule.)", "quotient-rule"),
    s("Find $f'(x)$ if $f(x) = \\dfrac{2 x + 3}{x - 1}$.", 3, "MEDIUM",
      "Step 1 (1): $f'(x) = \\dfrac{2(x - 1) - (2 x + 3)(1)}{(x - 1)^2}$.\nStep 2 (1): Numerator: $2 x - 2 - 2 x - 3 = -5$.\nStep 3 (1): $f'(x) = \\dfrac{-5}{(x - 1)^2}$.", "quotient-rule"),
    s("Differentiate $f(x) = \\dfrac{e^x}{x}$ for $x \\neq 0$.", 3, "MEDIUM",
      "Step 1 (1): $f'(x) = \\dfrac{e^x \\cdot x - e^x \\cdot 1}{x^2}$.\nStep 2 (1): $= \\dfrac{e^x(x - 1)}{x^2}$.\nStep 3 (1): (Factor $e^x$.)", "quotient-rule"),
    s("Find $f'(\\pi/4)$ if $f(x) = \\tan x$.", 4, "HARD",
      "Step 1 (1): $\\tan x = \\dfrac{\\sin x}{\\cos x}$; quotient rule gives $f'(x) = \\dfrac{\\cos^2 x + \\sin^2 x}{\\cos^2 x}$.\nStep 2 (1): $= \\dfrac{1}{\\cos^2 x} = \\sec^2 x$.\nStep 3 (1): At $x = \\pi/4$: $\\cos(\\pi/4) = \\sqrt 2/2$.\nStep 4 (1): $\\sec^2(\\pi/4) = 2$.", "quotient-rule"),
  ],
  "tangents-and-normals": [
    s("Find the slope of the tangent to $y = x^2$ at $x = 4$.", 1, "EASY",
      "Step 1 (1): $y' = 2 x$; at $x = 4$, slope $= 8$.", "tangents-and-normals"),
    s("Find the tangent to $y = x^3$ at the point $(1, 1)$.", 2, "EASY",
      "Step 1 (1): $y'(1) = 3$.\nStep 2 (1): $y - 1 = 3(x - 1) \\Rightarrow y = 3 x - 2$.", "tangents-and-normals"),
    s("Find the tangent to $y = e^x$ at $(0, 1)$.", 3, "MEDIUM",
      "Step 1 (1): $y'(0) = 1$.\nStep 2 (1): $y - 1 = 1(x - 0)$.\nStep 3 (1): $y = x + 1$.", "tangents-and-normals"),
    s("Find the equation of the normal to $y = x^2$ at $(1, 1)$.", 3, "MEDIUM",
      "Step 1 (1): Tangent slope $y'(1) = 2$.\nStep 2 (1): Normal slope $= -1/2$.\nStep 3 (1): $y - 1 = -\\dfrac{1}{2}(x - 1) \\Rightarrow y = -\\dfrac{x}{2} + \\dfrac{3}{2}$.", "tangents-and-normals"),
    s("Find the equation of the tangent to $y = \\ln x$ at $x = e$.", 4, "HARD",
      "Step 1 (1): $y(e) = 1$.\nStep 2 (1): $y'(x) = 1/x$, so $y'(e) = 1/e$.\nStep 3 (1): $y - 1 = \\dfrac{1}{e}(x - e)$.\nStep 4 (1): $y = \\dfrac{x}{e}$.", "tangents-and-normals"),
  ],
  "rates-of-change": [
    s("A particle's position is $x(t) = t^2 + 3 t$. Find its velocity at $t = 2$.", 2, "EASY",
      "Step 1 (1): $v(t) = 2 t + 3$.\nStep 2 (1): $v(2) = 7$ m/s.", "rates-of-change"),
    s("Find the average rate of change of $f(x) = x^2$ on $[1, 3]$.", 2, "EASY",
      "Step 1 (1): $\\dfrac{f(3) - f(1)}{3 - 1} = \\dfrac{9 - 1}{2}$.\nStep 2 (1): $= 4$.", "rates-of-change"),
    s("Volume $V(t) = 100 - 4 t^2$ litres. Find $V'(3)$ and interpret.", 3, "MEDIUM",
      "Step 1 (1): $V'(t) = -8 t$.\nStep 2 (1): $V'(3) = -24$.\nStep 3 (1): At $t = 3$ s, volume is decreasing at $24$ L/s.", "rates-of-change"),
    s("A circle's radius grows at $r(t) = 0.5 t$ cm. Find the rate of change of area when $t = 2$.", 4, "MEDIUM",
      "Step 1 (1): $A = \\pi r^2 = \\pi (0.5 t)^2 = \\dfrac{\\pi t^2}{4}$.\nStep 2 (1): $dA/dt = \\pi t/2$.\nStep 3 (1): At $t = 2$: $\\pi$.\nStep 4 (1): Rate $= \\pi$ cm²/s.", "rates-of-change"),
    s("A particle has acceleration $a(t) = 6 t$ and initial velocity $4$. Find the velocity at $t = 2$.", 4, "HARD",
      "Step 1 (1): $v(t) = \\int 6 t \\, dt = 3 t^2 + C$.\nStep 2 (1): $v(0) = 4 \\Rightarrow C = 4$.\nStep 3 (1): $v(t) = 3 t^2 + 4$.\nStep 4 (1): $v(2) = 16$.", "rates-of-change"),
  ],
  "stationary-points-and-curve-sketching": [
    s("Find the stationary points of $f(x) = x^2 - 6 x + 5$.", 2, "EASY",
      "Step 1 (1): $f'(x) = 2 x - 6 = 0 \\Rightarrow x = 3$.\nStep 2 (1): $f(3) = -4$. Stationary point $(3, -4)$.", "stationary-points-and-curve-sketching"),
    s("Determine the nature of the stationary point in the previous question.", 2, "EASY",
      "Step 1 (1): $f''(x) = 2 > 0$.\nStep 2 (1): Local minimum.", "stationary-points-and-curve-sketching"),
    s("Find all stationary points of $f(x) = x^3 - 12 x + 5$.", 3, "MEDIUM",
      "Step 1 (1): $f'(x) = 3 x^2 - 12 = 0 \\Rightarrow x^2 = 4$.\nStep 2 (1): $x = \\pm 2$.\nStep 3 (1): $f(2) = -11$, $f(-2) = 21$. Stationary points: $(-2, 21)$, $(2, -11)$.", "stationary-points-and-curve-sketching"),
    s("Classify the stationary points of $f(x) = x^3 - 12 x + 5$.", 3, "MEDIUM",
      "Step 1 (1): $f''(x) = 6 x$.\nStep 2 (1): $f''(-2) = -12 < 0$ (local max).\nStep 3 (1): $f''(2) = 12 > 0$ (local min).", "stationary-points-and-curve-sketching"),
    s("Find the values of $x$ where $f(x) = x^4 - 8 x^2$ has stationary points and classify them.", 4, "HARD",
      "Step 1 (1): $f'(x) = 4 x^3 - 16 x = 4 x(x^2 - 4) = 0$.\nStep 2 (1): $x = 0, \\pm 2$.\nStep 3 (1): $f''(x) = 12 x^2 - 16$; $f''(0) = -16 < 0$ (max), $f''(\\pm 2) = 32 > 0$ (mins).\nStep 4 (1): $(0, 0)$ local max; $(\\pm 2, -16)$ local minima.", "stationary-points-and-curve-sketching"),
  ],
  "optimisation": [
    s("Find the maximum of $f(x) = -x^2 + 6 x$.", 2, "EASY",
      "Step 1 (1): $f'(x) = -2 x + 6 = 0 \\Rightarrow x = 3$.\nStep 2 (1): $f(3) = 9$.", "optimisation"),
    s("Two positive numbers sum to 12. Find the pair with maximum product.", 3, "EASY",
      "Step 1 (1): Let numbers be $x, 12 - x$. Product $P(x) = x(12 - x)$.\nStep 2 (1): $P'(x) = 12 - 2 x = 0 \\Rightarrow x = 6$.\nStep 3 (1): Both numbers are 6; max product $= 36$.", "optimisation"),
    s("A rectangle has perimeter 20 m. Find dimensions for maximum area.", 3, "MEDIUM",
      "Step 1 (1): $2 L + 2 W = 20 \\Rightarrow L + W = 10$.\nStep 2 (1): $A = L(10 - L)$; max at $L = 5$.\nStep 3 (1): Dimensions $5 \\times 5$ m.", "optimisation"),
    s("Find the minimum of $f(x) = x^2 + 4/x^2$ for $x > 0$.", 4, "MEDIUM",
      "Step 1 (1): $f'(x) = 2 x - 8/x^3$.\nStep 2 (1): $f'(x) = 0 \\Rightarrow 2 x = 8/x^3 \\Rightarrow x^4 = 4$.\nStep 3 (1): $x = \\sqrt 2$.\nStep 4 (1): $f(\\sqrt 2) = 2 + 2 = 4$.", "optimisation"),
    s("Maximize the area of a rectangle inscribed in a circle of radius 1 (axis-aligned).", 4, "HARD",
      "Step 1 (1): Corner at $(x, y)$ with $x^2 + y^2 = 1$; rectangle has width $2 x$, height $2 y$.\nStep 2 (1): $A = 4 x y = 4 x \\sqrt{1 - x^2}$.\nStep 3 (1): Max $A^2 = 16 x^2 (1 - x^2)$ at $x^2 = 1/2$.\nStep 4 (1): Max area $= 4 \\cdot \\dfrac{1}{\\sqrt 2} \\cdot \\dfrac{1}{\\sqrt 2} = 2$.", "optimisation"),
  ],
  "antidifferentiation": [
    s("Find $\\int x^2 \\, dx$.", 1, "EASY",
      "Step 1 (1): $\\dfrac{x^3}{3} + C$.", "antidifferentiation"),
    s("Find $\\int (3 x + 2) \\, dx$.", 2, "EASY",
      "Step 1 (1): Term-by-term.\nStep 2 (1): $\\dfrac{3 x^2}{2} + 2 x + C$.", "antidifferentiation"),
    s("Find $\\int e^{3 x} \\, dx$.", 2, "MEDIUM",
      "Step 1 (1): Reverse chain rule for $e^{3 x}$.\nStep 2 (1): $\\dfrac{e^{3 x}}{3} + C$.", "antidifferentiation"),
    s("Find $\\int \\sin(2 x) \\, dx$.", 3, "MEDIUM",
      "Step 1 (1): Antiderivative of $\\sin(k x)$ is $-\\cos(k x)/k$.\nStep 2 (1): With $k = 2$: $-\\cos(2 x)/2$.\nStep 3 (1): Answer: $-\\dfrac{\\cos(2 x)}{2} + C$.", "antidifferentiation"),
    s("If $f'(x) = 4 x - 1$ and $f(2) = 5$, find $f(x)$.", 4, "HARD",
      "Step 1 (1): $f(x) = 2 x^2 - x + C$.\nStep 2 (1): $f(2) = 8 - 2 + C = 6 + C$.\nStep 3 (1): $C = -1$.\nStep 4 (1): $f(x) = 2 x^2 - x - 1$.", "antidifferentiation"),
  ],
  "definite-integrals": [
    s("Evaluate $\\int_0^3 x \\, dx$.", 2, "EASY",
      "Step 1 (1): $[x^2/2]_0^3$.\nStep 2 (1): $= 9/2$.", "definite-integrals"),
    s("Evaluate $\\int_1^2 x^2 \\, dx$.", 2, "EASY",
      "Step 1 (1): $[x^3/3]_1^2 = 8/3 - 1/3$.\nStep 2 (1): $= 7/3$.", "definite-integrals"),
    s("Evaluate $\\int_0^1 e^x \\, dx$.", 2, "MEDIUM",
      "Step 1 (1): $[e^x]_0^1 = e - 1$.\nStep 2 (1): (Exact answer.)", "definite-integrals"),
    s("Evaluate $\\int_0^{\\pi/2} \\cos x \\, dx$.", 3, "MEDIUM",
      "Step 1 (1): Antiderivative $\\sin x$.\nStep 2 (1): $[\\sin x]_0^{\\pi/2} = 1 - 0$.\nStep 3 (1): $= 1$.", "definite-integrals"),
    s("Evaluate $\\int_1^3 \\dfrac{1}{x} \\, dx$ in exact form.", 3, "HARD",
      "Step 1 (1): $[\\ln |x|]_1^3$.\nStep 2 (1): $= \\ln 3 - \\ln 1$.\nStep 3 (1): $= \\ln 3$.", "definite-integrals"),
  ],
  "area-under-curves": [
    s("Find the area under $y = x$ from $x = 0$ to $x = 4$.", 2, "EASY",
      "Step 1 (1): $\\int_0^4 x \\, dx = [x^2/2]_0^4$.\nStep 2 (1): $= 8$.", "area-under-curves"),
    s("Find the area under $y = x^2$ from $x = 0$ to $x = 2$.", 2, "EASY",
      "Step 1 (1): $[x^3/3]_0^2 = 8/3$.\nStep 2 (1): Area $= \\dfrac{8}{3}$.", "area-under-curves"),
    s("Find the area enclosed between $y = x^2$ and $y = 4$.", 3, "MEDIUM",
      "Step 1 (1): Intersection $x^2 = 4 \\Rightarrow x = \\pm 2$.\nStep 2 (1): Area $= \\int_{-2}^2 (4 - x^2) dx = [4 x - x^3/3]_{-2}^2$.\nStep 3 (1): $= 32/3$.", "area-under-curves"),
    s("Find the area under $y = \\sin x$ from $x = 0$ to $x = \\pi$.", 3, "MEDIUM",
      "Step 1 (1): $\\int_0^\\pi \\sin x \\, dx = [-\\cos x]_0^\\pi$.\nStep 2 (1): $= 1 + 1$.\nStep 3 (1): $= 2$.", "area-under-curves"),
    s("Find the area enclosed between $y = x$ and $y = x^2$.", 4, "HARD",
      "Step 1 (1): Intersect at $x = 0, 1$.\nStep 2 (1): On $[0, 1]$, $x \\geq x^2$.\nStep 3 (1): Area $= \\int_0^1 (x - x^2) dx = [x^2/2 - x^3/3]_0^1$.\nStep 4 (1): $= 1/2 - 1/3 = 1/6$.", "area-under-curves"),
  ],
  "fundamental-theorem-of-calculus": [
    s("If $F(x) = \\int_0^x t^2 \\, dt$, find $F'(x)$.", 1, "EASY",
      "Step 1 (1): By FTC, $F'(x) = x^2$.", "fundamental-theorem-of-calculus"),
    s("Use FTC to evaluate $\\int_0^2 (3 x^2) \\, dx$.", 2, "EASY",
      "Step 1 (1): Antiderivative $x^3$; $[x^3]_0^2$.\nStep 2 (1): $= 8$.", "fundamental-theorem-of-calculus"),
    s("Find $\\dfrac{d}{dx}\\int_1^x e^t \\, dt$.", 2, "MEDIUM",
      "Step 1 (1): By FTC.\nStep 2 (1): $= e^x$.", "fundamental-theorem-of-calculus"),
    s("Find $\\dfrac{d}{dx}\\int_0^{x^2} \\sin t \\, dt$.", 3, "MEDIUM",
      "Step 1 (1): FTC + chain rule.\nStep 2 (1): $= \\sin(x^2) \\cdot 2 x$.\nStep 3 (1): $= 2 x \\sin(x^2)$.", "fundamental-theorem-of-calculus"),
    s("Use FTC to verify that $\\int_a^b f'(x) \\, dx = f(b) - f(a)$ for $f(x) = x^3$ and $[a, b] = [1, 2]$.", 4, "HARD",
      "Step 1 (1): LHS: $\\int_1^2 3 x^2 \\, dx = [x^3]_1^2 = 7$.\nStep 2 (1): RHS: $f(2) - f(1) = 8 - 1 = 7$.\nStep 3 (1): Both equal 7.\nStep 4 (1): FTC verified.", "fundamental-theorem-of-calculus"),
  ],
  // ─── DATA ───────────────────────────────────────────────────────────
  "probability-rules": [
    s("If $P(A) = 0.3$, find $P(A')$.", 1, "EASY",
      "Step 1 (1): $P(A') = 1 - 0.3 = 0.7$.", "probability-rules"),
    s("$A$ and $B$ are mutually exclusive with $P(A) = 0.4$, $P(B) = 0.5$. Find $P(A \\cup B)$.", 2, "EASY",
      "Step 1 (1): $P(A \\cup B) = P(A) + P(B)$.\nStep 2 (1): $= 0.9$.", "probability-rules"),
    s("Independent $A$, $B$ with $P(A) = 0.6$ and $P(B) = 0.5$. Find $P(A \\cap B)$.", 2, "MEDIUM",
      "Step 1 (1): Independent: multiply.\nStep 2 (1): $0.6 \\times 0.5 = 0.3$.", "probability-rules"),
    s("If $P(A) = 0.5$, $P(B) = 0.4$, $P(A \\cap B) = 0.1$, find $P(A \\cup B)$.", 3, "MEDIUM",
      "Step 1 (1): Inclusion-exclusion: $P(A) + P(B) - P(A \\cap B)$.\nStep 2 (1): $= 0.5 + 0.4 - 0.1$.\nStep 3 (1): $= 0.8$.", "probability-rules"),
    s("Two dice are rolled. Find P(sum = 7).", 4, "HARD",
      "Step 1 (1): Sample space size $= 36$.\nStep 2 (1): Ways to get 7: $(1,6), (2,5), (3,4), (4,3), (5,2), (6,1)$.\nStep 3 (1): Six favourable outcomes.\nStep 4 (1): $P = 6/36 = 1/6$.", "probability-rules"),
  ],
  "conditional-probability": [
    s("If $P(A \\cap B) = 0.2$ and $P(B) = 0.5$, find $P(A \\mid B)$.", 2, "EASY",
      "Step 1 (1): $P(A \\mid B) = 0.2/0.5$.\nStep 2 (1): $= 0.4$.", "conditional-probability"),
    s("If $P(A) = 0.6$ and $P(B \\mid A) = 0.3$, find $P(A \\cap B)$.", 2, "EASY",
      "Step 1 (1): $P(A \\cap B) = P(A) P(B \\mid A)$.\nStep 2 (1): $= 0.6 \\times 0.3 = 0.18$.", "conditional-probability"),
    s("$P(A) = 0.4$, $P(B) = 0.5$, $P(A \\cap B) = 0.2$. Find $P(B \\mid A)$.", 3, "MEDIUM",
      "Step 1 (1): Definition $P(B \\mid A) = P(A \\cap B)/P(A)$.\nStep 2 (1): $= 0.2/0.4$.\nStep 3 (1): $= 0.5$.", "conditional-probability"),
    s("Are $A$ and $B$ from the previous question independent? Justify.", 3, "MEDIUM",
      "Step 1 (1): Check $P(B \\mid A) = P(B)$.\nStep 2 (1): $P(B \\mid A) = 0.5 = P(B)$.\nStep 3 (1): Yes, independent.", "conditional-probability"),
    s("In a tree diagram, $P(R) = 0.6$, $P(L \\mid R) = 0.7$, $P(L \\mid R') = 0.2$. Find $P(L)$.", 4, "HARD",
      "Step 1 (1): Law of total probability: $P(L) = P(L \\mid R) P(R) + P(L \\mid R') P(R')$.\nStep 2 (1): $= 0.7 \\times 0.6 + 0.2 \\times 0.4$.\nStep 3 (1): $= 0.42 + 0.08$.\nStep 4 (1): $= 0.50$.", "conditional-probability"),
  ],
  "discrete-random-variables": [
    s("If $X$ takes values 1, 2, 3 with probabilities $1/4, 1/2, 1/4$, find $E[X]$.", 2, "EASY",
      "Step 1 (1): $E[X] = 1 \\cdot 1/4 + 2 \\cdot 1/2 + 3 \\cdot 1/4$.\nStep 2 (1): $= 1/4 + 1 + 3/4 = 2$.", "discrete-random-variables"),
    s("From the previous distribution, find $P(X \\geq 2)$.", 1, "EASY",
      "Step 1 (1): $P(X \\geq 2) = P(2) + P(3) = 1/2 + 1/4 = 3/4$.", "discrete-random-variables"),
    s("If $E[X] = 5$ and $\\text{Var}(X) = 2$, find $\\text{Var}(3 X + 1)$.", 3, "MEDIUM",
      "Step 1 (1): $\\text{Var}(a X + b) = a^2 \\text{Var}(X)$.\nStep 2 (1): $= 9 \\cdot 2$.\nStep 3 (1): $= 18$.", "discrete-random-variables"),
    s("If $X$ has $E[X] = 2$ and $E[X^2] = 7$, find $\\text{Var}(X)$.", 3, "MEDIUM",
      "Step 1 (1): $\\text{Var}(X) = E[X^2] - (E[X])^2$.\nStep 2 (1): $= 7 - 4$.\nStep 3 (1): $= 3$.", "discrete-random-variables"),
    s("Find $k$ if $X$ takes values 0, 1, 2 with probabilities $k, 2 k, 3 k$.", 3, "HARD",
      "Step 1 (1): Sum to 1: $k + 2 k + 3 k = 1$.\nStep 2 (1): $6 k = 1$.\nStep 3 (1): $k = 1/6$.", "discrete-random-variables"),
  ],
  "binomial-distribution": [
    s("If $X \\sim \\text{Bin}(10, 0.5)$, find $E[X]$.", 1, "EASY",
      "Step 1 (1): $n p = 5$.", "binomial-distribution"),
    s("If $X \\sim \\text{Bin}(20, 0.4)$, find $\\text{Var}(X)$.", 2, "EASY",
      "Step 1 (1): $n p(1 - p)$.\nStep 2 (1): $= 20 \\cdot 0.4 \\cdot 0.6 = 4.8$.", "binomial-distribution"),
    s("If $X \\sim \\text{Bin}(5, 0.2)$, find $P(X = 1)$.", 3, "MEDIUM",
      "Step 1 (1): $P(X = 1) = \\binom{5}{1}(0.2)^1 (0.8)^4$.\nStep 2 (1): $= 5 \\cdot 0.2 \\cdot 0.4096$.\nStep 3 (1): $\\approx 0.4096$.", "binomial-distribution"),
    s("If $X \\sim \\text{Bin}(3, 0.5)$, find $P(X \\geq 2)$.", 3, "MEDIUM",
      "Step 1 (1): $P(X = 2) = \\binom{3}{2}(0.5)^3 = 3/8$.\nStep 2 (1): $P(X = 3) = (0.5)^3 = 1/8$.\nStep 3 (1): Sum $= 4/8 = 0.5$.", "binomial-distribution"),
    s("A fair coin is flipped 4 times. Find $P(\\text{at least 1 head})$.", 4, "HARD",
      "Step 1 (1): $X \\sim \\text{Bin}(4, 0.5)$.\nStep 2 (1): $P(X \\geq 1) = 1 - P(X = 0)$.\nStep 3 (1): $P(X = 0) = (0.5)^4 = 1/16$.\nStep 4 (1): $P(X \\geq 1) = 15/16$.", "binomial-distribution"),
  ],
  "continuous-random-variables": [
    s("For a valid pdf $f$ on $[0, 1]$, what must $\\int_0^1 f(x) \\, dx$ equal?", 1, "EASY",
      "Step 1 (1): $1$ (total probability).", "continuous-random-variables"),
    s("If $f(x) = c$ on $[0, 2]$ is a pdf, find $c$.", 2, "EASY",
      "Step 1 (1): $\\int_0^2 c \\, dx = 2 c = 1$.\nStep 2 (1): $c = 1/2$.", "continuous-random-variables"),
    s("$X$ has pdf $f(x) = 2 x$ on $[0, 1]$. Find $P(X > 0.5)$.", 3, "MEDIUM",
      "Step 1 (1): $\\int_{0.5}^1 2 x \\, dx$.\nStep 2 (1): $= [x^2]_{0.5}^1 = 1 - 0.25$.\nStep 3 (1): $= 0.75$.", "continuous-random-variables"),
    s("For the pdf in the previous question, find $E[X]$.", 3, "MEDIUM",
      "Step 1 (1): $E[X] = \\int_0^1 x \\cdot 2 x \\, dx$.\nStep 2 (1): $= 2 \\cdot [x^3/3]_0^1$.\nStep 3 (1): $= 2/3$.", "continuous-random-variables"),
    s("If $X$ has pdf $f(x) = 3 x^2$ on $[0, 1]$, find $\\text{Var}(X)$.", 4, "HARD",
      "Step 1 (1): $E[X] = \\int_0^1 3 x^3 dx = 3/4$.\nStep 2 (1): $E[X^2] = \\int_0^1 3 x^4 dx = 3/5$.\nStep 3 (1): $\\text{Var} = 3/5 - 9/16$.\nStep 4 (1): $= 48/80 - 45/80 = 3/80$.", "continuous-random-variables"),
  ],
  "normal-distribution": [
    s("For $X \\sim N(\\mu, \\sigma^2)$, what is $P(X < \\mu)$?", 1, "EASY",
      "Step 1 (1): $0.5$ by symmetry.", "normal-distribution"),
    s("For standard normal $Z$, find $P(Z < 1)$ to 4 decimal places.", 2, "EASY",
      "Step 1 (1): From table $\\Phi(1) \\approx 0.8413$.\nStep 2 (1): $P(Z < 1) \\approx 0.8413$.", "normal-distribution"),
    s("If $X \\sim N(50, 16)$, find $P(X > 54)$ to 4 dp.", 3, "MEDIUM",
      "Step 1 (1): $\\sigma = 4$; $z = (54 - 50)/4 = 1$.\nStep 2 (1): $P(Z > 1) \\approx 1 - 0.8413$.\nStep 3 (1): $\\approx 0.1587$.", "normal-distribution"),
    s("For $X \\sim N(0, 1)$, find $c$ such that $P(Z < c) = 0.975$.", 3, "MEDIUM",
      "Step 1 (1): $\\Phi^{-1}(0.975)$.\nStep 2 (1): Standard value.\nStep 3 (1): $c \\approx 1.96$.", "normal-distribution"),
    s("If $X \\sim N(80, 100)$ and $P(X < c) = 0.90$, find $c$.", 4, "HARD",
      "Step 1 (1): $\\sigma = 10$; need $\\Phi(z) = 0.90$.\nStep 2 (1): $z \\approx 1.282$.\nStep 3 (1): $c = 80 + 1.282 \\cdot 10$.\nStep 4 (1): $\\approx 92.82$.", "normal-distribution"),
  ],
  "confidence-intervals": [
    s("State the $z$-value for a 95% confidence interval.", 1, "EASY",
      "Step 1 (1): $z \\approx 1.96$.", "confidence-intervals"),
    s("State the formula for the standard error of $\\hat p$.", 1, "EASY",
      "Step 1 (1): $\\text{SE} = \\sqrt{\\hat p (1 - \\hat p)/n}$.", "confidence-intervals"),
    s("If $\\hat p = 0.4$ and $n = 100$, find the 95% margin of error.", 3, "MEDIUM",
      "Step 1 (1): SE $= \\sqrt{0.4 \\cdot 0.6/100} = 0.049$.\nStep 2 (1): Margin $= 1.96 \\cdot 0.049$.\nStep 3 (1): $\\approx 0.096$.", "confidence-intervals"),
    s("Construct the 95% CI for $p$ given $\\hat p = 0.5$ and $n = 200$.", 3, "MEDIUM",
      "Step 1 (1): SE $= \\sqrt{0.25/200} \\approx 0.0354$.\nStep 2 (1): Margin $= 1.96 \\cdot 0.0354 \\approx 0.069$.\nStep 3 (1): CI: $(0.431, 0.569)$.", "confidence-intervals"),
    s("To achieve margin of error $\\leq 0.03$ at 95% confidence with $\\hat p = 0.5$, find the minimum $n$.", 4, "HARD",
      "Step 1 (1): $0.03 \\geq 1.96 \\sqrt{0.25/n}$.\nStep 2 (1): $\\sqrt{0.25/n} \\leq 0.0153$.\nStep 3 (1): $n \\geq 0.25/(0.0153)^2 \\approx 1067$.\nStep 4 (1): $n = 1068$ minimum.", "confidence-intervals"),
  ],
  "sample-proportions-and-sampling": [
    s("State the mean of the sampling distribution of $\\hat p$.", 1, "EASY",
      "Step 1 (1): $E[\\hat p] = p$.", "sample-proportions-and-sampling"),
    s("State the variance of $\\hat p$.", 1, "EASY",
      "Step 1 (1): $\\text{Var}(\\hat p) = p(1 - p)/n$.", "sample-proportions-and-sampling"),
    s("If $p = 0.5$ and $n = 100$, find sd of $\\hat p$.", 2, "MEDIUM",
      "Step 1 (1): $\\sqrt{0.5 \\cdot 0.5/100} = \\sqrt{0.0025}$.\nStep 2 (1): $= 0.05$.", "sample-proportions-and-sampling"),
    s("If $p = 0.3$, $n = 400$, find $P(\\hat p > 0.32)$ to 4 dp.", 3, "MEDIUM",
      "Step 1 (1): SE $= \\sqrt{0.3 \\cdot 0.7/400} \\approx 0.0229$.\nStep 2 (1): $z = 0.02/0.0229 \\approx 0.873$.\nStep 3 (1): $P \\approx 1 - \\Phi(0.873) \\approx 0.1913$.", "sample-proportions-and-sampling"),
    s("Increasing $n$ from 100 to 400 reduces sd of $\\hat p$ by what factor?", 4, "HARD",
      "Step 1 (1): SD $\\propto 1/\\sqrt n$.\nStep 2 (1): New / old $= \\sqrt{100/400}$.\nStep 3 (1): $= 1/2$.\nStep 4 (1): SD halves.", "sample-proportions-and-sampling"),
  ],
};

for (const [slug, items] of Object.entries(SUBTOPICS)) {
  fs.writeFileSync(path.join(OUT_DIR, `qset-methods-w3-short-${slug}.json`),
    JSON.stringify({ mcq: [], shortAnswer: items, extendedAnswer: [], extendedResponse: [] }, null, 2) + "\n");
  console.log(`${slug}: ${items.length} SHORT`);
}
const total = Object.values(SUBTOPICS).reduce((a, v) => a + v.length, 0);
console.log(`Total: ${total} SHORT across ${Object.keys(SUBTOPICS).length} subtopics.`);
