/**
 * Wave 2, batch 1: Algebra MCQ.
 *
 * 8 MCQ per subtopic across the 6 Algebra subtopics = 48 MCQ total.
 * Output: one JSON per subtopic.
 *
 * Usage:
 *   npx tsx scripts/figures/generate-algebra-mcq.ts
 */

import * as fs from "fs";
import * as path from "path";

const OUT_DIR = "scripts/output";

interface MCQ {
  content: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: "A" | "B" | "C" | "D";
  marks: number;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  solutionContent: string;
  subtopicSlugs: string[];
}

const m = (
  content: string,
  options: [string, string, string, string],
  correct: "A" | "B" | "C" | "D",
  difficulty: "EASY" | "MEDIUM" | "HARD",
  solution: string,
  primarySlug: string,
  secondarySlugs: string[] = [],
): MCQ => ({
  content,
  optionA: options[0],
  optionB: options[1],
  optionC: options[2],
  optionD: options[3],
  correctOption: correct,
  marks: 1,
  difficulty,
  solutionContent: solution,
  subtopicSlugs: [primarySlug, ...secondarySlugs],
});

const SUBTOPICS: Record<string, MCQ[]> = {
  "polynomial-equations": [
    m("The solutions of $x^2 - 5x + 6 = 0$ are:",
      ["$x = -2$ and $x = -3$", "$x = 2$ and $x = 3$", "$x = -1$ and $x = 6$", "$x = 1$ and $x = -6$"],
      "B", "EASY",
      "Factor: $(x - 2)(x - 3) = 0 \\Rightarrow x = 2$ or $x = 3$. **Answer: B**",
      "polynomial-equations"),
    m("The solutions of $2x^2 + 7x - 4 = 0$ are:",
      ["$x = 4$ and $x = -\\dfrac{1}{2}$", "$x = -4$ and $x = \\dfrac{1}{2}$", "$x = 2$ and $x = -\\dfrac{1}{4}$", "$x = -2$ and $x = \\dfrac{1}{4}$"],
      "B", "EASY",
      "Factor: $(2x - 1)(x + 4) = 0 \\Rightarrow x = \\dfrac{1}{2}$ or $x = -4$. **Answer: B**",
      "polynomial-equations"),
    m("Solve $3(x - 2) = 5x + 4$.",
      ["$x = -5$", "$x = 5$", "$x = -\\dfrac{1}{2}$", "$x = \\dfrac{1}{2}$"],
      "A", "EASY",
      "$3x - 6 = 5x + 4 \\Rightarrow -10 = 2x \\Rightarrow x = -5$. **Answer: A**",
      "polynomial-equations"),
    m("The values of $k$ for which $x^2 - 4x + k = 0$ has two distinct real solutions are:",
      ["$k > 4$", "$k < 4$", "$k = 4$", "$k \\geq 4$"],
      "B", "MEDIUM",
      "Discriminant $> 0$: $16 - 4 k > 0 \\Rightarrow k < 4$. **Answer: B**",
      "polynomial-equations"),
    m("If $x = 2$ is a solution of $x^3 - a x^2 + 4 = 0$, then $a$ equals:",
      ["$2$", "$3$", "$4$", "$6$"],
      "B", "MEDIUM",
      "Substitute $x = 2$: $8 - 4 a + 4 = 0 \\Rightarrow a = 3$. **Answer: B**",
      "polynomial-equations"),
    m("The number of real solutions of $x^4 - 5 x^2 + 4 = 0$ is:",
      ["$1$", "$2$", "$3$", "$4$"],
      "D", "MEDIUM",
      "Let $u = x^2$: $u^2 - 5 u + 4 = 0 \\Rightarrow (u - 1)(u - 4) = 0$, so $u = 1$ or $u = 4$. Then $x = \\pm 1, \\pm 2$: four real solutions. **Answer: D**",
      "polynomial-equations"),
    m("The exact solutions of $x^2 - 2 x - 4 = 0$ are:",
      ["$x = 1 \\pm \\sqrt{5}$", "$x = -1 \\pm \\sqrt{5}$", "$x = 1 \\pm \\sqrt{3}$", "$x = 2 \\pm \\sqrt{5}$"],
      "A", "HARD",
      "Quadratic formula: $x = \\dfrac{2 \\pm \\sqrt{4 + 16}}{2} = \\dfrac{2 \\pm 2\\sqrt{5}}{2} = 1 \\pm \\sqrt{5}$. **Answer: A**",
      "polynomial-equations"),
    m("If $x^3 - 3 x^2 + a x - 2 = 0$ has $x = 1$ as a root, then $a$ equals:",
      ["$-4$", "$2$", "$4$", "$6$"],
      "C", "HARD",
      "Substitute $x = 1$: $1 - 3 + a - 2 = 0 \\Rightarrow a = 4$. **Answer: C**",
      "polynomial-equations"),
  ],

  "exponential-equations": [
    m("Solve $2^x = 8$.",
      ["$x = 2$", "$x = 3$", "$x = 4$", "$x = 6$"],
      "B", "EASY",
      "$2^x = 2^3 \\Rightarrow x = 3$. **Answer: B**",
      "exponential-equations"),
    m("Solve $e^x = 5$, exact form.",
      ["$x = \\dfrac{1}{5}$", "$x = \\log_{10} 5$", "$x = \\ln 5$", "$x = 5 e$"],
      "C", "EASY",
      "Take natural log: $x = \\ln 5$. **Answer: C**",
      "exponential-equations"),
    m("Solve $3^{x + 1} = 27$.",
      ["$x = 1$", "$x = 2$", "$x = 3$", "$x = 4$"],
      "B", "EASY",
      "$3^{x + 1} = 3^3 \\Rightarrow x + 1 = 3 \\Rightarrow x = 2$. **Answer: B**",
      "exponential-equations"),
    m("Solve $e^{2 x} = 9$ exactly.",
      ["$x = \\ln 9$", "$x = 2 \\ln 3$", "$x = \\ln 3$", "$x = \\dfrac{\\ln 3}{2}$"],
      "C", "MEDIUM",
      "$2 x = \\ln 9 = 2 \\ln 3 \\Rightarrow x = \\ln 3$. **Answer: C**",
      "exponential-equations"),
    m("The solutions of $e^{2 x} - 5 e^x + 6 = 0$ are:",
      ["$x = 2, 3$", "$x = \\ln 2, \\ln 3$", "$x = \\ln 5, \\ln 6$", "$x = -\\ln 2, -\\ln 3$"],
      "B", "MEDIUM",
      "Let $u = e^x$: $u^2 - 5 u + 6 = (u - 2)(u - 3) = 0 \\Rightarrow u = 2$ or $u = 3$, so $x = \\ln 2$ or $x = \\ln 3$. **Answer: B**",
      "exponential-equations"),
    m("Solve $4^x = 5$ correct to 3 decimal places.",
      ["$1.161$", "$1.250$", "$1.609$", "$2.322$"],
      "A", "MEDIUM",
      "$x = \\dfrac{\\ln 5}{\\ln 4} = \\dfrac{1.6094}{1.3863} \\approx 1.161$. **Answer: A**",
      "exponential-equations"),
    m("Solve $2^x \\cdot 5^x = 100$ exactly.",
      ["$x = 2$", "$x = \\log_{10} 50$", "$x = \\log_2 100$", "$x = \\dfrac{\\ln 100}{\\ln 7}$"],
      "A", "HARD",
      "$2^x \\cdot 5^x = (2 \\cdot 5)^x = 10^x = 100 \\Rightarrow x = 2$. **Answer: A**",
      "exponential-equations"),
    m("The smallest integer $n$ such that $(0.5)^n < 0.01$ is:",
      ["$5$", "$6$", "$7$", "$8$"],
      "C", "HARD",
      "$n > \\dfrac{\\ln 0.01}{\\ln 0.5} = \\dfrac{-4.605}{-0.693} \\approx 6.64$, so $n = 7$. **Answer: C**",
      "exponential-equations"),
  ],

  "logarithmic-equations": [
    m("Solve $\\log_2 x = 3$.",
      ["$x = 6$", "$x = 8$", "$x = 9$", "$x = 16$"],
      "B", "EASY",
      "$x = 2^3 = 8$. **Answer: B**",
      "logarithmic-equations"),
    m("Solve $\\ln x = 2$, exact form.",
      ["$x = 2 e$", "$x = e^2$", "$x = 2 \\ln e$", "$x = \\dfrac{1}{e^2}$"],
      "B", "EASY",
      "$x = e^2$. **Answer: B**",
      "logarithmic-equations"),
    m("Solve $\\log_{10}(x - 1) = 1$.",
      ["$x = 9$", "$x = 10$", "$x = 11$", "$x = 100$"],
      "C", "EASY",
      "$x - 1 = 10 \\Rightarrow x = 11$. **Answer: C**",
      "logarithmic-equations"),
    m("Solve $\\log_2 x + \\log_2(x - 2) = 3$.",
      ["$x = 2$", "$x = 4$", "$x = 8$", "$x = -2, 4$"],
      "B", "MEDIUM",
      "$\\log_2[x(x - 2)] = 3 \\Rightarrow x^2 - 2 x = 8 \\Rightarrow (x - 4)(x + 2) = 0$. Only $x = 4$ is valid ($x > 2$). **Answer: B**",
      "logarithmic-equations"),
    m("Solve $\\log_3 x = -2$ exactly.",
      ["$x = -9$", "$x = -\\dfrac{1}{9}$", "$x = \\dfrac{1}{9}$", "$x = 9$"],
      "C", "MEDIUM",
      "$x = 3^{-2} = \\dfrac{1}{9}$. **Answer: C**",
      "logarithmic-equations"),
    m("Solve $\\log_e(x + 1) = 2$ exactly.",
      ["$x = e^2 - 1$", "$x = 2 e - 1$", "$x = e^2 + 1$", "$x = \\dfrac{e}{2}$"],
      "A", "MEDIUM",
      "$x + 1 = e^2 \\Rightarrow x = e^2 - 1$. **Answer: A**",
      "logarithmic-equations"),
    m("The number of real solutions of $\\log_2(x^2) = 4$ is:",
      ["$0$", "$1$", "$2$", "infinitely many"],
      "C", "HARD",
      "$x^2 = 16 \\Rightarrow x = \\pm 4$. Both are valid ($x \\neq 0$). **Answer: C**",
      "logarithmic-equations"),
    m("Solve $\\log_4 x = \\log_2 3$ exactly.",
      ["$x = 9$", "$x = 12$", "$x = 3$", "$x = 6$"],
      "A", "HARD",
      "$\\log_4 x = \\log_2 3$ converts to $\\dfrac{\\log_2 x}{2} = \\log_2 3 \\Rightarrow \\log_2 x = 2 \\log_2 3 = \\log_2 9 \\Rightarrow x = 9$. **Answer: A**",
      "logarithmic-equations"),
  ],

  "trigonometric-equations": [
    m("The solutions of $\\sin x = 0$ for $x \\in [0, 2\\pi]$ are:",
      ["$0, \\pi$", "$0, \\dfrac{\\pi}{2}, \\pi$", "$0, \\pi, 2\\pi$", "$\\dfrac{\\pi}{2}, \\pi, \\dfrac{3\\pi}{2}$"],
      "C", "EASY",
      "$\\sin x = 0$ at $x = 0, \\pi, 2\\pi$. **Answer: C**",
      "trigonometric-equations"),
    m("If $\\cos x = \\dfrac{1}{2}$ and $x \\in [0, \\pi]$, then $x$ equals:",
      ["$\\dfrac{\\pi}{6}$", "$\\dfrac{\\pi}{4}$", "$\\dfrac{\\pi}{3}$", "$\\dfrac{\\pi}{2}$"],
      "C", "EASY",
      "$\\cos(\\pi/3) = 1/2$. **Answer: C**",
      "trigonometric-equations"),
    m("Solve $\\tan x = 1$ for the principal value in $\\left[-\\dfrac{\\pi}{2}, \\dfrac{\\pi}{2}\\right]$.",
      ["$x = -\\dfrac{\\pi}{4}$", "$x = \\dfrac{\\pi}{4}$", "$x = \\dfrac{\\pi}{2}$", "$x = \\dfrac{3\\pi}{4}$"],
      "B", "EASY",
      "$\\tan(\\pi/4) = 1$. **Answer: B**",
      "trigonometric-equations"),
    m("The solutions of $2 \\sin x = 1$ for $x \\in [0, 2\\pi]$ are:",
      ["$\\dfrac{\\pi}{6}, \\dfrac{5\\pi}{6}$", "$\\dfrac{\\pi}{3}, \\dfrac{2\\pi}{3}$", "$\\dfrac{\\pi}{4}, \\dfrac{3\\pi}{4}$", "$\\dfrac{\\pi}{6}, \\dfrac{7\\pi}{6}$"],
      "A", "MEDIUM",
      "$\\sin x = 1/2 \\Rightarrow x = \\pi/6$ or $\\pi - \\pi/6 = 5\\pi/6$. **Answer: A**",
      "trigonometric-equations"),
    m("The number of solutions of $\\sin(2 x) = 0$ for $x \\in [0, \\pi]$ is:",
      ["$1$", "$2$", "$3$", "$4$"],
      "C", "MEDIUM",
      "$2 x = 0, \\pi, 2\\pi$ for $2x \\in [0, 2\\pi]$, giving $x = 0, \\pi/2, \\pi$: three solutions. **Answer: C**",
      "trigonometric-equations"),
    m("Solve $\\cos\\left(x - \\dfrac{\\pi}{4}\\right) = \\dfrac{1}{2}$ for the smallest positive $x$.",
      ["$x = \\dfrac{\\pi}{12}$", "$x = \\dfrac{5\\pi}{12}$", "$x = \\dfrac{7\\pi}{12}$", "$x = \\dfrac{11\\pi}{12}$"],
      "C", "MEDIUM",
      "$x - \\dfrac{\\pi}{4} = \\pm \\dfrac{\\pi}{3} + 2 k \\pi$. Smallest positive $x$: $x = \\dfrac{\\pi}{4} + \\dfrac{\\pi}{3} = \\dfrac{7\\pi}{12}$. **Answer: C**",
      "trigonometric-equations"),
    m("The solutions of $2 \\sin^2 x - \\sin x - 1 = 0$ in $[0, 2\\pi]$ are:",
      ["$\\dfrac{\\pi}{2}$ only", "$\\dfrac{\\pi}{2}, \\dfrac{7\\pi}{6}, \\dfrac{11\\pi}{6}$", "$0, \\pi$", "$\\dfrac{7\\pi}{6}, \\dfrac{11\\pi}{6}$"],
      "B", "HARD",
      "Let $u = \\sin x$: $2 u^2 - u - 1 = (2 u + 1)(u - 1) = 0 \\Rightarrow u = 1$ or $u = -\\dfrac{1}{2}$. $\\sin x = 1 \\Rightarrow x = \\pi/2$; $\\sin x = -1/2 \\Rightarrow x = 7\\pi/6$ or $11\\pi/6$. **Answer: B**",
      "trigonometric-equations"),
    m("How many solutions does $\\tan x = 2$ have in $[0, 2\\pi]$?",
      ["$0$", "$1$", "$2$", "$3$"],
      "C", "HARD",
      "$\\tan x$ has period $\\pi$ and crosses each value once per period. In $[0, 2\\pi]$ there are 2 solutions. **Answer: C**",
      "trigonometric-equations"),
  ],

  "simultaneous-equations": [
    m("Solve the system $x + y = 5$, $x - y = 1$.",
      ["$x = 2, y = 3$", "$x = 3, y = 2$", "$x = 4, y = 1$", "$x = 1, y = 4$"],
      "B", "EASY",
      "Adding: $2 x = 6 \\Rightarrow x = 3$. Then $y = 2$. **Answer: B**",
      "simultaneous-equations"),
    m("Solve $2 x + 3 y = 14$, $x = 2 y$.",
      ["$x = 4, y = 2$", "$x = 6, y = 1$", "$x = 2, y = 4$", "$x = 8, y = -1$"],
      "A", "EASY",
      "Substitute $x = 2 y$: $2(2 y) + 3 y = 14 \\Rightarrow 7 y = 14 \\Rightarrow y = 2$, $x = 4$. **Answer: A**",
      "simultaneous-equations"),
    m("For the system $3 x + 2 y = 7$, $6 x + 4 y = 14$, the solution is:",
      ["unique: $x = 1, y = 2$", "infinitely many", "no solution", "$x = 0, y = 0$"],
      "B", "EASY",
      "Second equation is 2× first — they're equivalent, so infinitely many solutions. **Answer: B**",
      "simultaneous-equations"),
    m("Solve $y = x^2$ and $y = x + 2$ simultaneously.",
      ["$(-1, 1)$ and $(2, 4)$", "$(1, 1)$ and $(2, 4)$", "$(-1, 1)$ and $(-2, 4)$", "$(0, 0)$ and $(2, 4)$"],
      "A", "MEDIUM",
      "Set equal: $x^2 = x + 2 \\Rightarrow x^2 - x - 2 = (x - 2)(x + 1) = 0 \\Rightarrow x = 2$ or $x = -1$. **Answer: A**",
      "simultaneous-equations"),
    m("For what value of $k$ does $2 x + y = 3$, $4 x + 2 y = k$ have infinitely many solutions?",
      ["$k = 3$", "$k = 6$", "$k = 9$", "$k = 12$"],
      "B", "MEDIUM",
      "Need second equation to be 2× first: $k = 6$. **Answer: B**",
      "simultaneous-equations"),
    m("For what value of $k$ does $x + 2 y = 4$, $2 x + k y = 9$ have NO solution?",
      ["$k = -4$", "$k = 4$", "$k = 8$", "$k = 2$"],
      "B", "MEDIUM",
      "Parallel-but-distinct requires equal slope ratios but unequal constants: $\\dfrac{2}{1} = \\dfrac{k}{2} \\Rightarrow k = 4$. Check the constants: $\\dfrac{9}{4} \\neq 2$ ✓, so lines are parallel but distinct. **Answer: B**",
      "simultaneous-equations"),
    m("Solve $y = 2 x$ and $y = x^2 - 3$ simultaneously.",
      ["$(-1, -2)$ and $(3, 6)$", "$(1, 2)$ and $(-3, -6)$", "$(0, 0)$ and $(2, 4)$", "$(-1, -2)$ and $(-3, -6)$"],
      "A", "HARD",
      "$x^2 - 3 = 2 x \\Rightarrow x^2 - 2 x - 3 = (x - 3)(x + 1) = 0$. So $x = 3, y = 6$ or $x = -1, y = -2$. **Answer: A**",
      "simultaneous-equations"),
    m("The system $x + y + z = 6$, $x - y + z = 2$, $x + y - z = 0$ has solution:",
      ["$(1, 2, 3)$", "$(2, 1, 3)$", "$(1, 3, 2)$", "$(3, 2, 1)$"],
      "A", "HARD",
      "Eq1 − Eq2: $2 y = 4 \\Rightarrow y = 2$. Eq1 − Eq3: $2 z = 6 \\Rightarrow z = 3$. Eq1: $x = 6 - 2 - 3 = 1$. So $(1, 2, 3)$. **Answer: A**",
      "simultaneous-equations"),
  ],

  "exponent-and-logarithm-laws": [
    m("$2^3 \\cdot 2^5$ equals:",
      ["$2^{15}$", "$4^8$", "$2^8$", "$4^{15}$"],
      "C", "EASY",
      "Add exponents: $2^{3 + 5} = 2^8$. **Answer: C**",
      "exponent-and-logarithm-laws"),
    m("$\\log_2 8$ equals:",
      ["$2$", "$3$", "$4$", "$8$"],
      "B", "EASY",
      "$2^3 = 8$, so $\\log_2 8 = 3$. **Answer: B**",
      "exponent-and-logarithm-laws"),
    m("$\\log(M N)$ equals:",
      ["$\\log M \\cdot \\log N$", "$\\dfrac{\\log M}{\\log N}$", "$\\log M + \\log N$", "$\\log M - \\log N$"],
      "C", "EASY",
      "Product rule: $\\log(M N) = \\log M + \\log N$. **Answer: C**",
      "exponent-and-logarithm-laws"),
    m("Simplify $\\dfrac{(2^3)^2 \\cdot 2^{-1}}{2^4}$.",
      ["$2$", "$\\dfrac{1}{2}$", "$4$", "$8$"],
      "A", "MEDIUM",
      "$\\dfrac{2^6 \\cdot 2^{-1}}{2^4} = \\dfrac{2^5}{2^4} = 2$. **Answer: A**",
      "exponent-and-logarithm-laws"),
    m("$\\log_3 27 - \\log_3 9$ equals:",
      ["$\\dfrac{1}{2}$", "$1$", "$2$", "$3$"],
      "B", "MEDIUM",
      "$\\log_3 27 = 3$, $\\log_3 9 = 2$, difference $= 1$. **Answer: B**",
      "exponent-and-logarithm-laws"),
    m("Express $\\log_4 64$ as a base-2 log.",
      ["$\\log_2 64$", "$\\log_2 8$", "$3$", "$2$"],
      "C", "MEDIUM",
      "$\\log_4 64 = \\dfrac{\\log_2 64}{\\log_2 4} = \\dfrac{6}{2} = 3$. **Answer: C**",
      "exponent-and-logarithm-laws"),
    m("If $\\log_a x^3 - \\log_a x^2 = \\log_a x$, this identity holds because:",
      ["Quotient rule and power rule combined", "Sum-of-logs is log-of-product", "Difference of squares", "Pythagoras"],
      "A", "HARD",
      "$\\log_a x^3 - \\log_a x^2 = \\log_a(x^3 / x^2) = \\log_a x$. Uses both rules. **Answer: A**",
      "exponent-and-logarithm-laws"),
    m("$2 \\log_{10} 5 + \\log_{10} 4$ equals:",
      ["$1$", "$2$", "$\\log_{10} 14$", "$\\log_{10} 25 \\cdot 4$"],
      "B", "HARD",
      "$2 \\log 5 = \\log 25$. $\\log 25 + \\log 4 = \\log 100 = 2$. **Answer: B**",
      "exponent-and-logarithm-laws"),
  ],
};

for (const [slug, mcqs] of Object.entries(SUBTOPICS)) {
  const output = {
    mcq: mcqs,
    shortAnswer: [],
    extendedAnswer: [],
    extendedResponse: [],
  };
  const file = path.join(OUT_DIR, `qset-methods-w2-${slug}.json`);
  fs.writeFileSync(file, JSON.stringify(output, null, 2) + "\n");
  console.log(`${file}: ${mcqs.length} MCQ`);
}

const totalMcq = Object.values(SUBTOPICS).reduce((s, arr) => s + arr.length, 0);
console.log(`Total: ${totalMcq} MCQ across ${Object.keys(SUBTOPICS).length} subtopics.`);
