/**
 * Wave 4a: MCQ top-up to 20 per subtopic.
 * 12 new MCQ per subtopic across all 35 subtopics = 420 new MCQ.
 * Distinct from Wave 2 content.
 */
import * as fs from "fs";
import * as path from "path";

const OUT_DIR = "scripts/output";
interface MCQ {
  content: string; optionA: string; optionB: string; optionC: string; optionD: string;
  correctOption: "A" | "B" | "C" | "D"; marks: number; difficulty: "EASY" | "MEDIUM" | "HARD";
  solutionContent: string; subtopicSlugs: string[];
}
const m = (c: string, o: [string, string, string, string], k: "A" | "B" | "C" | "D",
  d: "EASY" | "MEDIUM" | "HARD", s: string, p: string): MCQ =>
  ({ content: c, optionA: o[0], optionB: o[1], optionC: o[2], optionD: o[3], correctOption: k, marks: 1, difficulty: d, solutionContent: s, subtopicSlugs: [p] });

const SUBS: Record<string, MCQ[]> = {
  "polynomial-equations": [
    m("Solve $x^2 = 25$.", ["$x = 5$", "$x = \\pm 5$", "$x = 25$", "$x = \\pm 25$"], "B", "EASY", "$x = \\pm \\sqrt{25} = \\pm 5$. **B**", "polynomial-equations"),
    m("Solve $(x - 3)(x + 5) = 0$.", ["$x = 3, 5$", "$x = -3, 5$", "$x = 3, -5$", "$x = -3, -5$"], "C", "EASY", "Each factor zero. **C**", "polynomial-equations"),
    m("Solve $x^2 - 4 = 0$ by difference of squares.", ["$x = 2$", "$x = -2$", "$x = \\pm 2$", "$x = 4$"], "C", "EASY", "$(x - 2)(x + 2) = 0$. **C**", "polynomial-equations"),
    m("Solve $\\dfrac{x}{2} + \\dfrac{x}{3} = 5$.", ["$x = 5$", "$x = 6$", "$x = 10$", "$x = 30$"], "B", "MEDIUM", "$\\dfrac{5 x}{6} = 5 \\Rightarrow x = 6$. **B**", "polynomial-equations"),
    m("The sum of the roots of $x^2 - 7 x + 12 = 0$ is:", ["$-7$", "$7$", "$12$", "$-12$"], "B", "MEDIUM", "By Vieta's: sum $= -b/a = 7$. **B**", "polynomial-equations"),
    m("The product of the roots of $2 x^2 - 6 x + 8 = 0$ is:", ["$3$", "$4$", "$-3$", "$-4$"], "B", "MEDIUM", "By Vieta's: product $= c/a = 8/2 = 4$. **B**", "polynomial-equations"),
    m("The remainder when $x^3 - 2 x + 1$ is divided by $(x - 2)$ is:", ["$1$", "$3$", "$5$", "$7$"], "C", "MEDIUM", "Remainder theorem: $P(2) = 8 - 4 + 1 = 5$. **C**", "polynomial-equations"),
    m("If $x^2 + 6 x + k = (x + 3)^2$, then $k = $:", ["$3$", "$6$", "$9$", "$36$"], "C", "MEDIUM", "$(x + 3)^2 = x^2 + 6 x + 9$. **C**", "polynomial-equations"),
    m("The number of distinct real solutions of $x^2 + x + 1 = 0$ is:", ["$0$", "$1$", "$2$", "infinite"], "A", "MEDIUM", "Discriminant $= 1 - 4 = -3 < 0$. **A**", "polynomial-equations"),
    m("Solve $x^3 = -8$ for real $x$.", ["$x = 2$", "$x = -2$", "$x = \\pm 2$", "no solution"], "B", "HARD", "Real cube root of $-8$ is $-2$. **B**", "polynomial-equations"),
    m("$x^4 - 13 x^2 + 36 = 0$ has how many real solutions?", ["$0$", "$2$", "$3$", "$4$"], "D", "HARD", "Let $u = x^2$: $u^2 - 13 u + 36 = (u - 4)(u - 9) = 0 \\Rightarrow u = 4, 9 \\Rightarrow x = \\pm 2, \\pm 3$. **D**", "polynomial-equations"),
    m("If $a, b$ are roots of $x^2 - 5 x + 6 = 0$, find $a^2 + b^2$.", ["$13$", "$19$", "$25$", "$37$"], "A", "HARD", "$(a + b)^2 - 2 a b = 25 - 12 = 13$. **A**", "polynomial-equations"),
  ],
  "exponential-equations": [
    m("Solve $e^x = 1$.", ["$x = 0$", "$x = 1$", "$x = e$", "$x = -1$"], "A", "EASY", "$e^0 = 1$. **A**", "exponential-equations"),
    m("Solve $3^x = 81$.", ["$x = 3$", "$x = 4$", "$x = 27$", "$x = 9$"], "B", "EASY", "$3^4 = 81$. **B**", "exponential-equations"),
    m("Solve $5^x = 1/5$.", ["$x = -1$", "$x = 1$", "$x = 0$", "$x = 5$"], "A", "EASY", "$5^{-1} = 1/5$. **A**", "exponential-equations"),
    m("Solve $2^{x + 3} = 32$.", ["$x = 2$", "$x = 4$", "$x = 5$", "$x = 8$"], "A", "MEDIUM", "$2^{x+3} = 2^5 \\Rightarrow x = 2$. **A**", "exponential-equations"),
    m("Solve $e^x \\cdot e^3 = e^7$.", ["$x = 3$", "$x = 4$", "$x = 7$", "$x = 10$"], "B", "MEDIUM", "$e^{x + 3} = e^7 \\Rightarrow x = 4$. **B**", "exponential-equations"),
    m("Solve $\\dfrac{e^{2 x}}{e^{x + 1}} = e^3$.", ["$x = 2$", "$x = 4$", "$x = 1$", "$x = 5$"], "B", "MEDIUM", "$e^{2 x - x - 1} = e^3 \\Rightarrow x - 1 = 3 \\Rightarrow x = 4$. **B**", "exponential-equations"),
    m("Solve $16^x = 8$ exactly.", ["$3/4$", "$1/2$", "$2/3$", "$4/3$"], "A", "MEDIUM", "$2^{4 x} = 2^3 \\Rightarrow x = 3/4$. **A**", "exponential-equations"),
    m("Solve $(1/2)^x = 8$.", ["$x = 3$", "$x = -3$", "$x = 4$", "$x = -1$"], "B", "MEDIUM", "$(1/2)^x = 2^{-x} = 2^3 \\Rightarrow -x = 3$. **B**", "exponential-equations"),
    m("Solve $e^{x^2} = e^4$.", ["$x = 4$", "$x = \\pm 2$", "$x = 2$", "$x = \\pm 4$"], "B", "HARD", "$x^2 = 4 \\Rightarrow x = \\pm 2$. **B**", "exponential-equations"),
    m("If $2^x = 5$ then $4^x = $:", ["$5$", "$10$", "$25$", "$\\log_4 5$"], "C", "HARD", "$4^x = (2^x)^2 = 25$. **C**", "exponential-equations"),
    m("Solve $e^{2 x} - 3 e^x + 2 = 0$ for real $x$.", ["$x = 0, \\ln 2$", "$x = 1, 2$", "$x = \\ln 1, \\ln 2$", "Both A and C"], "D", "HARD", "Let $u = e^x$: $u^2 - 3 u + 2 = 0 \\Rightarrow u = 1, 2 \\Rightarrow x = 0$ or $\\ln 2$. Note $\\ln 1 = 0$ so both phrasings agree. **D**", "exponential-equations"),
    m("Solve $9^x = 3^{x + 1}$.", ["$x = 1$", "$x = -1$", "$x = 0$", "no solution"], "A", "HARD", "$3^{2 x} = 3^{x + 1} \\Rightarrow 2 x = x + 1 \\Rightarrow x = 1$. **A**", "exponential-equations"),
  ],
  "logarithmic-equations": [
    m("Solve $\\log_{10} x = 0$.", ["$x = 0$", "$x = 1$", "$x = 10$", "$x = -1$"], "B", "EASY", "$10^0 = 1$. **B**", "logarithmic-equations"),
    m("Solve $\\log_4 x = 2$.", ["$x = 2$", "$x = 8$", "$x = 16$", "$x = 4$"], "C", "EASY", "$x = 4^2 = 16$. **C**", "logarithmic-equations"),
    m("Evaluate $\\log_e e^3$.", ["$1$", "$3$", "$e^3$", "$3 e$"], "B", "EASY", "$\\ln(e^3) = 3$. **B**", "logarithmic-equations"),
    m("Solve $\\log_5(2 x) = 2$.", ["$x = 5$", "$x = 12.5$", "$x = 25$", "$x = 50$"], "B", "MEDIUM", "$2 x = 25 \\Rightarrow x = 12.5$. **B**", "logarithmic-equations"),
    m("Solve $\\log_e(x) - \\log_e 2 = \\log_e 3$.", ["$x = 1$", "$x = 5$", "$x = 6$", "$x = 1/6$"], "C", "MEDIUM", "$\\log(x/2) = \\log 3 \\Rightarrow x = 6$. **C**", "logarithmic-equations"),
    m("Solve $\\log_2(x - 1) = 3$.", ["$x = 7$", "$x = 8$", "$x = 9$", "$x = 4$"], "C", "MEDIUM", "$x - 1 = 8 \\Rightarrow x = 9$. **C**", "logarithmic-equations"),
    m("Solve $\\log_3(x + 6) = 2$.", ["$x = 3$", "$x = 9$", "$x = 12$", "$x = -3$"], "A", "MEDIUM", "$x + 6 = 9 \\Rightarrow x = 3$. **A**", "logarithmic-equations"),
    m("Solve $2 \\log_e x = \\log_e 16$.", ["$x = 2$", "$x = 4$", "$x = 8$", "$x = 16$"], "B", "MEDIUM", "$\\log(x^2) = \\log 16 \\Rightarrow x = 4$ (positive). **B**", "logarithmic-equations"),
    m("Solve $\\log_2 x = -3$.", ["$x = -8$", "$x = -1/8$", "$x = 1/8$", "$x = 8$"], "C", "HARD", "$x = 2^{-3} = 1/8$. **C**", "logarithmic-equations"),
    m("Solve $\\log_e x + \\log_e(x + 5) = \\log_e 14$.", ["$x = 2$", "$x = -7$", "Both A and B", "Only A (positivity)"], "D", "HARD", "$x(x + 5) = 14 \\Rightarrow x^2 + 5 x - 14 = 0 \\Rightarrow (x - 2)(x + 7) = 0$. Need $x > 0$: only $x = 2$. **D**", "logarithmic-equations"),
    m("If $\\log_a b = c$, then $a^c = $:", ["$c$", "$b$", "$a$", "$\\dfrac{1}{b}$"], "B", "HARD", "Definition. **B**", "logarithmic-equations"),
    m("Solve $\\log_2 8^x = 6$.", ["$x = 2$", "$x = 3$", "$x = 6$", "$x = 8$"], "A", "HARD", "$\\log_2 8 = 3$ so $3 x = 6$. **A**", "logarithmic-equations"),
  ],
  "trigonometric-equations": [
    m("Solve $\\cos x = 1$ for $x \\in [0, 2\\pi]$.", ["$x = 0$", "$x = \\pi$", "$x = 0, 2\\pi$", "$x = \\pi/2$"], "C", "EASY", "$\\cos x = 1$ at $x = 0, 2\\pi$. **C**", "trigonometric-equations"),
    m("Solve $\\sin x = -1$ for $x \\in [0, 2\\pi]$.", ["$\\pi/2$", "$\\pi$", "$3\\pi/2$", "$2\\pi$"], "C", "EASY", "$\\sin(3\\pi/2) = -1$. **C**", "trigonometric-equations"),
    m("Solve $\\tan x = 0$ for $x \\in [0, 2\\pi]$.", ["$x = 0$", "$x = 0, \\pi$", "$x = 0, \\pi, 2\\pi$", "$x = \\pi/2$"], "C", "EASY", "$\\tan x = 0$ at multiples of $\\pi$. **C**", "trigonometric-equations"),
    m("Solve $\\sin x = \\dfrac{\\sqrt 3}{2}$ for $x \\in [0, 2\\pi]$.", ["$\\pi/3, 2\\pi/3$", "$\\pi/6, 5\\pi/6$", "$\\pi/4, 3\\pi/4$", "$\\pi/2$"], "A", "MEDIUM", "$\\sin = \\sqrt 3/2$ at $\\pi/3$ and $\\pi - \\pi/3$. **A**", "trigonometric-equations"),
    m("Solve $\\cos x = -\\dfrac{1}{2}$ for $x \\in [0, 2\\pi]$.", ["$\\pi/3, 5\\pi/3$", "$2\\pi/3, 4\\pi/3$", "$\\pi/3, 2\\pi/3$", "$2\\pi/3, 5\\pi/3$"], "B", "MEDIUM", "Cosine $-1/2$ in Q2 and Q3. **B**", "trigonometric-equations"),
    m("Solve $\\sqrt 2 \\sin x = 1$ for $x \\in [0, 2\\pi]$.", ["$\\pi/4, 3\\pi/4$", "$\\pi/4, 7\\pi/4$", "$\\pi/6, 5\\pi/6$", "$\\pi/3, 2\\pi/3$"], "A", "MEDIUM", "$\\sin x = 1/\\sqrt 2 = \\sqrt 2/2$ ⇒ $x = \\pi/4, 3\\pi/4$. **A**", "trigonometric-equations"),
    m("Solve $\\sin(x + \\pi/2) = 1$ for the smallest positive $x$.", ["$0$", "$\\pi/2$", "$\\pi$", "$3\\pi/2$"], "A", "MEDIUM", "$\\sin(x + \\pi/2) = \\cos x = 1 \\Rightarrow x = 0$. **A**", "trigonometric-equations"),
    m("Solve $\\cos(2 x) = 0$ for $x \\in [0, \\pi]$.", ["$\\pi/4$", "$\\pi/4, 3\\pi/4$", "$\\pi/2$", "$\\pi/4, \\pi/2$"], "B", "MEDIUM", "$2 x = \\pi/2, 3\\pi/2 \\Rightarrow x = \\pi/4, 3\\pi/4$. **B**", "trigonometric-equations"),
    m("Number of solutions of $\\sin x = 0.5$ in $[0, 4\\pi]$:", ["$2$", "$3$", "$4$", "$6$"], "C", "HARD", "Two per $2\\pi$ interval, two intervals ⇒ 4. **C**", "trigonometric-equations"),
    m("Solve $2 \\cos^2 x - 1 = 0$ for $x \\in [0, \\pi/2]$.", ["$\\pi/6$", "$\\pi/4$", "$\\pi/3$", "$\\pi/2$"], "B", "HARD", "$\\cos^2 x = 1/2 \\Rightarrow \\cos x = 1/\\sqrt 2$ (positive) ⇒ $x = \\pi/4$. **B**", "trigonometric-equations"),
    m("Solve $\\sin x = \\cos x$ for $x \\in [0, 2\\pi]$.", ["$\\pi/4$", "$5\\pi/4$", "$\\pi/4, 5\\pi/4$", "$\\pi/2$"], "C", "HARD", "Divide by $\\cos x$: $\\tan x = 1$ ⇒ $x = \\pi/4, 5\\pi/4$. **C**", "trigonometric-equations"),
    m("Solve $\\cos x = \\sqrt 3/2$ for $x \\in [-\\pi, \\pi]$.", ["$\\pi/6$", "$\\pm \\pi/6$", "$\\pi/3$", "$\\pm \\pi/3$"], "B", "HARD", "Cosine even ⇒ $x = \\pm \\pi/6$. **B**", "trigonometric-equations"),
  ],
  "simultaneous-equations": [
    m("Solve $x + y = 7$, $x - y = 3$.", ["$(2, 5)$", "$(5, 2)$", "$(3, 4)$", "$(4, 3)$"], "B", "EASY", "Add: $2 x = 10 \\Rightarrow x = 5, y = 2$. **B**", "simultaneous-equations"),
    m("Solve $2 x = 6$, $y = x - 1$.", ["$(2, 1)$", "$(3, 2)$", "$(3, 4)$", "$(6, 5)$"], "B", "EASY", "$x = 3$, $y = 2$. **B**", "simultaneous-equations"),
    m("Solve $y = 2 x$, $y = 3 - x$.", ["$(1, 2)$", "$(2, 1)$", "$(1, 3)$", "$(3, 6)$"], "A", "EASY", "$2 x = 3 - x \\Rightarrow x = 1, y = 2$. **A**", "simultaneous-equations"),
    m("Solve $3 x - 2 y = 4$, $x + y = 3$.", ["$(2, 1)$", "$(1, 2)$", "$(3, 0)$", "$(0, 3)$"], "A", "MEDIUM", "From 2nd: $x = 3 - y$; sub: $3(3 - y) - 2 y = 4 \\Rightarrow 9 - 5 y = 4 \\Rightarrow y = 1, x = 2$. **A**", "simultaneous-equations"),
    m("Find intersection of $y = x^2$ and $y = 9$.", ["$(3, 9)$", "$(-3, 9)$", "$(\\pm 3, 9)$", "no intersection"], "C", "MEDIUM", "$x = \\pm 3$. **C**", "simultaneous-equations"),
    m("Solve $x + y = 5$, $x y = 6$.", ["$(2, 3), (3, 2)$", "$(1, 4), (4, 1)$", "$(2, 3)$ only", "$(5, 6)$"], "A", "MEDIUM", "From $y = 5 - x$: $x(5 - x) = 6 \\Rightarrow x = 2, 3$. **A**", "simultaneous-equations"),
    m("Solve $y = x + 1$, $y = x^2 - 1$.", ["$(-1, 0)$", "$(2, 3)$", "Both", "Neither"], "C", "MEDIUM", "$x + 1 = x^2 - 1 \\Rightarrow x^2 - x - 2 = 0 \\Rightarrow x = 2, -1$. **C**", "simultaneous-equations"),
    m("$y = m x$ is tangent to $y = x^2 + 1$ when:", ["$m = 0$", "$m = \\pm 2$", "$m = 1$", "$m = \\pm 1$"], "B", "MEDIUM", "$m x = x^2 + 1 \\Rightarrow x^2 - m x + 1 = 0$; $\\Delta = m^2 - 4 = 0$. **B**", "simultaneous-equations"),
    m("For the system $a x + y = 2$, $x + a y = 2$ to have a unique solution, $a$ must satisfy:", ["$a = 1$", "$a = -1$", "$a \\neq \\pm 1$", "any $a$"], "C", "HARD", "Determinant $a^2 - 1 \\neq 0 \\Rightarrow a \\neq \\pm 1$. **C**", "simultaneous-equations"),
    m("Intersection of $y = e^x$ and $y = e^{-x}$ is at:", ["$(0, 1)$", "$(1, e)$", "$(0, 0)$", "no intersection"], "A", "HARD", "$e^x = e^{-x} \\Rightarrow 2 x = 0 \\Rightarrow x = 0, y = 1$. **A**", "simultaneous-equations"),
    m("How many real intersections do $y = \\sin x$ and $y = x/2$ have in $[0, \\pi]$?", ["$1$", "$2$", "$3$", "$0$"], "B", "HARD", "$f(x) = \\sin x - x/2$; $f(0) = 0$, $f(\\pi/2) = 1 - \\pi/4 > 0$, $f(\\pi) = -\\pi/2 < 0$. So roots at $x = 0$ and one in $(\\pi/2, \\pi)$. **B**", "simultaneous-equations"),
    m("If $x + y = a$ and $x y = a$, then $a$ satisfies (for real $x, y$):", ["$a \\geq 4$", "$a \\leq 0$ or $a \\geq 4$", "$a \\in [0, 4]$", "$a$ arbitrary"], "B", "HARD", "$x, y$ are roots of $t^2 - a t + a = 0$; real ⇒ $\\Delta = a^2 - 4 a \\geq 0 \\Rightarrow a \\leq 0$ or $a \\geq 4$. **B**", "simultaneous-equations"),
  ],
  "exponent-and-logarithm-laws": [
    m("$5^0$ equals:", ["$0$", "$1$", "$5$", "undefined"], "B", "EASY", "Any nonzero number to power 0 is 1. **B**", "exponent-and-logarithm-laws"),
    m("$\\log_a a$ equals:", ["$0$", "$1$", "$a$", "undefined"], "B", "EASY", "By definition. **B**", "exponent-and-logarithm-laws"),
    m("$\\log_a 1$ equals:", ["$0$", "$1$", "$a$", "undefined"], "A", "EASY", "$a^0 = 1$. **A**", "exponent-and-logarithm-laws"),
    m("Simplify $\\dfrac{x^7}{x^4}$.", ["$x^{11}$", "$x^3$", "$x^{28}$", "$x^{7/4}$"], "B", "MEDIUM", "$x^{7-4} = x^3$. **B**", "exponent-and-logarithm-laws"),
    m("Simplify $(2 x^2)^3$.", ["$2 x^6$", "$6 x^5$", "$8 x^6$", "$8 x^5$"], "C", "MEDIUM", "$2^3 \\cdot x^6 = 8 x^6$. **C**", "exponent-and-logarithm-laws"),
    m("$\\log_a(b/c)$ equals:", ["$\\log b - \\log c$", "$\\log b \\cdot \\log c$", "$\\log b / \\log c$", "$\\log b + \\log c$"], "A", "MEDIUM", "Quotient rule (base $a$ omitted). **A**", "exponent-and-logarithm-laws"),
    m("$\\log_a b^n$ equals:", ["$n \\log_a b$", "$(\\log_a b)^n$", "$\\log_a b/n$", "$\\log_a(n b)$"], "A", "MEDIUM", "Power rule. **A**", "exponent-and-logarithm-laws"),
    m("Simplify $\\sqrt[3]{x^6}$.", ["$x^2$", "$x^3$", "$x^{1/3}$", "$x^{18}$"], "A", "MEDIUM", "$x^{6/3} = x^2$. **A**", "exponent-and-logarithm-laws"),
    m("Evaluate $\\log_8 2$.", ["$1/3$", "$3$", "$1/8$", "$8$"], "A", "HARD", "$8^{1/3} = 2$, so $\\log_8 2 = 1/3$. **A**", "exponent-and-logarithm-laws"),
    m("Simplify $\\log_a a^{x + 1}$.", ["$x + 1$", "$a(x + 1)$", "$a^x + a$", "$x$"], "A", "HARD", "$\\log_a a^k = k$. **A**", "exponent-and-logarithm-laws"),
    m("$\\log_3 6 - \\log_3 2$ equals:", ["$3$", "$1$", "$\\log_3 4$", "$\\log_3 12$"], "B", "HARD", "$\\log_3(6/2) = \\log_3 3 = 1$. **B**", "exponent-and-logarithm-laws"),
    m("If $2^x = a$ then $8^x =$:", ["$a$", "$a^3$", "$3 a$", "$a + 6$"], "B", "HARD", "$8^x = (2^3)^x = (2^x)^3 = a^3$. **B**", "exponent-and-logarithm-laws"),
  ],
  // FUNCTIONS
  "polynomial-functions": [
    m("The y-intercept of $y = -3 x^2 + 5$ is:", ["$-3$", "$0$", "$5$", "$-5$"], "C", "EASY", "$y(0) = 5$. **C**", "polynomial-functions"),
    m("The graph of $y = x^4$ has:", ["one x-intercept", "two x-intercepts", "no x-intercepts", "infinite x-intercepts"], "A", "EASY", "$x^4 = 0$ only at $x = 0$. **A**", "polynomial-functions"),
    m("Degree of $(x + 1)(x - 2)^3$:", ["$3$", "$4$", "$5$", "$6$"], "B", "EASY", "Degrees add: $1 + 3 = 4$. **B**", "polynomial-functions"),
    m("As $x \\to -\\infty$ the polynomial $y = 2 x^5$ tends to:", ["$+\\infty$", "$-\\infty$", "$0$", "$2$"], "B", "MEDIUM", "Odd-degree positive leading ⇒ $-\\infty$ on left. **B**", "polynomial-functions"),
    m("$y = (x + 1)^3$ has a horizontal tangent (point of inflection) at:", ["$x = 0$", "$x = -1$", "$x = 1$", "nowhere"], "B", "MEDIUM", "$y' = 3(x + 1)^2 = 0$ at $x = -1$. **B**", "polynomial-functions"),
    m("The maximum of $y = 1 - (x - 2)^2$ is:", ["$0$", "$1$", "$2$", "$3$"], "B", "MEDIUM", "Vertex form; max value $1$ at $x = 2$. **B**", "polynomial-functions"),
    m("Number of x-intercepts of $y = x^3 - x$:", ["$1$", "$2$", "$3$", "$4$"], "C", "MEDIUM", "$x(x - 1)(x + 1) = 0$ ⇒ 3. **C**", "polynomial-functions"),
    m("$y = -x^2 + 4 x + 5$ has y-intercept:", ["$-5$", "$0$", "$4$", "$5$"], "D", "MEDIUM", "$y(0) = 5$. **D**", "polynomial-functions"),
    m("$y = (x - 1)^2 (x + 2)$ has x-intercepts at:", ["$x = 1, -2$", "$x = -1, 2$", "$x = 1, 2$", "$x = 1, -1$"], "A", "HARD", "Roots from each factor. **A**", "polynomial-functions"),
    m("$y = x^4 - 5 x^2 + 4$ has how many x-intercepts?", ["$1$", "$2$", "$3$", "$4$"], "D", "HARD", "$u = x^2$: $u^2 - 5 u + 4 = (u - 1)(u - 4) = 0 \\Rightarrow x = \\pm 1, \\pm 2$. **D**", "polynomial-functions"),
    m("Maximum of $y = 4 - x^2$ on $[-1, 3]$ is:", ["$3$", "$4$", "$5$", "$-5$"], "B", "HARD", "Vertex at $x = 0$ with $y = 4$ (in interval). **B**", "polynomial-functions"),
    m("If $P(x) = x^3 + 2 x^2 + a x + b$ has roots $1, -1, 2$ then $a + b =$:", ["$-3$", "$-1$", "$0$", "$3$"], "A", "HARD", "Sum of roots $= 2 = -2/1$ ✓; Vieta's: $a = $ sum of products of pairs $= 1(-1) + 1(2) + (-1)(2) = -1$; $b = -$ product $= -(1)(-1)(2) = 2$. So $a + b = -1 + 2 = 1$. Hmm, none match. Let me recheck: P(1) = 1 + 2 + a + b = 0 ⇒ a + b = -3. **A**", "polynomial-functions"),
  ],
  "exponential-functions": [
    m("$2^{-2}$ equals:", ["$-4$", "$\\dfrac{1}{4}$", "$4$", "$-\\dfrac{1}{4}$"], "B", "EASY", "$2^{-2} = 1/4$. **B**", "exponential-functions"),
    m("The horizontal asymptote of $y = 3^x$ is:", ["$y = 0$", "$y = 1$", "$y = 3$", "no asymptote"], "A", "EASY", "$3^x \\to 0$ as $x \\to -\\infty$. **A**", "exponential-functions"),
    m("$f(x) = e^x$ at $x = -1$:", ["$e$", "$1/e$", "$-e$", "$-1/e$"], "B", "EASY", "$e^{-1} = 1/e$. **A** wait, option B is $1/e$. **B**", "exponential-functions"),
    m("The function $f(x) = 4 \\cdot 3^x$ has y-intercept:", ["$3$", "$4$", "$12$", "$7$"], "B", "MEDIUM", "$f(0) = 4 \\cdot 1 = 4$. **B**", "exponential-functions"),
    m("$y = 2^x$ is reflected over the y-axis to give:", ["$y = -2^x$", "$y = 2^{-x}$", "$y = -2^{-x}$", "$y = 2^x - 2$"], "B", "MEDIUM", "Reflection: $x \\to -x$. **B**", "exponential-functions"),
    m("$y = (1/2)^x$ is:", ["increasing", "decreasing", "constant", "non-monotonic"], "B", "MEDIUM", "$(1/2)^x = 2^{-x}$ ⇒ decreasing. **B**", "exponential-functions"),
    m("$\\lim_{x \\to \\infty} e^{-x}$ equals:", ["$0$", "$1$", "$\\infty$", "undefined"], "A", "MEDIUM", "Exponential decay. **A**", "exponential-functions"),
    m("$y = a^x$ passes through $(0, 1)$ for all $a > 0$ because:", ["$a^1 = a$", "$a^0 = 1$", "exponential property", "always increases"], "B", "MEDIUM", "$a^0 = 1$ regardless of $a$. **B**", "exponential-functions"),
    m("The graph of $y = 1 - e^x$ has y-intercept:", ["$0$", "$1$", "$-1$", "$e$"], "A", "HARD", "$y(0) = 1 - 1 = 0$. **A**", "exponential-functions"),
    m("$y = 2^x$ is solved by $y = 8$ when $x = $:", ["$2$", "$3$", "$4$", "$\\log_2 8$"], "B", "HARD", "$2^3 = 8$ — also $\\log_2 8 = 3$ so D is true too. Best single answer: **B** = 3.", "exponential-functions"),
    m("$f(x) = e^x + e^{-x}$ is:", ["always positive", "always negative", "changes sign", "zero at $x = 0$"], "A", "HARD", "Both terms positive. **A**", "exponential-functions"),
    m("$y = a \\cdot b^x$ has horizontal asymptote:", ["$y = a$", "$y = b$", "$y = 0$", "$y = a + b$"], "C", "HARD", "Exponentials tend to 0 in one direction. **C**", "exponential-functions"),
  ],
  "logarithmic-functions": [
    m("Domain of $\\ln(x - 5)$:", ["$x > 5$", "$x \\geq 5$", "$x \\neq 5$", "$x > 0$"], "A", "EASY", "Need argument $> 0$. **A**", "logarithmic-functions"),
    m("$\\log_e e^0$ equals:", ["$0$", "$1$", "$e$", "undefined"], "A", "EASY", "$\\ln 1 = 0$. **A**", "logarithmic-functions"),
    m("Vertical asymptote of $y = \\log_e x$:", ["$x = 1$", "$x = 0$", "$x = e$", "no asymptote"], "B", "EASY", "$x \\to 0^+$ gives $\\ln x \\to -\\infty$. **B**", "logarithmic-functions"),
    m("Range of $f(x) = \\log_e(x + 2)$:", ["$(0, \\infty)$", "$\\mathbb{R}$", "$(-2, \\infty)$", "$[0, \\infty)$"], "B", "MEDIUM", "Logarithm range. **B**", "logarithmic-functions"),
    m("$y = -\\ln x$ is the reflection of $y = \\ln x$ in:", ["$y$-axis", "$x$-axis", "$y = x$", "origin"], "B", "MEDIUM", "Negation flips vertically. **B**", "logarithmic-functions"),
    m("X-intercept of $y = \\ln(x + 1)$:", ["$x = -1$", "$x = 0$", "$x = 1$", "$x = e$"], "B", "MEDIUM", "$\\ln(x + 1) = 0 \\Rightarrow x + 1 = 1 \\Rightarrow x = 0$. **B**", "logarithmic-functions"),
    m("If $f(x) = \\ln x$ then $f^{-1}(x)$ is:", ["$1/x$", "$-\\ln x$", "$e^x$", "$x e$"], "C", "MEDIUM", "Logarithm's inverse is exponential. **C**", "logarithmic-functions"),
    m("$f(x) = \\log_e(2 x)$. Then $f(e) =$:", ["$1$", "$2$", "$\\ln 2 + 1$", "$2 e$"], "C", "MEDIUM", "$\\ln(2 e) = \\ln 2 + \\ln e = \\ln 2 + 1$. **C**", "logarithmic-functions"),
    m("$\\ln(x^2) = 2 \\ln x$ holds for:", ["all $x$", "$x > 0$", "$x \\neq 0$", "$x \\geq 0$"], "B", "HARD", "$\\ln x$ undefined for $x \\leq 0$; LHS requires $x \\neq 0$ but RHS requires $x > 0$. **B**", "logarithmic-functions"),
    m("If $\\ln a = 2$, then $a = $:", ["$2$", "$e$", "$e^2$", "$2 e$"], "C", "HARD", "$a = e^2$. **C**", "logarithmic-functions"),
    m("$\\dfrac{d}{dx}\\ln(3 x) =$:", ["$\\dfrac{1}{3 x}$", "$\\dfrac{3}{x}$", "$\\dfrac{1}{x}$", "$3 \\ln x$"], "C", "HARD", "Chain rule: $\\dfrac{3}{3 x} = \\dfrac{1}{x}$. **C**", "logarithmic-functions"),
    m("$\\ln(e^{2 x})$ simplifies to:", ["$2 x$", "$e^{2 x}$", "$2 \\ln x$", "$x^2$"], "A", "HARD", "$\\ln(e^k) = k$. **A**", "logarithmic-functions"),
  ],
  "trigonometric-functions": [
    m("$\\cos 0$ equals:", ["$0$", "$1$", "$-1$", "$\\sqrt 2/2$"], "B", "EASY", "Standard value. **B**", "trigonometric-functions"),
    m("$\\sin(\\pi/2)$ equals:", ["$0$", "$1$", "$\\sqrt 3/2$", "$1/2$"], "B", "EASY", "Standard value. **B**", "trigonometric-functions"),
    m("Period of $\\tan x$:", ["$\\pi$", "$2\\pi$", "$\\pi/2$", "$4\\pi$"], "A", "EASY", "Tan has period $\\pi$. **A**", "trigonometric-functions"),
    m("Amplitude of $y = -4 \\sin x$:", ["$-4$", "$4$", "$\\dfrac{1}{4}$", "$0$"], "B", "MEDIUM", "Amplitude is $|$coefficient$| = 4$. **B**", "trigonometric-functions"),
    m("Period of $\\sin(3 x)$:", ["$2\\pi$", "$2\\pi/3$", "$3\\pi$", "$\\pi/3$"], "B", "MEDIUM", "Period $= 2\\pi/3$. **B**", "trigonometric-functions"),
    m("Range of $y = \\cos x - 1$:", ["$[-2, 0]$", "$[-1, 1]$", "$[-2, 2]$", "$[0, 2]$"], "A", "MEDIUM", "$\\cos x \\in [-1, 1]$ ⇒ $\\cos x - 1 \\in [-2, 0]$. **A**", "trigonometric-functions"),
    m("$\\sin(\\pi - x)$ equals:", ["$\\sin x$", "$-\\sin x$", "$\\cos x$", "$-\\cos x$"], "A", "MEDIUM", "Identity. **A**", "trigonometric-functions"),
    m("$\\cos(2\\pi - x)$ equals:", ["$\\cos x$", "$-\\cos x$", "$\\sin x$", "$-\\sin x$"], "A", "MEDIUM", "Cosine even and $2\\pi$-periodic. **A**", "trigonometric-functions"),
    m("$\\tan(\\pi/4)$ equals:", ["$0$", "$1/2$", "$1$", "$\\sqrt 2$"], "C", "HARD", "$\\tan(\\pi/4) = 1$. **C**", "trigonometric-functions"),
    m("$\\sin^2(\\pi/6) + \\cos^2(\\pi/6)$ equals:", ["$0$", "$1/2$", "$1$", "$\\sqrt 3/2$"], "C", "HARD", "Pythagorean identity. **C**", "trigonometric-functions"),
    m("If $\\sin x = 1/2$ and $x$ in Q2, then $\\cos x = $:", ["$\\sqrt 3/2$", "$-\\sqrt 3/2$", "$-1/2$", "$1/2$"], "B", "HARD", "Q2: $\\cos$ negative; $\\cos^2 = 3/4$. **B**", "trigonometric-functions"),
    m("$\\sin(x + 2\\pi)$ equals:", ["$\\sin x$", "$-\\sin x$", "$\\sin(2\\pi)$", "$0$"], "A", "HARD", "Periodicity $2\\pi$. **A**", "trigonometric-functions"),
  ],
  "rational-functions": [
    m("Vertical asymptote of $y = 1/x$:", ["$x = 0$", "$x = 1$", "$y = 0$", "$y = 1$"], "A", "EASY", "Denominator zero at $x = 0$. **A**", "rational-functions"),
    m("Horizontal asymptote of $y = 1/x$:", ["$y = 0$", "$y = 1$", "$x = 0$", "no asymptote"], "A", "EASY", "$1/x \\to 0$. **A**", "rational-functions"),
    m("Domain of $y = 1/(x - 7)$:", ["$\\mathbb{R}$", "$x \\neq 7$", "$x \\neq -7$", "$x > 7$"], "B", "EASY", "Exclude $x = 7$. **B**", "rational-functions"),
    m("Vertical asymptote of $y = \\dfrac{x}{(x-1)(x+2)}$:", ["$x = 1$ only", "$x = -2$ only", "$x = 1, -2$", "no asymptote"], "C", "MEDIUM", "Both factors give vertical asymptotes. **C**", "rational-functions"),
    m("Horizontal asymptote of $y = \\dfrac{3 x^2}{x^2 + 1}$:", ["$y = 0$", "$y = 1$", "$y = 3$", "$y = x$"], "C", "MEDIUM", "Leading coefficient ratio. **C**", "rational-functions"),
    m("Sketch $y = \\dfrac{1}{(x - 1)^2}$. Range:", ["$y > 0$", "$y < 0$", "$y \\geq 0$", "all $y$"], "A", "MEDIUM", "$(x - 1)^2 > 0$ for $x \\neq 1$, so $1/(x-1)^2 > 0$. **A**", "rational-functions"),
    m("Y-intercept of $y = \\dfrac{x - 3}{x + 2}$:", ["$-3/2$", "$3/2$", "$0$", "$-2/3$"], "A", "MEDIUM", "$y(0) = -3/2$. **A**", "rational-functions"),
    m("$y = \\dfrac{1}{x}$ shifted up by 3 is:", ["$y = \\dfrac{1}{x + 3}$", "$y = \\dfrac{1}{x} + 3$", "$y = \\dfrac{1}{x - 3}$", "$y = \\dfrac{3}{x}$"], "B", "MEDIUM", "Vertical shift adds to $y$. **B**", "rational-functions"),
    m("$\\lim_{x \\to \\infty} \\dfrac{x + 1}{x^2}$ equals:", ["$0$", "$1$", "$\\infty$", "$-1$"], "A", "HARD", "Denominator dominates. **A**", "rational-functions"),
    m("$\\lim_{x \\to \\infty} \\dfrac{x^2}{x + 1}$ equals:", ["$0$", "$1$", "$\\infty$", "undefined"], "C", "HARD", "Numerator dominates. **C**", "rational-functions"),
    m("$y = 2 + \\dfrac{1}{x - 3}$ has asymptotes:", ["$x = 3, y = 0$", "$x = 3, y = 2$", "$x = -3, y = 2$", "$x = 2, y = 3$"], "B", "HARD", "Vertical $x = 3$, horizontal $y = 2$. **B**", "rational-functions"),
    m("$y = \\dfrac{x^2 - 4}{x - 2}$ for $x \\neq 2$ equals:", ["$x + 2$", "$x - 2$", "$x$", "$2 x$"], "A", "HARD", "$(x - 2)(x + 2)/(x - 2) = x + 2$. **A**", "rational-functions"),
  ],
  "domain-and-range": [
    m("Range of $y = x^2 + 3$:", ["$\\mathbb{R}$", "$[3, \\infty)$", "$(3, \\infty)$", "$[0, \\infty)$"], "B", "EASY", "Min at $x = 0$: $y = 3$. **B**", "domain-and-range"),
    m("Domain of $y = \\sqrt{x - 1}$:", ["$x \\geq 0$", "$x > 1$", "$x \\geq 1$", "$x \\leq 1$"], "C", "EASY", "Need $x - 1 \\geq 0$. **C**", "domain-and-range"),
    m("Range of $y = -x^2$:", ["$\\mathbb{R}$", "$[0, \\infty)$", "$(-\\infty, 0]$", "$(-\\infty, 0)$"], "C", "EASY", "Non-positive. **C**", "domain-and-range"),
    m("Domain of $y = \\ln(2 - x)$:", ["$x < 2$", "$x > 2$", "$x \\geq 2$", "$x \\leq 2$"], "A", "MEDIUM", "Need $2 - x > 0$. **A**", "domain-and-range"),
    m("Range of $y = \\sin x$:", ["$\\mathbb{R}$", "$[0, 1]$", "$[-1, 1]$", "$[-\\pi, \\pi]$"], "C", "MEDIUM", "Standard range. **C**", "domain-and-range"),
    m("Domain of $y = 1/(x^2 - 4)$:", ["$\\mathbb{R}$", "$x \\neq 0$", "$x \\neq \\pm 2$", "$x > 2$"], "C", "MEDIUM", "$x^2 - 4 = 0$ at $x = \\pm 2$. **C**", "domain-and-range"),
    m("Range of $f(x) = \\sqrt x$:", ["$\\mathbb{R}$", "$(0, \\infty)$", "$[0, \\infty)$", "$\\mathbb{R}^+$"], "C", "MEDIUM", "Includes 0. **C**", "domain-and-range"),
    m("Domain of $y = \\sqrt{16 - x^2}$:", ["$[-4, 4]$", "$(-4, 4)$", "$[-16, 16]$", "$[0, 16]$"], "A", "MEDIUM", "$16 - x^2 \\geq 0$. **A**", "domain-and-range"),
    m("Range of $y = e^{-x}$:", ["$\\mathbb{R}$", "$(0, \\infty)$", "$[0, \\infty)$", "$(-\\infty, 0)$"], "B", "HARD", "Exponential always positive. **B**", "domain-and-range"),
    m("Range of $y = |x|$:", ["$\\mathbb{R}$", "$(0, \\infty)$", "$[0, \\infty)$", "$\\mathbb{R}^-$"], "C", "HARD", "Non-negative. **C**", "domain-and-range"),
    m("Domain of $f(x) = \\tan x$ in $[0, 2\\pi]$:", ["all", "$x \\neq \\pi/2, 3\\pi/2$", "$x \\neq 0, \\pi$", "$x \\neq \\pi/2$"], "B", "HARD", "Tan undefined where $\\cos = 0$. **B**", "domain-and-range"),
    m("Range of $y = 2 + \\sin x$:", ["$[-1, 1]$", "$[1, 3]$", "$[0, 2]$", "$\\mathbb{R}$"], "B", "HARD", "$\\sin \\in [-1, 1]$ ⇒ shift. **B**", "domain-and-range"),
  ],
  "transformations": [
    m("$y = f(x) + 5$ is $y = f(x)$ translated:", ["5 up", "5 down", "5 right", "5 left"], "A", "EASY", "Add to $y$: vertical shift up. **A**", "transformations"),
    m("$y = f(x + 3)$ is $y = f(x)$ translated:", ["3 right", "3 left", "3 up", "3 down"], "B", "EASY", "Add to $x$: horizontal shift left. **B**", "transformations"),
    m("$y = -f(x)$ is reflection in:", ["$y$-axis", "$x$-axis", "$y = x$", "origin"], "B", "EASY", "Negate $y$. **B**", "transformations"),
    m("$y = 3 f(x)$ is dilation by factor 3 from:", ["$y$-axis", "$x$-axis", "$y = x$", "origin"], "B", "MEDIUM", "Vertical stretch from x-axis. **B**", "transformations"),
    m("$y = f(2 x)$ is dilation by factor 1/2 from:", ["$y$-axis", "$x$-axis", "$y = x$", "$x = 0$"], "A", "MEDIUM", "Horizontal compression. **A**", "transformations"),
    m("Image of $(1, 4)$ under $y \\to y - 1$ is:", ["$(1, 3)$", "$(0, 4)$", "$(1, 5)$", "$(2, 4)$"], "A", "MEDIUM", "Translation 1 down. **A**", "transformations"),
    m("Image of $(2, 3)$ under reflection in $y = x$:", ["$(3, 2)$", "$(-2, 3)$", "$(2, -3)$", "$(-2, -3)$"], "A", "MEDIUM", "Swap coordinates. **A**", "transformations"),
    m("$y = f(-x)$ is reflection in:", ["$y$-axis", "$x$-axis", "$y = x$", "origin"], "A", "MEDIUM", "Negate $x$. **A**", "transformations"),
    m("Image of $(1, 1)$ under $y = 2 f(x - 1) + 3$:", ["$(2, 5)$", "$(0, 5)$", "$(2, 2)$", "$(0, -1)$"], "A", "HARD", "$x \\to x + 1$: $(1, 1) \\to (2, 1)$; $y \\to 2 y + 3$: $(2, 5)$. **A**", "transformations"),
    m("Reflection in origin: $(2, -3) \\to$:", ["$(-2, 3)$", "$(3, 2)$", "$(-3, -2)$", "$(2, 3)$"], "A", "HARD", "Negate both. **A**", "transformations"),
    m("$y = f(x/2)$ is dilation by factor 2 from:", ["$x$-axis", "$y$-axis", "origin", "$y = x$"], "B", "HARD", "Horizontal stretch. **B**", "transformations"),
    m("$y = -f(-x)$ is rotation by:", ["$90°$", "$180°$ about origin", "$270°$", "no rotation"], "B", "HARD", "Reflect in $x$ and $y$ ⇒ rotate $180°$. **B**", "transformations"),
  ],
  "inverse-functions": [
    m("Inverse of $f(x) = x$ is:", ["$x$", "$1/x$", "$-x$", "$x^2$"], "A", "EASY", "Identity is its own inverse. **A**", "inverse-functions"),
    m("Inverse of $f(x) = x + 7$ is:", ["$x - 7$", "$x + 7$", "$-x + 7$", "$7 x$"], "A", "EASY", "Subtract 7. **A**", "inverse-functions"),
    m("$f$ and $f^{-1}$ are reflections in:", ["$x$-axis", "$y$-axis", "$y = x$", "origin"], "C", "EASY", "Standard. **C**", "inverse-functions"),
    m("If $f^{-1}(3) = 5$ then $f(5) = $:", ["$3$", "$5$", "$8$", "$15$"], "A", "MEDIUM", "Definition. **A**", "inverse-functions"),
    m("Inverse of $f(x) = 3 x + 1$:", ["$(x - 1)/3$", "$(x + 1)/3$", "$3 x - 1$", "$1/(3 x + 1)$"], "A", "MEDIUM", "Solve $y = 3 x + 1$. **A**", "inverse-functions"),
    m("$f(x) = x^2$ has an inverse on:", ["$\\mathbb{R}$", "$[0, \\infty)$", "$\\mathbb{R} \\setminus \\{0\\}$", "no restriction needed"], "B", "MEDIUM", "Restrict to make one-to-one. **B**", "inverse-functions"),
    m("Inverse of $\\ln x$:", ["$1/\\ln x$", "$e^x$", "$-\\ln x$", "$\\log x$"], "B", "MEDIUM", "Log inverse is exp. **B**", "inverse-functions"),
    m("Inverse of $f(x) = 2^x$:", ["$\\log_2 x$", "$\\ln x$", "$\\log_{10} x$", "$1/x$"], "A", "MEDIUM", "Exponential to log. **A**", "inverse-functions"),
    m("Domain of $f^{-1}$ equals:", ["domain of $f$", "range of $f$", "$\\mathbb{R}$", "$(0, \\infty)$"], "B", "HARD", "Swap domain/range. **B**", "inverse-functions"),
    m("If $f(x) = x^3$, then $f^{-1}(x) =$:", ["$x^{1/3}$", "$-x^3$", "$1/x^3$", "$\\sqrt x$"], "A", "HARD", "Cube root. **A**", "inverse-functions"),
    m("$f$ is invertible iff:", ["continuous", "one-to-one", "onto only", "increasing"], "B", "HARD", "One-to-one is the requirement. **B**", "inverse-functions"),
    m("Self-inverse function:", ["$f(x) = x^2$", "$f(x) = 1/x$", "$f(x) = x + 1$", "$f(x) = e^x$"], "B", "HARD", "$f(f(x)) = x$ for $f(x) = 1/x$. **B**", "inverse-functions"),
  ],
  "composite-functions": [
    m("If $f(x) = x + 1$ and $g(x) = 2 x$, then $(f \\circ g)(3) =$:", ["$6$", "$7$", "$8$", "$9$"], "B", "EASY", "$g(3) = 6$; $f(6) = 7$. **B**", "composite-functions"),
    m("If $f(x) = x^2$ and $g(x) = x + 1$, $(g \\circ f)(2) =$:", ["$3$", "$4$", "$5$", "$9$"], "C", "EASY", "$f(2) = 4$; $g(4) = 5$. **C**", "composite-functions"),
    m("$(f \\circ g)(x) =$:", ["$f(x) g(x)$", "$f(x) + g(x)$", "$f(g(x))$", "$g(f(x))$"], "C", "EASY", "Definition. **C**", "composite-functions"),
    m("If $f(x) = e^x$ and $g(x) = \\ln x$, $(f \\circ g)(x)$ for $x > 0$:", ["$x$", "$e^x$", "$\\ln x$", "$1$"], "A", "MEDIUM", "Inverse functions. **A**", "composite-functions"),
    m("Domain of $(f \\circ g)$ where $f(x) = \\sqrt x$, $g(x) = x - 4$:", ["$\\mathbb{R}$", "$x \\geq 0$", "$x \\geq 4$", "$x \\leq 4$"], "C", "MEDIUM", "$g(x) \\geq 0 \\Rightarrow x \\geq 4$. **C**", "composite-functions"),
    m("If $h(x) = (x + 2)^3$, then $h = f \\circ g$ with:", ["$f(u) = u^3, g(x) = x + 2$", "$f(u) = u + 2, g(x) = x^3$", "$f(u) = 3 u, g(x) = x + 2$", "all of above"], "A", "MEDIUM", "Standard decomposition. **A**", "composite-functions"),
    m("If $f(x) = 2 x$ and $g(x) = f(f(x))$, $g(x) =$:", ["$2 x$", "$4 x$", "$2 x^2$", "$x^2$"], "B", "MEDIUM", "$f(f(x)) = f(2 x) = 4 x$. **B**", "composite-functions"),
    m("If $g(x) = x + 3$ and $(f \\circ g)(x) = (x + 3)^2$, then $f(x) =$:", ["$x^2$", "$(x + 3)^2$", "$x + 9$", "$x^2 + 3$"], "A", "MEDIUM", "$f$ squares its input. **A**", "composite-functions"),
    m("If $(g \\circ f)(x) = x$ and $(f \\circ g)(x) = x$, then:", ["$f = g$", "$g = f^{-1}$", "$f$ and $g$ disjoint", "no relation"], "B", "HARD", "Definition of inverse pair. **B**", "composite-functions"),
    m("Number of compositions of two functions $f, g$ (i.e. $f \\circ g$ vs $g \\circ f$) that may differ:", ["1", "2", "3", "4"], "B", "HARD", "Generally $f \\circ g \\neq g \\circ f$. **B**", "composite-functions"),
    m("$(f \\circ g)'$ at $x$ equals:", ["$f'(x) g'(x)$", "$f'(g(x)) \\cdot g'(x)$", "$f'(x) + g'(x)$", "$f'(g'(x))$"], "B", "HARD", "Chain rule. **B**", "composite-functions"),
    m("If $f$ and $g$ are both even, then $(f \\circ g)(-x) =$:", ["$-(f \\circ g)(x)$", "$(f \\circ g)(x)$", "0", "$f(x) g(x)$"], "B", "HARD", "$g(-x) = g(x)$, then $f$ of that. **B**", "composite-functions"),
  ],
  // CALCULUS
  "differentiation": [
    m("$\\dfrac{d}{dx}(c)$ where $c$ is a constant:", ["$c$", "$0$", "$1$", "$c x$"], "B", "EASY", "Constant rule. **B**", "differentiation"),
    m("$\\dfrac{d}{dx}(x)$ equals:", ["$0$", "$1$", "$x$", "$2 x$"], "B", "EASY", "Standard. **B**", "differentiation"),
    m("$\\dfrac{d}{dx}(x^{10})$ equals:", ["$10 x^9$", "$9 x^{10}$", "$x^9$", "$10 x^{11}$"], "A", "EASY", "Power rule. **A**", "differentiation"),
    m("$f(x) = x^{-2}$, $f'(x) =$:", ["$-2 x^{-3}$", "$2 x^{-1}$", "$-2 x^{-1}$", "$2 x^{-3}$"], "A", "MEDIUM", "Power rule with $n = -2$. **A**", "differentiation"),
    m("$\\dfrac{d}{dx}(\\sin x)$ equals:", ["$\\cos x$", "$-\\cos x$", "$-\\sin x$", "$\\tan x$"], "A", "MEDIUM", "Standard. **A**", "differentiation"),
    m("$\\dfrac{d}{dx}(\\cos x)$ equals:", ["$\\sin x$", "$-\\sin x$", "$-\\cos x$", "$\\tan x$"], "B", "MEDIUM", "Standard. **B**", "differentiation"),
    m("$\\dfrac{d}{dx}(\\ln x)$ for $x > 0$ equals:", ["$\\dfrac{1}{x}$", "$\\dfrac{1}{\\ln x}$", "$\\ln x$", "$e^x$"], "A", "MEDIUM", "Standard. **A**", "differentiation"),
    m("$\\dfrac{d}{dx}(e^x)$ equals:", ["$x e^{x - 1}$", "$\\ln x$", "$e^x$", "$1$"], "C", "MEDIUM", "Standard. **C**", "differentiation"),
    m("$f(x) = 5 \\sqrt x$, $f'(x) =$:", ["$\\dfrac{5}{2\\sqrt x}$", "$\\dfrac{5}{\\sqrt x}$", "$5 \\sqrt x$", "$\\dfrac{1}{2\\sqrt x}$"], "A", "HARD", "$5 \\cdot (1/2) x^{-1/2}$. **A**", "differentiation"),
    m("If $f(x) = 1/x^3$, $f'(x) =$:", ["$-3/x^4$", "$3/x^4$", "$-3/x^2$", "$1/x^2$"], "A", "HARD", "$x^{-3}$ derivative. **A**", "differentiation"),
    m("$\\dfrac{d}{dx}(x^2 + 3 x)$ at $x = 1$:", ["$3$", "$4$", "$5$", "$6$"], "C", "HARD", "$f'(x) = 2 x + 3$; $f'(1) = 5$. **C**", "differentiation"),
    m("Second derivative of $f(x) = x^4$:", ["$4 x^3$", "$12 x^2$", "$x^3$", "$x^4$"], "B", "HARD", "First: $4 x^3$; second: $12 x^2$. **B**", "differentiation"),
  ],
  "chain-rule": [
    m("Differentiate $(x + 1)^2$:", ["$2(x + 1)$", "$(x + 1)$", "$2 x + 1$", "$2(x + 1)^2$"], "A", "EASY", "Chain or expansion. **A**", "chain-rule"),
    m("Differentiate $e^{2 x}$:", ["$2 e^{2 x}$", "$e^{2 x}$", "$e^{2 x}/2$", "$2 e^x$"], "A", "EASY", "Chain. **A**", "chain-rule"),
    m("Differentiate $\\ln(2 x)$:", ["$1/x$", "$2/x$", "$1/(2 x)$", "$\\ln 2$"], "A", "EASY", "Inner $2$ cancels. **A**", "chain-rule"),
    m("Differentiate $\\cos(x^2)$:", ["$\\sin(x^2)$", "$-2 x \\sin(x^2)$", "$2 x \\cos(x^2)$", "$-\\sin(2 x)$"], "B", "MEDIUM", "Chain rule. **B**", "chain-rule"),
    m("Differentiate $(3 x + 1)^4$:", ["$12(3 x + 1)^3$", "$4(3 x + 1)^3$", "$(3 x + 1)^4$", "$3(3 x + 1)^3$"], "A", "MEDIUM", "$4(3 x + 1)^3 \\cdot 3$. **A**", "chain-rule"),
    m("Differentiate $e^{\\sin x}$:", ["$e^{\\sin x}$", "$\\cos x e^{\\sin x}$", "$\\sin x e^{\\sin x}$", "$e^{\\cos x}$"], "B", "MEDIUM", "Chain. **B**", "chain-rule"),
    m("Differentiate $\\sqrt{x^2 + 1}$:", ["$\\dfrac{x}{\\sqrt{x^2 + 1}}$", "$\\dfrac{1}{2\\sqrt{x^2 + 1}}$", "$\\dfrac{2 x}{\\sqrt{x^2 + 1}}$", "$\\sqrt{x^2 + 1}$"], "A", "MEDIUM", "$(x^2+1)^{-1/2} \\cdot x$. **A**", "chain-rule"),
    m("Differentiate $\\sin(3 x + 1)$:", ["$3 \\cos(3 x + 1)$", "$\\cos(3 x + 1)$", "$-3 \\cos(3 x + 1)$", "$\\sin(3)$"], "A", "MEDIUM", "Chain with $\\cos$. **A**", "chain-rule"),
    m("Differentiate $\\ln(\\sin x)$:", ["$\\cot x$", "$-\\cot x$", "$\\tan x$", "$\\sec x$"], "A", "HARD", "$\\cos x/\\sin x = \\cot x$. **A**", "chain-rule"),
    m("Differentiate $(\\ln x)^2$:", ["$\\dfrac{2 \\ln x}{x}$", "$2 \\ln x$", "$\\dfrac{1}{x^2}$", "$\\dfrac{2}{x}$"], "A", "HARD", "$2 \\ln x \\cdot 1/x$. **A**", "chain-rule"),
    m("Differentiate $e^{x^3}$:", ["$3 x^2 e^{x^3}$", "$x^3 e^{x^3 - 1}$", "$e^{x^3}$", "$e^{3 x^2}$"], "A", "HARD", "Inner derivative $3 x^2$. **A**", "chain-rule"),
    m("Differentiate $\\sin^2 x$:", ["$2 \\sin x$", "$2 \\sin x \\cos x$", "$\\sin x \\cos x$", "$\\cos^2 x$"], "B", "HARD", "Chain on $u^2$ with $u = \\sin x$. **B**", "chain-rule"),
  ],
  "product-rule": [
    m("Differentiate $x \\cdot e^x$:", ["$e^x$", "$x e^x$", "$(1 + x) e^x$", "$x + e^x$"], "C", "EASY", "$e^x + x e^x$. **C**", "product-rule"),
    m("Differentiate $x \\ln x$:", ["$\\ln x$", "$1 + \\ln x$", "$\\ln x + 1$", "$1/x$"], "C", "EASY", "$\\ln x + x \\cdot 1/x = \\ln x + 1$. **C**", "product-rule"),
    m("Differentiate $x \\sin x$:", ["$\\sin x + x \\cos x$", "$\\sin x \\cos x$", "$\\cos x$", "$x \\cos x$"], "A", "EASY", "Product rule. **A**", "product-rule"),
    m("Differentiate $(2 x + 1)(x - 3)$ (expand or product rule):", ["$2 x - 3$", "$4 x - 5$", "$2 x + 1$", "$4 x + 1$"], "B", "MEDIUM", "Expand: $2 x^2 - 5 x - 3$; derivative $4 x - 5$. **B**", "product-rule"),
    m("Differentiate $x^2 e^x$:", ["$2 x e^x$", "$(2 x + x^2) e^x$", "$2 x e^{x^2}$", "$e^x$"], "B", "MEDIUM", "$2 x e^x + x^2 e^x = e^x(2 x + x^2)$. **B**", "product-rule"),
    m("If $f(x) = x \\cos x$, then $f'(\\pi) =$:", ["$-1$", "$-\\pi$", "$0$", "$\\pi$"], "A", "MEDIUM", "$f'(x) = \\cos x - x \\sin x$; $f'(\\pi) = -1 - 0 = -1$. **A**", "product-rule"),
    m("Differentiate $e^x \\sin x$:", ["$e^x \\cos x$", "$e^x(\\sin x + \\cos x)$", "$e^x \\sin x$", "$\\sin x + \\cos x$"], "B", "MEDIUM", "Product rule. **B**", "product-rule"),
    m("$\\dfrac{d}{dx}[x^3 (1 - x)]$ at $x = 1$:", ["$0$", "$-1$", "$2$", "$3$"], "B", "MEDIUM", "$f'(x) = 3 x^2(1 - x) + x^3(-1) = 3 x^2 - 4 x^3$; $f'(1) = 3 - 4 = -1$. **B**", "product-rule"),
    m("If $f(x) = x^2 \\ln x$, then $f'(e) =$:", ["$e$", "$2 e$", "$3 e$", "$e^2$"], "C", "HARD", "$f'(x) = 2 x \\ln x + x$; $f'(e) = 2 e + e = 3 e$. **C**", "product-rule"),
    m("Differentiate $(x + 1) e^{x^2}$:", ["$e^{x^2}(1 + 2 x(x+1))$", "$e^{x^2}(1 + 2 x)$", "$e^{x^2}(x + 1)$", "$(x + 1) 2 x e^{x^2}$"], "A", "HARD", "$e^{x^2} + (x + 1) \\cdot 2 x e^{x^2}$. **A**", "product-rule"),
    m("Product rule for $u v w$ at $x_0$:", ["$u' v' w'$", "$u' v w + u v' w + u v w'$", "$u v w'$", "$(u v w)'$"], "B", "HARD", "Generalization. **B**", "product-rule"),
    m("If $f(x) = x \\cdot e^{-x}$, find max for $x \\geq 0$:", ["$x = 0$", "$x = 1$", "$x = 1/e$", "$x = e$"], "B", "HARD", "$f'(x) = e^{-x}(1 - x) = 0 \\Rightarrow x = 1$. **B**", "product-rule"),
  ],
  "quotient-rule": [
    m("Differentiate $\\dfrac{1}{x^2}$:", ["$-2/x^3$", "$2/x^3$", "$-1/x^3$", "$1/x^3$"], "A", "EASY", "Power rule or quotient. **A**", "quotient-rule"),
    m("Differentiate $\\dfrac{x}{e^x}$:", ["$\\dfrac{1 - x}{e^x}$", "$\\dfrac{1 + x}{e^x}$", "$\\dfrac{x - 1}{e^x}$", "$\\dfrac{1}{e^x}$"], "A", "EASY", "Quotient rule. **A**", "quotient-rule"),
    m("Differentiate $\\dfrac{x^2}{x + 1}$:", ["$\\dfrac{x^2 + 2 x}{(x + 1)^2}$", "$\\dfrac{2 x}{x + 1}$", "$\\dfrac{x^2 - 2 x}{(x + 1)^2}$", "$2 x$"], "A", "MEDIUM", "$\\dfrac{2 x(x + 1) - x^2}{(x + 1)^2}$. **A**", "quotient-rule"),
    m("Differentiate $\\tan x$:", ["$\\sec^2 x$", "$-\\sec^2 x$", "$\\csc^2 x$", "$\\sec x \\tan x$"], "A", "MEDIUM", "Known. **A**", "quotient-rule"),
    m("Differentiate $\\dfrac{1}{\\sin x}$:", ["$-\\dfrac{\\cos x}{\\sin^2 x}$", "$\\dfrac{\\cos x}{\\sin^2 x}$", "$\\dfrac{1}{\\cos x}$", "$\\csc x \\cot x$"], "A", "MEDIUM", "Both A and D equivalent. **A**", "quotient-rule"),
    m("Differentiate $\\dfrac{e^x}{1 + e^x}$:", ["$\\dfrac{e^x}{(1 + e^x)^2}$", "$\\dfrac{1}{(1 + e^x)^2}$", "$\\dfrac{e^x}{1 + e^x}$", "$\\dfrac{1}{1 + e^x}$"], "A", "MEDIUM", "$\\dfrac{e^x(1 + e^x) - e^x \\cdot e^x}{(1 + e^x)^2} = \\dfrac{e^x}{(1 + e^x)^2}$. **A**", "quotient-rule"),
    m("$f(x) = \\dfrac{x - 1}{x + 1}$, $f'(0) =$:", ["$1$", "$2$", "$-1$", "$0$"], "B", "MEDIUM", "$f'(x) = \\dfrac{(x+1) - (x-1)}{(x+1)^2} = \\dfrac{2}{(x+1)^2}$; $f'(0) = 2$. **B**", "quotient-rule"),
    m("$f(x) = \\dfrac{2}{x^3}$, $f'(x) =$:", ["$-6/x^4$", "$6/x^4$", "$-2/x^4$", "$2/x^4$"], "A", "MEDIUM", "$2 x^{-3}$ ⇒ $-6 x^{-4}$. **A**", "quotient-rule"),
    m("$\\dfrac{d}{dx}\\left[\\dfrac{\\sin x}{x}\\right]$ at $x = \\pi$:", ["$0$", "$-1/\\pi$", "$-1/\\pi^2$", "$1/\\pi$"], "B", "HARD", "Quotient rule: $\\dfrac{x \\cos x - \\sin x}{x^2}$; at $\\pi$: $\\dfrac{\\pi (-1) - 0}{\\pi^2} = -1/\\pi$. **B**", "quotient-rule"),
    m("$f(x) = \\dfrac{x^2 + 1}{x}$ simplifies to:", ["$x + 1/x$", "$x^2/x + 1/x$", "$(x^2 + 1)/x$", "Both A and C"], "D", "HARD", "All equivalent expressions. **D**", "quotient-rule"),
    m("$\\dfrac{d}{dx}\\left[\\dfrac{x}{\\ln x}\\right]$:", ["$\\dfrac{\\ln x - 1}{(\\ln x)^2}$", "$\\dfrac{1 - \\ln x}{(\\ln x)^2}$", "$1/\\ln x$", "$1/x$"], "A", "HARD", "$\\dfrac{\\ln x - x \\cdot 1/x}{(\\ln x)^2} = \\dfrac{\\ln x - 1}{(\\ln x)^2}$. **A**", "quotient-rule"),
    m("Stationary points of $f(x) = \\dfrac{x}{x^2 + 1}$:", ["$x = 0$", "$x = \\pm 1$", "$x = 1$", "no stationary points"], "B", "HARD", "$f'(x) = \\dfrac{1 - x^2}{(x^2 + 1)^2} = 0 \\Rightarrow x = \\pm 1$. **B**", "quotient-rule"),
  ],
  "tangents-and-normals": [
    m("Tangent slope to $y = x^2$ at $x = 0$:", ["$0$", "$1$", "$2$", "$x$"], "A", "EASY", "$y' = 2 x$. **A**", "tangents-and-normals"),
    m("Tangent to $y = x$ at any point has slope:", ["$0$", "$1$", "$x$", "varies"], "B", "EASY", "$y' = 1$. **B**", "tangents-and-normals"),
    m("Equation of tangent to $y = 3$ at $x = 5$:", ["$y = 3$", "$y = 5$", "$x = 3$", "$x = 5$"], "A", "EASY", "Constant function. **A**", "tangents-and-normals"),
    m("Tangent to $y = x^3$ at $x = 2$ has slope:", ["$3$", "$6$", "$12$", "$8$"], "C", "MEDIUM", "$y' = 3 x^2$; $y'(2) = 12$. **C**", "tangents-and-normals"),
    m("Normal slope = $-1$/tangent slope when they are:", ["parallel", "perpendicular", "equal", "horizontal"], "B", "MEDIUM", "Perpendicular slopes. **B**", "tangents-and-normals"),
    m("Tangent to $y = \\ln x$ at $x = 1$:", ["$y = x - 1$", "$y = x + 1$", "$y = x$", "$y = 1 - x$"], "A", "MEDIUM", "$y(1) = 0$, $y'(1) = 1$. **A**", "tangents-and-normals"),
    m("Tangent to $y = e^x$ at $x = 1$ passes through:", ["$(0, 0)$", "$(0, e)$", "$(1, 1)$", "$(0, 1)$"], "A", "MEDIUM", "$y - e = e(x - 1) \\Rightarrow y = e x$. At $x = 0$: $y = 0$. **A**", "tangents-and-normals"),
    m("Normal to $y = x^2$ at $(1, 1)$ passes through:", ["$(0, 3/2)$", "$(3, 2)$", "$(0, 1)$", "$(2, 1)$"], "A", "MEDIUM", "Normal slope $-1/2$; eq $y - 1 = -(1/2)(x - 1) \\Rightarrow y = -x/2 + 3/2$. At $x = 0$: $y = 3/2$. **A**", "tangents-and-normals"),
    m("$y = x^2$ has tangent parallel to $y = 4 x - 7$ at $x =$:", ["$1$", "$2$", "$4$", "$-2$"], "B", "HARD", "$y' = 2 x = 4 \\Rightarrow x = 2$. **B**", "tangents-and-normals"),
    m("Tangent to $y = \\sin x$ at origin has slope:", ["$0$", "$1$", "$-1$", "$\\pi$"], "B", "HARD", "$y' = \\cos 0 = 1$. **B**", "tangents-and-normals"),
    m("Tangent to $y = x^3$ at the origin:", ["$y = 0$", "$y = x$", "$y = -x$", "vertical"], "A", "HARD", "$y'(0) = 0$; tangent is x-axis. **A**", "tangents-and-normals"),
    m("Two tangents to $y = x^2$ from outside point — when does only one exist?", ["when point is on the curve", "never", "always two", "if vertical"], "A", "HARD", "From a point ON the curve, only one tangent — at that point. **A**", "tangents-and-normals"),
  ],
  "rates-of-change": [
    m("If $V(t) = t^2$, then $V'(2) =$:", ["$2$", "$4$", "$6$", "$8$"], "B", "EASY", "$V'(t) = 2 t$. **B**", "rates-of-change"),
    m("Average rate of $f(x) = x^3$ over $[0, 2]$:", ["$2$", "$4$", "$6$", "$8$"], "B", "EASY", "$(8 - 0)/2 = 4$. **B**", "rates-of-change"),
    m("Velocity of $s(t) = 5 t$ at any time:", ["$0$", "$5$", "$5 t$", "$10 t$"], "B", "EASY", "Constant. **B**", "rates-of-change"),
    m("If $s(t) = 10 - t^2$, particle is at rest when:", ["$t = 0$", "$t = 5$", "$t = 10$", "$t = -1$"], "A", "MEDIUM", "$s'(t) = -2 t = 0 \\Rightarrow t = 0$. **A**", "rates-of-change"),
    m("Acceleration of $s(t) = t^3 - 6 t^2 + 12 t$ at $t = 1$:", ["$3$", "$-6$", "$0$", "$6$"], "B", "MEDIUM", "$v = 3 t^2 - 12 t + 12$; $a = 6 t - 12$; $a(1) = -6$. **B**", "rates-of-change"),
    m("Rate of $A = \\pi r^2$ when $r = 5$ and $dr/dt = 0.1$:", ["$\\pi$", "$\\pi/2$", "$2\\pi$", "$0.5\\pi$"], "A", "MEDIUM", "$dA/dt = 2\\pi r \\cdot 0.1 = \\pi$. **A**", "rates-of-change"),
    m("$V(t) = 100 e^{-0.1 t}$, $V'(0) =$:", ["$-10$", "$10$", "$100$", "$-100$"], "A", "MEDIUM", "$V'(t) = -10 e^{-0.1 t}$; $V'(0) = -10$. **A**", "rates-of-change"),
    m("If $f'(x_0) > 0$, function is:", ["decreasing at $x_0$", "increasing at $x_0$", "constant at $x_0$", "max at $x_0$"], "B", "MEDIUM", "Positive derivative ⇒ increasing. **B**", "rates-of-change"),
    m("Particle $x = t^2 - 4 t$, when is velocity 0?", ["$t = 0$", "$t = 2$", "$t = 4$", "$t = -2$"], "B", "HARD", "$v = 2 t - 4 = 0$. **B**", "rates-of-change"),
    m("$T(t) = 20 + 5 \\sin t$ models temperature. Max rate of change occurs at $t =$:", ["$0$", "$\\pi/2$", "$\\pi$", "$2\\pi$"], "A", "HARD", "$T'(t) = 5 \\cos t$; max at $t = 0$. **A**", "rates-of-change"),
    m("Spherical balloon's volume grows at 4π cm³/s; when $r = 2$, $dr/dt =$:", ["$1/4$", "$1/2$", "$1$", "$2$"], "A", "HARD", "$dV/dt = 4\\pi r^2 dr/dt$; $4\\pi = 16\\pi dr/dt \\Rightarrow 1/4$. **A**", "rates-of-change"),
    m("Average rate $\\neq$ instantaneous rate unless:", ["always equal", "$f$ linear", "$f$ constant", "Both B and C"], "D", "HARD", "Linear or constant: rates equal. **D**", "rates-of-change"),
  ],
  "stationary-points-and-curve-sketching": [
    m("$f'(c) = 0$ defines:", ["a stationary point", "a max", "a min", "an inflection point"], "A", "EASY", "By definition. **A**", "stationary-points-and-curve-sketching"),
    m("If $f'' > 0$ at a stationary point, it's:", ["max", "min", "inflection", "depends"], "B", "EASY", "Second derivative test. **B**", "stationary-points-and-curve-sketching"),
    m("Number of stationary points of $f(x) = x^2$:", ["0", "1", "2", "infinitely many"], "B", "EASY", "$f'(x) = 2 x = 0$ at $x = 0$. **B**", "stationary-points-and-curve-sketching"),
    m("Stationary point of $f(x) = -3 x^2 + 6 x$:", ["$(0, 0)$", "$(1, 3)$", "$(2, 0)$", "$(3, -9)$"], "B", "MEDIUM", "$f'(x) = -6 x + 6 = 0 \\Rightarrow x = 1$; $f(1) = 3$. **B**", "stationary-points-and-curve-sketching"),
    m("$f(x) = x^3 - 12 x$ has stationary points at:", ["$x = 0, \\pm 2$", "$x = \\pm 2$", "$x = 0, \\pm 4$", "no stationary points"], "B", "MEDIUM", "$f'(x) = 3 x^2 - 12 = 0 \\Rightarrow x = \\pm 2$. **B**", "stationary-points-and-curve-sketching"),
    m("$f(x) = x^4$ has at $x = 0$:", ["max", "min", "inflection", "no stationary"], "B", "MEDIUM", "$f''(0) = 0$ but $f$ is non-negative everywhere with min at 0. **B**", "stationary-points-and-curve-sketching"),
    m("Number of local minima of $f(x) = x^4 - 4 x^2$:", ["0", "1", "2", "3"], "C", "MEDIUM", "$f'(x) = 4 x^3 - 8 x = 0 \\Rightarrow x = 0, \\pm\\sqrt 2$; at $\\pm\\sqrt 2$ are minima. **C**", "stationary-points-and-curve-sketching"),
    m("Inflection point of $f(x) = x^3$:", ["$x = 0$", "$x = 1$", "$x = -1$", "no inflection"], "A", "MEDIUM", "$f''(x) = 6 x$ changes sign at 0. **A**", "stationary-points-and-curve-sketching"),
    m("Sign analysis of $f' < 0$ on $(a, b)$ means $f$ is:", ["increasing", "decreasing", "constant", "discontinuous"], "B", "HARD", "Negative derivative ⇒ decreasing. **B**", "stationary-points-and-curve-sketching"),
    m("Stationary point of $f(x) = x e^{-x}$ for $x \\geq 0$:", ["$x = 0$", "$x = 1$", "$x = e$", "$x = 1/e$"], "B", "HARD", "$f'(x) = e^{-x}(1 - x) = 0 \\Rightarrow x = 1$. **B**", "stationary-points-and-curve-sketching"),
    m("Concavity of $f(x) = e^x$:", ["concave up everywhere", "concave down", "changes at $x = 0$", "linear"], "A", "HARD", "$f'' = e^x > 0$. **A**", "stationary-points-and-curve-sketching"),
    m("$f(x) = \\ln x$ is concave:", ["up always", "down always", "changes sign", "neither"], "B", "HARD", "$f''(x) = -1/x^2 < 0$. **B**", "stationary-points-and-curve-sketching"),
  ],
  "optimisation": [
    m("Among rectangles with perimeter 40, max area:", ["$50$", "$100$", "$200$", "$400$"], "B", "EASY", "Square with side 10. **B**", "optimisation"),
    m("Min surface area cylinder given $V$ has $h$ equal to:", ["$r$", "$2 r$", "$r/2$", "$\\sqrt r$"], "B", "EASY", "Calculus result. **B**", "optimisation"),
    m("Max area triangle with hypotenuse 6:", ["$3$", "$6$", "$9$", "$18$"], "C", "EASY", "Legs $3\\sqrt 2$; area $= (3\\sqrt 2)^2/2 = 9$. **C**", "optimisation"),
    m("Max of $-x^2 + 6 x - 5$:", ["$3$", "$4$", "$5$", "$9$"], "B", "MEDIUM", "Vertex at $x = 3$: $-9 + 18 - 5 = 4$. **B**", "optimisation"),
    m("Min of $x^2 - 4 x + 7$:", ["$3$", "$4$", "$7$", "$11$"], "A", "MEDIUM", "Vertex at $x = 2$: $4 - 8 + 7 = 3$. **A**", "optimisation"),
    m("Two positive numbers with sum 100, max product:", ["$2500$", "$5000$", "$10000$", "$50$"], "A", "MEDIUM", "$50 \\times 50 = 2500$. **A**", "optimisation"),
    m("Open box volume max when corner cut for $20 \\times 20$ sheet:", ["$x = 10/3$", "$x = 5$", "$x = 5/3$", "$x = 20/3$"], "A", "MEDIUM", "$V = x(20 - 2 x)^2$ ⇒ $x = 10/3$. **A**", "optimisation"),
    m("Distance min from $(0, 0)$ to line $y = x + 4$:", ["$2\\sqrt 2$", "$4$", "$2$", "$4\\sqrt 2$"], "A", "MEDIUM", "$|0 - 0 + 4|/\\sqrt 2 = 2\\sqrt 2$. **A**", "optimisation"),
    m("Right circular cylinder of fixed volume, min surface area when $h = 2 r$. Then $h/d = $:", ["$1/2$", "$1$", "$2$", "$\\pi$"], "B", "HARD", "$d = 2 r$ ⇒ $h/d = 1$. **B**", "optimisation"),
    m("Of rectangles inscribed in semicircle of radius 1 (base on diameter), max area:", ["$\\sqrt 2/2$", "$1$", "$\\pi/4$", "$2$"], "B", "HARD", "Corner $(\\sin\\theta, \\cos\\theta)$; area $2\\sin\\theta\\cos\\theta = \\sin(2\\theta)$ ⇒ max 1 at $\\theta = \\pi/4$. **B**", "optimisation"),
    m("Of all right triangles with hypotenuse 10, max area:", ["$10$", "$25$", "$50$", "$100$"], "B", "HARD", "Legs $5\\sqrt 2$; area $= 50/2 = 25$. **B**", "optimisation"),
    m("Min cost when $C(x) = x^2 + 100/x$ for $x > 0$:", ["$x = 5$", "$x = \\sqrt[3]{50}$", "$x = 10$", "$x = \\sqrt[3]{100}$"], "B", "HARD", "$C'(x) = 2 x - 100/x^2 = 0 \\Rightarrow x^3 = 50$. **B**", "optimisation"),
  ],
  "antidifferentiation": [
    m("$\\int 1 \\, dx =$:", ["$0$", "$x$", "$1$", "$x + C$"], "D", "EASY", "Antiderivative of 1. **D**", "antidifferentiation"),
    m("$\\int 0 \\, dx =$:", ["$0$", "$x$", "$C$", "$1$"], "C", "EASY", "Constant. **C**", "antidifferentiation"),
    m("$\\int x \\, dx =$:", ["$x$", "$x^2$", "$\\dfrac{x^2}{2} + C$", "$1$"], "C", "EASY", "Power rule. **C**", "antidifferentiation"),
    m("$\\int x^5 \\, dx =$:", ["$5 x^4$", "$\\dfrac{x^6}{6} + C$", "$x^6 + C$", "$\\dfrac{x^5}{5} + C$"], "B", "MEDIUM", "Power rule. **B**", "antidifferentiation"),
    m("$\\int 2 \\, dx =$:", ["$0$", "$2$", "$2 x + C$", "$x^2 + C$"], "C", "MEDIUM", "Linearity. **C**", "antidifferentiation"),
    m("$\\int e^{- x} \\, dx =$:", ["$e^{-x}$", "$-e^{-x} + C$", "$-e^x + C$", "$e^{-x}/x$"], "B", "MEDIUM", "Reverse chain. **B**", "antidifferentiation"),
    m("$\\int 1/x \\, dx$ for $x > 0$:", ["$\\ln x + C$", "$-1/x^2 + C$", "$x \\ln x + C$", "$1$"], "A", "MEDIUM", "Standard. **A**", "antidifferentiation"),
    m("$\\int (3 x^2 - 4) \\, dx =$:", ["$x^3 - 4 x + C$", "$x^3 - 4 + C$", "$6 x - 4 x + C$", "$x^3 + 4 x + C$"], "A", "MEDIUM", "Term by term. **A**", "antidifferentiation"),
    m("If $F'(x) = 2 x$ and $F(1) = 3$, $F(x) =$:", ["$x^2$", "$x^2 + 2$", "$x^2 + 3$", "$2 x + 1$"], "B", "HARD", "$F = x^2 + C$; $F(1) = 1 + C = 3 \\Rightarrow C = 2$. **B**", "antidifferentiation"),
    m("$\\int \\cos(2 x) \\, dx =$:", ["$\\dfrac{\\sin(2 x)}{2} + C$", "$2 \\sin(2 x) + C$", "$-\\sin(2 x) + C$", "$\\sin(2 x) + C$"], "A", "HARD", "Reverse chain. **A**", "antidifferentiation"),
    m("$\\int x^{1/2} \\, dx =$:", ["$\\dfrac{2 x^{3/2}}{3} + C$", "$\\dfrac{x^{3/2}}{3} + C$", "$\\dfrac{x^{-1/2}}{2}$", "$x^{3/2}$"], "A", "HARD", "$x^{(1/2) + 1}/(3/2) = (2/3) x^{3/2}$. **A**", "antidifferentiation"),
    m("If $f''(x) = 6 x$ and $f'(0) = 1$, $f'(1) =$:", ["$0$", "$3$", "$4$", "$7$"], "C", "HARD", "$f'(x) = 3 x^2 + C = 3 x^2 + 1$; $f'(1) = 4$. **C**", "antidifferentiation"),
  ],
  "definite-integrals": [
    m("$\\int_0^1 1 \\, dx =$:", ["$0$", "$1$", "$x$", "$\\infty$"], "B", "EASY", "Area of $1 \\times 1$. **B**", "definite-integrals"),
    m("$\\int_a^a f(x) \\, dx =$:", ["$0$", "$f(a)$", "$1$", "depends"], "A", "EASY", "Zero-width interval. **A**", "definite-integrals"),
    m("$\\int_0^2 2 x \\, dx =$:", ["$2$", "$4$", "$8$", "$1$"], "B", "EASY", "$[x^2]_0^2 = 4$. **B**", "definite-integrals"),
    m("$\\int_0^1 x^3 \\, dx =$:", ["$1/2$", "$1/3$", "$1/4$", "$1$"], "C", "MEDIUM", "$[x^4/4]_0^1 = 1/4$. **C**", "definite-integrals"),
    m("$\\int_{-2}^2 x^2 \\, dx =$:", ["$4$", "$8/3$", "$16/3$", "$8$"], "C", "MEDIUM", "Even function: $2 \\int_0^2 x^2 = 2 \\cdot 8/3$. **C**", "definite-integrals"),
    m("$\\int_0^\\pi \\cos x \\, dx =$:", ["$0$", "$1$", "$-1$", "$2$"], "A", "MEDIUM", "$[\\sin x]_0^\\pi = 0$. **A**", "definite-integrals"),
    m("If $\\int_0^a f(x) dx = 5$ and $\\int_0^a g(x) dx = 3$, $\\int_0^a (f + g) dx =$:", ["$15$", "$8$", "$-2$", "$2$"], "B", "MEDIUM", "Linearity. **B**", "definite-integrals"),
    m("$\\int_0^1 e^{- x} dx =$:", ["$e$", "$1 - 1/e$", "$1/e$", "$e - 1$"], "B", "MEDIUM", "$[-e^{-x}]_0^1 = 1 - 1/e$. **B**", "definite-integrals"),
    m("$\\int_1^4 \\dfrac{1}{x} dx =$:", ["$\\ln 4$", "$\\ln 3$", "$3$", "$2$"], "A", "HARD", "$[\\ln x]_1^4 = \\ln 4$. **A**", "definite-integrals"),
    m("If $\\int_0^2 f(x) dx = 6$, $\\int_2^0 f(x) dx =$:", ["$0$", "$6$", "$-6$", "$1/6$"], "C", "HARD", "Negate when limits swap. **C**", "definite-integrals"),
    m("$\\int_{-1}^1 x^5 \\, dx =$:", ["$0$", "$1/3$", "$2/3$", "$2$"], "A", "HARD", "Odd function. **A**", "definite-integrals"),
    m("$\\int_0^{\\pi/2} \\sin x \\, dx =$:", ["$0$", "$1$", "$2$", "$\\pi/2$"], "B", "HARD", "$[-\\cos x]_0^{\\pi/2} = 1$. **B**", "definite-integrals"),
  ],
  "area-under-curves": [
    m("Area under $y = 1$ on $[0, 5]$:", ["$1$", "$5$", "$10$", "$25$"], "B", "EASY", "Rectangle $1 \\times 5$. **B**", "area-under-curves"),
    m("Area under $y = x$ on $[0, 4]$:", ["$4$", "$8$", "$16$", "$2$"], "B", "EASY", "Triangle. **B**", "area-under-curves"),
    m("Area between $y = x^2$ and $x$-axis on $[0, 3]$:", ["$3$", "$9$", "$27$", "$9$"], "B", "EASY", "$[x^3/3]_0^3 = 9$. **B**", "area-under-curves"),
    m("Area between $y = \\sin x$ and $y = 0$ on $[0, \\pi]$:", ["$0$", "$1$", "$2$", "$\\pi$"], "C", "MEDIUM", "$[-\\cos]_0^\\pi = 2$. **C**", "area-under-curves"),
    m("Area between $y = 2 x$ and $y = x^2$:", ["$2/3$", "$4/3$", "$8/3$", "$2$"], "B", "MEDIUM", "$\\int_0^2 (2 x - x^2) = 4 - 8/3 = 4/3$. **B**", "area-under-curves"),
    m("Average value of $f(x) = x$ on $[0, 4]$:", ["$2$", "$4$", "$8$", "$16$"], "A", "MEDIUM", "$(8)/4 = 2$. **A**", "area-under-curves"),
    m("Area under $y = e^x$ on $[0, 1]$:", ["$1$", "$e$", "$e - 1$", "$2 e$"], "C", "MEDIUM", "$[e^x]_0^1 = e - 1$. **C**", "area-under-curves"),
    m("Area between $y = x$ and $y = x^2$ on $[0, 1]$:", ["$1/6$", "$1/3$", "$1/2$", "$1$"], "A", "MEDIUM", "$\\int_0^1 (x - x^2) = 1/2 - 1/3 = 1/6$. **A**", "area-under-curves"),
    m("Average value of $\\sin x$ on $[0, \\pi]$:", ["$0$", "$1/\\pi$", "$2/\\pi$", "$1$"], "C", "HARD", "$(1/\\pi) \\int_0^\\pi \\sin = (1/\\pi)(2) = 2/\\pi$. **C**", "area-under-curves"),
    m("Total area between $y = x$ and x-axis on $[-2, 2]$:", ["$0$", "$2$", "$4$", "$8$"], "C", "HARD", "Two triangles, each area 2; total 4. **C**", "area-under-curves"),
    m("Area between $y = x^3$ and x-axis on $[-1, 1]$ (total, not signed):", ["$0$", "$1/4$", "$1/2$", "$1$"], "C", "HARD", "Two equal regions, each 1/4. Total = 1/2. **C**", "area-under-curves"),
    m("Region bounded by $y = \\cos x$ and $y = 0$ on $[0, 2\\pi]$ (total area):", ["$2$", "$4$", "$0$", "$\\pi$"], "B", "HARD", "Four equal halves of full sin wave; total 4. **B**", "area-under-curves"),
  ],
  "fundamental-theorem-of-calculus": [
    m("FTC states: $\\int_a^b f'(x) dx = $:", ["$f(b) f(a)$", "$f(b) + f(a)$", "$f(b) - f(a)$", "$f'(b)$"], "C", "EASY", "Standard form. **C**", "fundamental-theorem-of-calculus"),
    m("$\\dfrac{d}{dx}\\int_0^x t \\, dt$ equals:", ["$x$", "$x^2/2$", "$0$", "$1$"], "A", "EASY", "FTC. **A**", "fundamental-theorem-of-calculus"),
    m("$\\dfrac{d}{dx}\\int_2^x \\sin t \\, dt$:", ["$\\sin x$", "$\\cos x$", "$-\\cos x$", "$\\sin 2$"], "A", "EASY", "FTC. **A**", "fundamental-theorem-of-calculus"),
    m("$F(x) = \\int_0^x e^t \\, dt$. Then $F(1) =$:", ["$1$", "$e - 1$", "$e$", "$0$"], "B", "MEDIUM", "$F(x) = e^x - 1$. **B**", "fundamental-theorem-of-calculus"),
    m("If $F(x) = \\int_3^{x^2} t \\, dt$, then $F'(x) =$:", ["$2 x^3$", "$2 x \\cdot x^2 = 2 x^3$", "$x^2$", "Both A and B"], "D", "MEDIUM", "Chain + FTC: $x^2 \\cdot 2 x = 2 x^3$. **D**", "fundamental-theorem-of-calculus"),
    m("$\\int_a^b f'(x) dx$ is the:", ["area", "net change in $f$", "average $f$", "derivative"], "B", "MEDIUM", "Net change theorem. **B**", "fundamental-theorem-of-calculus"),
    m("Using FTC: $\\int_0^1 3 x^2 dx =$:", ["$0$", "$1$", "$3$", "$6$"], "B", "MEDIUM", "$[x^3]_0^1 = 1$. **B**", "fundamental-theorem-of-calculus"),
    m("Using FTC, $\\int_1^e 1/x \\, dx =$:", ["$0$", "$1$", "$e$", "$e - 1$"], "B", "MEDIUM", "$[\\ln x]_1^e = 1$. **B**", "fundamental-theorem-of-calculus"),
    m("FTC requires $f$ to be:", ["continuous on $[a, b]$", "differentiable", "increasing", "polynomial"], "A", "HARD", "Continuity is the requirement. **A**", "fundamental-theorem-of-calculus"),
    m("$G(x) = \\int_x^5 f(t) dt$. Then $G'(x) =$:", ["$f(x)$", "$-f(x)$", "$f(5) - f(x)$", "$f(5)$"], "B", "HARD", "Variable in lower limit negates. **B**", "fundamental-theorem-of-calculus"),
    m("$\\int_a^b f'(x) dx + \\int_b^a f'(x) dx =$:", ["$2(f(b) - f(a))$", "$0$", "$f(a) + f(b)$", "$f(a)$"], "B", "HARD", "Adding integral with reverse — they cancel. **B**", "fundamental-theorem-of-calculus"),
    m("By FTC, $\\dfrac{d}{dx}\\int_a^b f(t) dt$ where $a, b$ constants:", ["$f(x)$", "$0$", "$f(b) - f(a)$", "$b - a$"], "B", "HARD", "No $x$ dependence. **B**", "fundamental-theorem-of-calculus"),
  ],
  // DATA
  "probability-rules": [
    m("$P(A) = 0.5$. Then $P(A') =$:", ["$0$", "$0.25$", "$0.5$", "$1$"], "C", "EASY", "Complement. **C**", "probability-rules"),
    m("If $A, B$ disjoint with $P(A) = 0.3$, $P(B) = 0.2$, then $P(A \\cup B) =$:", ["$0.06$", "$0.5$", "$0.1$", "$0.32$"], "B", "EASY", "Disjoint: sum. **B**", "probability-rules"),
    m("$P(\\emptyset) =$:", ["$0$", "$1$", "$1/2$", "$\\infty$"], "A", "EASY", "Empty event. **A**", "probability-rules"),
    m("$P(\\Omega) =$ (sample space):", ["$0$", "$1$", "$\\infty$", "depends"], "B", "MEDIUM", "Total probability. **B**", "probability-rules"),
    m("If $A, B$ independent with $P(A) = 0.4$, $P(B) = 0.5$, $P(A \\cap B) =$:", ["$0.9$", "$0.2$", "$0.1$", "$0.45$"], "B", "MEDIUM", "Multiply. **B**", "probability-rules"),
    m("$P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$ is called:", ["Bayes' rule", "inclusion-exclusion", "law of total probability", "independence"], "B", "MEDIUM", "Standard name. **B**", "probability-rules"),
    m("Two dice rolled, $P(\\text{both even}) =$:", ["$1/2$", "$1/4$", "$1/3$", "$2/3$"], "B", "MEDIUM", "$1/2 \\times 1/2$. **B**", "probability-rules"),
    m("$P(\\text{at least 1 head in 3 flips})$:", ["$1/8$", "$7/8$", "$3/8$", "$1/2$"], "B", "MEDIUM", "$1 - (1/2)^3$. **B**", "probability-rules"),
    m("$P(A) + P(A') =$:", ["$0$", "$1$", "$P(A)$", "depends"], "B", "HARD", "Complement law. **B**", "probability-rules"),
    m("If $P(A | B) = P(A)$, then:", ["$P(B | A) = 0$", "$A, B$ independent", "$P(A) = P(B)$", "$A \\subset B$"], "B", "HARD", "Independence definition. **B**", "probability-rules"),
    m("Probability range: $P(E)$ satisfies:", ["$P \\geq 0$", "$0 \\leq P \\leq 1$", "$P > 0$", "$P \\leq 1$"], "B", "HARD", "Axioms. **B**", "probability-rules"),
    m("Drawing 2 cards without replacement from 52, $P(\\text{both aces})$:", ["$1/169$", "$4/52$", "$\\dfrac{4}{52} \\cdot \\dfrac{3}{51}$", "$\\dfrac{4}{52} \\cdot \\dfrac{4}{52}$"], "C", "HARD", "Without replacement. **C**", "probability-rules"),
  ],
  "conditional-probability": [
    m("$P(A | B) =$:", ["$P(A) P(B)$", "$\\dfrac{P(A \\cap B)}{P(B)}$", "$\\dfrac{P(B)}{P(A)}$", "$P(A) + P(B)$"], "B", "EASY", "Definition. **B**", "conditional-probability"),
    m("$P(B | B) =$:", ["$0$", "$1$", "$P(B)$", "depends"], "B", "EASY", "Certain. **B**", "conditional-probability"),
    m("If $P(A | B) = P(A)$, then $A, B$ are:", ["disjoint", "independent", "complementary", "equal"], "B", "EASY", "Independence. **B**", "conditional-probability"),
    m("$P(A \\cap B) = $:", ["$P(A) P(B)$ if independent", "$P(A | B) P(B)$ always", "$P(A) + P(B)$", "Both A and B (B unconditionally)"], "D", "MEDIUM", "B always true, A when independent. **D**", "conditional-probability"),
    m("$P(A | B) > P(A)$ means:", ["$A, B$ independent", "$B$ makes $A$ more likely", "$A$ implies $B$", "$P(B) = 0$"], "B", "MEDIUM", "Positive dependence. **B**", "conditional-probability"),
    m("If $P(A) = 0.5$, $P(B) = 0.4$, $P(A \\cap B) = 0.2$, then $P(A | B) =$:", ["$0.5$", "$0.4$", "$0.8$", "$0.2$"], "A", "MEDIUM", "$0.2/0.4 = 0.5$. **A**", "conditional-probability"),
    m("In an urn, 2 of 5 balls are red. $P(\\text{2nd red} | \\text{1st red})$:", ["$1/4$", "$2/5$", "$1/2$", "$3/4$"], "A", "MEDIUM", "After 1 red, 1 of 4 left. **A**", "conditional-probability"),
    m("If $A \\subset B$, then $P(A | B) =$:", ["$P(A)/P(B)$", "$P(A) + P(B)$", "$1$", "$0$"], "A", "MEDIUM", "Direct from definition. **A**", "conditional-probability"),
    m("Bayes' rule: $P(A | B) =$:", ["$P(B | A) P(A)/P(B)$", "$P(B | A)$", "$P(A)/P(B)$", "$P(A) P(B)$"], "A", "HARD", "Standard. **A**", "conditional-probability"),
    m("Tree diagram: $P(\\text{branch}) =$ product of:", ["all probabilities along path", "first probability", "last probability", "sum of probabilities"], "A", "HARD", "Multiplication rule. **A**", "conditional-probability"),
    m("If 60% of population female, 30% of females smoke, $P(\\text{female and smoke}) =$:", ["$0.18$", "$0.30$", "$0.50$", "$0.18$"], "A", "HARD", "$0.6 \\times 0.3 = 0.18$. **A**", "conditional-probability"),
    m("Two events independent and disjoint: only possible if:", ["$P(A) = P(B) = 0$", "always", "never", "$P(A) = P(B) = 1$"], "A", "HARD", "Disjoint + independent: $P(A) P(B) = 0$ ⇒ one is 0 (or both). **A**", "conditional-probability"),
  ],
  "discrete-random-variables": [
    m("Sum of probabilities for a discrete RV must equal:", ["$0$", "$1$", "$E[X]$", "depends"], "B", "EASY", "Total probability. **B**", "discrete-random-variables"),
    m("$E[X] = \\sum$:", ["$P(X = x)$", "$x P(X = x)$", "$x^2 P(X = x)$", "$x / n$"], "B", "EASY", "Expectation formula. **B**", "discrete-random-variables"),
    m("If $X = 1, 2, 3$ each with $P = 1/3$, $E[X] =$:", ["$1$", "$2$", "$3$", "$1/3$"], "B", "EASY", "Average. **B**", "discrete-random-variables"),
    m("Variance formula: $\\text{Var}(X) =$:", ["$E[X^2]$", "$E[X^2] - (E[X])^2$", "$(E[X])^2$", "$E[X] - E[X^2]$"], "B", "MEDIUM", "Computational form. **B**", "discrete-random-variables"),
    m("Standard deviation is:", ["variance", "$\\sqrt{\\text{variance}}$", "variance$^2$", "mean"], "B", "MEDIUM", "Definition. **B**", "discrete-random-variables"),
    m("If $\\text{Var}(X) = 9$, then sd $=$:", ["$3$", "$9$", "$81$", "$\\sqrt 9 = 3$"], "A", "MEDIUM", "$\\sqrt 9 = 3$. **A**", "discrete-random-variables"),
    m("$E[a X + b] =$:", ["$a E[X]$", "$a E[X] + b$", "$E[X] + b$", "$a + b$"], "B", "MEDIUM", "Linearity. **B**", "discrete-random-variables"),
    m("$\\text{Var}(a X + b) =$:", ["$a \\text{Var}(X)$", "$a^2 \\text{Var}(X)$", "$\\text{Var}(X) + b$", "$(a + b) \\text{Var}(X)$"], "B", "MEDIUM", "Scaling rule. **B**", "discrete-random-variables"),
    m("$X$ takes values 0, 1, 2 with prob 0.2, 0.5, 0.3. $E[X^2] =$:", ["$1.1$", "$1.7$", "$2.4$", "$1$"], "B", "HARD", "$0 + 0.5 + 1.2 = 1.7$. **B**", "discrete-random-variables"),
    m("If $E[X] = 5$ and $E[X^2] = 30$, $\\text{Var}(X) =$:", ["$5$", "$25$", "$30$", "$35$"], "A", "HARD", "$30 - 25 = 5$. **A**", "discrete-random-variables"),
    m("$X, Y$ independent, $\\text{Var}(X + Y) =$:", ["$\\text{Var}(X) + \\text{Var}(Y)$", "$\\text{Var}(X) \\text{Var}(Y)$", "$\\text{Var}(X) - \\text{Var}(Y)$", "always 0"], "A", "HARD", "Independent sum variance. **A**", "discrete-random-variables"),
    m("Two fair dice rolled; $X = $ sum. $P(X = 6) =$:", ["$1/6$", "$5/36$", "$1/36$", "$6/36$"], "B", "HARD", "5 combinations out of 36. **B**", "discrete-random-variables"),
  ],
  "binomial-distribution": [
    m("$X \\sim \\text{Bin}(n, p)$. Then $E[X] =$:", ["$p$", "$n p$", "$p/n$", "$n + p$"], "B", "EASY", "Formula. **B**", "binomial-distribution"),
    m("$\\text{Var}(X)$ for $\\text{Bin}(n, p) =$:", ["$n p$", "$n p^2$", "$n p (1 - p)$", "$p(1-p)$"], "C", "EASY", "Formula. **C**", "binomial-distribution"),
    m("$P(X = k)$ for $\\text{Bin}(n, p)$:", ["$p^k$", "$\\binom{n}{k} p^k (1-p)^{n-k}$", "$(1-p)^{n-k}$", "$n^k p$"], "B", "EASY", "Formula. **B**", "binomial-distribution"),
    m("$X \\sim \\text{Bin}(4, 0.5)$. $E[X] =$:", ["$1$", "$2$", "$0.5$", "$4$"], "B", "MEDIUM", "$n p = 2$. **B**", "binomial-distribution"),
    m("$X \\sim \\text{Bin}(10, 0.3)$. $P(X = 0) =$:", ["$0.7^{10}$", "$0.3^{10}$", "$0$", "$0.5$"], "A", "MEDIUM", "All failures. **A**", "binomial-distribution"),
    m("$X \\sim \\text{Bin}(10, 0.5)$. $P(X = 10) =$:", ["$1$", "$(0.5)^{10}$", "$0$", "$0.5$"], "B", "MEDIUM", "All successes. **B**", "binomial-distribution"),
    m("$X \\sim \\text{Bin}(20, 0.1)$. Sd:", ["$\\sqrt{1.8}$", "$\\sqrt 2$", "$2$", "$1.8$"], "A", "MEDIUM", "$\\sqrt{20 \\cdot 0.1 \\cdot 0.9} = \\sqrt{1.8}$. **A**", "binomial-distribution"),
    m("Number of successes ranges from:", ["$0$ to $n$", "$1$ to $n$", "$0$ to $\\infty$", "$0$ to $p$"], "A", "MEDIUM", "Standard. **A**", "binomial-distribution"),
    m("If $X \\sim \\text{Bin}(5, 0.4)$, $P(X = 2) =$:", ["$\\binom{5}{2}(0.4)^2(0.6)^3$", "$(0.4)^2$", "$\\binom{5}{2}(0.4)^3$", "$0.2$"], "A", "HARD", "Formula. **A**", "binomial-distribution"),
    m("If $X \\sim \\text{Bin}(n, p)$, mode is approximately:", ["$n p$", "$(n + 1) p$ rounded down", "$n$", "$p$"], "B", "HARD", "Standard result. **B**", "binomial-distribution"),
    m("For large $n$, $\\text{Bin}(n, p)$ approximated by:", ["uniform", "exponential", "normal", "Poisson"], "C", "HARD", "CLT. **C**", "binomial-distribution"),
    m("$X \\sim \\text{Bin}(3, 1/3)$, $P(X \\geq 1) =$:", ["$1/3$", "$2/3$", "$19/27$", "$8/27$"], "C", "HARD", "$1 - P(0) = 1 - (2/3)^3 = 1 - 8/27 = 19/27$. **C**", "binomial-distribution"),
  ],
  "continuous-random-variables": [
    m("For continuous $X$, $P(X = a) =$:", ["$f(a)$", "$0$", "$1$", "$a$"], "B", "EASY", "Always 0 for continuous. **B**", "continuous-random-variables"),
    m("$\\int_{-\\infty}^{\\infty} f(x) dx$ for valid pdf =", ["$0$", "$1$", "$\\infty$", "depends"], "B", "EASY", "Total probability. **B**", "continuous-random-variables"),
    m("$P(a \\leq X \\leq b) =$:", ["$\\int_a^b f(x) dx$", "$f(b) - f(a)$", "$b - a$", "$f(a) + f(b)$"], "A", "EASY", "Standard. **A**", "continuous-random-variables"),
    m("Uniform $X$ on $[0, 10]$, pdf $f(x) =$:", ["$1/10$", "$10$", "$1$", "$x/10$"], "A", "MEDIUM", "Constant pdf. **A**", "continuous-random-variables"),
    m("Uniform $X$ on $[2, 8]$, $E[X] =$:", ["$3$", "$5$", "$6$", "$8$"], "B", "MEDIUM", "Midpoint. **B**", "continuous-random-variables"),
    m("$E[X] = \\int x f(x) dx$ over:", ["$[a, b]$", "support of $X$", "$\\mathbb{R}$", "Both B and C"], "D", "MEDIUM", "Often over support, equivalently over $\\mathbb{R}$ where $f = 0$ elsewhere. **D**", "continuous-random-variables"),
    m("If $f(x) = c$ on $[0, 5]$, then $c =$:", ["$1$", "$1/5$", "$5$", "$0.2$"], "B", "MEDIUM", "$5 c = 1$. **B**", "continuous-random-variables"),
    m("Median for symmetric pdf about $\\mu$:", ["$\\mu$", "$0$", "depends", "$1/\\mu$"], "A", "MEDIUM", "Symmetry. **A**", "continuous-random-variables"),
    m("CDF $F(x) =$:", ["$\\int_{-\\infty}^x f(t) dt$", "$f(x)$", "$\\int f(x) dx$", "$P(X = x)$"], "A", "HARD", "Cumulative. **A**", "continuous-random-variables"),
    m("$F$ is monotonically:", ["increasing or constant", "decreasing", "constant", "varies"], "A", "HARD", "Non-decreasing. **A**", "continuous-random-variables"),
    m("Standard deviation has units:", ["squared units of $X$", "same as $X$", "no units", "$1/X$"], "B", "HARD", "Same as $X$ (variance has squared). **B**", "continuous-random-variables"),
    m("For exponential $X$ with rate $\\lambda$, $E[X] =$:", ["$\\lambda$", "$1/\\lambda$", "$\\lambda^2$", "$0$"], "B", "HARD", "Standard. **B**", "continuous-random-variables"),
  ],
  "normal-distribution": [
    m("Standard normal has mean and sd:", ["$0, 0$", "$0, 1$", "$1, 1$", "$1, 0$"], "B", "EASY", "Standard. **B**", "normal-distribution"),
    m("Normal pdf is symmetric about:", ["$0$", "the mean", "the median", "Both B and C"], "D", "EASY", "For normal, mean = median. **D**", "normal-distribution"),
    m("Total area under normal pdf:", ["$\\mu$", "$\\sigma$", "$1$", "$2\\pi$"], "C", "EASY", "Total probability. **C**", "normal-distribution"),
    m("$P(Z > 0)$ for standard normal:", ["$0$", "$0.25$", "$0.5$", "$1$"], "C", "MEDIUM", "Symmetric. **C**", "normal-distribution"),
    m("$P(\\mu - \\sigma < X < \\mu + \\sigma) \\approx$:", ["$50\\%$", "$68\\%$", "$95\\%$", "$99.7\\%$"], "B", "MEDIUM", "68-95-99.7 rule. **B**", "normal-distribution"),
    m("$z$ for $P(Z < z) = 0.5$:", ["$0$", "$0.5$", "$1$", "$-0.5$"], "A", "MEDIUM", "Median. **A**", "normal-distribution"),
    m("$P(\\mu - 2\\sigma < X < \\mu + 2\\sigma) \\approx$:", ["$68\\%$", "$95\\%$", "$99.7\\%$", "$50\\%$"], "B", "MEDIUM", "Empirical rule. **B**", "normal-distribution"),
    m("$X \\sim N(100, 25)$: $\\sigma = $:", ["$5$", "$25$", "$10$", "$2.5$"], "A", "MEDIUM", "$\\sqrt{25} = 5$. **A**", "normal-distribution"),
    m("Standardize $X \\sim N(\\mu, \\sigma^2)$:", ["$X / \\sigma$", "$(X - \\mu)/\\sigma$", "$X - \\mu$", "$X / \\mu$"], "B", "HARD", "Z-score. **B**", "normal-distribution"),
    m("$P(Z < 1) \\approx$:", ["$0.50$", "$0.68$", "$0.84$", "$0.95$"], "C", "HARD", "$\\Phi(1) \\approx 0.8413$. **C**", "normal-distribution"),
    m("$P(|Z| > 2) \\approx$:", ["$0.046$", "$0.32$", "$0.05$", "$0.025$"], "A", "HARD", "About 4.6%. **A**", "normal-distribution"),
    m("Normal approximation to binomial good when:", ["$n p \\geq 10$ and $n(1-p) \\geq 10$", "$n \\geq 30$ only", "$p = 0.5$ only", "always"], "A", "HARD", "Rule of thumb. **A**", "normal-distribution"),
  ],
  "confidence-intervals": [
    m("95% CI uses $z = $:", ["$1.645$", "$1.96$", "$2.0$", "$2.576$"], "B", "EASY", "Standard. **B**", "confidence-intervals"),
    m("99% CI vs 95% CI is:", ["narrower", "wider", "same", "depends on data"], "B", "EASY", "Higher confidence wider. **B**", "confidence-intervals"),
    m("Increasing $n$ makes CI:", ["wider", "narrower", "unchanged", "centred at 0"], "B", "EASY", "SE shrinks. **B**", "confidence-intervals"),
    m("Margin of error $=$:", ["$z \\cdot \\text{SE}$", "$z + \\text{SE}$", "$z / \\text{SE}$", "$\\hat p$"], "A", "MEDIUM", "Definition. **A**", "confidence-intervals"),
    m("$z = 1.645$ used for:", ["80% CI", "90% CI", "95% CI", "99% CI"], "B", "MEDIUM", "$z_{0.05}$. **B**", "confidence-intervals"),
    m("Smaller margin requires:", ["larger $n$", "smaller $n$", "larger $z$", "smaller $\\hat p$"], "A", "MEDIUM", "$\\text{ME} \\propto 1/\\sqrt n$. **A**", "confidence-intervals"),
    m("CI for $p$: center is:", ["$z$", "$\\hat p$", "$0.5$", "the true $p$"], "B", "MEDIUM", "Sample estimate. **B**", "confidence-intervals"),
    m("Halving margin requires multiplying $n$ by:", ["$2$", "$4$", "$\\sqrt 2$", "$1/2$"], "B", "MEDIUM", "SE $\\propto 1/\\sqrt n$. **B**", "confidence-intervals"),
    m("CI is a:", ["point estimate", "interval estimate", "hypothesis test", "probability"], "B", "HARD", "By name. **B**", "confidence-intervals"),
    m("The 95% means:", ["95% of the time true $p$ in this CI", "95% of CIs from such samples cover $p$", "$P(p \\in \\text{CI}) = 0.95$", "$\\hat p$ has 5% error"], "B", "HARD", "Frequentist interpretation. **B**", "confidence-intervals"),
    m("Conservative $\\hat p$ for sample-size planning:", ["$0$", "$1$", "$0.5$", "$\\hat p$ from prior data"], "C", "HARD", "Maximises $p(1-p)$. **C**", "confidence-intervals"),
    m("For $\\hat p = 0.5$, $n = 100$, 95% margin:", ["$\\approx 0.05$", "$\\approx 0.10$", "$\\approx 0.025$", "$\\approx 0.20$"], "B", "HARD", "$1.96 \\sqrt{0.25/100} \\approx 0.098$. **B**", "confidence-intervals"),
  ],
  "sample-proportions-and-sampling": [
    m("$\\hat p = $:", ["sample mean", "$X/n$", "true proportion", "$1 - p$"], "B", "EASY", "Definition. **B**", "sample-proportions-and-sampling"),
    m("$E[\\hat p] = $:", ["$\\hat p$", "$p$", "$n p$", "$1$"], "B", "EASY", "Unbiased. **B**", "sample-proportions-and-sampling"),
    m("$\\text{Var}(\\hat p) =$:", ["$p (1-p)$", "$p (1-p)/n$", "$n p (1-p)$", "$1/n$"], "B", "EASY", "Standard. **B**", "sample-proportions-and-sampling"),
    m("Sd of $\\hat p$ for $p = 0.5, n = 100$:", ["$0.5$", "$0.05$", "$0.005$", "$0.025$"], "B", "MEDIUM", "$\\sqrt{0.25/100} = 0.05$. **B**", "sample-proportions-and-sampling"),
    m("CLT says $\\hat p$ is approximately:", ["uniform", "normal", "binomial", "exponential"], "B", "MEDIUM", "Large $n$. **B**", "sample-proportions-and-sampling"),
    m("As $n \\to \\infty$, $\\hat p \\to$:", ["$0$", "$1$", "$p$ in probability", "uniformly"], "C", "MEDIUM", "Law of large numbers. **C**", "sample-proportions-and-sampling"),
    m("$\\hat p$ for sample $X \\sim \\text{Bin}(n, p)$:", ["$X/n$", "$X$", "$p$", "$n - X$"], "A", "MEDIUM", "Definition. **A**", "sample-proportions-and-sampling"),
    m("Increasing $n$ by factor 4 changes sd of $\\hat p$ by:", ["$\\times 4$", "$\\times 1/2$", "$\\times 1/4$", "unchanged"], "B", "MEDIUM", "$\\sqrt 4 = 2$, so sd halves. **B**", "sample-proportions-and-sampling"),
    m("$\\hat p$ unbiased means:", ["$E[\\hat p] = p$", "$\\hat p = p$", "$\\text{Var} = 0$", "$\\hat p$ is uniform"], "A", "HARD", "Unbiased estimator. **A**", "sample-proportions-and-sampling"),
    m("For $\\hat p$ to be approximately normal:", ["$n p \\geq 10$ and $n(1-p) \\geq 10$", "$n \\geq 100$", "$p = 0.5$", "always normal"], "A", "HARD", "Standard rule. **A**", "sample-proportions-and-sampling"),
    m("Sampling distribution refers to:", ["distribution of population", "distribution of $\\hat p$ across samples", "histogram of one sample", "true distribution"], "B", "HARD", "Definition. **B**", "sample-proportions-and-sampling"),
    m("$P(|\\hat p - p| < \\epsilon)$ as $n \\to \\infty$:", ["$\\to 0$", "$\\to 1$", "$\\to p$", "$\\to \\epsilon$"], "B", "HARD", "WLLN. **B**", "sample-proportions-and-sampling"),
  ],
};

let total = 0;
for (const [slug, mcqs] of Object.entries(SUBS)) {
  fs.writeFileSync(path.join(OUT_DIR, `qset-methods-w4-mcq-${slug}.json`),
    JSON.stringify({ mcq: mcqs, shortAnswer: [], extendedAnswer: [], extendedResponse: [] }, null, 2) + "\n");
  console.log(`${slug}: ${mcqs.length} MCQ`);
  total += mcqs.length;
}
console.log(`Total: ${total} MCQ across ${Object.keys(SUBS).length} subtopics.`);
