/** Wave 2 batch 3: Calculus MCQ — 12 subtopics × 8 = 96 MCQ. */
import * as fs from "fs";
import * as path from "path";

const OUT_DIR = "scripts/output";

interface MCQ {
  content: string; optionA: string; optionB: string; optionC: string; optionD: string;
  correctOption: "A" | "B" | "C" | "D"; marks: number; difficulty: "EASY" | "MEDIUM" | "HARD";
  solutionContent: string; subtopicSlugs: string[];
}
const m = (c: string, o: [string, string, string, string], k: "A" | "B" | "C" | "D",
  d: "EASY" | "MEDIUM" | "HARD", s: string, p: string, sec: string[] = []): MCQ =>
  ({ content: c, optionA: o[0], optionB: o[1], optionC: o[2], optionD: o[3], correctOption: k, marks: 1, difficulty: d, solutionContent: s, subtopicSlugs: [p, ...sec] });

const SUBTOPICS: Record<string, MCQ[]> = {
  "differentiation": [
    m("The derivative of $f(x) = x^5$ is:",
      ["$5 x^4$", "$x^4$", "$5 x^5$", "$\\dfrac{x^6}{6}$"], "A", "EASY",
      "Power rule. **Answer: A**", "differentiation"),
    m("The derivative of $f(x) = 7$ is:",
      ["$7$", "$1$", "$0$", "$7 x$"], "C", "EASY",
      "Derivative of a constant is 0. **Answer: C**", "differentiation"),
    m("The derivative of $f(x) = 3 x^2 - 4 x + 1$ is:",
      ["$6 x - 4$", "$6 x + 4$", "$3 x - 4$", "$6 x^2 - 4$"], "A", "EASY",
      "Term-by-term. **Answer: A**", "differentiation"),
    m("The derivative of $f(x) = \\sqrt x$ is:",
      ["$\\dfrac{1}{2 \\sqrt x}$", "$\\dfrac{1}{\\sqrt x}$", "$\\dfrac{1}{2 x}$", "$\\sqrt x$"], "A", "MEDIUM",
      "$\\sqrt x = x^{1/2}$; derivative is $\\dfrac{1}{2} x^{-1/2}$. **Answer: A**", "differentiation"),
    m("The derivative of $f(x) = e^{3 x}$ is:",
      ["$e^{3 x}$", "$3 e^{3 x}$", "$3 x e^{3 x}$", "$\\dfrac{e^{3 x}}{3}$"], "B", "MEDIUM",
      "Chain rule. **Answer: B**", "differentiation"),
    m("If $f(x) = \\ln(x)$, then $f'(2) =$:",
      ["$\\dfrac{1}{2}$", "$2$", "$\\ln 2$", "$\\dfrac{1}{\\ln 2}$"], "A", "MEDIUM",
      "$f'(x) = 1/x$, so $f'(2) = 1/2$. **Answer: A**", "differentiation"),
    m("If $f(x) = \\sin(x) \\cos(x)$, then $f'(\\pi/4) =$:",
      ["$0$", "$1$", "$\\dfrac{1}{2}$", "$-1$"], "A", "HARD",
      "$f = \\dfrac{1}{2}\\sin(2x)$, $f' = \\cos(2x)$. $f'(\\pi/4) = \\cos(\\pi/2) = 0$. **Answer: A**", "differentiation"),
    m("$\\displaystyle\\lim_{h \\to 0} \\dfrac{f(x + h) - f(x)}{h}$ is:",
      ["the average rate", "the second derivative", "the derivative $f'(x)$", "$0$"], "C", "HARD",
      "Definition of the derivative. **Answer: C**", "differentiation"),
  ],
  "chain-rule": [
    m("The derivative of $(2 x + 1)^3$ is:",
      ["$3(2 x + 1)^2$", "$6(2 x + 1)^2$", "$(2 x + 1)^2$", "$2(2 x + 1)^3$"], "B", "EASY",
      "Outer: $3 u^2$; inner: $2$; product: $6(2x+1)^2$. **Answer: B**", "chain-rule"),
    m("The derivative of $e^{x^2}$ is:",
      ["$e^{x^2}$", "$2 x e^{x^2}$", "$2 x^2 e^{x^2}$", "$e^{2 x}$"], "B", "EASY",
      "Inner derivative: $2 x$. **Answer: B**", "chain-rule"),
    m("The derivative of $\\sin(3 x)$ is:",
      ["$\\cos(3 x)$", "$3 \\cos(3 x)$", "$3 x \\cos(3 x)$", "$\\dfrac{1}{3} \\cos(3 x)$"], "B", "EASY",
      "Inner: $3$. **Answer: B**", "chain-rule"),
    m("The derivative of $\\ln(x^2 + 1)$ is:",
      ["$\\dfrac{1}{x^2 + 1}$", "$\\dfrac{2 x}{x^2 + 1}$", "$\\dfrac{1}{2 x}$", "$\\dfrac{1}{x}$"], "B", "MEDIUM",
      "Chain rule with $u = x^2 + 1$. **Answer: B**", "chain-rule"),
    m("The derivative of $\\sqrt{1 - x^2}$ is:",
      ["$\\dfrac{1}{2\\sqrt{1 - x^2}}$", "$\\dfrac{-x}{\\sqrt{1 - x^2}}$", "$\\dfrac{-2 x}{2\\sqrt{1 - x^2}}$", "$-2 x \\sqrt{1 - x^2}$"], "B", "MEDIUM",
      "Outer: $\\dfrac{1}{2\\sqrt u}$; inner: $-2 x$; product: $\\dfrac{-x}{\\sqrt{1 - x^2}}$. **Answer: B**", "chain-rule"),
    m("If $y = \\cos^2 x$, then $\\dfrac{dy}{dx} =$:",
      ["$2 \\cos x$", "$-2 \\cos x \\sin x$", "$2 \\cos x \\sin x$", "$-\\sin^2 x$"], "B", "MEDIUM",
      "$y = (\\cos x)^2$; derivative $2 \\cos x \\cdot (-\\sin x) = -2 \\sin x \\cos x$. **Answer: B**", "chain-rule"),
    m("If $f(x) = e^{\\sin x}$, then $f'(x) =$:",
      ["$e^{\\sin x} \\cos x$", "$e^{\\cos x}$", "$\\sin x e^{\\sin x}$", "$e^{\\sin x}$"], "A", "HARD",
      "Chain: $e^u \\cdot u' = e^{\\sin x} \\cos x$. **Answer: A**", "chain-rule"),
    m("If $g(x) = \\ln(\\cos x)$, then $g'(x) =$:",
      ["$-\\tan x$", "$\\tan x$", "$\\dfrac{1}{\\cos x}$", "$-\\sec x$"], "A", "HARD",
      "$\\dfrac{-\\sin x}{\\cos x} = -\\tan x$. **Answer: A**", "chain-rule"),
  ],
  "product-rule": [
    m("The derivative of $f(x) = x e^x$ is:",
      ["$e^x$", "$(x + 1) e^x$", "$x e^x$", "$e^x + x$"], "B", "EASY",
      "$1 \\cdot e^x + x \\cdot e^x = (1 + x) e^x$. **Answer: B**", "product-rule"),
    m("The derivative of $x \\sin x$ is:",
      ["$\\cos x$", "$\\sin x + x \\cos x$", "$x \\cos x$", "$\\sin x - x \\cos x$"], "B", "EASY",
      "$\\sin x + x \\cos x$. **Answer: B**", "product-rule"),
    m("If $f(x) = x^2 \\ln x$, then $f'(x) =$:",
      ["$2 x \\ln x$", "$x + 2 x \\ln x$", "$2 x \\ln x + x$", "$\\dfrac{1}{x}$"], "C", "MEDIUM",
      "$2 x \\cdot \\ln x + x^2 \\cdot \\dfrac{1}{x} = 2 x \\ln x + x$. **Answer: C**", "product-rule"),
    m("If $f(x) = (x + 1)(x - 2)$, then $f'(x) =$:",
      ["$1$", "$2 x - 1$", "$x^2 - x$", "$2 x + 1$"], "B", "MEDIUM",
      "Expand: $x^2 - x - 2$, derivative $2 x - 1$. **Answer: B**", "product-rule"),
    m("If $h(x) = e^x \\cos x$, then $h'(x) =$:",
      ["$e^x \\cos x$", "$e^x(\\cos x - \\sin x)$", "$e^x \\sin x$", "$-e^x \\sin x$"], "B", "MEDIUM",
      "$e^x \\cos x + e^x(-\\sin x) = e^x(\\cos x - \\sin x)$. **Answer: B**", "product-rule"),
    m("If $u(x) v(x) = x^3$ and $u(x) = x^2$, then $v(x) =$:",
      ["$x^3$", "$x$", "$\\dfrac{1}{x}$", "$3 x$"], "B", "MEDIUM",
      "$v = x^3 / x^2 = x$. **Answer: B**", "product-rule"),
    m("If $f(x) = x \\sqrt{x + 1}$, then $f'(x) =$:",
      ["$\\sqrt{x + 1} + \\dfrac{x}{2\\sqrt{x + 1}}$", "$\\dfrac{1}{2\\sqrt{x + 1}}$", "$\\sqrt{x + 1}$", "$\\dfrac{x}{\\sqrt{x + 1}}$"], "A", "HARD",
      "Product rule with $u = x$ and $v = \\sqrt{x + 1}$. **Answer: A**", "product-rule"),
    m("If $g(x) = (2 x + 3) \\sin x$, then $g'(0) =$:",
      ["$0$", "$2$", "$3$", "$5$"], "C", "HARD",
      "$g'(x) = 2 \\sin x + (2x+3)\\cos x$; at $x = 0$: $0 + 3 = 3$. **Answer: C**", "product-rule"),
  ],
  "quotient-rule": [
    m("The derivative of $\\dfrac{1}{x}$ is:",
      ["$\\dfrac{1}{x^2}$", "$-\\dfrac{1}{x^2}$", "$\\ln x$", "$\\dfrac{-1}{x}$"], "B", "EASY",
      "$x^{-1} \\to -x^{-2}$. **Answer: B**", "quotient-rule"),
    m("If $f(x) = \\dfrac{x}{x + 1}$, then $f'(x) =$:",
      ["$\\dfrac{1}{(x + 1)^2}$", "$\\dfrac{x + 1}{(x + 1)^2}$", "$\\dfrac{1}{x + 1}$", "$\\dfrac{-1}{(x + 1)^2}$"], "A", "EASY",
      "$\\dfrac{(x+1)(1) - x(1)}{(x+1)^2} = \\dfrac{1}{(x+1)^2}$. **Answer: A**", "quotient-rule"),
    m("$\\dfrac{d}{dx}\\left[\\dfrac{\\sin x}{x}\\right] =$",
      ["$\\dfrac{\\cos x}{x}$", "$\\dfrac{x \\cos x - \\sin x}{x^2}$", "$\\dfrac{x \\cos x + \\sin x}{x^2}$", "$\\cos x$"], "B", "MEDIUM",
      "Quotient rule. **Answer: B**", "quotient-rule"),
    m("If $f(x) = \\dfrac{x^2}{x - 1}$, then $f'(x) =$:",
      ["$\\dfrac{x^2 - 2 x}{(x - 1)^2}$", "$\\dfrac{2 x}{x - 1}$", "$\\dfrac{x^2 + 2x}{(x-1)^2}$", "$\\dfrac{x^2(x-2)}{(x-1)^2}$"], "A", "MEDIUM",
      "$\\dfrac{2x(x-1) - x^2}{(x-1)^2} = \\dfrac{x^2 - 2x}{(x-1)^2}$. **Answer: A**", "quotient-rule"),
    m("If $g(x) = \\dfrac{e^x}{x}$ for $x \\neq 0$, then $g'(x) =$:",
      ["$\\dfrac{e^x(x - 1)}{x^2}$", "$\\dfrac{e^x}{x^2}$", "$\\dfrac{e^x(x + 1)}{x^2}$", "$\\dfrac{e^x - 1}{x^2}$"], "A", "MEDIUM",
      "$\\dfrac{e^x \\cdot x - e^x \\cdot 1}{x^2}$. **Answer: A**", "quotient-rule"),
    m("$\\dfrac{d}{dx}\\left[\\tan x\\right] =$",
      ["$\\sec^2 x$", "$\\dfrac{1}{\\cos^2 x}$", "Both A and B", "$-\\cot x$"], "C", "MEDIUM",
      "$\\sec^2 x = 1/\\cos^2 x$ — both are correct. **Answer: C**", "quotient-rule"),
    m("If $h(x) = \\dfrac{\\ln x}{x}$, then $h'(x) =$:",
      ["$\\dfrac{1 - \\ln x}{x^2}$", "$\\dfrac{\\ln x - 1}{x^2}$", "$\\dfrac{1}{x^2}$", "$\\dfrac{\\ln x}{x^2}$"], "A", "HARD",
      "$\\dfrac{(1/x) \\cdot x - \\ln x}{x^2}$. **Answer: A**", "quotient-rule"),
    m("The stationary point of $f(x) = \\dfrac{x}{x^2 + 1}$ occurs at $x =$:",
      ["$0$", "$\\pm 1$", "$1$ only", "$-1$ only"], "B", "HARD",
      "$f'(x) = \\dfrac{(x^2+1) - x(2x)}{(x^2+1)^2} = \\dfrac{1 - x^2}{(x^2+1)^2} = 0 \\Rightarrow x = \\pm 1$. **Answer: B**", "quotient-rule"),
  ],
  "tangents-and-normals": [
    m("The slope of the tangent to $y = x^2$ at $x = 3$ is:",
      ["$3$", "$6$", "$9$", "$12$"], "B", "EASY",
      "$y' = 2x$, $y'(3) = 6$. **Answer: B**", "tangents-and-normals"),
    m("The equation of the tangent to $y = x^2$ at $(1, 1)$ is:",
      ["$y = 2 x - 1$", "$y = 2 x + 1$", "$y = x + 1$", "$y = x - 1$"], "A", "EASY",
      "Slope 2 at $(1, 1)$: $y - 1 = 2(x - 1) \\Rightarrow y = 2 x - 1$. **Answer: A**", "tangents-and-normals"),
    m("The slope of the normal to $y = x^2$ at $(1, 1)$ is:",
      ["$2$", "$-2$", "$\\dfrac{1}{2}$", "$-\\dfrac{1}{2}$"], "D", "EASY",
      "Normal slope = $-1/$tangent slope $= -1/2$. **Answer: D**", "tangents-and-normals"),
    m("The tangent to $y = e^x$ at $x = 0$ has equation:",
      ["$y = x$", "$y = x + 1$", "$y = e x$", "$y = 1$"], "B", "MEDIUM",
      "$y(0) = 1$, $y'(0) = 1$: $y - 1 = 1(x - 0)$. **Answer: B**", "tangents-and-normals"),
    m("Where on $y = x^3$ is the tangent horizontal?",
      ["$x = 0$", "$x = 1$", "$x = -1$", "nowhere"], "A", "MEDIUM",
      "$y' = 3 x^2 = 0 \\Rightarrow x = 0$. **Answer: A**", "tangents-and-normals"),
    m("The tangent to $y = \\ln x$ at $x = 1$ has equation:",
      ["$y = x - 1$", "$y = x + 1$", "$y = x$", "$y = e x$"], "A", "MEDIUM",
      "$y(1) = 0$, $y'(1) = 1$: $y - 0 = 1(x - 1)$. **Answer: A**", "tangents-and-normals"),
    m("The tangent to $y = \\sin x$ at $x = \\pi/2$ has slope:",
      ["$1$", "$0$", "$-1$", "$\\pi/2$"], "B", "HARD",
      "$y' = \\cos x$, $\\cos(\\pi/2) = 0$. **Answer: B**", "tangents-and-normals"),
    m("The point on $y = x^2$ where the tangent has slope 6 is:",
      ["$(2, 4)$", "$(3, 9)$", "$(6, 36)$", "$(1, 1)$"], "B", "HARD",
      "$y' = 2 x = 6 \\Rightarrow x = 3$, $y = 9$. **Answer: B**", "tangents-and-normals"),
  ],
  "rates-of-change": [
    m("If $s(t) = t^2$, the velocity at $t = 3$ is:",
      ["$3$", "$6$", "$9$", "$12$"], "B", "EASY",
      "$v = s'(t) = 2 t$, $v(3) = 6$. **Answer: B**", "rates-of-change"),
    m("If $V(t) = 1000 - 5 t^2$, then $V'(0) =$:",
      ["$0$", "$1000$", "$-5$", "$-10 t$"], "A", "EASY",
      "$V'(t) = -10 t$, $V'(0) = 0$. **Answer: A**", "rates-of-change"),
    m("The instantaneous rate of change of $f(x) = x^3$ at $x = 2$ is:",
      ["$6$", "$8$", "$12$", "$24$"], "C", "EASY",
      "$f'(2) = 3(4) = 12$. **Answer: C**", "rates-of-change"),
    m("The average rate of change of $f(x) = x^2$ from $x = 1$ to $x = 4$ is:",
      ["$3$", "$5$", "$6$", "$15$"], "B", "MEDIUM",
      "$\\dfrac{16 - 1}{4 - 1} = 5$. **Answer: B**", "rates-of-change"),
    m("A particle has position $x(t) = t^3 - 3 t$. Its acceleration at $t = 1$ is:",
      ["$0$", "$3$", "$6$", "$12$"], "C", "MEDIUM",
      "$v = 3 t^2 - 3$, $a = 6 t$, $a(1) = 6$. **Answer: C**", "rates-of-change"),
    m("If $r(t) = 2 t$ is the radius of an expanding circle, then $\\dfrac{dA}{dt}$ at $t = 1$ is:",
      ["$2\\pi$", "$4\\pi$", "$8\\pi$", "$\\pi$"], "C", "MEDIUM",
      "$A = \\pi r^2 = 4\\pi t^2$; $dA/dt = 8\\pi t$; at $t = 1$: $8\\pi$. **Answer: C**", "rates-of-change"),
    m("If $f(x) = e^{2 x}$, then the rate of change at $x = 0$ is:",
      ["$1$", "$2$", "$e$", "$2 e$"], "B", "HARD",
      "$f'(x) = 2 e^{2 x}$; at $x = 0$: $2$. **Answer: B**", "rates-of-change"),
    m("A balloon volume is $V(t) = 4\\pi t^3 / 3$. Its rate of change at $t = 2$ is:",
      ["$8\\pi$", "$16\\pi$", "$24\\pi$", "$32\\pi$"], "B", "HARD",
      "$dV/dt = 4\\pi t^2$; at $t = 2$: $16\\pi$. **Answer: B**", "rates-of-change"),
  ],
  "stationary-points-and-curve-sketching": [
    m("$f(x) = x^2 - 4 x + 3$ has a stationary point at:",
      ["$x = 0$", "$x = 1$", "$x = 2$", "$x = 4$"], "C", "EASY",
      "$f'(x) = 2 x - 4 = 0 \\Rightarrow x = 2$. **Answer: C**", "stationary-points-and-curve-sketching"),
    m("The stationary point of $f(x) = -x^2 + 6 x$ is:",
      ["min at $x = 3$", "max at $x = 3$", "min at $x = 6$", "max at $x = 6$"], "B", "EASY",
      "$f'(x) = -2x + 6 = 0 \\Rightarrow x = 3$. $f''(x) = -2 < 0$ ⇒ max. **Answer: B**", "stationary-points-and-curve-sketching"),
    m("The number of stationary points of $f(x) = x^3 - 3 x$ is:",
      ["$0$", "$1$", "$2$", "$3$"], "C", "EASY",
      "$f'(x) = 3 x^2 - 3 = 0 \\Rightarrow x = \\pm 1$: two. **Answer: C**", "stationary-points-and-curve-sketching"),
    m("$f(x) = x^3$ has at $x = 0$:",
      ["a local max", "a local min", "a point of inflection", "no stationary point"], "C", "MEDIUM",
      "$f'(0) = 0$ but no sign change in $f'$; it's a horizontal point of inflection. **Answer: C**", "stationary-points-and-curve-sketching"),
    m("If $f'(c) = 0$ and $f''(c) > 0$, then $c$ is:",
      ["a local max", "a local min", "an inflection point", "an undefined point"], "B", "MEDIUM",
      "Second derivative positive ⇒ minimum. **Answer: B**", "stationary-points-and-curve-sketching"),
    m("The function $f(x) = x^4 - 2 x^2$ has stationary points at:",
      ["$x = 0, \\pm 1$", "$x = \\pm 2$", "$x = 0$ only", "$x = \\pm \\sqrt 2$"], "A", "MEDIUM",
      "$f'(x) = 4 x^3 - 4 x = 4 x(x^2 - 1) = 0 \\Rightarrow x = 0, \\pm 1$. **Answer: A**", "stationary-points-and-curve-sketching"),
    m("Concavity of $f$ changes where:",
      ["$f' = 0$", "$f''$ changes sign", "$f = 0$", "$f$ has a max"], "B", "HARD",
      "Inflection point: where $f''$ changes sign. **Answer: B**", "stationary-points-and-curve-sketching"),
    m("On $[0, 4]$, the function $f(x) = x^3 - 6 x^2 + 9 x$ has absolute maximum at:",
      ["$x = 0$", "$x = 1$", "$x = 3$", "$x = 4$"], "B", "HARD",
      "Stationary points $x = 1$ (local max with $f = 4$), $x = 3$ (local min, $f = 0$). Endpoints: $f(0) = 0$, $f(4) = 4$. Absolute max at $x = 1$ or $x = 4$ (both $4$). **Answer: B**", "stationary-points-and-curve-sketching"),
  ],
  "optimisation": [
    m("To find the maximum of $f$ on $[a, b]$, you should examine:",
      ["only endpoints", "only stationary points", "stationary points and endpoints", "the second derivative only"], "C", "EASY",
      "On a closed interval, candidates are stationary points and endpoints. **Answer: C**", "optimisation"),
    m("If $A(x) = x(10 - x)$, the maximum value of $A$ is:",
      ["$10$", "$20$", "$25$", "$100$"], "C", "EASY",
      "$A'(x) = 10 - 2 x = 0 \\Rightarrow x = 5$; $A(5) = 25$. **Answer: C**", "optimisation"),
    m("Among rectangles with perimeter 20, the largest area is:",
      ["$20$", "$25$", "$50$", "$100$"], "B", "EASY",
      "Square gives max area: side 5, area 25. **Answer: B**", "optimisation"),
    m("Two positive numbers sum to 10; their max product is:",
      ["$24$", "$25$", "$50$", "$100$"], "B", "MEDIUM",
      "$P = x(10 - x)$ max at $x = 5$: $P = 25$. **Answer: B**", "optimisation"),
    m("The minimum value of $f(x) = x^2 + 9/x^2$ for $x > 0$ is:",
      ["$3$", "$6$", "$9$", "$12$"], "B", "MEDIUM",
      "$f'(x) = 2x - 18/x^3 = 0 \\Rightarrow x^4 = 9 \\Rightarrow x = \\sqrt 3$. $f(\\sqrt 3) = 3 + 3 = 6$. **Answer: B**", "optimisation"),
    m("A closed cylindrical can has fixed volume $V$. Min surface area occurs when:",
      ["$r = h$", "$h = 2 r$", "$h = r/2$", "$r = 2 h$"], "B", "MEDIUM",
      "Setting $dS/dr = 0$ gives $h = 2 r$. **Answer: B**", "optimisation"),
    m("An open box from a 10×10 sheet with corner cuts of side $x$ has max volume at $x =$:",
      ["$\\dfrac{5}{3}$", "$\\dfrac{10}{3}$", "$\\dfrac{5}{2}$", "$5$"], "A", "HARD",
      "$V = x(10 - 2x)^2$; $V' = (10 - 2x)(10 - 6x) = 0 \\Rightarrow x = 10/6 = 5/3$ (in $(0, 5)$). **Answer: A**", "optimisation"),
    m("Min distance from $(0, 0)$ to $y = x + 3$ is:",
      ["$\\sqrt 3$", "$\\dfrac{3}{\\sqrt 2}$", "$3$", "$\\sqrt 6$"], "B", "HARD",
      "Distance = $|0 - 0 + 3|/\\sqrt{1^2 + 1^2} = 3/\\sqrt 2$. **Answer: B**", "optimisation"),
  ],
  "antidifferentiation": [
    m("$\\int x^3 \\, dx =$",
      ["$3 x^2 + C$", "$\\dfrac{x^4}{4} + C$", "$\\dfrac{x^3}{3} + C$", "$4 x^4 + C$"], "B", "EASY",
      "Power rule for integration. **Answer: B**", "antidifferentiation"),
    m("$\\int e^x \\, dx =$",
      ["$e^x + C$", "$e^x$", "$\\dfrac{e^x}{x}$", "$x e^x + C$"], "A", "EASY",
      "$e^x$ is its own antiderivative. **Answer: A**", "antidifferentiation"),
    m("$\\int \\sin x \\, dx =$",
      ["$\\cos x + C$", "$-\\cos x + C$", "$-\\sin x + C$", "$\\sin x + C$"], "B", "EASY",
      "Derivative of $-\\cos x$ is $\\sin x$. **Answer: B**", "antidifferentiation"),
    m("$\\int (2 x + 3) \\, dx =$",
      ["$x^2 + 3 x + C$", "$x^2 + 3 + C$", "$2 x + 3 x + C$", "$x^2 + 3 x$"], "A", "MEDIUM",
      "$\\int 2x dx + \\int 3 dx$. **Answer: A**", "antidifferentiation"),
    m("$\\int \\dfrac{1}{x} \\, dx =$ (for $x > 0$)",
      ["$\\ln |x| + C$", "$-\\dfrac{1}{x^2} + C$", "$\\dfrac{1}{x^2} + C$", "$x + C$"], "A", "MEDIUM",
      "Standard log antiderivative. **Answer: A**", "antidifferentiation"),
    m("If $F'(x) = 3 x^2$ and $F(0) = 5$, then $F(x) =$:",
      ["$x^3$", "$x^3 + 5$", "$3 x^3 + 5$", "$6 x + 5$"], "B", "MEDIUM",
      "$F(x) = x^3 + C$, $F(0) = C = 5$. **Answer: B**", "antidifferentiation"),
    m("$\\int e^{2 x} \\, dx =$",
      ["$e^{2 x} + C$", "$2 e^{2 x} + C$", "$\\dfrac{e^{2 x}}{2} + C$", "$\\dfrac{e^{2 x}}{x} + C$"], "C", "HARD",
      "Reverse chain rule. **Answer: C**", "antidifferentiation"),
    m("$\\int \\cos(3 x) \\, dx =$",
      ["$\\dfrac{1}{3}\\sin(3 x) + C$", "$3\\sin(3 x) + C$", "$\\sin(3 x) + C$", "$-\\dfrac{1}{3}\\sin(3 x) + C$"], "A", "HARD",
      "Antiderivative of $\\cos(kx)$ is $\\sin(kx)/k$. **Answer: A**", "antidifferentiation"),
  ],
  "definite-integrals": [
    m("$\\displaystyle\\int_0^1 x \\, dx =$",
      ["$0$", "$\\dfrac{1}{2}$", "$1$", "$2$"], "B", "EASY",
      "$[x^2/2]_0^1 = 1/2$. **Answer: B**", "definite-integrals"),
    m("$\\displaystyle\\int_0^2 e^x \\, dx =$",
      ["$e^2$", "$e^2 - 1$", "$e^2 + 1$", "$2 e$"], "B", "EASY",
      "$[e^x]_0^2 = e^2 - 1$. **Answer: B**", "definite-integrals"),
    m("$\\displaystyle\\int_0^\\pi \\sin x \\, dx =$",
      ["$0$", "$1$", "$2$", "$\\pi$"], "C", "EASY",
      "$[-\\cos x]_0^\\pi = -(-1) - (-1) = 2$. **Answer: C**", "definite-integrals"),
    m("$\\displaystyle\\int_{-1}^1 x^3 \\, dx =$",
      ["$0$", "$1$", "$\\dfrac{1}{2}$", "$2$"], "A", "MEDIUM",
      "Odd function over symmetric interval: 0. **Answer: A**", "definite-integrals"),
    m("If $\\displaystyle\\int_0^a f(x) dx = 4$ and $\\displaystyle\\int_a^b f(x) dx = 7$, then $\\displaystyle\\int_0^b f(x) dx =$:",
      ["$3$", "$11$", "$28$", "cannot determine"], "B", "MEDIUM",
      "Additivity: $4 + 7 = 11$. **Answer: B**", "definite-integrals"),
    m("$\\displaystyle\\int_1^4 \\dfrac{1}{x} \\, dx =$",
      ["$\\ln 4$", "$\\ln 3$", "$\\ln 5$", "$4 - 1$"], "A", "MEDIUM",
      "$[\\ln x]_1^4 = \\ln 4 - 0 = \\ln 4$. **Answer: A**", "definite-integrals"),
    m("$\\displaystyle\\int_0^2 (3 x^2 - 2 x) \\, dx =$",
      ["$0$", "$2$", "$4$", "$8$"], "C", "HARD",
      "$[x^3 - x^2]_0^2 = 8 - 4 = 4$. **Answer: C**", "definite-integrals"),
    m("If $\\displaystyle\\int_a^b f(x) dx = -3$, then $\\displaystyle\\int_b^a f(x) dx =$:",
      ["$-3$", "$3$", "$0$", "$3 b - 3 a$"], "B", "HARD",
      "Swapping limits negates the integral. **Answer: B**", "definite-integrals"),
  ],
  "area-under-curves": [
    m("The area under $y = x$ from $x = 0$ to $x = 4$ is:",
      ["$4$", "$8$", "$16$", "$2$"], "B", "EASY",
      "Triangle, $(4 \\cdot 4)/2 = 8$. **Answer: B**", "area-under-curves"),
    m("The area between $y = x^2$ and the $x$-axis on $[0, 3]$ is:",
      ["$3$", "$9$", "$\\dfrac{27}{3}$", "$\\dfrac{9}{2}$"], "C", "EASY",
      "$[x^3/3]_0^3 = 9$. (Choice C is $9$.) **Answer: C**", "area-under-curves"),
    m("The area between $y = \\cos x$ and the $x$-axis on $[0, \\pi/2]$ is:",
      ["$0$", "$1$", "$\\pi/2$", "$2$"], "B", "EASY",
      "$[\\sin x]_0^{\\pi/2} = 1$. **Answer: B**", "area-under-curves"),
    m("The area enclosed between $y = x^2$ and $y = x$ from $x = 0$ to $x = 1$ is:",
      ["$\\dfrac{1}{6}$", "$\\dfrac{1}{3}$", "$\\dfrac{1}{2}$", "$1$"], "A", "MEDIUM",
      "$\\int_0^1 (x - x^2) dx = [x^2/2 - x^3/3]_0^1 = 1/2 - 1/3 = 1/6$. **Answer: A**", "area-under-curves"),
    m("If $f(x) \\geq 0$ on $[a, b]$, the area under $f$ from $a$ to $b$ equals:",
      ["$f(b) - f(a)$", "$\\int_a^b f(x) dx$", "$\\int_a^b |f'(x)| dx$", "$\\dfrac{f(a) + f(b)}{2}$"], "B", "MEDIUM",
      "Definition. **Answer: B**", "area-under-curves"),
    m("The total area between $y = x$ and the $x$-axis from $x = -2$ to $x = 2$ is:",
      ["$0$", "$2$", "$4$", "$8$"], "C", "MEDIUM",
      "Two triangles: each area $2$, total $4$. (The integral $\\int_{-2}^2 x dx = 0$; area uses $|f|$.) **Answer: C**", "area-under-curves"),
    m("Region between $y = 4 - x^2$ and the $x$-axis has area:",
      ["$\\dfrac{16}{3}$", "$\\dfrac{32}{3}$", "$8$", "$16$"], "B", "HARD",
      "Roots $\\pm 2$. $\\int_{-2}^2 (4 - x^2) dx = [4x - x^3/3]_{-2}^2 = (8 - 8/3) - (-8 + 8/3) = 32/3$. **Answer: B**", "area-under-curves"),
    m("Area between $y = e^x$ and $y = e$ for $x \\in [0, 1]$ is:",
      ["$e - 1$", "$1$", "$e - 2$", "$e + 1$"], "B", "HARD",
      "$\\int_0^1 (e - e^x) dx = [ex - e^x]_0^1 = (e - e) - (0 - 1) = 1$. **Answer: B**", "area-under-curves"),
  ],
  "fundamental-theorem-of-calculus": [
    m("$\\displaystyle\\int_a^b f'(x) \\, dx =$",
      ["$f'(b) - f'(a)$", "$f(b) - f(a)$", "$f(a) - f(b)$", "$f(b) + f(a)$"], "B", "EASY",
      "FTC. **Answer: B**", "fundamental-theorem-of-calculus"),
    m("If $F(x) = \\displaystyle\\int_0^x t^2 \\, dt$, then $F'(x) =$:",
      ["$x^2$", "$\\dfrac{x^3}{3}$", "$2 x$", "$x$"], "A", "EASY",
      "FTC: derivative of integral with variable upper limit. **Answer: A**", "fundamental-theorem-of-calculus"),
    m("$\\dfrac{d}{dx}\\displaystyle\\int_1^x \\sin t \\, dt =$",
      ["$\\cos x$", "$\\sin x$", "$-\\cos x$", "$0$"], "B", "EASY",
      "FTC. **Answer: B**", "fundamental-theorem-of-calculus"),
    m("If $g(x) = \\displaystyle\\int_0^{x^2} e^t \\, dt$, then $g'(x) =$:",
      ["$e^{x^2}$", "$2 x e^{x^2}$", "$e^{2 x}$", "$2 e^{x^2}$"], "B", "MEDIUM",
      "Chain + FTC: $e^{x^2} \\cdot 2 x$. **Answer: B**", "fundamental-theorem-of-calculus"),
    m("$\\displaystyle\\int_0^2 (2 x) \\, dx$ equals $f(2) - f(0)$ where $f(x) =$:",
      ["$x^2$", "$2 x^2$", "$\\dfrac{x^2}{2}$", "$2 x$"], "A", "MEDIUM",
      "$f(x) = x^2$ since $f'(x) = 2 x$. **Answer: A**", "fundamental-theorem-of-calculus"),
    m("If $H(x) = \\displaystyle\\int_x^5 t^3 \\, dt$, then $H'(x) =$:",
      ["$x^3$", "$-x^3$", "$5^3 - x^3$", "$\\dfrac{x^4}{4}$"], "B", "MEDIUM",
      "Variable in lower limit gives negative sign. **Answer: B**", "fundamental-theorem-of-calculus"),
    m("Using FTC, the value of $\\displaystyle\\int_0^4 (3 x^2 - 6 x) \\, dx$ is:",
      ["$0$", "$16$", "$32$", "$8$"], "B", "HARD",
      "$[x^3 - 3 x^2]_0^4 = 64 - 48 = 16$. **Answer: B**", "fundamental-theorem-of-calculus"),
    m("If the area under $f$ from 0 to $x$ is $A(x) = x^3$, then $f(x) =$:",
      ["$x^3$", "$3 x^2$", "$\\dfrac{x^4}{4}$", "$3 x$"], "B", "HARD",
      "$f(x) = A'(x) = 3 x^2$. **Answer: B**", "fundamental-theorem-of-calculus"),
  ],
};

for (const [slug, mcqs] of Object.entries(SUBTOPICS)) {
  fs.writeFileSync(path.join(OUT_DIR, `qset-methods-w2-${slug}.json`),
    JSON.stringify({ mcq: mcqs, shortAnswer: [], extendedAnswer: [], extendedResponse: [] }, null, 2) + "\n");
  console.log(`${slug}: ${mcqs.length} MCQ`);
}
console.log(`Total: ${Object.values(SUBTOPICS).reduce((s, a) => s + a.length, 0)} MCQ.`);
