/** Wave 2 batch 2: Functions MCQ — 9 subtopics × 8 = 72 MCQ. */
import * as fs from "fs";
import * as path from "path";

const OUT_DIR = "scripts/output";

interface MCQ {
  content: string; optionA: string; optionB: string; optionC: string; optionD: string;
  correctOption: "A" | "B" | "C" | "D"; marks: number; difficulty: "EASY" | "MEDIUM" | "HARD";
  solutionContent: string; subtopicSlugs: string[];
}
const m = (c: string, o: [string, string, string, string], k: "A" | "B" | "C" | "D",
  d: "EASY" | "MEDIUM" | "HARD", s: string, p: string, sec: string[] = []): MCQ =>
  ({ content: c, optionA: o[0], optionB: o[1], optionC: o[2], optionD: o[3], correctOption: k, marks: 1, difficulty: d, solutionContent: s, subtopicSlugs: [p, ...sec] });

const SUBTOPICS: Record<string, MCQ[]> = {
  "polynomial-functions": [
    m("The graph of $y = (x - 1)(x + 2)(x - 3)$ has $x$-intercepts at:",
      ["$-1, 2, -3$", "$1, -2, 3$", "$0, -2, 3$", "$-1, -2, 3$"], "B", "EASY",
      "Setting $y = 0$ gives $x = 1, -2, 3$. **Answer: B**", "polynomial-functions"),
    m("The $y$-intercept of $y = x^3 - 4 x + 5$ is:",
      ["$0$", "$4$", "$5$", "$-4$"], "C", "EASY",
      "$y(0) = 5$. **Answer: C**", "polynomial-functions"),
    m("The degree of the polynomial $f(x) = 2 x^4 - x^3 + 5 x - 7$ is:",
      ["$2$", "$3$", "$4$", "$7$"], "C", "EASY",
      "Highest exponent is 4. **Answer: C**", "polynomial-functions"),
    m("As $x \\to \\infty$, the polynomial $y = -3 x^3 + 2 x^2 - 1$ tends to:",
      ["$+\\infty$", "$-\\infty$", "$0$", "$-3$"], "B", "MEDIUM",
      "Leading term $-3 x^3 \\to -\\infty$. **Answer: B**", "polynomial-functions"),
    m("The graph of $y = (x - 2)^2 (x + 1)$ touches but does not cross the $x$-axis at:",
      ["$x = -1$", "$x = 0$", "$x = 2$", "$x = -2$"], "C", "MEDIUM",
      "Double root at $x = 2$ (from $(x - 2)^2$) gives touch-but-not-cross. **Answer: C**", "polynomial-functions"),
    m("The minimum value of $f(x) = (x - 3)^2 + 5$ is:",
      ["$-3$", "$3$", "$5$", "$-5$"], "C", "MEDIUM",
      "Vertex form; minimum at $x = 3$ with value $5$. **Answer: C**", "polynomial-functions"),
    m("The number of turning points of $y = x^4 - 4 x^2$ is:",
      ["$0$", "$1$", "$2$", "$3$"], "D", "HARD",
      "$y' = 4 x^3 - 8 x = 4 x(x^2 - 2) = 0 \\Rightarrow x = 0, \\pm\\sqrt 2$: three stationary points. **Answer: D**", "polynomial-functions"),
    m("If $P(x) = x^3 + a x + 2$ and $P(-1) = 0$, then $a$ equals:",
      ["$-3$", "$1$", "$3$", "$-1$"], "B", "HARD",
      "$P(-1) = -1 - a + 2 = 1 - a = 0 \\Rightarrow a = 1$. **Answer: B**", "polynomial-functions"),
  ],
  "exponential-functions": [
    m("The $y$-intercept of $y = 3^x$ is:",
      ["$0$", "$1$", "$3$", "$\\dfrac{1}{3}$"], "B", "EASY",
      "$3^0 = 1$. **Answer: B**", "exponential-functions"),
    m("The horizontal asymptote of $y = e^x$ is:",
      ["$y = 0$", "$y = 1$", "$y = e$", "no asymptote"], "A", "EASY",
      "As $x \\to -\\infty$, $e^x \\to 0$. **Answer: A**", "exponential-functions"),
    m("The range of $f(x) = e^x$ is:",
      ["$\\mathbb{R}$", "$(0, \\infty)$", "$[0, \\infty)$", "$(-\\infty, 1)$"], "B", "EASY",
      "Exponential is always positive. **Answer: B**", "exponential-functions"),
    m("The horizontal asymptote of $y = 2 - e^{-x}$ is:",
      ["$y = 0$", "$y = 2$", "$y = -2$", "$y = -1$"], "B", "MEDIUM",
      "As $x \\to \\infty$, $e^{-x} \\to 0$, so $y \\to 2$. **Answer: B**", "exponential-functions"),
    m("If $f(x) = 4 e^{2 x}$, then $f(0)$ equals:",
      ["$0$", "$2$", "$4$", "$8$"], "C", "MEDIUM",
      "$f(0) = 4 e^0 = 4$. **Answer: C**", "exponential-functions"),
    m("The graph of $y = 2^{x + 3}$ is the graph of $y = 2^x$ translated:",
      ["3 units right", "3 units left", "3 units up", "3 units down"], "B", "MEDIUM",
      "$x \\to x + 3$ shifts left. **Answer: B**", "exponential-functions"),
    m("$\\displaystyle\\lim_{x \\to \\infty} x e^{-x}$ equals:",
      ["$\\infty$", "$0$", "$1$", "$e$"], "B", "HARD",
      "Exponential decay dominates polynomial; the limit is $0$. **Answer: B**", "exponential-functions"),
    m("The smallest $x$ for which $e^x \\geq 10$ is:",
      ["$\\log_{10} e$", "$\\ln 10$", "$10 \\ln e$", "$e^{10}$"], "B", "HARD",
      "$e^x = 10 \\Rightarrow x = \\ln 10$. **Answer: B**", "exponential-functions"),
  ],
  "logarithmic-functions": [
    m("$\\log_2 16$ equals:",
      ["$2$", "$3$", "$4$", "$8$"], "C", "EASY",
      "$2^4 = 16$. **Answer: C**", "logarithmic-functions"),
    m("$\\log_e e$ equals:",
      ["$0$", "$1$", "$e$", "undefined"], "B", "EASY",
      "$\\ln e = 1$. **Answer: B**", "logarithmic-functions"),
    m("The domain of $y = \\ln(x)$ is:",
      ["$\\mathbb{R}$", "$[0, \\infty)$", "$(0, \\infty)$", "$(-\\infty, 0)$"], "C", "EASY",
      "Log defined only for positive arguments. **Answer: C**", "logarithmic-functions"),
    m("The graph of $y = \\ln(x)$ has vertical asymptote at:",
      ["$x = -1$", "$x = 0$", "$x = 1$", "$x = e$"], "B", "MEDIUM",
      "As $x \\to 0^+$, $\\ln x \\to -\\infty$. **Answer: B**", "logarithmic-functions"),
    m("If $\\log_e a + \\log_e b = \\log_e 12$ and $a = 3$, then $b$ equals:",
      ["$3$", "$4$", "$6$", "$9$"], "B", "MEDIUM",
      "$\\log(ab) = \\log 12 \\Rightarrow ab = 12 \\Rightarrow b = 4$. **Answer: B**", "logarithmic-functions"),
    m("The graph of $y = \\ln(x + 2)$ is obtained from $y = \\ln(x)$ by:",
      ["translation 2 right", "translation 2 left", "translation 2 up", "dilation by 2"], "B", "MEDIUM",
      "$x \\to x + 2$ shifts left. **Answer: B**", "logarithmic-functions"),
    m("$\\displaystyle\\lim_{x \\to \\infty} \\dfrac{\\ln x}{x}$ equals:",
      ["$\\infty$", "$0$", "$1$", "$e$"], "B", "HARD",
      "Power dominates log; limit is $0$. **Answer: B**", "logarithmic-functions"),
    m("If $f(x) = \\log_e(x^2)$ for $x > 0$, then $f(x)$ can be simplified to:",
      ["$2 \\log_e x$", "$\\log_e(2 x)$", "$(\\log_e x)^2$", "$\\dfrac{\\log_e x}{2}$"], "A", "HARD",
      "Power rule: $\\log(x^2) = 2 \\log x$. **Answer: A**", "logarithmic-functions"),
  ],
  "trigonometric-functions": [
    m("The period of $y = \\sin x$ is:",
      ["$\\pi$", "$2\\pi$", "$\\dfrac{\\pi}{2}$", "$4\\pi$"], "B", "EASY",
      "Standard sine period. **Answer: B**", "trigonometric-functions"),
    m("The amplitude of $y = 3 \\cos x$ is:",
      ["$1$", "$3$", "$\\dfrac{1}{3}$", "$6$"], "B", "EASY",
      "Coefficient of cos is the amplitude. **Answer: B**", "trigonometric-functions"),
    m("$\\sin(\\pi/6)$ equals:",
      ["$\\dfrac{1}{2}$", "$\\dfrac{\\sqrt 3}{2}$", "$\\dfrac{\\sqrt 2}{2}$", "$1$"], "A", "EASY",
      "Standard value. **Answer: A**", "trigonometric-functions"),
    m("The period of $y = \\sin(2 x)$ is:",
      ["$\\pi$", "$2\\pi$", "$\\dfrac{\\pi}{2}$", "$4\\pi$"], "A", "MEDIUM",
      "Period $= \\dfrac{2\\pi}{2} = \\pi$. **Answer: A**", "trigonometric-functions"),
    m("The range of $y = 2 \\sin x + 3$ is:",
      ["$[2, 4]$", "$[1, 5]$", "$[-2, 2]$", "$[3, 5]$"], "B", "MEDIUM",
      "$\\sin x \\in [-1, 1]$ so $2 \\sin x + 3 \\in [1, 5]$. **Answer: B**", "trigonometric-functions"),
    m("The graph of $y = \\cos(x - \\pi/2)$ is the same as the graph of:",
      ["$y = -\\sin x$", "$y = \\sin x$", "$y = \\cos x$", "$y = -\\cos x$"], "B", "MEDIUM",
      "$\\cos(x - \\pi/2) = \\sin x$. **Answer: B**", "trigonometric-functions"),
    m("$\\tan(3\\pi/4)$ equals:",
      ["$1$", "$-1$", "$\\sqrt 3$", "$-\\sqrt 3$"], "B", "HARD",
      "$\\tan(3\\pi/4) = -\\tan(\\pi/4) = -1$. **Answer: B**", "trigonometric-functions"),
    m("If $\\sin x = \\dfrac{3}{5}$ and $x$ is acute, then $\\cos x$ equals:",
      ["$\\dfrac{4}{5}$", "$-\\dfrac{4}{5}$", "$\\dfrac{3}{4}$", "$\\dfrac{5}{4}$"], "A", "HARD",
      "$\\cos^2 x = 1 - 9/25 = 16/25$; positive since acute, so $\\cos x = 4/5$. **Answer: A**", "trigonometric-functions"),
  ],
  "rational-functions": [
    m("The vertical asymptote of $y = \\dfrac{1}{x - 3}$ is:",
      ["$x = -3$", "$x = 3$", "$x = 0$", "$x = 1$"], "B", "EASY",
      "Denominator $= 0$ at $x = 3$. **Answer: B**", "rational-functions"),
    m("The horizontal asymptote of $y = \\dfrac{1}{x}$ is:",
      ["$y = 0$", "$y = 1$", "$y = x$", "none"], "A", "EASY",
      "$1/x \\to 0$ as $|x| \\to \\infty$. **Answer: A**", "rational-functions"),
    m("The domain of $f(x) = \\dfrac{1}{x - 2}$ is:",
      ["$\\mathbb{R}$", "$\\mathbb{R} \\setminus \\{2\\}$", "$\\mathbb{R} \\setminus \\{-2\\}$", "$\\mathbb{R} \\setminus \\{0\\}$"], "B", "EASY",
      "Exclude $x = 2$. **Answer: B**", "rational-functions"),
    m("The horizontal asymptote of $y = \\dfrac{2 x + 3}{x - 1}$ is:",
      ["$y = 0$", "$y = 1$", "$y = 2$", "$y = 3$"], "C", "MEDIUM",
      "Ratio of leading coefficients $= 2/1 = 2$. **Answer: C**", "rational-functions"),
    m("As $x \\to \\infty$, $\\dfrac{x^2 + 1}{x}$ behaves like:",
      ["$1$", "$x$", "$x^2$", "$0$"], "B", "MEDIUM",
      "$\\dfrac{x^2 + 1}{x} = x + \\dfrac{1}{x} \\to x$. **Answer: B**", "rational-functions"),
    m("The $x$-intercept of $y = \\dfrac{x - 4}{x + 1}$ is:",
      ["$x = -1$", "$x = 4$", "$x = 0$", "$x = -4$"], "B", "MEDIUM",
      "Numerator $= 0$ at $x = 4$. **Answer: B**", "rational-functions"),
    m("$y = \\dfrac{1}{x^2}$ is even and:",
      ["always positive", "always negative", "changes sign at 0", "constant"], "A", "HARD",
      "Squaring makes denominator positive; $1/x^2 > 0$ for all $x \\neq 0$. **Answer: A**", "rational-functions"),
    m("The graph of $y = \\dfrac{1}{x - 2} + 3$ has asymptotes:",
      ["$x = 2, y = 3$", "$x = -2, y = -3$", "$x = 3, y = 2$", "$x = 0, y = 0$"], "A", "HARD",
      "Vertical: $x = 2$ (denominator zero); horizontal: $y = 3$ (translation). **Answer: A**", "rational-functions"),
  ],
  "domain-and-range": [
    m("The domain of $f(x) = \\sqrt{x}$ is:",
      ["$\\mathbb{R}$", "$(0, \\infty)$", "$[0, \\infty)$", "$(-\\infty, 0]$"], "C", "EASY",
      "Square root requires non-negative input. **Answer: C**", "domain-and-range"),
    m("The range of $f(x) = x^2$ is:",
      ["$\\mathbb{R}$", "$[0, \\infty)$", "$(0, \\infty)$", "$(-\\infty, 0]$"], "B", "EASY",
      "Square is non-negative. **Answer: B**", "domain-and-range"),
    m("The domain of $f(x) = \\ln(x - 1)$ is:",
      ["$(0, \\infty)$", "$(1, \\infty)$", "$[1, \\infty)$", "$\\mathbb{R}$"], "B", "EASY",
      "Need $x - 1 > 0$. **Answer: B**", "domain-and-range"),
    m("The range of $f(x) = 3 - x^2$ is:",
      ["$[3, \\infty)$", "$(-\\infty, 3]$", "$\\mathbb{R}$", "$[0, 3]$"], "B", "MEDIUM",
      "Max at $x = 0$ gives $y = 3$; opens downward. **Answer: B**", "domain-and-range"),
    m("The maximal domain of $f(x) = \\sqrt{4 - x^2}$ is:",
      ["$[-2, 2]$", "$[0, 4]$", "$(-2, 2)$", "$\\mathbb{R}$"], "A", "MEDIUM",
      "Need $4 - x^2 \\geq 0 \\Rightarrow x^2 \\leq 4$. **Answer: A**", "domain-and-range"),
    m("The range of $f(x) = e^x - 1$ is:",
      ["$\\mathbb{R}$", "$(0, \\infty)$", "$(-1, \\infty)$", "$[-1, \\infty)$"], "C", "MEDIUM",
      "$e^x > 0$ so $e^x - 1 > -1$. **Answer: C**", "domain-and-range"),
    m("The maximal domain of $f(x) = \\dfrac{1}{\\sqrt{x - 3}}$ is:",
      ["$[3, \\infty)$", "$(3, \\infty)$", "$\\mathbb{R} \\setminus \\{3\\}$", "$\\mathbb{R}$"], "B", "HARD",
      "Need $x - 3 > 0$ (strict, since in denominator). **Answer: B**", "domain-and-range"),
    m("The range of $f(x) = 2 \\sin(3 x) + 1$ is:",
      ["$[-1, 3]$", "$[0, 2]$", "$[-2, 4]$", "$[-3, 5]$"], "A", "HARD",
      "$\\sin \\in [-1, 1]$ so $2 \\sin(3 x) \\in [-2, 2]$, plus 1: $[-1, 3]$. **Answer: A**", "domain-and-range"),
  ],
  "transformations": [
    m("The graph of $y = (x - 2)^2$ is the graph of $y = x^2$ translated:",
      ["2 units up", "2 units down", "2 units right", "2 units left"], "C", "EASY",
      "$x \\to x - 2$ shifts right. **Answer: C**", "transformations"),
    m("Reflecting $y = x^2$ in the $x$-axis gives:",
      ["$y = -x^2$", "$y = (-x)^2$", "$y = x^{-2}$", "$y = -x$"], "A", "EASY",
      "Reflection in $x$-axis: $y \\to -y$. **Answer: A**", "transformations"),
    m("The graph of $y = 2 \\sin x$ has amplitude:",
      ["$\\dfrac{1}{2}$", "$2$", "$1$", "$2\\pi$"], "B", "EASY",
      "Vertical dilation by 2. **Answer: B**", "transformations"),
    m("The graph of $y = -e^x + 3$ is obtained from $y = e^x$ by:",
      ["reflection in $x$-axis then translation up 3", "reflection in $y$-axis then translation up 3", "translation up 3 only", "reflection in $y$-axis only"], "A", "MEDIUM",
      "$y \\to -y$ then add 3. **Answer: A**", "transformations"),
    m("The image of the point $(1, 4)$ under the transformation $y = f(x) \\to y = 2 f(x - 1)$ is:",
      ["$(2, 8)$", "$(0, 8)$", "$(2, 4)$", "$(1, 8)$"], "A", "MEDIUM",
      "$x \\to x + 1$ (shift right 1): $(1, 4) \\to (2, 4)$; then $y \\to 2 y$: $(2, 8)$. **Answer: A**", "transformations"),
    m("If $g(x) = f(2 x)$, then $g$ is the graph of $f$:",
      ["dilated by 2 from $y$-axis", "dilated by $1/2$ from $y$-axis", "dilated by 2 from $x$-axis", "translated 2 right"], "B", "MEDIUM",
      "$x \\to 2 x$ compresses horizontally by 2 (i.e. dilation factor $1/2$). **Answer: B**", "transformations"),
    m("The graph of $y = \\sin(x + \\pi/4)$ is the graph of $y = \\sin(x)$ translated:",
      ["$\\pi/4$ right", "$\\pi/4$ left", "$\\pi/4$ up", "$\\pi/4$ down"], "B", "HARD",
      "$x \\to x + \\pi/4$ shifts left. **Answer: B**", "transformations"),
    m("Under the transformation $(x, y) \\to (-x, -y)$, the point $(3, 5)$ maps to:",
      ["$(-3, -5)$", "$(-3, 5)$", "$(3, -5)$", "$(5, 3)$"], "A", "HARD",
      "Reflection through origin. **Answer: A**", "transformations"),
  ],
  "inverse-functions": [
    m("The inverse of $f(x) = x + 5$ is:",
      ["$f^{-1}(x) = x - 5$", "$f^{-1}(x) = 5 - x$", "$f^{-1}(x) = \\dfrac{1}{x + 5}$", "$f^{-1}(x) = -x - 5$"], "A", "EASY",
      "Solve $y = x + 5$ for $x$: $x = y - 5$. **Answer: A**", "inverse-functions"),
    m("The inverse of $f(x) = 2 x$ is:",
      ["$f^{-1}(x) = \\dfrac{x}{2}$", "$f^{-1}(x) = -2 x$", "$f^{-1}(x) = \\dfrac{1}{2 x}$", "$f^{-1}(x) = 2 - x$"], "A", "EASY",
      "Divide by 2. **Answer: A**", "inverse-functions"),
    m("The graphs of $f$ and $f^{-1}$ are reflections of each other in:",
      ["the $x$-axis", "the $y$-axis", "the line $y = x$", "the origin"], "C", "EASY",
      "Standard property of inverse functions. **Answer: C**", "inverse-functions"),
    m("The inverse of $f(x) = e^x$ is:",
      ["$\\ln x$", "$e^{-x}$", "$\\dfrac{1}{e^x}$", "$-e^x$"], "A", "MEDIUM",
      "Inverse of exponential is logarithm. **Answer: A**", "inverse-functions"),
    m("If $f$ is one-to-one and $f(3) = 7$, then $f^{-1}(7) =$:",
      ["$3$", "$7$", "$1/7$", "$1/3$"], "A", "MEDIUM",
      "Definition of inverse: $f(a) = b \\Leftrightarrow f^{-1}(b) = a$. **Answer: A**", "inverse-functions"),
    m("The function $f(x) = x^2$ on $\\mathbb{R}$ has no inverse because:",
      ["it is not one-to-one", "it is not continuous", "it is unbounded", "it has no $x$-intercept"], "A", "MEDIUM",
      "$f(a) = f(-a)$, so $f$ fails the one-to-one test. **Answer: A**", "inverse-functions"),
    m("If $f(x) = \\dfrac{x + 1}{x - 1}$, then $f^{-1}(x) =$:",
      ["$\\dfrac{x + 1}{x - 1}$", "$\\dfrac{x - 1}{x + 1}$", "$\\dfrac{1 - x}{1 + x}$", "$\\dfrac{-x - 1}{x - 1}$"], "A", "HARD",
      "Solve $y = (x+1)/(x-1)$: $yx - y = x + 1 \\Rightarrow x(y-1) = y+1 \\Rightarrow x = (y+1)/(y-1)$. So $f^{-1} = f$ — self-inverse. **Answer: A**", "inverse-functions"),
    m("The domain of $f^{-1}$ equals:",
      ["the domain of $f$", "the range of $f$", "$\\mathbb{R}$", "$(0, \\infty)$"], "B", "HARD",
      "Inverse swaps domain and range. **Answer: B**", "inverse-functions"),
  ],
  "composite-functions": [
    m("If $f(x) = x + 1$ and $g(x) = x^2$, then $(f \\circ g)(x) =$:",
      ["$(x + 1)^2$", "$x^2 + 1$", "$x^2 + x$", "$x + 1$"], "B", "EASY",
      "$f(g(x)) = f(x^2) = x^2 + 1$. **Answer: B**", "composite-functions"),
    m("If $f(x) = x + 1$ and $g(x) = x^2$, then $(g \\circ f)(x) =$:",
      ["$(x + 1)^2$", "$x^2 + 1$", "$x^2 + x$", "$x + 1$"], "A", "EASY",
      "$g(f(x)) = g(x + 1) = (x + 1)^2$. **Answer: A**", "composite-functions"),
    m("If $f(x) = 2 x$ and $g(x) = x + 3$, then $(f \\circ g)(1) =$:",
      ["$2$", "$5$", "$7$", "$8$"], "D", "EASY",
      "$g(1) = 4$, $f(4) = 8$. **Answer: D**", "composite-functions"),
    m("If $f(x) = \\sqrt x$ and $g(x) = x - 1$, the domain of $(f \\circ g)$ is:",
      ["$\\mathbb{R}$", "$[0, \\infty)$", "$[1, \\infty)$", "$(0, \\infty)$"], "C", "MEDIUM",
      "Need $g(x) \\geq 0 \\Rightarrow x \\geq 1$. **Answer: C**", "composite-functions"),
    m("If $f(x) = e^x$ and $g(x) = \\ln x$, then $(f \\circ g)(x)$ for $x > 0$ equals:",
      ["$x$", "$e^x$", "$\\ln x$", "$1$"], "A", "MEDIUM",
      "$f$ and $g$ are inverses: $e^{\\ln x} = x$. **Answer: A**", "composite-functions"),
    m("If $h(x) = (2 x + 1)^3$, this can be written as $f(g(x))$ where:",
      ["$f(u) = u^3$, $g(x) = 2 x + 1$", "$f(u) = 2 u + 1$, $g(x) = x^3$", "$f(u) = u + 1$, $g(x) = (2 x)^3$", "$f(u) = u$, $g(x) = (2 x + 1)^3$"], "A", "MEDIUM",
      "Inner $g(x) = 2 x + 1$, outer $f(u) = u^3$. **Answer: A**", "composite-functions"),
    m("If $f(x) = x^2$ and $g(x) = \\sin x$, then $(g \\circ f)(x) =$:",
      ["$\\sin(x^2)$", "$\\sin^2 x$", "$(\\sin x)^2$", "$\\sin x \\cdot x^2$"], "A", "HARD",
      "$g(f(x)) = g(x^2) = \\sin(x^2)$. Note this differs from $(f \\circ g)(x) = \\sin^2 x$. **Answer: A**", "composite-functions"),
    m("If $f(x) = 2 x - 1$ and $f(g(x)) = 4 x + 5$, then $g(x) =$:",
      ["$2 x + 3$", "$2 x + 6$", "$4 x + 6$", "$2 x - 2$"], "A", "HARD",
      "$2 g(x) - 1 = 4 x + 5 \\Rightarrow g(x) = 2 x + 3$. **Answer: A**", "composite-functions"),
  ],
};

for (const [slug, mcqs] of Object.entries(SUBTOPICS)) {
  fs.writeFileSync(path.join(OUT_DIR, `qset-methods-w2-${slug}.json`),
    JSON.stringify({ mcq: mcqs, shortAnswer: [], extendedAnswer: [], extendedResponse: [] }, null, 2) + "\n");
  console.log(`${slug}: ${mcqs.length} MCQ`);
}
console.log(`Total: ${Object.values(SUBTOPICS).reduce((s, a) => s + a.length, 0)} MCQ.`);
