/**
 * Wave 3b: EXT_ANS across 31 subtopics (4 per subtopic = 124 total).
 * Excludes 4 core-drill subtopics (exponent-and-logarithm-laws, domain-and-range,
 * fundamental-theorem-of-calculus, probability-rules).
 */
import * as fs from "fs";
import * as path from "path";

const OUT_DIR = "scripts/output";
interface EA { content: string; marks: number; difficulty: "EASY" | "MEDIUM" | "HARD"; solutionContent: string; subtopicSlugs: string[]; }
const e = (c: string, m: number, d: "EASY" | "MEDIUM" | "HARD", sol: string, p: string, sec: string[] = []): EA =>
  ({ content: c, marks: m, difficulty: d, solutionContent: sol, subtopicSlugs: [p, ...sec] });

const SUBS: Record<string, EA[]> = {
  "polynomial-equations": [
    e("Let $f(x) = x^2 - 6 x + k$.\n\n**a.** Find the discriminant in terms of $k$. (2 marks)\n\n**b.** Find the values of $k$ for which $f$ has two distinct real roots. (2 marks)\n\n**c.** Find $k$ such that the roots are equal. (2 marks)", 6, "EASY",
      "**a.** (2) $\\Delta = 36 - 4 k$. **b.** (2) $\\Delta > 0 \\Rightarrow k < 9$. **c.** (2) $\\Delta = 0 \\Rightarrow k = 9$.", "polynomial-equations"),
    e("Consider $P(x) = x^3 - 7 x + 6$.\n\n**a.** Show that $x = 1$ is a root. (1 mark)\n\n**b.** Factor $P(x)$ completely. (3 marks)\n\n**c.** State all roots of $P(x) = 0$. (2 marks)", 6, "MEDIUM",
      "**a.** (1) $P(1) = 1 - 7 + 6 = 0$. ✓\n**b.** (3) Divide by $(x - 1)$: $P(x) = (x - 1)(x^2 + x - 6) = (x - 1)(x + 3)(x - 2)$.\n**c.** (2) $x = 1, 2, -3$.", "polynomial-equations"),
    e("Let $f(x) = x^4 - 5 x^2 + 4$.\n\n**a.** Use substitution $u = x^2$ to rewrite. (1 mark)\n\n**b.** Solve $f(x) = 0$ for all real $x$. (4 marks)\n\n**c.** Sketch the graph showing intercepts. (2 marks)", 7, "MEDIUM",
      "**a.** (1) $u^2 - 5 u + 4 = 0$.\n**b.** (4) $(u - 1)(u - 4) = 0 \\Rightarrow u = 1, 4 \\Rightarrow x = \\pm 1, \\pm 2$.\n**c.** (2) Quartic with x-intercepts at $\\pm 1, \\pm 2$, y-intercept 4, opens up, two local minima.", "polynomial-equations"),
    e("Given $P(x) = x^3 + a x^2 + b x - 6$ has roots $1$ and $-2$:\n\n**a.** Use the roots to write two equations in $a$ and $b$. (2 marks)\n\n**b.** Solve to find $a$ and $b$. (3 marks)\n\n**c.** Find the third root. (3 marks)", 8, "HARD",
      "**a.** (2) $P(1) = 1 + a + b - 6 = 0 \\Rightarrow a + b = 5$. $P(-2) = -8 + 4 a - 2 b - 6 = 0 \\Rightarrow 4 a - 2 b = 14$, i.e. $2 a - b = 7$.\n**b.** (3) Adding gives $3 a = 12 \\Rightarrow a = 4$; then $b = 1$.\n**c.** (3) $P(x) = x^3 + 4 x^2 + x - 6 = (x - 1)(x + 2)(x + 3)$ ⇒ third root $x = -3$.", "polynomial-equations"),
  ],
  "exponential-equations": [
    e("Solve the equation $e^{2 x} - 5 e^x + 6 = 0$ exactly.\n\n**a.** Let $u = e^x$ and write as a quadratic in $u$. (1 mark)\n\n**b.** Solve for $u$. (2 marks)\n\n**c.** Find $x$. (2 marks)", 5, "EASY",
      "**a.** (1) $u^2 - 5 u + 6 = 0$.\n**b.** (2) $(u - 2)(u - 3) = 0 \\Rightarrow u = 2, 3$.\n**c.** (2) $x = \\ln 2$ or $x = \\ln 3$.", "exponential-equations"),
    e("Consider $4^x - 6 \\cdot 2^x + 8 = 0$.\n\n**a.** Substitute $u = 2^x$ to obtain a quadratic. (2 marks)\n\n**b.** Solve the quadratic. (2 marks)\n\n**c.** Find $x$ exactly. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $4^x = (2^x)^2 = u^2$; equation $u^2 - 6 u + 8 = 0$.\n**b.** (2) $(u - 2)(u - 4) = 0 \\Rightarrow u = 2, 4$.\n**c.** (3) $2^x = 2 \\Rightarrow x = 1$; $2^x = 4 \\Rightarrow x = 2$.", "exponential-equations"),
    e("A bacterial colony has population $N(t) = 200 e^{0.1 t}$.\n\n**a.** Find $N(0)$. (1 mark)\n\n**b.** Find the exact time at which $N$ doubles. (3 marks)\n\n**c.** Find $N$ at $t = 10\\ln 2$. (2 marks)", 6, "MEDIUM",
      "**a.** (1) $N(0) = 200$.\n**b.** (3) $200 e^{0.1 t} = 400 \\Rightarrow e^{0.1 t} = 2 \\Rightarrow t = 10 \\ln 2$.\n**c.** (2) From b, $N = 400$.", "exponential-equations"),
    e("Solve $e^x + 4 e^{-x} = 4$ exactly.\n\n**a.** Multiply by $e^x$ to clear. (2 marks)\n\n**b.** Substitute $u = e^x$ and solve. (3 marks)\n\n**c.** State all real solutions for $x$. (2 marks)", 7, "HARD",
      "**a.** (2) $e^{2 x} + 4 = 4 e^x \\Rightarrow e^{2 x} - 4 e^x + 4 = 0$.\n**b.** (3) $u^2 - 4 u + 4 = (u - 2)^2 = 0 \\Rightarrow u = 2$.\n**c.** (2) $e^x = 2 \\Rightarrow x = \\ln 2$ (only solution).", "exponential-equations"),
  ],
  "logarithmic-equations": [
    e("Solve $\\log_e(x) + \\log_e(x - 3) = \\log_e 4$.\n\n**a.** Combine the logs. (1 mark)\n\n**b.** Solve the resulting quadratic. (2 marks)\n\n**c.** State valid solutions. (2 marks)", 5, "EASY",
      "**a.** (1) $\\log[x(x - 3)] = \\log 4 \\Rightarrow x^2 - 3 x = 4$.\n**b.** (2) $x^2 - 3 x - 4 = 0 \\Rightarrow (x - 4)(x + 1) = 0$.\n**c.** (2) $x > 3$ required, so only $x = 4$.", "logarithmic-equations"),
    e("Solve $\\log_2(x) + \\log_2(x + 2) = 3$.\n\n**a.** Combine logs. (2 marks)\n\n**b.** Solve the quadratic. (2 marks)\n\n**c.** State valid solutions. (2 marks)", 6, "MEDIUM",
      "**a.** (2) $\\log_2[x(x + 2)] = 3 \\Rightarrow x(x + 2) = 8$.\n**b.** (2) $x^2 + 2 x - 8 = 0 \\Rightarrow (x + 4)(x - 2) = 0$.\n**c.** (2) Need $x > 0$ ⇒ $x = 2$.", "logarithmic-equations"),
    e("Let $f(x) = 2 \\log_e(x) - \\log_e(x + 6)$.\n\n**a.** Express as a single log. (2 marks)\n\n**b.** Solve $f(x) = 0$. (3 marks)\n\n**c.** State the domain of $f$. (2 marks)", 7, "MEDIUM",
      "**a.** (2) $f(x) = \\log\\left(\\dfrac{x^2}{x + 6}\\right)$.\n**b.** (3) $\\dfrac{x^2}{x + 6} = 1 \\Rightarrow x^2 = x + 6 \\Rightarrow (x - 3)(x + 2) = 0$. Need $x > 0$ ⇒ $x = 3$.\n**c.** (2) $x > 0$ and $x + 6 > 0$ ⇒ $x > 0$.", "logarithmic-equations"),
    e("Solve $\\log_4(x^2 - 8 x + 16) = 1$.\n\n**a.** Rewrite using $4^1$. (2 marks)\n\n**b.** Note that the argument factors as a perfect square. (2 marks)\n\n**c.** Find all solutions. (4 marks)", 8, "HARD",
      "**a.** (2) $x^2 - 8 x + 16 = 4$.\n**b.** (2) $(x - 4)^2 = 4$ — perfect square.\n**c.** (4) $x - 4 = \\pm 2 \\Rightarrow x = 6$ or $x = 2$. Both make argument $= 4 > 0$ ⇒ both valid.", "logarithmic-equations"),
  ],
  "trigonometric-equations": [
    e("Solve $2 \\sin x - 1 = 0$ for $x \\in [0, 2\\pi]$.\n\n**a.** Isolate $\\sin x$. (1 mark)\n\n**b.** Find solutions. (2 marks)\n\n**c.** Verify each by substitution. (2 marks)", 5, "EASY",
      "**a.** (1) $\\sin x = 1/2$.\n**b.** (2) $x = \\pi/6$, $5\\pi/6$.\n**c.** (2) $\\sin(\\pi/6) = 1/2$ ✓; $\\sin(5\\pi/6) = 1/2$ ✓.", "trigonometric-equations"),
    e("Solve $\\sin(2 x) = \\dfrac{1}{2}$ for $x \\in [0, \\pi]$.\n\n**a.** Let $u = 2 x$; state the new interval. (2 marks)\n\n**b.** Solve for $u$. (2 marks)\n\n**c.** Find $x$. (2 marks)", 6, "MEDIUM",
      "**a.** (2) $u \\in [0, 2\\pi]$.\n**b.** (2) $u = \\pi/6, 5\\pi/6$.\n**c.** (2) $x = \\pi/12, 5\\pi/12$.", "trigonometric-equations"),
    e("Solve $2 \\sin^2 x = \\sin x$ for $x \\in [0, 2\\pi]$.\n\n**a.** Factor. (2 marks)\n\n**b.** Find all solutions. (4 marks)", 6, "MEDIUM",
      "**a.** (2) $\\sin x(2 \\sin x - 1) = 0$.\n**b.** (4) $\\sin x = 0 \\Rightarrow x = 0, \\pi, 2\\pi$; $\\sin x = 1/2 \\Rightarrow x = \\pi/6, 5\\pi/6$.", "trigonometric-equations"),
    e("Solve $\\cos(2 x) + \\sin(x) = 1$ for $x \\in [0, 2\\pi]$.\n\n**a.** Use double-angle: $\\cos(2 x) = 1 - 2\\sin^2 x$. (2 marks)\n\n**b.** Form a quadratic in $\\sin x$. (3 marks)\n\n**c.** Solve. (3 marks)", 8, "HARD",
      "**a.** (2) Equation: $1 - 2\\sin^2 x + \\sin x = 1$.\n**b.** (3) $-2 \\sin^2 x + \\sin x = 0 \\Rightarrow \\sin x(1 - 2 \\sin x) = 0$.\n**c.** (3) $\\sin x = 0$ or $\\sin x = 1/2$ ⇒ $x = 0, \\pi, 2\\pi, \\pi/6, 5\\pi/6$.", "trigonometric-equations"),
  ],
  "simultaneous-equations": [
    e("Solve simultaneously: $y = 2 x + 1$ and $y = x^2 - 2$.\n\n**a.** Set the expressions equal. (1 mark)\n\n**b.** Solve the resulting quadratic. (2 marks)\n\n**c.** Find the points of intersection. (2 marks)", 5, "EASY",
      "**a.** (1) $x^2 - 2 = 2 x + 1$.\n**b.** (2) $x^2 - 2 x - 3 = 0 \\Rightarrow (x - 3)(x + 1) = 0$.\n**c.** (2) $(3, 7)$ and $(-1, -1)$.", "simultaneous-equations"),
    e("Solve the system $x^2 + y^2 = 25$, $y = x + 1$.\n\n**a.** Substitute. (2 marks)\n\n**b.** Solve. (3 marks)\n\n**c.** State solution pairs. (2 marks)", 7, "MEDIUM",
      "**a.** (2) $x^2 + (x + 1)^2 = 25 \\Rightarrow 2 x^2 + 2 x - 24 = 0$.\n**b.** (3) $x^2 + x - 12 = 0 \\Rightarrow (x + 4)(x - 3) = 0$.\n**c.** (2) $(3, 4)$ and $(-4, -3)$.", "simultaneous-equations"),
    e("Find $k$ such that the line $y = x + k$ is tangent to the circle $x^2 + y^2 = 2$.\n\n**a.** Substitute. (2 marks)\n\n**b.** Use discriminant = 0. (3 marks)\n\n**c.** Solve for $k$. (2 marks)", 7, "MEDIUM",
      "**a.** (2) $x^2 + (x + k)^2 = 2 \\Rightarrow 2 x^2 + 2 k x + k^2 - 2 = 0$.\n**b.** (3) Tangent ⇒ $\\Delta = 0$: $4 k^2 - 8(k^2 - 2) = 0$.\n**c.** (2) $-4 k^2 + 16 = 0 \\Rightarrow k = \\pm 2$.", "simultaneous-equations"),
    e("A small business sells two items, A and B. Each A costs \\$3 and sells for \\$5; each B costs \\$2 and sells for \\$4. The business sold $x$ of A and $y$ of B in a week. Total revenue \\$40, total cost \\$22.\n\n**a.** Form the equations. (2 marks)\n\n**b.** Solve. (3 marks)\n\n**c.** Verify. (2 marks)", 7, "HARD",
      "**a.** (2) $5 x + 4 y = 40$ and $3 x + 2 y = 22$.\n**b.** (3) From second eq: $y = (22 - 3 x)/2 = 11 - 1.5 x$. Substitute: $5 x + 4(11 - 1.5 x) = 40 \\Rightarrow -x + 44 = 40 \\Rightarrow x = 4, y = 5$.\n**c.** (2) Revenue: $5(4) + 4(5) = 40$ ✓; Cost: $3(4) + 2(5) = 22$ ✓.", "simultaneous-equations"),
  ],
  // ─── FUNCTIONS (EXT_ANS) ────────────────────────────────────────────
  "polynomial-functions": [
    e("Let $f(x) = x^3 - 3 x^2$.\n\n**a.** Find $f'(x)$. (1 mark)\n\n**b.** Find the stationary points. (3 marks)\n\n**c.** Sketch the graph. (2 marks)", 6, "EASY",
      "**a.** (1) $f'(x) = 3 x^2 - 6 x$.\n**b.** (3) $3 x(x - 2) = 0 \\Rightarrow x = 0, 2$. $f(0) = 0$, $f(2) = -4$. Points $(0, 0)$, $(2, -4)$.\n**c.** (2) Cubic with local max at $(0, 0)$, local min at $(2, -4)$, $f(3) = 0$, rising rightward.", "polynomial-functions"),
    e("Express $g(x) = x^2 + 4 x + 5$ in completed square form, and find its minimum value.\n\n**a.** Complete the square. (3 marks)\n\n**b.** State the vertex. (1 mark)\n\n**c.** State the minimum value. (2 marks)", 6, "MEDIUM",
      "**a.** (3) $x^2 + 4 x = (x + 2)^2 - 4 \\Rightarrow g(x) = (x + 2)^2 + 1$.\n**b.** (1) $(-2, 1)$.\n**c.** (2) Min value $= 1$.", "polynomial-functions"),
    e("Given the polynomial $P(x) = 2 x^3 - 3 x^2 - 12 x + 8$:\n\n**a.** Find $P'(x)$. (1 mark)\n\n**b.** Find all stationary points. (4 marks)\n\n**c.** Classify each. (2 marks)", 7, "MEDIUM",
      "**a.** (1) $P'(x) = 6 x^2 - 6 x - 12$.\n**b.** (4) $6(x^2 - x - 2) = 6(x - 2)(x + 1) = 0 \\Rightarrow x = 2, -1$. $P(2) = -12$, $P(-1) = 15$. Points $(2, -12)$, $(-1, 15)$.\n**c.** (2) $P''(x) = 12 x - 6$. $P''(-1) = -18 < 0$ (max); $P''(2) = 18 > 0$ (min).", "polynomial-functions"),
    e("A polynomial $f(x) = a x^3 + b x + c$ has $f(1) = 0$, $f'(1) = 6$, $f(0) = -2$.\n\n**a.** Use $f(0) = -2$ to find $c$. (1 mark)\n\n**b.** Use $f(1) = 0$ and $f'(1) = 6$ to find $a$ and $b$. (4 marks)\n\n**c.** Write the polynomial. (2 marks)", 7, "HARD",
      "**a.** (1) $c = -2$.\n**b.** (4) $f(1) = a + b + c = a + b - 2 = 0 \\Rightarrow a + b = 2$. $f'(x) = 3 a x^2 + b$. $f'(1) = 3 a + b = 6$. Solve: $2 a = 4 \\Rightarrow a = 2$, $b = 0$.\n**c.** (2) $f(x) = 2 x^3 - 2$.", "polynomial-functions"),
  ],
  "exponential-functions": [
    e("Let $f(x) = 3 e^{2 x}$.\n\n**a.** Find $f(0)$. (1 mark)\n\n**b.** Find $f'(x)$. (2 marks)\n\n**c.** Find $f'(0)$. (1 mark)\n\n**d.** State the range of $f$. (1 mark)", 5, "EASY",
      "**a.** (1) $f(0) = 3$. **b.** (2) $f'(x) = 6 e^{2 x}$. **c.** (1) $f'(0) = 6$. **d.** (1) $(0, \\infty)$.", "exponential-functions"),
    e("A radioactive substance has mass $M(t) = 100 e^{-0.05 t}$ grams after $t$ years.\n\n**a.** State the initial mass. (1 mark)\n\n**b.** Find the time for the mass to halve, in exact form. (3 marks)\n\n**c.** Find $M(20)$ to nearest gram. (2 marks)", 6, "MEDIUM",
      "**a.** (1) $M(0) = 100$ g.\n**b.** (3) $100 e^{-0.05 t} = 50 \\Rightarrow e^{-0.05 t} = 1/2 \\Rightarrow t = 20 \\ln 2$ years.\n**c.** (2) $M(20) = 100 e^{-1} \\approx 37$ g.", "exponential-functions"),
    e("Let $f(x) = e^x - 2 e^{-x}$.\n\n**a.** Find $f(0)$. (1 mark)\n\n**b.** Find $f'(x)$. (2 marks)\n\n**c.** Solve $f'(x) = 0$ exactly. (3 marks)\n\n**d.** Find the y-coordinate at that point. (1 mark)", 7, "MEDIUM",
      "**a.** (1) $f(0) = 1 - 2 = -1$.\n**b.** (2) $f'(x) = e^x + 2 e^{-x}$.\n**c.** (3) $e^x + 2 e^{-x} = 0 \\Rightarrow e^{2 x} = -2$, no real solution. So no stationary point.\n**d.** (1) N/A — $f$ is strictly increasing.", "exponential-functions"),
    e("The number of microbes $N(t) = 50 \\cdot 2^t$ where $t$ is hours.\n\n**a.** Find $N(3)$. (1 mark)\n\n**b.** Find the time for the population to reach 6400, in exact form. (3 marks)\n\n**c.** Express $N(t)$ in terms of $e$. (3 marks)", 7, "HARD",
      "**a.** (1) $N(3) = 400$.\n**b.** (3) $50 \\cdot 2^t = 6400 \\Rightarrow 2^t = 128 = 2^7 \\Rightarrow t = 7$ hours.\n**c.** (3) $2^t = e^{t \\ln 2}$, so $N(t) = 50 e^{t \\ln 2}$.", "exponential-functions"),
  ],
  "logarithmic-functions": [
    e("Let $f(x) = \\ln(2 x - 6)$.\n\n**a.** State the domain. (1 mark)\n\n**b.** Find $f'(x)$. (2 marks)\n\n**c.** Find the x-intercept of $f$. (2 marks)", 5, "EASY",
      "**a.** (1) $2 x - 6 > 0 \\Rightarrow x > 3$.\n**b.** (2) $f'(x) = \\dfrac{2}{2 x - 6} = \\dfrac{1}{x - 3}$.\n**c.** (2) $\\ln(2 x - 6) = 0 \\Rightarrow 2 x - 6 = 1 \\Rightarrow x = 7/2$.", "logarithmic-functions"),
    e("Let $g(x) = x \\ln x$ for $x > 0$.\n\n**a.** Find $g'(x)$ using the product rule. (2 marks)\n\n**b.** Find the stationary point exactly. (3 marks)\n\n**c.** State its nature. (1 mark)", 6, "MEDIUM",
      "**a.** (2) $g'(x) = \\ln x + 1$.\n**b.** (3) $g'(x) = 0 \\Rightarrow \\ln x = -1 \\Rightarrow x = 1/e$. $g(1/e) = -1/e$.\n**c.** (1) $g''(x) = 1/x > 0$ ⇒ local min.", "logarithmic-functions"),
    e("Given $f(x) = \\ln x$:\n\n**a.** Find the equation of the tangent at $(1, 0)$. (2 marks)\n\n**b.** Find the equation of the tangent at $(e, 1)$. (3 marks)\n\n**c.** Find their intersection. (2 marks)", 7, "MEDIUM",
      "**a.** (2) $f'(1) = 1$: $y = x - 1$.\n**b.** (3) $f'(e) = 1/e$: $y - 1 = (1/e)(x - e) \\Rightarrow y = x/e$.\n**c.** (2) $x - 1 = x/e \\Rightarrow x(1 - 1/e) = 1 \\Rightarrow x = e/(e - 1)$, $y = 1/(e - 1)$.", "logarithmic-functions"),
    e("Show that $\\dfrac{d}{dx}[x \\ln x - x] = \\ln x$, and hence find $\\displaystyle\\int_1^e \\ln x \\, dx$ exactly.\n\n**a.** Verify the derivative. (3 marks)\n\n**b.** Apply the result to find the integral. (3 marks)\n\n**c.** Simplify. (2 marks)", 8, "HARD",
      "**a.** (3) $\\dfrac{d}{dx}[x \\ln x] = \\ln x + 1$. Then $\\dfrac{d}{dx}[x \\ln x - x] = \\ln x + 1 - 1 = \\ln x$. ✓\n**b.** (3) $\\int_1^e \\ln x \\, dx = [x \\ln x - x]_1^e = (e \\cdot 1 - e) - (1 \\cdot 0 - 1) = 0 + 1 = 1$.\n**c.** (2) Value: $1$.", "logarithmic-functions"),
  ],
  "trigonometric-functions": [
    e("Let $f(x) = 2 \\sin x + 1$.\n\n**a.** State the period and amplitude. (2 marks)\n\n**b.** Find the range. (2 marks)\n\n**c.** Find the x-intercepts in $[0, 2\\pi]$. (2 marks)", 6, "EASY",
      "**a.** (2) Period $2\\pi$, amplitude 2.\n**b.** (2) $\\sin x \\in [-1, 1] \\Rightarrow f \\in [-1, 3]$.\n**c.** (2) $f = 0 \\Rightarrow \\sin x = -1/2 \\Rightarrow x = 7\\pi/6, 11\\pi/6$.", "trigonometric-functions"),
    e("Let $g(x) = \\sin(2 x) + \\cos x$ for $x \\in [0, 2\\pi]$.\n\n**a.** Use double-angle to rewrite $\\sin(2 x)$. (1 mark)\n\n**b.** Factor $g(x)$. (3 marks)\n\n**c.** Find all $x$ in $[0, 2\\pi]$ where $g(x) = 0$. (3 marks)", 7, "MEDIUM",
      "**a.** (1) $\\sin(2 x) = 2 \\sin x \\cos x$.\n**b.** (3) $g(x) = 2 \\sin x \\cos x + \\cos x = \\cos x(2 \\sin x + 1)$.\n**c.** (3) $\\cos x = 0 \\Rightarrow x = \\pi/2, 3\\pi/2$; $\\sin x = -1/2 \\Rightarrow x = 7\\pi/6, 11\\pi/6$. Four solutions.", "trigonometric-functions"),
    e("Show that $\\sin^2 x + \\cos^2 x = 1$ using the unit circle, and use this to simplify $\\dfrac{1 - \\cos^2 x}{\\sin x}$ for $\\sin x \\neq 0$.\n\n**a.** State the identity. (1 mark)\n\n**b.** Substitute. (3 marks)\n\n**c.** Simplify. (3 marks)", 7, "MEDIUM",
      "**a.** (1) $\\sin^2 x + \\cos^2 x = 1$ (Pythagorean identity from unit circle).\n**b.** (3) $1 - \\cos^2 x = \\sin^2 x$, so expression $= \\dfrac{\\sin^2 x}{\\sin x}$.\n**c.** (3) $= \\sin x$.", "trigonometric-functions"),
    e("A tide is modelled by $h(t) = 5 + 3 \\sin(\\pi t / 6)$, $t$ in hours.\n\n**a.** Find max and min depths. (2 marks)\n\n**b.** Find times of maxima in $[0, 24]$. (3 marks)\n\n**c.** Find $h'(t)$. (3 marks)", 8, "HARD",
      "**a.** (2) Max $= 8$, min $= 2$.\n**b.** (3) Max when $\\sin = 1$: $\\pi t/6 = \\pi/2, 5\\pi/2$ ⇒ $t = 3, 15$ hours.\n**c.** (3) $h'(t) = (\\pi/2) \\cos(\\pi t/6)$.", "trigonometric-functions"),
  ],
  "rational-functions": [
    e("Let $f(x) = \\dfrac{1}{x + 2}$.\n\n**a.** State the maximal domain. (1 mark)\n\n**b.** State the equations of both asymptotes. (2 marks)\n\n**c.** Sketch the graph indicating asymptotes. (2 marks)", 5, "EASY",
      "**a.** (1) $x \\neq -2$.\n**b.** (2) $x = -2$ (vertical), $y = 0$ (horizontal).\n**c.** (2) Hyperbola translated 2 left from $y = 1/x$; branches in upper-right and lower-left of $(-2, 0)$.", "rational-functions"),
    e("Let $g(x) = \\dfrac{2 x + 1}{x - 3}$.\n\n**a.** Find the y-intercept. (1 mark)\n\n**b.** Find the x-intercept. (2 marks)\n\n**c.** State both asymptotes. (3 marks)", 6, "MEDIUM",
      "**a.** (1) $g(0) = -1/3$.\n**b.** (2) Numerator $= 0$: $x = -1/2$.\n**c.** (3) Vertical: $x = 3$. Horizontal: limit of leading coefficients $2/1 = 2$, so $y = 2$.", "rational-functions"),
    e("Find the maximal domain of $h(x) = \\dfrac{x - 2}{x^2 - 9}$ and state all asymptotes.\n\n**a.** Factor the denominator. (1 mark)\n\n**b.** State the domain. (2 marks)\n\n**c.** State all asymptotes. (3 marks)", 6, "MEDIUM",
      "**a.** (1) $x^2 - 9 = (x - 3)(x + 3)$.\n**b.** (2) $x \\neq \\pm 3$.\n**c.** (3) Two vertical asymptotes $x = 3$ and $x = -3$; horizontal $y = 0$ (numerator degree < denominator degree).", "rational-functions"),
    e("Consider $y = \\dfrac{x^2 + 1}{x}$ for $x \\neq 0$.\n\n**a.** Rewrite as $y = x + 1/x$. (1 mark)\n\n**b.** Find $y'$. (2 marks)\n\n**c.** Find the stationary points exactly. (3 marks)\n\n**d.** Classify. (2 marks)", 8, "HARD",
      "**a.** (1) $y = x + 1/x$.\n**b.** (2) $y' = 1 - 1/x^2$.\n**c.** (3) $y' = 0 \\Rightarrow x^2 = 1 \\Rightarrow x = \\pm 1$. $y(1) = 2$, $y(-1) = -2$. Points $(1, 2)$, $(-1, -2)$.\n**d.** (2) $y'' = 2/x^3$. $y''(1) > 0$ (min); $y''(-1) < 0$ (max).", "rational-functions"),
  ],
  "transformations": [
    e("Describe the sequence of transformations that takes $y = x^2$ to $y = 2(x - 3)^2 + 1$.\n\n**a.** Translation in $x$. (1 mark)\n\n**b.** Dilation from x-axis. (2 marks)\n\n**c.** Translation in $y$. (1 mark)\n\n**d.** State the new vertex. (1 mark)", 5, "EASY",
      "**a.** (1) Translation 3 units right.\n**b.** (2) Dilation by factor 2 from x-axis.\n**c.** (1) Translation 1 unit up.\n**d.** (1) Vertex $(3, 1)$.", "transformations"),
    e("Let $f(x) = e^x$ and $g(x) = -e^{x - 1} + 2$.\n\n**a.** List the transformations from $f$ to $g$. (3 marks)\n\n**b.** State the asymptote of $g$. (2 marks)\n\n**c.** Find $g(1)$. (2 marks)", 7, "MEDIUM",
      "**a.** (3) (1) translate right by 1; (2) reflect in x-axis; (3) translate up by 2.\n**b.** (2) As $x \\to -\\infty$, $g \\to 2$. Asymptote $y = 2$.\n**c.** (2) $g(1) = -1 + 2 = 1$.", "transformations"),
    e("Given $y = \\sin x$, find the image of $(\\pi/2, 1)$ under the transformation $y = 2 f(x - \\pi/4) - 1$.\n\n**a.** Apply horizontal shift. (2 marks)\n\n**b.** Apply vertical dilation. (2 marks)\n\n**c.** Apply vertical shift. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $x \\to x + \\pi/4$: $(\\pi/2, 1) \\to (\\pi/2 + \\pi/4, 1) = (3\\pi/4, 1)$.\n**b.** (2) $y \\to 2 y$: $(3\\pi/4, 2)$.\n**c.** (3) $y \\to y - 1$: $(3\\pi/4, 1)$.", "transformations"),
    e("The graph of $y = f(x)$ passes through $(2, 5)$. Find the corresponding point on $y = 3 f(2 x + 4) - 1$.\n\n**a.** Solve $2 x + 4 = 2$ for $x$. (2 marks)\n\n**b.** Find new $y$. (3 marks)\n\n**c.** State the image point. (3 marks)", 8, "HARD",
      "**a.** (2) $2 x = -2 \\Rightarrow x = -1$.\n**b.** (3) At $x = -1$: $y = 3 \\cdot 5 - 1 = 14$.\n**c.** (3) Image: $(-1, 14)$.", "transformations"),
  ],
  "inverse-functions": [
    e("Find $f^{-1}$ for $f(x) = 3 x - 6$.\n\n**a.** Set $y = 3 x - 6$. (1 mark)\n\n**b.** Solve for $x$. (2 marks)\n\n**c.** State $f^{-1}$ and its domain. (2 marks)", 5, "EASY",
      "**a.** (1) $y = 3 x - 6$.\n**b.** (2) $x = (y + 6)/3$.\n**c.** (2) $f^{-1}(x) = (x + 6)/3$; domain $\\mathbb{R}$.", "inverse-functions"),
    e("Given $f(x) = (x - 1)^2$ for $x \\geq 1$:\n\n**a.** Justify why $f$ is one-to-one on this restricted domain. (2 marks)\n\n**b.** Find $f^{-1}$. (3 marks)\n\n**c.** State the domain of $f^{-1}$. (1 mark)", 6, "MEDIUM",
      "**a.** (2) $f'(x) = 2(x - 1) \\geq 0$ for $x \\geq 1$, so $f$ is increasing — one-to-one.\n**b.** (3) $y = (x - 1)^2 \\Rightarrow x = 1 + \\sqrt y$ (positive root). $f^{-1}(x) = 1 + \\sqrt x$.\n**c.** (1) $[0, \\infty)$ (= range of $f$).", "inverse-functions"),
    e("Let $f(x) = e^x + 3$.\n\n**a.** Find $f^{-1}(x)$. (3 marks)\n\n**b.** State the domain and range of $f^{-1}$. (2 marks)\n\n**c.** Sketch $f$ and $f^{-1}$ on the same axes (qualitative). (2 marks)", 7, "MEDIUM",
      "**a.** (3) $y = e^x + 3 \\Rightarrow e^x = y - 3 \\Rightarrow x = \\ln(y - 3)$. $f^{-1}(x) = \\ln(x - 3)$.\n**b.** (2) Domain $(3, \\infty)$, range $\\mathbb{R}$.\n**c.** (2) Mirror images across $y = x$.", "inverse-functions"),
    e("The functions $f(x) = e^{2 x}$ and $g(x) = (1/2) \\ln x$ are related.\n\n**a.** Compute $(g \\circ f)(x)$. (3 marks)\n\n**b.** Hence show $g = f^{-1}$. (3 marks)\n\n**c.** State the domain of $g$. (2 marks)", 8, "HARD",
      "**a.** (3) $g(f(x)) = g(e^{2 x}) = (1/2) \\ln(e^{2 x}) = (1/2)(2 x) = x$.\n**b.** (3) Since $g(f(x)) = x$ for all real $x$ (and one can also verify $f(g(x)) = x$ for $x > 0$), $g = f^{-1}$.\n**c.** (2) Domain $(0, \\infty)$ (= range of $f$).", "inverse-functions"),
  ],
  "composite-functions": [
    e("Let $f(x) = x^2 + 1$ and $g(x) = 2 x - 3$.\n\n**a.** Find $(f \\circ g)(x)$. (2 marks)\n\n**b.** Find $(g \\circ f)(x)$. (2 marks)\n\n**c.** Compute $(f \\circ g)(2)$. (1 mark)", 5, "EASY",
      "**a.** (2) $(f \\circ g)(x) = (2 x - 3)^2 + 1$.\n**b.** (2) $(g \\circ f)(x) = 2(x^2 + 1) - 3 = 2 x^2 - 1$.\n**c.** (1) $f(g(2)) = (1)^2 + 1 = 2$.", "composite-functions"),
    e("If $f(x) = \\sqrt x$ and $g(x) = x + 2$:\n\n**a.** Find $(f \\circ g)(x)$. (2 marks)\n\n**b.** State the domain of $f \\circ g$. (2 marks)\n\n**c.** Find $(g \\circ f)(x)$ and its domain. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $(f \\circ g)(x) = \\sqrt{x + 2}$.\n**b.** (2) Need $x + 2 \\geq 0 \\Rightarrow x \\geq -2$.\n**c.** (3) $(g \\circ f)(x) = \\sqrt x + 2$. Domain: $x \\geq 0$.", "composite-functions"),
    e("Given $h(x) = (2 x + 1)^3$, write as $f(g(x))$ with $g$ linear.\n\n**a.** Identify $g$ and $f$. (2 marks)\n\n**b.** Verify by computation. (2 marks)\n\n**c.** Differentiate $h$ using the chain rule. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $g(x) = 2 x + 1$, $f(u) = u^3$.\n**b.** (2) $f(g(x)) = (2 x + 1)^3 = h(x)$ ✓.\n**c.** (3) $h'(x) = 3(2 x + 1)^2 \\cdot 2 = 6(2 x + 1)^2$.", "composite-functions"),
    e("If $f(x) = e^x$ and $g(x) = x^2 - 4$:\n\n**a.** Find $(f \\circ g)(x)$. (2 marks)\n\n**b.** Find $(f \\circ g)'(x)$. (3 marks)\n\n**c.** Find where $(f \\circ g)'(x) = 0$. (3 marks)", 8, "HARD",
      "**a.** (2) $(f \\circ g)(x) = e^{x^2 - 4}$.\n**b.** (3) Chain: $e^{x^2 - 4} \\cdot 2 x = 2 x e^{x^2 - 4}$.\n**c.** (3) $2 x e^{...} = 0$ ⇒ $x = 0$ (exponential never zero).", "composite-functions"),
  ],
  // ─── CALCULUS (EXT_ANS) ──────────────────────────────────────────────
  "differentiation": [
    e("Let $f(x) = 3 x^2 - 4 x + 1$.\n\n**a.** Find $f'(x)$. (1 mark)\n\n**b.** Find $f'(1)$. (1 mark)\n\n**c.** Find the equation of the tangent to $f$ at $x = 1$. (3 marks)", 5, "EASY",
      "**a.** (1) $f'(x) = 6 x - 4$.\n**b.** (1) $f'(1) = 2$.\n**c.** (3) $f(1) = 0$; tangent $y - 0 = 2(x - 1) \\Rightarrow y = 2 x - 2$.", "differentiation"),
    e("Find the gradient of the curve $y = x^3 - 6 x$ at the point $(2, -4)$.\n\n**a.** Find $\\dfrac{dy}{dx}$. (2 marks)\n\n**b.** Substitute $x = 2$. (2 marks)\n\n**c.** State the gradient and tangent line. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $dy/dx = 3 x^2 - 6$.\n**b.** (2) At $x = 2$: $12 - 6 = 6$.\n**c.** (3) Gradient 6; tangent $y + 4 = 6(x - 2) \\Rightarrow y = 6 x - 16$.", "differentiation"),
    e("Let $f(x) = (2 x + 1)(x - 3)$.\n\n**a.** Expand and differentiate. (3 marks)\n\n**b.** Find the stationary point. (2 marks)\n\n**c.** Classify it. (2 marks)", 7, "MEDIUM",
      "**a.** (3) $f(x) = 2 x^2 - 5 x - 3$; $f'(x) = 4 x - 5$.\n**b.** (2) $f'(x) = 0 \\Rightarrow x = 5/4$; $f(5/4) = -49/8$.\n**c.** (2) $f''(x) = 4 > 0$ ⇒ local min.", "differentiation"),
    e("Use first principles to differentiate $f(x) = x^2$.\n\n**a.** Set up the limit. (2 marks)\n\n**b.** Expand and simplify. (3 marks)\n\n**c.** Take the limit. (3 marks)", 8, "HARD",
      "**a.** (2) $f'(x) = \\lim_{h \\to 0} \\dfrac{(x + h)^2 - x^2}{h}$.\n**b.** (3) Numerator: $x^2 + 2 x h + h^2 - x^2 = 2 x h + h^2$; divide by $h$: $2 x + h$.\n**c.** (3) $\\lim_{h \\to 0}(2 x + h) = 2 x$.", "differentiation"),
  ],
  "chain-rule": [
    e("Differentiate $f(x) = (3 x - 1)^4$.\n\n**a.** Apply the chain rule. (2 marks)\n\n**b.** Simplify. (1 mark)\n\n**c.** Find $f'(1)$. (2 marks)", 5, "EASY",
      "**a.** (2) Outer: $4 u^3$; inner: 3; so $4(3 x - 1)^3 \\cdot 3$.\n**b.** (1) $= 12(3 x - 1)^3$.\n**c.** (2) $f'(1) = 12(2)^3 = 96$.", "chain-rule"),
    e("Differentiate $g(x) = \\ln(x^2 + 4)$.\n\n**a.** Set up chain rule. (2 marks)\n\n**b.** Compute. (2 marks)\n\n**c.** Find $g'(0)$. (2 marks)", 6, "MEDIUM",
      "**a.** (2) Outer: $1/u$; inner: $2 x$.\n**b.** (2) $g'(x) = \\dfrac{2 x}{x^2 + 4}$.\n**c.** (2) $g'(0) = 0/4 = 0$.", "chain-rule"),
    e("Let $f(x) = e^{x^2 - 1}$.\n\n**a.** Find $f'(x)$. (2 marks)\n\n**b.** Find the stationary point. (3 marks)\n\n**c.** State the minimum value. (2 marks)", 7, "MEDIUM",
      "**a.** (2) $f'(x) = e^{x^2 - 1} \\cdot 2 x = 2 x e^{x^2 - 1}$.\n**b.** (3) $f'(x) = 0 \\Rightarrow x = 0$ (exponential ≠ 0). $f(0) = e^{-1}$. Point $(0, 1/e)$.\n**c.** (2) Min value $1/e$.", "chain-rule"),
    e("Differentiate $y = \\sqrt{4 - x^2}$ and find the equation of the tangent at $(\\sqrt 3, 1)$.\n\n**a.** Find $dy/dx$. (3 marks)\n\n**b.** Evaluate at $x = \\sqrt 3$. (2 marks)\n\n**c.** Write the tangent. (3 marks)", 8, "HARD",
      "**a.** (3) $y = (4 - x^2)^{1/2}$; $dy/dx = \\dfrac{-x}{\\sqrt{4 - x^2}}$.\n**b.** (2) At $x = \\sqrt 3$: $dy/dx = -\\sqrt 3/1 = -\\sqrt 3$.\n**c.** (3) $y - 1 = -\\sqrt 3 (x - \\sqrt 3) \\Rightarrow y = -\\sqrt 3 x + 4$.", "chain-rule"),
  ],
  "product-rule": [
    e("Differentiate $f(x) = x^2 e^x$.\n\n**a.** Apply product rule. (2 marks)\n\n**b.** Simplify. (1 mark)\n\n**c.** Find $f'(0)$. (1 mark)", 4, "EASY",
      "**a.** (2) $2 x \\cdot e^x + x^2 \\cdot e^x$. **b.** (1) $= e^x(2 x + x^2)$. **c.** (1) $f'(0) = 0$.", "product-rule"),
    e("Differentiate $g(x) = x \\sin x$.\n\n**a.** Apply product rule. (2 marks)\n\n**b.** Find $g'(\\pi)$. (2 marks)\n\n**c.** Find $g''(x)$. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $g'(x) = \\sin x + x \\cos x$.\n**b.** (2) $g'(\\pi) = 0 + \\pi \\cdot (-1) = -\\pi$.\n**c.** (3) $g''(x) = \\cos x + \\cos x - x \\sin x = 2 \\cos x - x \\sin x$.", "product-rule"),
    e("Find the stationary points of $h(x) = x e^{-x}$ for $x \\geq 0$.\n\n**a.** Find $h'(x)$. (2 marks)\n\n**b.** Solve $h'(x) = 0$. (2 marks)\n\n**c.** Classify. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $h'(x) = e^{-x} - x e^{-x} = e^{-x}(1 - x)$.\n**b.** (2) $e^{-x} > 0$, so $1 - x = 0 \\Rightarrow x = 1$.\n**c.** (3) $h(1) = e^{-1}$. $h''(x) = e^{-x}(x - 2)$; $h''(1) = -e^{-1} < 0$ ⇒ local max.", "product-rule"),
    e("If $f(x) = x^2 \\ln x$ for $x > 0$:\n\n**a.** Use product rule. (3 marks)\n\n**b.** Find the stationary point exactly. (3 marks)\n\n**c.** Classify it. (2 marks)", 8, "HARD",
      "**a.** (3) $f'(x) = 2 x \\ln x + x^2 \\cdot 1/x = 2 x \\ln x + x = x(2 \\ln x + 1)$.\n**b.** (3) $f'(x) = 0$: $x \\neq 0$, so $2 \\ln x + 1 = 0 \\Rightarrow \\ln x = -1/2 \\Rightarrow x = e^{-1/2}$. $f(e^{-1/2}) = e^{-1} \\cdot (-1/2) = -1/(2 e)$.\n**c.** (2) $f$ has unique stationary point; from sign of $f'$ (negative for small $x$, positive for $x > e^{-1/2}$): local min.", "product-rule"),
  ],
  "quotient-rule": [
    e("Differentiate $f(x) = \\dfrac{x}{x + 2}$.\n\n**a.** Apply quotient rule. (2 marks)\n\n**b.** Simplify. (1 mark)\n\n**c.** Find $f'(0)$. (1 mark)", 4, "EASY",
      "**a.** (2) $\\dfrac{(x + 2)(1) - x(1)}{(x + 2)^2}$. **b.** (1) $= \\dfrac{2}{(x + 2)^2}$. **c.** (1) $f'(0) = 2/4 = 1/2$.", "quotient-rule"),
    e("Let $f(x) = \\dfrac{x^2 + 1}{x - 1}$.\n\n**a.** Apply quotient rule. (3 marks)\n\n**b.** Find any stationary points. (3 marks)\n\n**c.** Verify by simplification. (1 mark)", 7, "MEDIUM",
      "**a.** (3) $f'(x) = \\dfrac{2 x (x - 1) - (x^2 + 1)}{(x - 1)^2} = \\dfrac{x^2 - 2 x - 1}{(x - 1)^2}$.\n**b.** (3) Numerator $= 0$: $x^2 - 2 x - 1 = 0 \\Rightarrow x = 1 \\pm \\sqrt 2$.\n**c.** (1) Both valid since $x \\neq 1$.", "quotient-rule"),
    e("Show $\\dfrac{d}{dx}\\tan x = \\sec^2 x$.\n\n**a.** Use $\\tan x = \\sin x / \\cos x$. (1 mark)\n\n**b.** Apply quotient rule. (3 marks)\n\n**c.** Simplify using $\\sin^2 + \\cos^2 = 1$. (3 marks)", 7, "MEDIUM",
      "**a.** (1) $\\tan x = \\sin x / \\cos x$.\n**b.** (3) $\\dfrac{\\cos x \\cdot \\cos x - \\sin x \\cdot (-\\sin x)}{\\cos^2 x} = \\dfrac{\\cos^2 x + \\sin^2 x}{\\cos^2 x}$.\n**c.** (3) $= \\dfrac{1}{\\cos^2 x} = \\sec^2 x$. ✓", "quotient-rule"),
    e("Let $g(x) = \\dfrac{\\ln x}{x}$ for $x > 0$.\n\n**a.** Find $g'(x)$. (3 marks)\n\n**b.** Find the stationary point. (3 marks)\n\n**c.** State $\\lim_{x \\to \\infty} g(x)$. (2 marks)", 8, "HARD",
      "**a.** (3) $g'(x) = \\dfrac{(1/x) x - \\ln x}{x^2} = \\dfrac{1 - \\ln x}{x^2}$.\n**b.** (3) $g'(x) = 0 \\Rightarrow \\ln x = 1 \\Rightarrow x = e$. $g(e) = 1/e$.\n**c.** (2) $\\lim = 0$ (denominator grows faster).", "quotient-rule"),
  ],
  "tangents-and-normals": [
    e("Find the tangent and normal to $y = x^2$ at $x = 1$.\n\n**a.** Find slope. (2 marks)\n\n**b.** Tangent line equation. (2 marks)\n\n**c.** Normal line equation. (2 marks)", 6, "EASY",
      "**a.** (2) $y'(1) = 2$.\n**b.** (2) $y(1) = 1$; tangent $y = 2 x - 1$.\n**c.** (2) Normal slope $-1/2$; $y - 1 = -\\dfrac{1}{2}(x - 1) \\Rightarrow y = -x/2 + 3/2$.", "tangents-and-normals"),
    e("Find the tangent to $y = e^x$ at $(0, 1)$, and find where it meets the x-axis.\n\n**a.** Find slope at $x = 0$. (1 mark)\n\n**b.** Tangent equation. (2 marks)\n\n**c.** x-intercept of tangent. (2 marks)", 5, "MEDIUM",
      "**a.** (1) $y'(0) = 1$.\n**b.** (2) $y = x + 1$.\n**c.** (2) $0 = x + 1 \\Rightarrow x = -1$. Intercept $(-1, 0)$.", "tangents-and-normals"),
    e("The tangent to $y = x^3 - 3 x$ at $(2, 2)$:\n\n**a.** Find slope. (2 marks)\n\n**b.** Tangent equation. (2 marks)\n\n**c.** Show it meets the curve again at another point. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $y'(2) = 12 - 3 = 9$.\n**b.** (2) $y = 9 x - 16$.\n**c.** (3) Solve $x^3 - 3 x = 9 x - 16 \\Rightarrow x^3 - 12 x + 16 = 0$. Factor with $x = 2$: $(x - 2)(x^2 + 2 x - 8) = (x - 2)(x + 4)(x - 2)$. So $x = 2$ (double root) and $x = -4$. Other intersection $(-4, -52)$.", "tangents-and-normals"),
    e("Find the points on $y = x^2 - 4 x + 5$ where the tangent has slope 2.\n\n**a.** Set $y'(x) = 2$ and solve. (2 marks)\n\n**b.** Find the y-coordinate. (2 marks)\n\n**c.** Write the tangent line. (3 marks)", 7, "HARD",
      "**a.** (2) $y'(x) = 2 x - 4 = 2 \\Rightarrow x = 3$.\n**b.** (2) $y(3) = 9 - 12 + 5 = 2$.\n**c.** (3) $y - 2 = 2(x - 3) \\Rightarrow y = 2 x - 4$.", "tangents-and-normals"),
  ],
  "rates-of-change": [
    e("A particle has position $x(t) = t^2 - 4 t + 3$.\n\n**a.** Find the velocity at $t = 3$. (2 marks)\n\n**b.** Find when the particle is at rest. (2 marks)\n\n**c.** Find acceleration. (1 mark)", 5, "EASY",
      "**a.** (2) $v(t) = 2 t - 4$; $v(3) = 2$.\n**b.** (2) $v = 0 \\Rightarrow t = 2$.\n**c.** (1) $a(t) = 2$ (constant).", "rates-of-change"),
    e("Water drains from a tank: $V(t) = 100(1 - t/10)^2$ litres for $0 \\leq t \\leq 10$.\n\n**a.** Find $V(0)$ and $V(10)$. (2 marks)\n\n**b.** Find $V'(t)$. (2 marks)\n\n**c.** Find the rate at $t = 5$. (2 marks)", 6, "MEDIUM",
      "**a.** (2) $V(0) = 100$, $V(10) = 0$.\n**b.** (2) $V'(t) = 100 \\cdot 2(1 - t/10) \\cdot (-1/10) = -20(1 - t/10)$.\n**c.** (2) $V'(5) = -10$ L/min (draining at 10 L/min).", "rates-of-change"),
    e("A sphere's volume is $V = (4/3)\\pi r^3$. The radius grows at $dr/dt = 0.2$ cm/s.\n\n**a.** Find $dV/dr$. (1 mark)\n\n**b.** Use chain rule for $dV/dt$. (3 marks)\n\n**c.** Compute $dV/dt$ at $r = 5$. (3 marks)", 7, "MEDIUM",
      "**a.** (1) $dV/dr = 4\\pi r^2$.\n**b.** (3) $dV/dt = dV/dr \\cdot dr/dt = 4\\pi r^2 \\cdot 0.2 = 0.8\\pi r^2$.\n**c.** (3) At $r = 5$: $0.8\\pi \\cdot 25 = 20\\pi$ cm³/s.", "rates-of-change"),
    e("A spotlight shines on a wall as a person walks past. If a 1.8 m person walks at 1.5 m/s away from a 6 m lamp post, find how fast their shadow lengthens.\n\n**a.** Set up similar triangles to get shadow length $s$ in terms of person's distance $x$. (3 marks)\n\n**b.** Differentiate to find $ds/dt$. (3 marks)\n\n**c.** Compute. (2 marks)", 8, "HARD",
      "**a.** (3) Similar triangles: $\\dfrac{s}{1.8} = \\dfrac{s + x}{6}$. Cross-multiply: $6 s = 1.8(s + x) \\Rightarrow 4.2 s = 1.8 x \\Rightarrow s = 3 x/7$.\n**b.** (3) $ds/dt = (3/7) dx/dt$.\n**c.** (2) $= (3/7)(1.5) = 9/14 \\approx 0.64$ m/s.", "rates-of-change"),
  ],
  "stationary-points-and-curve-sketching": [
    e("Sketch the graph of $f(x) = x^3 - 3 x + 2$.\n\n**a.** Find stationary points. (3 marks)\n\n**b.** Classify them. (2 marks)\n\n**c.** State y-intercept and sketch. (2 marks)", 7, "EASY",
      "**a.** (3) $f'(x) = 3 x^2 - 3 = 0 \\Rightarrow x = \\pm 1$; $f(1) = 0$, $f(-1) = 4$.\n**b.** (2) $f''(x) = 6 x$; $f''(1) > 0$ (min), $f''(-1) < 0$ (max).\n**c.** (2) y-intercept 2; cubic shape, local max $(-1, 4)$, local min $(1, 0)$.", "stationary-points-and-curve-sketching"),
    e("Investigate stationary points of $f(x) = x^4 - 2 x^2$.\n\n**a.** Find $f'(x)$. (2 marks)\n\n**b.** Find stationary points. (2 marks)\n\n**c.** Classify. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $f'(x) = 4 x^3 - 4 x = 4 x(x^2 - 1)$.\n**b.** (2) $x = 0, \\pm 1$. Values: $f(0) = 0$, $f(\\pm 1) = -1$.\n**c.** (3) $f''(x) = 12 x^2 - 4$; $f''(0) = -4 < 0$ (max); $f''(\\pm 1) = 8 > 0$ (mins).", "stationary-points-and-curve-sketching"),
    e("For $f(x) = x e^{-x}$:\n\n**a.** Find $f'(x)$. (2 marks)\n\n**b.** Stationary point. (3 marks)\n\n**c.** Behaviour at infinity. (2 marks)", 7, "MEDIUM",
      "**a.** (2) $f'(x) = e^{-x}(1 - x)$.\n**b.** (3) $f'(x) = 0 \\Rightarrow x = 1$; $f(1) = 1/e$; local max (from sign change).\n**c.** (2) $x \\to \\infty$: $f \\to 0$; $x \\to -\\infty$: $f \\to -\\infty$.", "stationary-points-and-curve-sketching"),
    e("For $f(x) = x + 1/x$ on $x > 0$:\n\n**a.** Find $f'(x)$. (2 marks)\n\n**b.** Find stationary point. (3 marks)\n\n**c.** Justify it is a minimum and state value. (3 marks)", 8, "HARD",
      "**a.** (2) $f'(x) = 1 - 1/x^2$.\n**b.** (3) $1 = 1/x^2 \\Rightarrow x = 1$ (positive root); $f(1) = 2$.\n**c.** (3) $f''(x) = 2/x^3$; $f''(1) = 2 > 0$ ⇒ local min. Value $2$.", "stationary-points-and-curve-sketching"),
  ],
  "optimisation": [
    e("Find two positive numbers summing to 20 with maximum product.\n\n**a.** Set up. (2 marks)\n\n**b.** Maximise. (2 marks)\n\n**c.** State answer. (2 marks)", 6, "EASY",
      "**a.** (2) Let $x, 20 - x$. Product $P(x) = x(20 - x)$.\n**b.** (2) $P'(x) = 20 - 2 x = 0 \\Rightarrow x = 10$.\n**c.** (2) Both numbers are 10; product 100.", "optimisation"),
    e("A 200 m rectangular fence (no constraint on shape) encloses maximum area.\n\n**a.** Set up. (2 marks)\n\n**b.** Express area. (2 marks)\n\n**c.** Maximise. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $2 L + 2 W = 200 \\Rightarrow W = 100 - L$.\n**b.** (2) $A = L(100 - L)$.\n**c.** (3) $A'(L) = 100 - 2 L = 0 \\Rightarrow L = 50$. $W = 50$, $A = 2500$ m². Square.", "optimisation"),
    e("A box has square base $x$ and height $h$, volume $V = 32$ m³.\n\n**a.** Express $h$. (1 mark)\n\n**b.** Express surface area (no top). (3 marks)\n\n**c.** Find $x$ for min surface area. (3 marks)", 7, "MEDIUM",
      "**a.** (1) $x^2 h = 32 \\Rightarrow h = 32/x^2$.\n**b.** (3) $S = x^2 + 4 x h = x^2 + 128/x$.\n**c.** (3) $S'(x) = 2 x - 128/x^2 = 0 \\Rightarrow 2 x^3 = 128 \\Rightarrow x = 4$.", "optimisation"),
    e("A right circular cylinder has fixed volume $V_0$. Find ratio $h/r$ for min surface area (closed).\n\n**a.** Express $h$. (1 mark)\n\n**b.** Express $S$. (3 marks)\n\n**c.** Minimise and find ratio. (4 marks)", 8, "HARD",
      "**a.** (1) $h = V_0/(\\pi r^2)$.\n**b.** (3) $S = 2 \\pi r^2 + 2 \\pi r h = 2 \\pi r^2 + 2 V_0/r$.\n**c.** (4) $S'(r) = 4 \\pi r - 2 V_0/r^2 = 0 \\Rightarrow r^3 = V_0/(2\\pi) \\Rightarrow V_0 = 2 \\pi r^3$. Then $h = 2 r$, so $h/r = 2$.", "optimisation"),
  ],
  "antidifferentiation": [
    e("Find $\\int (4 x^3 - 6 x + 1) \\, dx$.\n\n**a.** Term by term. (2 marks)\n\n**b.** Don't forget $+ C$. (1 mark)\n\n**c.** Verify by differentiation. (2 marks)", 5, "EASY",
      "**a.** (2) $x^4 - 3 x^2 + x$.\n**b.** (1) $+ C$.\n**c.** (2) $\\dfrac{d}{dx}(x^4 - 3 x^2 + x + C) = 4 x^3 - 6 x + 1$ ✓.", "antidifferentiation"),
    e("Find $f(x)$ given $f'(x) = 3 x^2 + 2 x - 5$ and $f(0) = 4$.\n\n**a.** Integrate. (3 marks)\n\n**b.** Use the initial condition. (2 marks)\n\n**c.** Write $f$. (1 mark)", 6, "MEDIUM",
      "**a.** (3) $f(x) = x^3 + x^2 - 5 x + C$.\n**b.** (2) $f(0) = C = 4$.\n**c.** (1) $f(x) = x^3 + x^2 - 5 x + 4$.", "antidifferentiation"),
    e("Find $\\int e^{2 x} \\, dx$ and verify.\n\n**a.** Apply reverse chain. (2 marks)\n\n**b.** Add constant. (1 mark)\n\n**c.** Differentiate to verify. (2 marks)", 5, "MEDIUM",
      "**a.** (2) $\\dfrac{e^{2 x}}{2}$.\n**b.** (1) $+ C$.\n**c.** (2) $\\dfrac{d}{dx}\\left[\\dfrac{e^{2 x}}{2} + C\\right] = e^{2 x}$ ✓.", "antidifferentiation"),
    e("Given $a(t) = 6 t$ and $v(0) = 3$, find the velocity at $t = 4$.\n\n**a.** Integrate $a$. (2 marks)\n\n**b.** Apply initial condition. (2 marks)\n\n**c.** Compute. (3 marks)", 7, "HARD",
      "**a.** (2) $v(t) = 3 t^2 + C$.\n**b.** (2) $v(0) = C = 3$.\n**c.** (3) $v(t) = 3 t^2 + 3$; $v(4) = 48 + 3 = 51$ m/s.", "antidifferentiation"),
  ],
  "definite-integrals": [
    e("Evaluate $\\displaystyle\\int_0^2 (x^2 + 1) \\, dx$.\n\n**a.** Antidifferentiate. (2 marks)\n\n**b.** Evaluate at bounds. (2 marks)\n\n**c.** State. (1 mark)", 5, "EASY",
      "**a.** (2) $F(x) = x^3/3 + x$.\n**b.** (2) $F(2) - F(0) = (8/3 + 2) - 0$.\n**c.** (1) $= 14/3$.", "definite-integrals"),
    e("Find $\\displaystyle\\int_0^\\pi \\sin x \\, dx$.\n\n**a.** Antidifferentiate. (2 marks)\n\n**b.** Evaluate. (2 marks)\n\n**c.** State. (1 mark)", 5, "MEDIUM",
      "**a.** (2) $F(x) = -\\cos x$.\n**b.** (2) $F(\\pi) - F(0) = 1 + 1$.\n**c.** (1) $= 2$.", "definite-integrals"),
    e("Find the area enclosed by $y = x^2$, $y = 0$, $x = 1$, and $x = 3$.\n\n**a.** Set up integral. (2 marks)\n\n**b.** Antidifferentiate. (2 marks)\n\n**c.** Evaluate. (3 marks)", 7, "MEDIUM",
      "**a.** (2) Area $= \\int_1^3 x^2 dx$.\n**b.** (2) $F(x) = x^3/3$.\n**c.** (3) $F(3) - F(1) = 9 - 1/3 = 26/3$.", "definite-integrals"),
    e("Evaluate $\\displaystyle\\int_0^1 e^x (1 + x) \\, dx$ given $\\displaystyle\\int e^x x \\, dx = e^x(x - 1) + C$.\n\n**a.** Split the integral. (2 marks)\n\n**b.** Use the given. (3 marks)\n\n**c.** Combine. (3 marks)", 8, "HARD",
      "**a.** (2) $\\int_0^1 e^x dx + \\int_0^1 x e^x dx$.\n**b.** (3) $[e^x]_0^1 = e - 1$; $[e^x(x - 1)]_0^1 = 0 - (-1) = 1$.\n**c.** (3) Sum $= e - 1 + 1 = e$.", "definite-integrals"),
  ],
  "area-under-curves": [
    e("Find the area between $y = 4 - x^2$ and the x-axis.\n\n**a.** Find x-intercepts. (2 marks)\n\n**b.** Set up integral. (2 marks)\n\n**c.** Evaluate. (2 marks)", 6, "EASY",
      "**a.** (2) $4 - x^2 = 0 \\Rightarrow x = \\pm 2$.\n**b.** (2) $\\int_{-2}^2 (4 - x^2) dx$.\n**c.** (2) $[4 x - x^3/3]_{-2}^2 = (8 - 8/3) - (-8 + 8/3) = 32/3$.", "area-under-curves"),
    e("Find the area between $y = x^3$ and $y = x$ in the first quadrant.\n\n**a.** Find intersections. (2 marks)\n\n**b.** Identify the upper curve. (2 marks)\n\n**c.** Compute area. (3 marks)", 7, "MEDIUM",
      "**a.** (2) $x^3 = x \\Rightarrow x(x^2 - 1) = 0 \\Rightarrow x = 0, 1$ (positive root).\n**b.** (2) On $(0, 1)$, $x > x^3$.\n**c.** (3) $\\int_0^1 (x - x^3) dx = [x^2/2 - x^4/4]_0^1 = 1/2 - 1/4 = 1/4$.", "area-under-curves"),
    e("A region is bounded by $y = e^x$, $y = 0$, $x = 0$, $x = 1$. Find its area.\n\n**a.** Set up. (1 mark)\n\n**b.** Antidifferentiate. (2 marks)\n\n**c.** Evaluate. (3 marks)", 6, "MEDIUM",
      "**a.** (1) $\\int_0^1 e^x dx$.\n**b.** (2) $F(x) = e^x$.\n**c.** (3) $F(1) - F(0) = e - 1$.", "area-under-curves"),
    e("Find the area between $y = x^2$ and $y = 2 x + 3$.\n\n**a.** Find intersections. (3 marks)\n\n**b.** Identify upper curve and set up. (2 marks)\n\n**c.** Compute. (3 marks)", 8, "HARD",
      "**a.** (3) $x^2 = 2 x + 3 \\Rightarrow x^2 - 2 x - 3 = (x - 3)(x + 1) = 0 \\Rightarrow x = -1, 3$.\n**b.** (2) On $(-1, 3)$, $2 x + 3 > x^2$.\n**c.** (3) $\\int_{-1}^3 (2 x + 3 - x^2) dx = [x^2 + 3 x - x^3/3]_{-1}^3 = (9 + 9 - 9) - (1 - 3 + 1/3) = 9 - (-5/3) = 32/3$.", "area-under-curves"),
  ],
  // ─── DATA (EXT_ANS) ─────────────────────────────────────────────────
  "conditional-probability": [
    e("A standard die is rolled. Let $A = $ \"even\", $B = $ \"$> 3$\".\n\n**a.** List events $A, B$. (1 mark)\n\n**b.** Compute $P(A), P(B), P(A \\cap B)$. (3 marks)\n\n**c.** Compute $P(A \\mid B)$. (2 marks)", 6, "EASY",
      "**a.** (1) $A = \\{2, 4, 6\\}$, $B = \\{4, 5, 6\\}$.\n**b.** (3) $P(A) = 1/2$, $P(B) = 1/2$, $P(A \\cap B) = P(\\{4, 6\\}) = 1/3$.\n**c.** (2) $P(A \\mid B) = (1/3)/(1/2) = 2/3$.", "conditional-probability"),
    e("In a deck of 52 cards, two cards are drawn without replacement.\n\n**a.** $P(\\text{first is heart})$. (1 mark)\n\n**b.** $P(\\text{both hearts})$. (2 marks)\n\n**c.** $P(\\text{first heart} \\mid \\text{second heart})$. (3 marks)", 6, "MEDIUM",
      "**a.** (1) $13/52 = 1/4$.\n**b.** (2) $(13/52)(12/51) = 156/2652 = 1/17$.\n**c.** (3) By symmetry $P(\\text{first H} | \\text{second H}) = P(\\text{first H})$... actually use Bayes: $P(\\text{first H} \\cap \\text{second H})/P(\\text{second H}) = (1/17)/(1/4) = 4/17$.", "conditional-probability"),
    e("A factory has two machines: Machine I produces 60% of items with 2% defective; Machine II produces 40% with 5% defective. A random defective item is found.\n\n**a.** $P(\\text{defective})$. (3 marks)\n\n**b.** $P(\\text{Machine I} \\mid \\text{defective})$. (3 marks)", 6, "MEDIUM",
      "**a.** (3) $P(D) = 0.6(0.02) + 0.4(0.05) = 0.012 + 0.020 = 0.032$.\n**b.** (3) $P(I | D) = 0.012/0.032 = 0.375$.", "conditional-probability"),
    e("Events $A, B$ satisfy $P(A) = 0.6$, $P(B) = 0.4$, $P(A \\cup B) = 0.7$.\n\n**a.** Compute $P(A \\cap B)$. (2 marks)\n\n**b.** Compute $P(A \\mid B)$. (3 marks)\n\n**c.** Are $A, B$ independent? Justify. (3 marks)", 8, "HARD",
      "**a.** (2) $P(A \\cap B) = P(A) + P(B) - P(A \\cup B) = 0.3$.\n**b.** (3) $P(A | B) = 0.3/0.4 = 0.75$.\n**c.** (3) $P(A) = 0.6 \\neq 0.75 = P(A | B)$ ⇒ NOT independent.", "conditional-probability"),
  ],
  "discrete-random-variables": [
    e("Let $X$ have distribution $P(X = k) = c \\cdot k$ for $k = 1, 2, 3, 4$.\n\n**a.** Find $c$. (2 marks)\n\n**b.** Compute $P(X \\leq 2)$. (2 marks)\n\n**c.** Compute $E[X]$. (3 marks)", 7, "EASY",
      "**a.** (2) $c(1 + 2 + 3 + 4) = 10 c = 1 \\Rightarrow c = 1/10$.\n**b.** (2) $P(X = 1) + P(X = 2) = 0.1 + 0.2 = 0.3$.\n**c.** (3) $E[X] = (1 \\cdot 1 + 2 \\cdot 2 + 3 \\cdot 3 + 4 \\cdot 4)/10 = 30/10 = 3$.", "discrete-random-variables"),
    e("$X$ takes values 0, 1, 2, 3 with probabilities 0.1, 0.3, 0.4, 0.2.\n\n**a.** Find $E[X]$. (2 marks)\n\n**b.** Find $E[X^2]$. (2 marks)\n\n**c.** Find $\\text{Var}(X)$. (2 marks)", 6, "MEDIUM",
      "**a.** (2) $E[X] = 0 + 0.3 + 0.8 + 0.6 = 1.7$.\n**b.** (2) $E[X^2] = 0 + 0.3 + 1.6 + 1.8 = 3.7$.\n**c.** (2) $\\text{Var} = 3.7 - 2.89 = 0.81$.", "discrete-random-variables"),
    e("Two dice are rolled. Let $X$ be the sum.\n\n**a.** Find $P(X = 7)$. (2 marks)\n\n**b.** Find $E[X]$. (3 marks)\n\n**c.** Find $\\text{Var}(X)$ (you may use $\\text{Var}(\\text{die}) = 35/12$). (3 marks)", 8, "MEDIUM",
      "**a.** (2) 6 ways out of 36: $P = 1/6$.\n**b.** (3) Mean of each die $= 3.5$; $E[X] = 7$.\n**c.** (3) Independent dice: $\\text{Var}(X) = 2(35/12) = 35/6$.", "discrete-random-variables"),
    e("A binomial random variable $X \\sim \\text{Bin}(10, 0.3)$.\n\n**a.** Find $E[X]$ and $\\text{Var}(X)$. (2 marks)\n\n**b.** $P(X = 3)$. (3 marks)\n\n**c.** $P(X \\geq 2)$, correct to 4 dp. (3 marks)", 8, "HARD",
      "**a.** (2) $E[X] = 3$, $\\text{Var}(X) = 2.1$.\n**b.** (3) $P(X = 3) = \\binom{10}{3}(0.3)^3(0.7)^7 \\approx 0.2668$.\n**c.** (3) $P(X \\geq 2) = 1 - P(X = 0) - P(X = 1)$. $P(0) = 0.0282$, $P(1) = 0.1211$. $P(X \\geq 2) \\approx 0.8507$.", "discrete-random-variables"),
  ],
  "binomial-distribution": [
    e("$X \\sim \\text{Bin}(8, 0.5)$.\n\n**a.** State $E[X]$ and $\\text{Var}(X)$. (2 marks)\n\n**b.** Find $P(X = 4)$. (2 marks)\n\n**c.** Find $P(X > 4)$ using symmetry. (2 marks)", 6, "EASY",
      "**a.** (2) $E[X] = 4$, $\\text{Var}(X) = 2$.\n**b.** (2) $\\binom{8}{4}(0.5)^8 = 70/256$.\n**c.** (2) Symmetry: $P(X > 4) = P(X < 4) = (1 - P(X = 4))/2$. $P(X = 4) = 70/256$, so $P(X > 4) = (1 - 70/256)/2 = 93/256$.", "binomial-distribution"),
    e("A multiple-choice quiz: 10 questions, 4 options each, all guessed. Let $X$ = correct.\n\n**a.** Distribution. (1 mark)\n\n**b.** $E[X]$ and sd. (2 marks)\n\n**c.** $P(X \\geq 5)$, 4 dp. (3 marks)", 6, "MEDIUM",
      "**a.** (1) $X \\sim \\text{Bin}(10, 0.25)$.\n**b.** (2) $E[X] = 2.5$, sd $= \\sqrt{10 \\cdot 0.25 \\cdot 0.75} = \\sqrt{1.875} \\approx 1.37$.\n**c.** (3) $P(X \\geq 5) \\approx 0.0781$ (calculator).", "binomial-distribution"),
    e("Among 20 patients, 60% respond to treatment.\n\n**a.** Distribution of $X$ = number responding. (1 mark)\n\n**b.** $E[X], \\text{Var}(X)$. (2 marks)\n\n**c.** $P(X \\geq 15)$ correct to 4 dp. (3 marks)", 6, "MEDIUM",
      "**a.** (1) $X \\sim \\text{Bin}(20, 0.6)$.\n**b.** (2) $E[X] = 12$, $\\text{Var}(X) = 4.8$.\n**c.** (3) $P(X \\geq 15) \\approx 0.1256$ (CAS).", "binomial-distribution"),
    e("Find $n$ such that for $X \\sim \\text{Bin}(n, 0.5)$, $P(X \\geq 1) \\geq 0.99$.\n\n**a.** Reformulate. (2 marks)\n\n**b.** Solve. (3 marks)\n\n**c.** Smallest $n$. (3 marks)", 8, "HARD",
      "**a.** (2) $1 - (0.5)^n \\geq 0.99 \\Rightarrow (0.5)^n \\leq 0.01$.\n**b.** (3) $n \\ln(0.5) \\leq \\ln(0.01) \\Rightarrow n \\geq \\ln(0.01)/\\ln(0.5) \\approx 6.64$.\n**c.** (3) Smallest integer: $n = 7$.", "binomial-distribution"),
  ],
  "continuous-random-variables": [
    e("$X$ has pdf $f(x) = 2 x$ for $0 \\leq x \\leq 1$, else 0.\n\n**a.** Verify valid pdf. (2 marks)\n\n**b.** Find $P(X > 1/2)$. (2 marks)\n\n**c.** Find $E[X]$. (2 marks)", 6, "EASY",
      "**a.** (2) $\\int_0^1 2 x dx = [x^2]_0^1 = 1$ ✓.\n**b.** (2) $\\int_{1/2}^1 2 x dx = [x^2]_{1/2}^1 = 1 - 1/4 = 3/4$.\n**c.** (2) $E[X] = \\int_0^1 2 x^2 dx = [2 x^3/3]_0^1 = 2/3$.", "continuous-random-variables"),
    e("$X$ has pdf $f(x) = k(1 - x^2)$ for $-1 \\leq x \\leq 1$, else 0.\n\n**a.** Find $k$. (3 marks)\n\n**b.** Find $E[X]$ using symmetry. (1 mark)\n\n**c.** Find $\\text{Var}(X)$. (3 marks)", 7, "MEDIUM",
      "**a.** (3) $\\int_{-1}^1 k(1 - x^2) dx = k[x - x^3/3]_{-1}^1 = k(2 - 2/3) = 4 k/3 = 1 \\Rightarrow k = 3/4$.\n**b.** (1) Symmetric pdf about 0 ⇒ $E[X] = 0$.\n**c.** (3) $\\text{Var}(X) = E[X^2] = \\int_{-1}^1 x^2 \\cdot (3/4)(1 - x^2) dx = (3/4)\\int_{-1}^1 (x^2 - x^4) dx = (3/4)(2/3 - 2/5) = (3/4)(4/15) = 1/5$.", "continuous-random-variables"),
    e("$X$ uniformly distributed on $[2, 10]$.\n\n**a.** State the pdf. (1 mark)\n\n**b.** Find $E[X], \\text{Var}(X)$. (3 marks)\n\n**c.** Find $P(4 < X < 7)$. (2 marks)", 6, "MEDIUM",
      "**a.** (1) $f(x) = 1/8$ on $[2, 10]$.\n**b.** (3) $E[X] = 6$ (midpoint); $\\text{Var}(X) = (10 - 2)^2/12 = 64/12 = 16/3$.\n**c.** (2) $(7 - 4)/8 = 3/8$.", "continuous-random-variables"),
    e("$X$ has pdf $f(x) = c x^2$ for $0 \\leq x \\leq 3$, else 0.\n\n**a.** Find $c$. (2 marks)\n\n**b.** $E[X]$. (3 marks)\n\n**c.** Median. (3 marks)", 8, "HARD",
      "**a.** (2) $\\int_0^3 c x^2 dx = c \\cdot 9 = 1 \\Rightarrow c = 1/9$.\n**b.** (3) $E[X] = (1/9)\\int_0^3 x^3 dx = (1/9)(81/4) = 9/4$.\n**c.** (3) Median $m$: $\\int_0^m (x^2/9) dx = m^3/27 = 1/2 \\Rightarrow m = \\sqrt[3]{27/2} = 3/\\sqrt[3]{2}$.", "continuous-random-variables"),
  ],
  "normal-distribution": [
    e("$X \\sim N(50, 25)$.\n\n**a.** State $\\mu, \\sigma$. (1 mark)\n\n**b.** Find $P(X > 55)$, 4 dp. (3 marks)\n\n**c.** Find $P(45 < X < 55)$. (3 marks)", 7, "EASY",
      "**a.** (1) $\\mu = 50$, $\\sigma = 5$.\n**b.** (3) $z = 1$; $P(Z > 1) \\approx 0.1587$.\n**c.** (3) $P(-1 < Z < 1) \\approx 0.6827$.", "normal-distribution"),
    e("$X \\sim N(0, 1)$ (standard normal).\n\n**a.** $P(Z < 1.96)$, 4 dp. (2 marks)\n\n**b.** $P(|Z| < 2)$. (3 marks)\n\n**c.** $c$ such that $P(Z < c) = 0.9$. (2 marks)", 7, "MEDIUM",
      "**a.** (2) $\\Phi(1.96) \\approx 0.9750$.\n**b.** (3) $P(-2 < Z < 2) = 2\\Phi(2) - 1 \\approx 0.9544$.\n**c.** (2) $c \\approx 1.2816$.", "normal-distribution"),
    e("$X \\sim N(100, 256)$ ($\\sigma = 16$).\n\n**a.** $P(X > 130)$, 4 dp. (3 marks)\n\n**b.** Top 5% cutoff. (3 marks)\n\n**c.** Interpret in context (e.g. exam scores). (1 mark)", 7, "MEDIUM",
      "**a.** (3) $z = 30/16 = 1.875$; $P(Z > 1.875) \\approx 0.0304$.\n**b.** (3) $P(Z > c) = 0.05 \\Rightarrow c \\approx 1.645$; $X = 100 + 1.645 \\cdot 16 \\approx 126.3$.\n**c.** (1) About 3% of students score above 130, and top 5% cutoff is about 126.", "normal-distribution"),
    e("Light bulbs $X \\sim N(\\mu, \\sigma^2)$ with $P(X < 800) = 0.10$ and $P(X < 1200) = 0.90$.\n\n**a.** Find $\\mu, \\sigma$. (5 marks)\n\n**b.** Find $P(X > 1000)$. (3 marks)", 8, "HARD",
      "**a.** (5) $\\Phi^{-1}(0.10) \\approx -1.282$; $\\Phi^{-1}(0.90) \\approx 1.282$. So $800 = \\mu - 1.282 \\sigma$ and $1200 = \\mu + 1.282 \\sigma$. Adding: $\\mu = 1000$. From first: $\\sigma = 200/1.282 \\approx 156.0$.\n**b.** (3) $z = 0/156 = 0$; $P(X > 1000) = 0.5$.", "normal-distribution"),
  ],
  "confidence-intervals": [
    e("In a sample of 200 voters, 110 prefer party A. Construct a 95% CI for the population proportion.\n\n**a.** $\\hat p$. (1 mark)\n\n**b.** SE. (2 marks)\n\n**c.** CI. (3 marks)", 6, "EASY",
      "**a.** (1) $\\hat p = 0.55$.\n**b.** (2) $\\sqrt{0.55 \\cdot 0.45/200} \\approx 0.0352$.\n**c.** (3) $0.55 \\pm 1.96 \\cdot 0.0352 \\approx (0.481, 0.619)$.", "confidence-intervals"),
    e("Compare 90% and 99% CIs given $\\hat p = 0.7$ and $n = 100$.\n\n**a.** SE. (1 mark)\n\n**b.** 90% CI ($z = 1.645$). (3 marks)\n\n**c.** 99% CI ($z = 2.576$). (3 marks)", 7, "MEDIUM",
      "**a.** (1) SE $= \\sqrt{0.21/100} \\approx 0.0458$.\n**b.** (3) $0.7 \\pm 0.0754 \\approx (0.625, 0.775)$.\n**c.** (3) $0.7 \\pm 0.118 \\approx (0.582, 0.818)$.", "confidence-intervals"),
    e("A 95% CI for a population proportion is $(0.42, 0.58)$.\n\n**a.** Point estimate $\\hat p$. (1 mark)\n\n**b.** Margin of error. (2 marks)\n\n**c.** Approximate sample size if SE is $0.0408$. (4 marks)", 7, "MEDIUM",
      "**a.** (1) $\\hat p = 0.5$ (midpoint).\n**b.** (2) Margin $= 0.08$.\n**c.** (4) $1.96 \\cdot \\text{SE} = 0.08 \\Rightarrow \\text{SE} = 0.0408$; $0.0408 = \\sqrt{0.25/n} \\Rightarrow n = 0.25/0.0408^2 \\approx 150$.", "confidence-intervals"),
    e("Required: 95% CI with margin $\\leq 0.02$, conservative $\\hat p = 0.5$.\n\n**a.** Formula. (2 marks)\n\n**b.** Solve for $n$. (3 marks)\n\n**c.** Round and state. (3 marks)", 8, "HARD",
      "**a.** (2) $0.02 \\geq 1.96 \\sqrt{0.25/n}$.\n**b.** (3) $0.25/n \\leq (0.02/1.96)^2 \\approx 0.000104 \\Rightarrow n \\geq 0.25/0.000104 \\approx 2401$.\n**c.** (3) Smallest integer: $n = 2401$.", "confidence-intervals"),
  ],
  "sample-proportions-and-sampling": [
    e("$p = 0.5$, $n = 100$. Approximate distribution of $\\hat p$?\n\n**a.** Mean. (1 mark)\n\n**b.** Sd. (2 marks)\n\n**c.** $P(0.4 < \\hat p < 0.6)$, 4 dp. (3 marks)", 6, "EASY",
      "**a.** (1) $E[\\hat p] = 0.5$.\n**b.** (2) $\\sqrt{0.25/100} = 0.05$.\n**c.** (3) $z$-scores $\\pm 2$; $P \\approx 0.9544$.", "sample-proportions-and-sampling"),
    e("True $p = 0.3$. Find $n$ so $\\text{sd}(\\hat p) \\leq 0.02$.\n\n**a.** Formula. (2 marks)\n\n**b.** Solve. (3 marks)\n\n**c.** Smallest $n$. (3 marks)", 8, "MEDIUM",
      "**a.** (2) $\\sqrt{0.21/n} \\leq 0.02$.\n**b.** (3) $0.21/n \\leq 0.0004 \\Rightarrow n \\geq 525$.\n**c.** (3) $n = 525$.", "sample-proportions-and-sampling"),
    e("Verify that $\\hat p$ is an unbiased estimator of $p$.\n\n**a.** Recall $X \\sim \\text{Bin}(n, p)$ counts successes. (1 mark)\n\n**b.** $E[X]$. (2 marks)\n\n**c.** Show $E[\\hat p] = p$. (3 marks)", 6, "MEDIUM",
      "**a.** (1) $X = $ number of successes in $n$ trials.\n**b.** (2) $E[X] = n p$.\n**c.** (3) $E[\\hat p] = E[X/n] = E[X]/n = n p/n = p$. ✓ Unbiased.", "sample-proportions-and-sampling"),
    e("Hypothetical: $n = 400$, $p = 0.6$.\n\n**a.** SE of $\\hat p$. (2 marks)\n\n**b.** Distribution of $\\hat p$. (2 marks)\n\n**c.** $P(\\hat p > 0.65)$, 4 dp. (3 marks)", 7, "HARD",
      "**a.** (2) $\\sqrt{0.6 \\cdot 0.4/400} = \\sqrt{0.0006} \\approx 0.0245$.\n**b.** (2) $\\hat p \\approx N(0.6, 0.0006)$ (by CLT).\n**c.** (3) $z = 0.05/0.0245 \\approx 2.041$; $P(Z > 2.041) \\approx 0.0206$.", "sample-proportions-and-sampling"),
  ],
};

for (const [slug, items] of Object.entries(SUBS)) {
  fs.writeFileSync(path.join(OUT_DIR, `qset-methods-w3-ea-${slug}.json`),
    JSON.stringify({ mcq: [], shortAnswer: [], extendedAnswer: items, extendedResponse: [] }, null, 2) + "\n");
  console.log(`${slug}: ${items.length} EXT_ANS`);
}
const total = Object.values(SUBS).reduce((a, v) => a + v.length, 0);
console.log(`Total: ${total} EXT_ANS across ${Object.keys(SUBS).length} subtopics.`);
