/** Wave 4b: SHORT top-up. 10 new SHORT per subtopic × 35 = 350 total. */
import * as fs from "fs";
import * as path from "path";

const OUT_DIR = "scripts/output";
interface SH { content: string; marks: number; difficulty: "EASY" | "MEDIUM" | "HARD"; solutionContent: string; subtopicSlugs: string[]; }
const s = (c: string, m: number, d: "EASY" | "MEDIUM" | "HARD", sol: string, p: string): SH =>
  ({ content: c, marks: m, difficulty: d, solutionContent: sol, subtopicSlugs: [p] });

const SUBS: Record<string, SH[]> = {
  "polynomial-equations": [
    s("Solve $x^2 - 9 = 0$.", 1, "EASY", "$x = \\pm 3$.", "polynomial-equations"),
    s("Solve $(x - 4)(x + 1) = 0$.", 1, "EASY", "$x = 4$ or $x = -1$.", "polynomial-equations"),
    s("Solve $3 x - 7 = 8$.", 1, "EASY", "$3 x = 15 \\Rightarrow x = 5$.", "polynomial-equations"),
    s("Solve $x^2 - 6 x + 9 = 0$.", 2, "EASY", "$(x - 3)^2 = 0 \\Rightarrow x = 3$ (repeated root).", "polynomial-equations"),
    s("Find the sum of the roots of $x^2 - 7 x + 10 = 0$.", 2, "MEDIUM", "By Vieta's: sum $= 7$.", "polynomial-equations"),
    s("Solve $2 x^2 - 8 = 0$.", 2, "MEDIUM", "$x^2 = 4 \\Rightarrow x = \\pm 2$.", "polynomial-equations"),
    s("Solve $x^2 = 5 x$.", 2, "MEDIUM", "$x(x - 5) = 0 \\Rightarrow x = 0, 5$.", "polynomial-equations"),
    s("Find the discriminant of $2 x^2 - 4 x + 3$.", 2, "MEDIUM", "$\\Delta = 16 - 24 = -8$.", "polynomial-equations"),
    s("Solve $x^3 - 27 = 0$ for real $x$.", 3, "HARD", "$x^3 = 27 \\Rightarrow x = 3$ (only real cube root).", "polynomial-equations"),
    s("If $x = -1$ is a root of $x^3 + 2 x^2 - x - 2$, factor completely.", 4, "HARD", "Divide by $(x + 1)$: $(x + 1)(x^2 + x - 2) = (x + 1)(x + 2)(x - 1)$.", "polynomial-equations"),
  ],
  "exponential-equations": [
    s("Solve $3^x = 9$.", 1, "EASY", "$x = 2$.", "exponential-equations"),
    s("Solve $e^x = e$.", 1, "EASY", "$x = 1$.", "exponential-equations"),
    s("Solve $5^x = 25$.", 1, "EASY", "$x = 2$.", "exponential-equations"),
    s("Solve $4^x = 1$.", 1, "EASY", "$x = 0$.", "exponential-equations"),
    s("Solve $e^{x - 1} = 1$.", 2, "MEDIUM", "$x - 1 = 0 \\Rightarrow x = 1$.", "exponential-equations"),
    s("Solve $2^x = 7$ exactly.", 2, "MEDIUM", "$x = \\log_2 7 = \\ln 7/\\ln 2$.", "exponential-equations"),
    s("Solve $e^{2 x + 1} = e^5$.", 2, "MEDIUM", "$2 x + 1 = 5 \\Rightarrow x = 2$.", "exponential-equations"),
    s("Solve $3^{x + 1} = 9^x$.", 3, "MEDIUM", "$3^{x + 1} = 3^{2 x} \\Rightarrow x + 1 = 2 x \\Rightarrow x = 1$.", "exponential-equations"),
    s("Solve $e^x = 4 e^{-x}$ exactly.", 3, "HARD", "$e^{2 x} = 4 \\Rightarrow 2 x = \\ln 4 \\Rightarrow x = \\ln 2$.", "exponential-equations"),
    s("Solve $4 \\cdot 2^x - 8 = 0$.", 3, "HARD", "$2^x = 2 \\Rightarrow x = 1$.", "exponential-equations"),
  ],
  "logarithmic-equations": [
    s("Solve $\\log_3 x = 2$.", 1, "EASY", "$x = 9$.", "logarithmic-equations"),
    s("Solve $\\ln x = 0$.", 1, "EASY", "$x = 1$.", "logarithmic-equations"),
    s("Solve $\\log_{10} x = -1$.", 2, "EASY", "$x = 10^{-1} = 0.1$.", "logarithmic-equations"),
    s("Solve $\\log_e(x + 4) = 0$.", 2, "MEDIUM", "$x + 4 = 1 \\Rightarrow x = -3$.", "logarithmic-equations"),
    s("Solve $\\log_2 x + 1 = 4$.", 2, "MEDIUM", "$\\log_2 x = 3 \\Rightarrow x = 8$.", "logarithmic-equations"),
    s("Solve $\\log_3(2 x - 1) = 1$.", 2, "MEDIUM", "$2 x - 1 = 3 \\Rightarrow x = 2$.", "logarithmic-equations"),
    s("Solve $\\log_4 x + \\log_4 8 = \\log_4 32$.", 3, "MEDIUM", "$\\log_4(8 x) = \\log_4 32 \\Rightarrow x = 4$.", "logarithmic-equations"),
    s("Solve $2 \\log_e x = \\log_e 9$.", 3, "MEDIUM", "$\\log(x^2) = \\log 9 \\Rightarrow x = 3$ (positive).", "logarithmic-equations"),
    s("Solve $\\log_e(x^2 - 4) = \\log_e 5$.", 3, "HARD", "$x^2 - 4 = 5 \\Rightarrow x = \\pm 3$.", "logarithmic-equations"),
    s("Solve $\\log_5(x - 2) + \\log_5(x + 2) = 1$.", 4, "HARD", "$\\log_5(x^2 - 4) = 1 \\Rightarrow x^2 = 9 \\Rightarrow x = 3$ (need $x > 2$).", "logarithmic-equations"),
  ],
  "trigonometric-equations": [
    s("Solve $\\cos x = -1$ for $x \\in [0, 2\\pi]$.", 1, "EASY", "$x = \\pi$.", "trigonometric-equations"),
    s("Solve $\\sin x = 0$ for $x \\in [0, \\pi]$.", 1, "EASY", "$x = 0, \\pi$.", "trigonometric-equations"),
    s("Solve $\\tan x = 0$ for $x \\in [-\\pi, \\pi]$.", 2, "EASY", "$x = -\\pi, 0, \\pi$.", "trigonometric-equations"),
    s("Solve $2 \\sin x = \\sqrt 3$ for $x \\in [0, \\pi]$.", 2, "MEDIUM", "$\\sin x = \\sqrt 3/2 \\Rightarrow x = \\pi/3, 2\\pi/3$.", "trigonometric-equations"),
    s("Solve $\\cos(2 x) = 1$ for $x \\in [0, 2\\pi]$.", 2, "MEDIUM", "$2 x = 0, 2\\pi, 4\\pi \\Rightarrow x = 0, \\pi, 2\\pi$.", "trigonometric-equations"),
    s("Solve $\\sin x = -\\dfrac{1}{2}$ for $x \\in [0, 2\\pi]$.", 3, "MEDIUM", "$x = \\pi + \\pi/6 = 7\\pi/6$ or $2\\pi - \\pi/6 = 11\\pi/6$.", "trigonometric-equations"),
    s("Solve $\\cos x = -\\dfrac{\\sqrt 2}{2}$ for $x \\in [0, 2\\pi]$.", 3, "MEDIUM", "$x = 3\\pi/4$ or $5\\pi/4$.", "trigonometric-equations"),
    s("Solve $\\tan x = \\sqrt 3$ for $x \\in [0, 2\\pi]$.", 3, "MEDIUM", "$x = \\pi/3, 4\\pi/3$.", "trigonometric-equations"),
    s("Solve $\\sin(3 x) = 0$ for $x \\in [0, \\pi]$.", 3, "HARD", "$3 x = 0, \\pi, 2\\pi, 3\\pi \\Rightarrow x = 0, \\pi/3, 2\\pi/3, \\pi$.", "trigonometric-equations"),
    s("Solve $\\cos^2 x = \\dfrac{1}{4}$ for $x \\in [0, \\pi]$.", 4, "HARD", "$\\cos x = \\pm 1/2 \\Rightarrow x = \\pi/3, 2\\pi/3$.", "trigonometric-equations"),
  ],
  "simultaneous-equations": [
    s("Solve $x = 2 y$, $x + y = 9$.", 2, "EASY", "$3 y = 9 \\Rightarrow y = 3, x = 6$.", "simultaneous-equations"),
    s("Solve $x + y = 0$, $x - y = 4$.", 2, "EASY", "$2 x = 4 \\Rightarrow x = 2, y = -2$.", "simultaneous-equations"),
    s("Solve $y = 3 x$, $y - x = 4$.", 2, "EASY", "$3 x - x = 4 \\Rightarrow x = 2, y = 6$.", "simultaneous-equations"),
    s("Find intersection of $y = 2 x$ and $y = x + 3$.", 2, "MEDIUM", "$2 x = x + 3 \\Rightarrow x = 3, y = 6$.", "simultaneous-equations"),
    s("Solve $x + 2 y = 7$, $3 x - y = 0$.", 3, "MEDIUM", "$y = 3 x$; sub: $x + 6 x = 7 \\Rightarrow x = 1, y = 3$.", "simultaneous-equations"),
    s("Find intersection of $y = x^2$ and $y = 4$.", 2, "MEDIUM", "$x^2 = 4 \\Rightarrow x = \\pm 2$. Points $(\\pm 2, 4)$.", "simultaneous-equations"),
    s("Solve $y = x + 1$, $y = -x + 5$.", 2, "MEDIUM", "$x + 1 = -x + 5 \\Rightarrow x = 2, y = 3$.", "simultaneous-equations"),
    s("Find intersection of $y = x^2 - 2$ and $y = x$.", 3, "MEDIUM", "$x^2 - 2 = x \\Rightarrow x^2 - x - 2 = 0 \\Rightarrow x = 2, -1$.", "simultaneous-equations"),
    s("Solve $2 x + y = 3$, $4 x + 2 y = 7$.", 3, "HARD", "Second is 2× first: $4 x + 2 y = 6 \\neq 7$, parallel-distinct. No solution.", "simultaneous-equations"),
    s("Find intersection of $y = e^x$ and $y = 1$.", 3, "HARD", "$e^x = 1 \\Rightarrow x = 0$. Point $(0, 1)$.", "simultaneous-equations"),
  ],
  "exponent-and-logarithm-laws": [
    s("Simplify $x^3 \\cdot x^7$.", 1, "EASY", "$x^{10}$.", "exponent-and-logarithm-laws"),
    s("Simplify $\\dfrac{a^5}{a^2}$.", 1, "EASY", "$a^3$.", "exponent-and-logarithm-laws"),
    s("Evaluate $2^{-3}$.", 1, "EASY", "$1/8$.", "exponent-and-logarithm-laws"),
    s("Simplify $(x^2)^4$.", 2, "EASY", "$x^8$.", "exponent-and-logarithm-laws"),
    s("Evaluate $\\log_2 32$.", 2, "MEDIUM", "$2^5 = 32 \\Rightarrow \\log_2 32 = 5$.", "exponent-and-logarithm-laws"),
    s("Evaluate $\\log_{10} 1000$.", 2, "MEDIUM", "$10^3 = 1000 \\Rightarrow 3$.", "exponent-and-logarithm-laws"),
    s("Simplify $\\log_e e^4$.", 2, "MEDIUM", "$4$.", "exponent-and-logarithm-laws"),
    s("Simplify $\\log_2 4 + \\log_2 8$.", 2, "MEDIUM", "$2 + 3 = 5$ (or via $\\log_2 32$).", "exponent-and-logarithm-laws"),
    s("Simplify $2 \\log_3 6 - \\log_3 4$.", 3, "HARD", "$\\log_3 36 - \\log_3 4 = \\log_3 9 = 2$.", "exponent-and-logarithm-laws"),
    s("Solve $\\log_4 x = 1/2$.", 3, "HARD", "$x = 4^{1/2} = 2$.", "exponent-and-logarithm-laws"),
  ],
  "polynomial-functions": [
    s("State the degree of $f(x) = -3 x^4 + x^2 - 7$.", 1, "EASY", "$4$.", "polynomial-functions"),
    s("State the leading coefficient of $f(x) = 5 - 2 x^3 + x$.", 1, "EASY", "$-2$.", "polynomial-functions"),
    s("Find $f(2)$ if $f(x) = x^3 - 4 x + 1$.", 2, "EASY", "$8 - 8 + 1 = 1$.", "polynomial-functions"),
    s("State the y-intercept of $y = 2 x^2 - 5 x - 3$.", 1, "EASY", "$y(0) = -3$.", "polynomial-functions"),
    s("Find x-intercepts of $y = x^2 - x - 6$.", 2, "MEDIUM", "$(x - 3)(x + 2) = 0 \\Rightarrow x = 3, -2$.", "polynomial-functions"),
    s("Sketch $y = -(x - 1)^2 + 4$, stating vertex.", 3, "MEDIUM", "Vertex $(1, 4)$; opens down; $y$-int $= 3$; sketch parabola opening down with vertex $(1, 4)$.", "polynomial-functions"),
    s("State the range of $y = (x - 2)^2 + 5$.", 2, "MEDIUM", "Min at $x = 2$: $y = 5$. Range $[5, \\infty)$.", "polynomial-functions"),
    s("Express $y = x^2 + 4 x - 1$ in vertex form.", 3, "MEDIUM", "$y = (x + 2)^2 - 5$.", "polynomial-functions"),
    s("Find values of $x$ where $y = x^3 - 4 x$ crosses x-axis.", 3, "HARD", "$x(x - 2)(x + 2) = 0 \\Rightarrow x = 0, \\pm 2$.", "polynomial-functions"),
    s("If $P(x) = x^4 + a x^3 + b$ has root $x = -1$ with $P(0) = 6$, find $a$ and $b$.", 4, "HARD", "$P(0) = b = 6$. $P(-1) = 1 - a + 6 = 0 \\Rightarrow a = 7$.", "polynomial-functions"),
  ],
  "exponential-functions": [
    s("Find $y$-intercept of $y = 3 \\cdot 2^x$.", 1, "EASY", "$y(0) = 3$.", "exponential-functions"),
    s("State the range of $y = e^x$.", 1, "EASY", "$(0, \\infty)$.", "exponential-functions"),
    s("Find $f(2)$ if $f(x) = e^x - 1$.", 2, "EASY", "$e^2 - 1$.", "exponential-functions"),
    s("State the horizontal asymptote of $y = 2 + e^{-x}$.", 2, "EASY", "$y = 2$.", "exponential-functions"),
    s("Find $x$-intercept of $y = 2^x - 8$.", 2, "MEDIUM", "$2^x = 8 \\Rightarrow x = 3$.", "exponential-functions"),
    s("State the domain of $y = e^{\\sqrt x}$.", 2, "MEDIUM", "$x \\geq 0$.", "exponential-functions"),
    s("Find $f'(x)$ if $f(x) = 5 e^{2 x}$.", 2, "MEDIUM", "$f'(x) = 10 e^{2 x}$.", "exponential-functions"),
    s("State range of $y = -e^x$.", 2, "MEDIUM", "$(-\\infty, 0)$.", "exponential-functions"),
    s("Solve $4 e^x = 12$ exactly.", 3, "HARD", "$e^x = 3 \\Rightarrow x = \\ln 3$.", "exponential-functions"),
    s("If $f(x) = a e^{k x}$ with $f(0) = 2$ and $f(1) = 6$, find $a, k$.", 4, "HARD", "$a = 2$; $2 e^k = 6 \\Rightarrow k = \\ln 3$.", "exponential-functions"),
  ],
  "logarithmic-functions": [
    s("State the domain of $y = \\ln x$.", 1, "EASY", "$(0, \\infty)$.", "logarithmic-functions"),
    s("Find $y$-intercept of $y = \\ln(x + e)$.", 1, "EASY", "$y(0) = \\ln e = 1$.", "logarithmic-functions"),
    s("Find $f(e^2)$ if $f(x) = \\ln x$.", 1, "EASY", "$2$.", "logarithmic-functions"),
    s("Solve $\\ln x = 3$ exactly.", 2, "EASY", "$x = e^3$.", "logarithmic-functions"),
    s("State range of $y = \\ln x$.", 1, "MEDIUM", "$\\mathbb{R}$.", "logarithmic-functions"),
    s("Find $x$-intercept of $y = \\ln(x - 2)$.", 2, "MEDIUM", "$\\ln(x - 2) = 0 \\Rightarrow x = 3$.", "logarithmic-functions"),
    s("State asymptote of $y = \\ln(x + 5)$.", 2, "MEDIUM", "$x = -5$.", "logarithmic-functions"),
    s("Find $f'(x)$ if $f(x) = \\ln(3 x)$.", 2, "MEDIUM", "$f'(x) = 1/x$.", "logarithmic-functions"),
    s("Solve $\\ln(2 x) = 1$ exactly.", 3, "HARD", "$2 x = e \\Rightarrow x = e/2$.", "logarithmic-functions"),
    s("If $f(x) = a \\ln(x) + b$ with $f(1) = 2$ and $f(e) = 5$, find $a, b$.", 4, "HARD", "$f(1) = b = 2$; $f(e) = a + 2 = 5 \\Rightarrow a = 3$.", "logarithmic-functions"),
  ],
  "trigonometric-functions": [
    s("State amplitude of $y = 5 \\sin x$.", 1, "EASY", "$5$.", "trigonometric-functions"),
    s("State period of $y = \\cos x$.", 1, "EASY", "$2\\pi$.", "trigonometric-functions"),
    s("Find $y$-intercept of $y = 2 \\cos x$.", 1, "EASY", "$y(0) = 2$.", "trigonometric-functions"),
    s("Evaluate $\\sin(\\pi/3)$.", 2, "EASY", "$\\sqrt 3/2$.", "trigonometric-functions"),
    s("State range of $y = 1 + 2 \\sin x$.", 2, "MEDIUM", "$\\sin \\in [-1, 1]$ ⇒ $1 + 2 \\sin x \\in [-1, 3]$.", "trigonometric-functions"),
    s("State period of $y = \\sin(\\pi x)$.", 2, "MEDIUM", "$2\\pi/\\pi = 2$.", "trigonometric-functions"),
    s("Sketch $y = -\\cos x$ on $[0, 2\\pi]$, marking key points.", 3, "MEDIUM", "Reflection of $\\cos x$; $(0, -1) \\to (\\pi/2, 0) \\to (\\pi, 1) \\to (3\\pi/2, 0) \\to (2\\pi, -1)$.", "trigonometric-functions"),
    s("Find period and amplitude of $y = 3 \\sin(2 x - \\pi)$.", 3, "MEDIUM", "Amp 3, period $\\pi$.", "trigonometric-functions"),
    s("Find $f'(x)$ if $f(x) = \\sin(2 x)$.", 2, "HARD", "Chain rule: $f'(x) = 2 \\cos(2 x)$.", "trigonometric-functions"),
    s("If $\\tan x = 3/4$ and $x$ in Q1, find $\\sin x$ and $\\cos x$.", 4, "HARD", "Right triangle 3-4-5: $\\sin x = 3/5$, $\\cos x = 4/5$.", "trigonometric-functions"),
  ],
  "rational-functions": [
    s("State vertical asymptote of $y = 1/(x + 4)$.", 1, "EASY", "$x = -4$.", "rational-functions"),
    s("State horizontal asymptote of $y = 1/x^2$.", 1, "EASY", "$y = 0$.", "rational-functions"),
    s("Find $y$-intercept of $y = 2/(x - 3)$.", 2, "EASY", "$y(0) = -2/3$.", "rational-functions"),
    s("State maximal domain of $y = 1/(x^2 + 1)$.", 2, "EASY", "$\\mathbb{R}$ (denominator never zero).", "rational-functions"),
    s("State asymptotes of $y = (3 x)/(x - 1)$.", 3, "MEDIUM", "Vertical $x = 1$, horizontal $y = 3$.", "rational-functions"),
    s("Find $x$-intercept of $y = (2 x - 6)/(x + 1)$.", 2, "MEDIUM", "$2 x - 6 = 0 \\Rightarrow x = 3$.", "rational-functions"),
    s("Simplify $\\dfrac{x^2 - 9}{x - 3}$ for $x \\neq 3$.", 3, "MEDIUM", "$\\dfrac{(x - 3)(x + 3)}{x - 3} = x + 3$.", "rational-functions"),
    s("Sketch $y = 2 + 1/(x - 1)$ stating both asymptotes.", 3, "MEDIUM", "Vertical $x = 1$, horizontal $y = 2$.", "rational-functions"),
    s("Find $f'(x)$ if $f(x) = 1/x$.", 2, "HARD", "$f'(x) = -1/x^2$.", "rational-functions"),
    s("State end behaviour of $y = (x^2 + 1)/x$ as $x \\to \\infty$.", 3, "HARD", "$\\to x$ (oblique asymptote).", "rational-functions"),
  ],
  "domain-and-range": [
    s("Domain of $y = \\sqrt{x - 2}$.", 1, "EASY", "$x \\geq 2$.", "domain-and-range"),
    s("Range of $y = x^2$.", 1, "EASY", "$[0, \\infty)$.", "domain-and-range"),
    s("Domain of $y = 1/x$.", 1, "EASY", "$x \\neq 0$.", "domain-and-range"),
    s("Range of $y = 3 - x^2$.", 2, "EASY", "$(-\\infty, 3]$.", "domain-and-range"),
    s("Domain of $y = \\ln(x - 5)$.", 2, "MEDIUM", "$x > 5$.", "domain-and-range"),
    s("Range of $y = e^x + 1$.", 2, "MEDIUM", "$(1, \\infty)$.", "domain-and-range"),
    s("Domain of $y = \\sqrt{x^2 - 9}$.", 3, "MEDIUM", "$|x| \\geq 3$, i.e. $x \\leq -3$ or $x \\geq 3$.", "domain-and-range"),
    s("Range of $y = \\sin x + 2$.", 2, "MEDIUM", "$[1, 3]$.", "domain-and-range"),
    s("Domain of $y = 1/\\sqrt{x - 1}$.", 3, "HARD", "$x > 1$ (denominator nonzero AND under sqrt).", "domain-and-range"),
    s("Range of $y = 1/(x^2 + 1)$.", 4, "HARD", "Max when denominator min at $x = 0$: $y = 1$. As $|x| \\to \\infty$, $y \\to 0$. Range $(0, 1]$.", "domain-and-range"),
  ],
  "transformations": [
    s("Describe transformation from $y = x^2$ to $y = (x + 3)^2$.", 1, "EASY", "Translation 3 left.", "transformations"),
    s("Describe from $y = x^2$ to $y = x^2 - 4$.", 1, "EASY", "Translation 4 down.", "transformations"),
    s("Describe from $y = e^x$ to $y = 3 e^x$.", 2, "EASY", "Dilation by factor 3 from x-axis.", "transformations"),
    s("Image of $(1, 2)$ under translation 3 right, 1 down.", 2, "EASY", "$(4, 1)$.", "transformations"),
    s("Describe from $y = \\sin x$ to $y = \\sin(x - \\pi/2)$.", 2, "MEDIUM", "Translation $\\pi/2$ right.", "transformations"),
    s("Describe from $y = x^2$ to $y = -x^2$.", 2, "MEDIUM", "Reflection in x-axis.", "transformations"),
    s("Image of $(2, 5)$ under reflection in y-axis.", 2, "MEDIUM", "$(-2, 5)$.", "transformations"),
    s("Image of $(3, 4)$ under dilation by factor 2 from x-axis.", 2, "MEDIUM", "$(3, 8)$.", "transformations"),
    s("Equation of $y = e^x$ after reflection in x-axis then translation 2 up.", 3, "HARD", "$y = -e^x + 2$.", "transformations"),
    s("Image of $(2, 6)$ under $y = -f(x) + 3$ given $(2, 6)$ on $y = f(x)$.", 3, "HARD", "Reflect $y$: $(2, -6)$; add 3: $(2, -3)$.", "transformations"),
  ],
  "inverse-functions": [
    s("Find inverse of $f(x) = x - 5$.", 1, "EASY", "$f^{-1}(x) = x + 5$.", "inverse-functions"),
    s("Find inverse of $f(x) = 4 x$.", 1, "EASY", "$f^{-1}(x) = x/4$.", "inverse-functions"),
    s("If $f(2) = 6$ and $f$ is one-to-one, find $f^{-1}(6)$.", 2, "EASY", "$2$.", "inverse-functions"),
    s("Find inverse of $f(x) = 3 x - 6$.", 2, "MEDIUM", "$y = 3 x - 6 \\Rightarrow x = (y + 6)/3$; $f^{-1}(x) = (x + 6)/3$.", "inverse-functions"),
    s("State domain of $f^{-1}$ if $f: [0, \\infty) \\to [0, \\infty)$, $f(x) = x^2$.", 2, "MEDIUM", "$[0, \\infty)$ (= range of $f$).", "inverse-functions"),
    s("Verify $f(x) = e^x$ and $g(x) = \\ln x$ are inverses.", 3, "MEDIUM", "$g(f(x)) = \\ln(e^x) = x$ for all $x$; $f(g(x)) = e^{\\ln x} = x$ for $x > 0$.", "inverse-functions"),
    s("Find inverse of $f(x) = (x + 1)^3$.", 3, "MEDIUM", "$y = (x + 1)^3 \\Rightarrow x = y^{1/3} - 1$; $f^{-1}(x) = \\sqrt[3]{x} - 1$.", "inverse-functions"),
    s("If $f: [1, \\infty) \\to [0, \\infty)$, $f(x) = \\sqrt{x - 1}$, find $f^{-1}$.", 3, "MEDIUM", "$y = \\sqrt{x - 1} \\Rightarrow x = y^2 + 1$; $f^{-1}(x) = x^2 + 1$.", "inverse-functions"),
    s("Find $f^{-1}$ if $f(x) = \\dfrac{2 x + 3}{x - 1}$ for $x \\neq 1$.", 4, "HARD", "$y(x - 1) = 2 x + 3 \\Rightarrow x(y - 2) = y + 3 \\Rightarrow x = (y + 3)/(y - 2)$. $f^{-1}(x) = (x + 3)/(x - 2)$.", "inverse-functions"),
    s("Find $x$ for which $f(x) = f^{-1}(x)$ where $f(x) = 2 x - 1$.", 3, "HARD", "Both on $y = x$: $2 x - 1 = x \\Rightarrow x = 1$.", "inverse-functions"),
  ],
  "composite-functions": [
    s("If $f(x) = x + 3$ and $g(x) = 2 x$, find $(g \\circ f)(x)$.", 1, "EASY", "$g(x + 3) = 2 x + 6$.", "composite-functions"),
    s("If $f(x) = x^2$, find $(f \\circ f)(2)$.", 2, "EASY", "$f(f(2)) = f(4) = 16$.", "composite-functions"),
    s("If $f(x) = x + 1$ and $g(x) = x^2$, find $(f \\circ g)(3)$.", 2, "EASY", "$g(3) = 9$; $f(9) = 10$.", "composite-functions"),
    s("If $f(x) = \\sqrt x$ and $g(x) = x + 5$, find $(f \\circ g)(x)$.", 2, "MEDIUM", "$\\sqrt{x + 5}$.", "composite-functions"),
    s("Find domain of $(f \\circ g)$ where $f(x) = \\sqrt x$, $g(x) = x - 4$.", 2, "MEDIUM", "Need $x - 4 \\geq 0 \\Rightarrow x \\geq 4$.", "composite-functions"),
    s("If $f(x) = e^x$ and $g(x) = -x$, find $(f \\circ g)(x)$.", 2, "MEDIUM", "$e^{-x}$.", "composite-functions"),
    s("Write $h(x) = (3 x - 2)^4$ as $f(g(x))$.", 3, "MEDIUM", "$g(x) = 3 x - 2$, $f(u) = u^4$.", "composite-functions"),
    s("If $f(x) = \\sin x$ and $g(x) = x^2$, find $(f \\circ g)(\\pi/2)$.", 3, "MEDIUM", "$g(\\pi/2) = \\pi^2/4$; $\\sin(\\pi^2/4) \\approx \\sin(2.467) \\approx 0.624$.", "composite-functions"),
    s("Compute $(f \\circ f)(x)$ if $f(x) = 2 x - 1$.", 3, "HARD", "$f(2 x - 1) = 2(2 x - 1) - 1 = 4 x - 3$.", "composite-functions"),
    s("Find $g$ given $f(x) = 2 x$ and $(f \\circ g)(x) = 4 x + 6$.", 4, "HARD", "$2 g(x) = 4 x + 6 \\Rightarrow g(x) = 2 x + 3$.", "composite-functions"),
  ],
  // CALCULUS
  "differentiation": [
    s("Find $\\dfrac{d}{dx}(x^7)$.", 1, "EASY", "$7 x^6$.", "differentiation"),
    s("Differentiate $y = 4 x - 9$.", 1, "EASY", "$y' = 4$.", "differentiation"),
    s("Differentiate $f(x) = 5$.", 1, "EASY", "$f'(x) = 0$.", "differentiation"),
    s("Differentiate $y = 3 \\sqrt x$.", 2, "EASY", "$y = 3 x^{1/2}$, $y' = 3/(2 \\sqrt x)$.", "differentiation"),
    s("Find $f'(2)$ if $f(x) = x^4 - 3 x$.", 2, "MEDIUM", "$f'(x) = 4 x^3 - 3$; $f'(2) = 32 - 3 = 29$.", "differentiation"),
    s("Differentiate $f(x) = e^{4 x}$.", 2, "MEDIUM", "$4 e^{4 x}$.", "differentiation"),
    s("Find $f'(1)$ if $f(x) = \\ln x$.", 2, "MEDIUM", "$f'(x) = 1/x$; $f'(1) = 1$.", "differentiation"),
    s("Differentiate $\\sin x + \\cos x$.", 2, "MEDIUM", "$\\cos x - \\sin x$.", "differentiation"),
    s("Find second derivative of $f(x) = x^3$.", 3, "HARD", "$f'(x) = 3 x^2$; $f''(x) = 6 x$.", "differentiation"),
    s("Differentiate $y = 2 x^3 + 4 e^x - 3 \\ln x$ for $x > 0$.", 4, "HARD", "$y' = 6 x^2 + 4 e^x - 3/x$.", "differentiation"),
  ],
  "chain-rule": [
    s("Differentiate $(x + 5)^4$.", 1, "EASY", "$4(x + 5)^3$.", "chain-rule"),
    s("Differentiate $e^{x + 1}$.", 1, "EASY", "$e^{x + 1}$.", "chain-rule"),
    s("Differentiate $\\ln(2 x)$ for $x > 0$.", 2, "EASY", "$\\dfrac{2}{2 x} = \\dfrac{1}{x}$.", "chain-rule"),
    s("Differentiate $\\sin(3 x)$.", 2, "EASY", "$3 \\cos(3 x)$.", "chain-rule"),
    s("Differentiate $(2 x^2 + 1)^3$.", 2, "MEDIUM", "$3(2 x^2 + 1)^2 \\cdot 4 x = 12 x(2 x^2 + 1)^2$.", "chain-rule"),
    s("Differentiate $e^{-x^2}$.", 2, "MEDIUM", "$e^{-x^2} \\cdot (-2 x) = -2 x e^{-x^2}$.", "chain-rule"),
    s("Differentiate $\\cos(x^3)$.", 2, "MEDIUM", "$-\\sin(x^3) \\cdot 3 x^2 = -3 x^2 \\sin(x^3)$.", "chain-rule"),
    s("Differentiate $\\ln(x^2 + 4)$.", 3, "MEDIUM", "$\\dfrac{2 x}{x^2 + 4}$.", "chain-rule"),
    s("Differentiate $\\sqrt{3 - x^2}$.", 3, "HARD", "$\\dfrac{-x}{\\sqrt{3 - x^2}}$.", "chain-rule"),
    s("Differentiate $e^{\\cos x}$.", 3, "HARD", "$e^{\\cos x} \\cdot (-\\sin x) = -\\sin x e^{\\cos x}$.", "chain-rule"),
  ],
  "product-rule": [
    s("Differentiate $x \\cdot \\ln x$.", 2, "EASY", "$\\ln x + 1$.", "product-rule"),
    s("Differentiate $x^2 \\cos x$.", 2, "EASY", "$2 x \\cos x - x^2 \\sin x$.", "product-rule"),
    s("Differentiate $(x + 1) e^x$.", 2, "EASY", "$e^x + (x + 1) e^x = (x + 2) e^x$.", "product-rule"),
    s("Differentiate $(2 x)(x + 3)$.", 2, "MEDIUM", "$2(x + 3) + 2 x = 4 x + 6$.", "product-rule"),
    s("Differentiate $x^3 \\sin x$.", 3, "MEDIUM", "$3 x^2 \\sin x + x^3 \\cos x$.", "product-rule"),
    s("Differentiate $e^x \\ln x$ for $x > 0$.", 3, "MEDIUM", "$e^x \\ln x + e^x/x$.", "product-rule"),
    s("Differentiate $(x^2 + 1)(x - 3)$.", 3, "MEDIUM", "$2 x(x - 3) + (x^2 + 1) = 3 x^2 - 6 x + 1$.", "product-rule"),
    s("Find $f'(0)$ if $f(x) = x^2 e^x$.", 3, "MEDIUM", "$f'(x) = 2 x e^x + x^2 e^x = e^x(2 x + x^2)$; $f'(0) = 0$.", "product-rule"),
    s("Find $f'(1)$ if $f(x) = x \\ln x$.", 3, "HARD", "$f'(x) = \\ln x + 1$; $f'(1) = 1$.", "product-rule"),
    s("Differentiate $x e^x \\sin x$.", 4, "HARD", "Product of 3: $(x e^x)' \\sin x + x e^x \\cos x = (e^x + x e^x)\\sin x + x e^x \\cos x = e^x[(1 + x)\\sin x + x \\cos x]$.", "product-rule"),
  ],
  "quotient-rule": [
    s("Differentiate $\\dfrac{1}{x + 1}$.", 2, "EASY", "$-\\dfrac{1}{(x + 1)^2}$.", "quotient-rule"),
    s("Differentiate $\\dfrac{x}{e^x}$.", 2, "EASY", "$\\dfrac{e^x - x e^x}{e^{2 x}} = \\dfrac{1 - x}{e^x}$.", "quotient-rule"),
    s("Differentiate $\\dfrac{3}{x^2}$.", 2, "EASY", "$-\\dfrac{6}{x^3}$.", "quotient-rule"),
    s("Differentiate $\\dfrac{x + 1}{x - 1}$.", 3, "MEDIUM", "$\\dfrac{(x - 1) - (x + 1)}{(x - 1)^2} = \\dfrac{-2}{(x - 1)^2}$.", "quotient-rule"),
    s("Differentiate $\\dfrac{x^2}{\\ln x}$ for $x > 0$.", 3, "MEDIUM", "$\\dfrac{2 x \\ln x - x}{(\\ln x)^2} = \\dfrac{x(2 \\ln x - 1)}{(\\ln x)^2}$.", "quotient-rule"),
    s("Differentiate $\\dfrac{\\cos x}{x}$.", 3, "MEDIUM", "$\\dfrac{-\\sin x \\cdot x - \\cos x}{x^2}$.", "quotient-rule"),
    s("Differentiate $\\dfrac{e^x + 1}{e^x - 1}$.", 4, "MEDIUM", "$\\dfrac{e^x(e^x - 1) - (e^x + 1) e^x}{(e^x - 1)^2} = \\dfrac{-2 e^x}{(e^x - 1)^2}$.", "quotient-rule"),
    s("Find $f'(1)$ if $f(x) = \\dfrac{x^2 - 1}{x + 1}$ for $x \\neq -1$.", 3, "MEDIUM", "Simplify: $f(x) = x - 1$; $f'(x) = 1$.", "quotient-rule"),
    s("Differentiate $\\tan x$ as $\\sin x/\\cos x$.", 3, "HARD", "Quotient rule: $\\dfrac{\\cos^2 x + \\sin^2 x}{\\cos^2 x} = \\sec^2 x$.", "quotient-rule"),
    s("Find stationary point of $f(x) = \\dfrac{x}{x^2 + 4}$.", 4, "HARD", "$f'(x) = \\dfrac{4 - x^2}{(x^2 + 4)^2} = 0 \\Rightarrow x = \\pm 2$.", "quotient-rule"),
  ],
  "tangents-and-normals": [
    s("Slope of tangent to $y = x^3$ at $(1, 1)$.", 1, "EASY", "$y'(1) = 3$.", "tangents-and-normals"),
    s("Slope of normal to $y = x^2$ at $(1, 1)$.", 2, "EASY", "Tangent slope $2$; normal slope $-1/2$.", "tangents-and-normals"),
    s("Find tangent to $y = 5$ at $(3, 5)$.", 1, "EASY", "$y = 5$ (constant).", "tangents-and-normals"),
    s("Find tangent to $y = 2 x^2$ at $(2, 8)$.", 2, "MEDIUM", "$y' = 4 x$, slope $8$ at $x = 2$. $y - 8 = 8(x - 2) \\Rightarrow y = 8 x - 8$.", "tangents-and-normals"),
    s("Find tangent to $y = \\sin x$ at $x = 0$.", 3, "MEDIUM", "$y'(0) = 1$; $y(0) = 0$. $y = x$.", "tangents-and-normals"),
    s("Find tangent to $y = 1/x$ at $(1, 1)$.", 3, "MEDIUM", "$y' = -1/x^2$; $y'(1) = -1$. $y - 1 = -(x - 1) \\Rightarrow y = -x + 2$.", "tangents-and-normals"),
    s("Find normal to $y = \\ln x$ at $(1, 0)$.", 3, "MEDIUM", "$y'(1) = 1$; normal slope $-1$. $y - 0 = -(x - 1) \\Rightarrow y = -x + 1$.", "tangents-and-normals"),
    s("Find $x$ where tangent to $y = x^2 - 4 x + 1$ is horizontal.", 3, "MEDIUM", "$y' = 2 x - 4 = 0 \\Rightarrow x = 2$.", "tangents-and-normals"),
    s("Find tangent to $y = e^x$ at $(\\ln 2, 2)$.", 4, "HARD", "$y'(\\ln 2) = 2$. $y - 2 = 2(x - \\ln 2) \\Rightarrow y = 2 x + 2 - 2 \\ln 2$.", "tangents-and-normals"),
    s("Find equation of tangent to $y = \\sqrt x$ at $(4, 2)$.", 4, "HARD", "$y' = 1/(2\\sqrt x)$; $y'(4) = 1/4$. $y - 2 = (1/4)(x - 4) \\Rightarrow y = x/4 + 1$.", "tangents-and-normals"),
  ],
  "rates-of-change": [
    s("Position $s = 3 t + 5$, velocity at $t = 2$.", 1, "EASY", "$v = s' = 3$ m/s (constant).", "rates-of-change"),
    s("$s(t) = t^2$, velocity at $t = 3$.", 1, "EASY", "$v = 2 t$; $v(3) = 6$.", "rates-of-change"),
    s("Average rate of change of $f(x) = x^3$ from $0$ to $2$.", 2, "EASY", "$(8 - 0)/2 = 4$.", "rates-of-change"),
    s("$V(t) = 100 - 4 t^2$, find $V'(5)$.", 2, "MEDIUM", "$V'(t) = -8 t$; $V'(5) = -40$.", "rates-of-change"),
    s("$s(t) = t^3 - 3 t^2$, find acceleration at $t = 1$.", 3, "MEDIUM", "$v = 3 t^2 - 6 t$, $a = 6 t - 6$; $a(1) = 0$.", "rates-of-change"),
    s("Particle $x = 2 t - t^2$, when is velocity zero?", 2, "MEDIUM", "$v = 2 - 2 t = 0 \\Rightarrow t = 1$.", "rates-of-change"),
    s("Circle radius $r = 3 t$, find $dA/dt$ at $t = 2$.", 3, "MEDIUM", "$A = \\pi r^2$; $r(2) = 6$. $dA/dt = 2\\pi r dr/dt = 2\\pi(6)(3) = 36\\pi$.", "rates-of-change"),
    s("If $f(x) = e^{2 x}$, instantaneous rate at $x = 0$.", 2, "MEDIUM", "$f'(x) = 2 e^{2 x}$; $f'(0) = 2$.", "rates-of-change"),
    s("Particle position $x(t) = t^3 - 6 t^2 + 9 t$, at rest when?", 3, "HARD", "$v = 3 t^2 - 12 t + 9 = 3(t-1)(t-3) = 0 \\Rightarrow t = 1, 3$.", "rates-of-change"),
    s("Tank fills at $V(t) = 10 \\sqrt t$, find rate when $t = 4$.", 4, "HARD", "$V'(t) = 5/\\sqrt t$; $V'(4) = 5/2$ L/s.", "rates-of-change"),
  ],
  "stationary-points-and-curve-sketching": [
    s("Find stationary point of $y = x^2 - 4 x + 7$.", 2, "EASY", "$y' = 2 x - 4 = 0 \\Rightarrow x = 2$; $y(2) = 3$.", "stationary-points-and-curve-sketching"),
    s("Classify stationary point of $y = x^2$ at $x = 0$.", 1, "EASY", "$y'' = 2 > 0$ ⇒ minimum.", "stationary-points-and-curve-sketching"),
    s("Stationary points of $y = x^3 - 12 x$.", 2, "EASY", "$y' = 3 x^2 - 12 = 0 \\Rightarrow x = \\pm 2$; $y(\\pm 2) = \\mp 16$. Points $(2, -16)$, $(-2, 16)$.", "stationary-points-and-curve-sketching"),
    s("Classify stationary point of $y = -3 x^2 + 12 x - 7$.", 2, "MEDIUM", "Max (negative leading coeff).", "stationary-points-and-curve-sketching"),
    s("Find inflection point of $y = x^3 - 3 x$.", 3, "MEDIUM", "$y'' = 6 x = 0 \\Rightarrow x = 0$. Inflection $(0, 0)$.", "stationary-points-and-curve-sketching"),
    s("Sketch shape of $y = x^4$ near $x = 0$.", 2, "MEDIUM", "Minimum, very flat near origin.", "stationary-points-and-curve-sketching"),
    s("How many stationary points does $y = x^2 + 3$ have?", 1, "MEDIUM", "One (the minimum at $x = 0$).", "stationary-points-and-curve-sketching"),
    s("Find local max of $y = -x^2 + 10 x$.", 3, "MEDIUM", "$y' = -2 x + 10 = 0 \\Rightarrow x = 5$; $y(5) = 25$.", "stationary-points-and-curve-sketching"),
    s("Sign of $y'$ for $y = x^3$ near $x = 0$.", 3, "HARD", "$y' = 3 x^2 \\geq 0$ always; horizontal point of inflection at 0.", "stationary-points-and-curve-sketching"),
    s("Find stationary points of $y = x^4 - 2 x^2 + 1$.", 4, "HARD", "$y' = 4 x^3 - 4 x = 4 x(x^2 - 1) = 0 \\Rightarrow x = 0, \\pm 1$. $y(0) = 1$, $y(\\pm 1) = 0$. Three stationary points.", "stationary-points-and-curve-sketching"),
  ],
  "optimisation": [
    s("Max of $y = 6 x - x^2$.", 2, "EASY", "$y' = 6 - 2 x = 0 \\Rightarrow x = 3$; $y(3) = 9$.", "optimisation"),
    s("Two numbers summing to 8, max product.", 2, "EASY", "$4 \\times 4 = 16$.", "optimisation"),
    s("Min of $y = x^2 + 4 x + 7$.", 2, "EASY", "$y' = 2 x + 4 = 0 \\Rightarrow x = -2$; min $= 3$.", "optimisation"),
    s("Rectangle perimeter 16, max area.", 3, "MEDIUM", "Square side 4, area 16.", "optimisation"),
    s("Max area triangle with hypotenuse 4.", 3, "MEDIUM", "Legs $2\\sqrt 2$; area $= 4$.", "optimisation"),
    s("Min of $y = x + 4/x$ for $x > 0$.", 3, "MEDIUM", "$y' = 1 - 4/x^2 = 0 \\Rightarrow x = 2$; $y(2) = 4$.", "optimisation"),
    s("Open box from $12 \\times 12$ sheet, find $x$ for max volume.", 3, "MEDIUM", "$V = x(12 - 2 x)^2$; $V' = (12 - 2x)(12 - 6x) = 0 \\Rightarrow x = 2$.", "optimisation"),
    s("Cylindrical can volume $V_0$, min surface area when $h =$:", 3, "MEDIUM", "$h = 2 r$ (standard result).", "optimisation"),
    s("Find $x$ minimising $f(x) = x^2 + 9/x$ for $x > 0$.", 3, "HARD", "$f'(x) = 2 x - 9/x^2 = 0 \\Rightarrow x^3 = 9/2$, $x = \\sqrt[3]{9/2}$.", "optimisation"),
    s("Min distance from origin to line $y = 2 x + 4$.", 4, "HARD", "Distance $= 4/\\sqrt 5 = 4\\sqrt 5/5$.", "optimisation"),
  ],
  "antidifferentiation": [
    s("Find $\\int 2 x \\, dx$.", 1, "EASY", "$x^2 + C$.", "antidifferentiation"),
    s("Find $\\int (3) \\, dx$.", 1, "EASY", "$3 x + C$.", "antidifferentiation"),
    s("Find $\\int x^4 \\, dx$.", 1, "EASY", "$x^5/5 + C$.", "antidifferentiation"),
    s("Find $\\int e^x \\, dx$.", 1, "EASY", "$e^x + C$.", "antidifferentiation"),
    s("Find $\\int \\sin x \\, dx$.", 2, "MEDIUM", "$-\\cos x + C$.", "antidifferentiation"),
    s("Find $\\int (x^2 + 1) \\, dx$.", 2, "MEDIUM", "$x^3/3 + x + C$.", "antidifferentiation"),
    s("Find $\\int \\dfrac{2}{x} \\, dx$ for $x > 0$.", 2, "MEDIUM", "$2 \\ln x + C$.", "antidifferentiation"),
    s("Find $\\int e^{2 x} \\, dx$.", 2, "MEDIUM", "$e^{2 x}/2 + C$.", "antidifferentiation"),
    s("Find $\\int \\cos(3 x) \\, dx$.", 3, "HARD", "$\\sin(3 x)/3 + C$.", "antidifferentiation"),
    s("If $f'(x) = 4 x^3$ and $f(0) = 1$, find $f$.", 3, "HARD", "$f(x) = x^4 + 1$.", "antidifferentiation"),
  ],
  "definite-integrals": [
    s("Evaluate $\\int_0^4 1 \\, dx$.", 1, "EASY", "$4$.", "definite-integrals"),
    s("Evaluate $\\int_0^1 x \\, dx$.", 1, "EASY", "$1/2$.", "definite-integrals"),
    s("Evaluate $\\int_0^2 x^2 \\, dx$.", 2, "EASY", "$8/3$.", "definite-integrals"),
    s("Evaluate $\\int_{-1}^1 x \\, dx$.", 1, "EASY", "$0$ (odd over symmetric).", "definite-integrals"),
    s("Evaluate $\\int_0^\\pi \\cos x \\, dx$.", 2, "MEDIUM", "$[\\sin x]_0^\\pi = 0$.", "definite-integrals"),
    s("Evaluate $\\int_0^2 e^x \\, dx$.", 2, "MEDIUM", "$e^2 - 1$.", "definite-integrals"),
    s("Evaluate $\\int_1^e 1/x \\, dx$.", 2, "MEDIUM", "$\\ln e - \\ln 1 = 1$.", "definite-integrals"),
    s("Evaluate $\\int_0^2 (2 x + 3) \\, dx$.", 3, "MEDIUM", "$[x^2 + 3 x]_0^2 = 4 + 6 = 10$.", "definite-integrals"),
    s("Evaluate $\\int_0^{\\pi/2} \\sin x \\, dx$.", 2, "HARD", "$[-\\cos x]_0^{\\pi/2} = 0 + 1 = 1$.", "definite-integrals"),
    s("If $\\int_a^b f = 5$ and $\\int_b^c f = 3$, find $\\int_a^c f$.", 2, "HARD", "$8$.", "definite-integrals"),
  ],
  "area-under-curves": [
    s("Area under $y = 2$ on $[0, 5]$.", 1, "EASY", "$10$.", "area-under-curves"),
    s("Area under $y = x$ on $[0, 6]$.", 1, "EASY", "$18$.", "area-under-curves"),
    s("Area under $y = x^2$ on $[0, 2]$.", 2, "EASY", "$8/3$.", "area-under-curves"),
    s("Area under $y = e^x$ on $[0, 1]$.", 2, "MEDIUM", "$e - 1$.", "area-under-curves"),
    s("Average value of $f(x) = x$ on $[0, 4]$.", 2, "MEDIUM", "$\\dfrac{1}{4} \\cdot 8 = 2$.", "area-under-curves"),
    s("Area between $y = x^2$ and $y = x$ on $[0, 1]$.", 3, "MEDIUM", "$\\int_0^1 (x - x^2) = 1/2 - 1/3 = 1/6$.", "area-under-curves"),
    s("Area under $y = \\sin x$ on $[0, \\pi]$.", 2, "MEDIUM", "$2$.", "area-under-curves"),
    s("Area between $y = 4 - x^2$ and x-axis.", 3, "MEDIUM", "$\\int_{-2}^2 (4 - x^2) = 32/3$.", "area-under-curves"),
    s("Average value of $\\sin x$ on $[0, \\pi]$.", 3, "HARD", "$(1/\\pi)(2) = 2/\\pi$.", "area-under-curves"),
    s("Total area between $y = x^3$ and x-axis on $[-1, 1]$.", 3, "HARD", "$2 \\int_0^1 x^3 = 2 \\cdot 1/4 = 1/2$.", "area-under-curves"),
  ],
  "fundamental-theorem-of-calculus": [
    s("State FTC.", 1, "EASY", "$\\int_a^b f'(x) dx = f(b) - f(a)$.", "fundamental-theorem-of-calculus"),
    s("Find $\\dfrac{d}{dx}\\int_0^x t^2 \\, dt$.", 1, "EASY", "$x^2$.", "fundamental-theorem-of-calculus"),
    s("Find $\\dfrac{d}{dx}\\int_2^x e^t \\, dt$.", 1, "EASY", "$e^x$.", "fundamental-theorem-of-calculus"),
    s("Use FTC: $\\int_0^1 3 x^2 \\, dx$.", 2, "MEDIUM", "$[x^3]_0^1 = 1$.", "fundamental-theorem-of-calculus"),
    s("Use FTC: $\\int_0^\\pi \\sin x \\, dx$.", 2, "MEDIUM", "$[-\\cos x]_0^\\pi = 2$.", "fundamental-theorem-of-calculus"),
    s("Find $\\dfrac{d}{dx}\\int_0^{x^2} 1 \\, dt$.", 3, "MEDIUM", "$1 \\cdot 2 x = 2 x$.", "fundamental-theorem-of-calculus"),
    s("Use FTC to find $f$ where $f'(x) = 1/x$ and $f(1) = 0$.", 3, "MEDIUM", "$f(x) = \\ln x$.", "fundamental-theorem-of-calculus"),
    s("Compute $\\int_0^a f'(x) \\, dx$ given $f(0) = 3$, $f(a) = 7$.", 2, "MEDIUM", "$f(a) - f(0) = 4$.", "fundamental-theorem-of-calculus"),
    s("If $G(x) = \\int_x^5 \\sqrt t \\, dt$, find $G'(x)$.", 3, "HARD", "$-\\sqrt x$.", "fundamental-theorem-of-calculus"),
    s("Verify FTC for $f(x) = x^3$ on $[1, 2]$.", 3, "HARD", "LHS: $[x^3]_1^2 = 7$; RHS: $\\int_1^2 3 x^2 dx = [x^3]_1^2 = 7$ ✓.", "fundamental-theorem-of-calculus"),
  ],
  // DATA
  "probability-rules": [
    s("$P(A) = 0.4$. Find $P(A')$.", 1, "EASY", "$0.6$.", "probability-rules"),
    s("$A, B$ mutually exclusive, $P(A) = 0.3$, $P(B) = 0.4$. Find $P(A \\cup B)$.", 1, "EASY", "$0.7$.", "probability-rules"),
    s("Toss a fair coin twice. $P(\\text{both heads})$.", 2, "EASY", "$1/4$.", "probability-rules"),
    s("Independent $A, B$ with $P(A) = 0.5, P(B) = 0.2$. $P(A \\cap B)$.", 2, "EASY", "$0.1$.", "probability-rules"),
    s("$P(A) = 0.6, P(B) = 0.4, P(A \\cap B) = 0.2$. Find $P(A \\cup B)$.", 2, "MEDIUM", "$0.6 + 0.4 - 0.2 = 0.8$.", "probability-rules"),
    s("Roll a die. $P(\\text{even or } > 4)$.", 3, "MEDIUM", "$\\{2, 4, 5, 6\\}$: $4/6 = 2/3$.", "probability-rules"),
    s("$P(\\text{at least 1 head in 3 flips})$.", 3, "MEDIUM", "$1 - 1/8 = 7/8$.", "probability-rules"),
    s("Two events independent if:", 2, "MEDIUM", "$P(A \\cap B) = P(A) P(B)$.", "probability-rules"),
    s("Draw a card; $P(\\text{heart or jack})$.", 3, "HARD", "$13/52 + 4/52 - 1/52 = 16/52 = 4/13$.", "probability-rules"),
    s("$P(A) = 0.5$, $P(B) = 0.4$, independent. $P(A' \\cap B')$.", 3, "HARD", "$0.5 \\times 0.6 = 0.3$.", "probability-rules"),
  ],
  "conditional-probability": [
    s("$P(A \\cap B) = 0.15$, $P(B) = 0.3$. Find $P(A | B)$.", 1, "EASY", "$0.5$.", "conditional-probability"),
    s("$P(A) = 0.4$, $P(B | A) = 0.5$. Find $P(A \\cap B)$.", 1, "EASY", "$0.2$.", "conditional-probability"),
    s("If $A$ and $B$ independent, $P(A | B) =$?", 1, "EASY", "$P(A)$.", "conditional-probability"),
    s("$P(A | B) = 0.7$, $P(B) = 0.5$. Find $P(A \\cap B)$.", 2, "MEDIUM", "$0.35$.", "conditional-probability"),
    s("Tree: $P(R) = 0.4$, $P(L | R) = 0.8$. Find $P(R \\cap L)$.", 2, "MEDIUM", "$0.32$.", "conditional-probability"),
    s("$P(M) = 0.6$, $P(F | M) = 0.3$. Find $P(M \\cap F)$.", 2, "MEDIUM", "$0.18$.", "conditional-probability"),
    s("$P(D) = 0.01$, $P(+|D) = 0.95$, $P(+|D') = 0.05$. Find $P(+)$.", 3, "MEDIUM", "$0.95 \\cdot 0.01 + 0.05 \\cdot 0.99 = 0.0095 + 0.0495 = 0.059$.", "conditional-probability"),
    s("If $A \\subset B$, then $P(A | B) = $?", 2, "MEDIUM", "$P(A)/P(B)$.", "conditional-probability"),
    s("$P(A \\cap B) = 0.3$, $P(B | A) = 0.6$. Find $P(A)$.", 3, "HARD", "$P(A) = P(A \\cap B)/P(B | A) = 0.5$.", "conditional-probability"),
    s("If $P(\\bar A | B) = 0.3$, then $P(A | B) =$?", 2, "HARD", "$0.7$.", "conditional-probability"),
  ],
  "discrete-random-variables": [
    s("$X$ takes values $1, 2$ with prob $0.4, 0.6$. $E[X]$.", 1, "EASY", "$1(0.4) + 2(0.6) = 1.6$.", "discrete-random-variables"),
    s("Sum of probabilities for discrete RV must equal:", 1, "EASY", "$1$.", "discrete-random-variables"),
    s("If $\\text{Var}(X) = 16$, sd $=$?", 1, "EASY", "$4$.", "discrete-random-variables"),
    s("$E[2 X + 3]$ if $E[X] = 4$.", 2, "MEDIUM", "$2(4) + 3 = 11$.", "discrete-random-variables"),
    s("$\\text{Var}(3 X)$ if $\\text{Var}(X) = 2$.", 2, "MEDIUM", "$9 \\cdot 2 = 18$.", "discrete-random-variables"),
    s("If $E[X] = 5$, $E[X^2] = 30$, find $\\text{Var}(X)$.", 2, "MEDIUM", "$30 - 25 = 5$.", "discrete-random-variables"),
    s("$X$ binomial $n = 5, p = 0.3$. $E[X]$.", 2, "MEDIUM", "$1.5$.", "discrete-random-variables"),
    s("$P(X = k) = c k$ for $k = 1, 2, 3$. Find $c$.", 2, "MEDIUM", "$6 c = 1 \\Rightarrow c = 1/6$.", "discrete-random-variables"),
    s("$X$ uniform on $\\{1, 2, ..., 6\\}$. $E[X]$.", 2, "HARD", "$3.5$.", "discrete-random-variables"),
    s("$X$ binomial $n = 10, p = 0.5$. Find $P(X = 5)$ to 4 dp.", 3, "HARD", "$\\binom{10}{5}(0.5)^{10} = 252/1024 \\approx 0.2461$.", "discrete-random-variables"),
  ],
  "binomial-distribution": [
    s("$X \\sim \\text{Bin}(20, 0.5)$. $E[X]$.", 1, "EASY", "$10$.", "binomial-distribution"),
    s("$X \\sim \\text{Bin}(10, 0.2)$. $\\text{Var}(X)$.", 1, "EASY", "$10 \\cdot 0.2 \\cdot 0.8 = 1.6$.", "binomial-distribution"),
    s("$X \\sim \\text{Bin}(8, 0.5)$. $P(X = 0)$.", 1, "EASY", "$(0.5)^8 = 1/256$.", "binomial-distribution"),
    s("$X \\sim \\text{Bin}(3, 0.4)$. $P(X = 2)$ to 4 dp.", 2, "MEDIUM", "$3 \\cdot 0.16 \\cdot 0.6 = 0.288$.", "binomial-distribution"),
    s("$X \\sim \\text{Bin}(5, 0.3)$. Sd to 3 dp.", 2, "MEDIUM", "$\\sqrt{5 \\cdot 0.3 \\cdot 0.7} = \\sqrt{1.05} \\approx 1.025$.", "binomial-distribution"),
    s("$X \\sim \\text{Bin}(10, 0.5)$. $P(X \\geq 1)$.", 2, "MEDIUM", "$1 - (0.5)^{10} \\approx 0.999$.", "binomial-distribution"),
    s("If $E[X] = 6$ for $X \\sim \\text{Bin}(n, 0.3)$, $n = ?$", 2, "MEDIUM", "$n = 20$.", "binomial-distribution"),
    s("$X \\sim \\text{Bin}(4, 0.5)$. $P(X = 4)$.", 2, "MEDIUM", "$1/16$.", "binomial-distribution"),
    s("$X \\sim \\text{Bin}(6, 1/3)$. $P(X = 3)$ to 4 dp.", 3, "HARD", "$\\binom{6}{3}(1/3)^3(2/3)^3 = 20 \\cdot 1/27 \\cdot 8/27 = 160/729 \\approx 0.2195$.", "binomial-distribution"),
    s("Two dice; let $X = $ number of sixes. $E[X]$ and $\\text{Var}(X)$.", 3, "HARD", "$X \\sim \\text{Bin}(2, 1/6)$. $E = 1/3$, $\\text{Var} = 5/18$.", "binomial-distribution"),
  ],
  "continuous-random-variables": [
    s("For continuous $X$, $P(X = a) = $?", 1, "EASY", "$0$.", "continuous-random-variables"),
    s("$\\int_{-\\infty}^{\\infty} f(x) dx$ for valid pdf $=$?", 1, "EASY", "$1$.", "continuous-random-variables"),
    s("$X$ uniform on $[2, 8]$. Pdf $f(x)$.", 1, "EASY", "$1/6$ on $[2, 8]$.", "continuous-random-variables"),
    s("$X$ uniform on $[0, 4]$. $E[X]$.", 1, "EASY", "$2$.", "continuous-random-variables"),
    s("$X$ uniform on $[0, 4]$. $\\text{Var}(X)$.", 2, "MEDIUM", "$(4 - 0)^2/12 = 16/12 = 4/3$.", "continuous-random-variables"),
    s("If $f(x) = c$ on $[0, 5]$ is a pdf, $c = $?", 2, "MEDIUM", "$1/5$.", "continuous-random-variables"),
    s("$X$ has pdf $f(x) = 3 x^2$ on $[0, 1]$. $P(X \\leq 0.5)$.", 2, "MEDIUM", "$\\int_0^{0.5} 3 x^2 = [x^3]_0^{0.5} = 0.125$.", "continuous-random-variables"),
    s("$X$ has pdf $f(x) = 2 x$ on $[0, 1]$. $E[X]$.", 2, "MEDIUM", "$\\int_0^1 x \\cdot 2 x dx = 2/3$.", "continuous-random-variables"),
    s("$X$ has pdf $f(x) = 2 x$ on $[0, 1]$. Median.", 3, "HARD", "$\\int_0^m 2 x = m^2 = 1/2 \\Rightarrow m = 1/\\sqrt 2$.", "continuous-random-variables"),
    s("$X$ has pdf $f(x) = e^{-x}$ for $x \\geq 0$. Find $P(X > 2)$.", 3, "HARD", "$\\int_2^\\infty e^{-x} dx = e^{-2}$.", "continuous-random-variables"),
  ],
  "normal-distribution": [
    s("Standard normal mean and sd.", 1, "EASY", "$\\mu = 0$, $\\sigma = 1$.", "normal-distribution"),
    s("$P(Z < 0)$ for standard normal.", 1, "EASY", "$0.5$.", "normal-distribution"),
    s("$P(Z > 0)$.", 1, "EASY", "$0.5$.", "normal-distribution"),
    s("$X \\sim N(50, 100)$. State $\\mu$ and $\\sigma$.", 1, "EASY", "$\\mu = 50$, $\\sigma = 10$.", "normal-distribution"),
    s("$P(|Z| < 1)$ approximately.", 2, "MEDIUM", "$\\approx 0.6827$.", "normal-distribution"),
    s("Standardise: $X \\sim N(60, 25)$, find $z$ for $X = 70$.", 2, "MEDIUM", "$\\sigma = 5$; $z = 2$.", "normal-distribution"),
    s("$P(Z < 1.96)$ to 4 dp.", 2, "MEDIUM", "$\\approx 0.9750$.", "normal-distribution"),
    s("$P(Z > 2)$ to 4 dp.", 2, "MEDIUM", "$\\approx 0.0228$.", "normal-distribution"),
    s("$X \\sim N(100, 400)$. Find $P(X < 80)$, 4 dp.", 3, "HARD", "$\\sigma = 20$, $z = -1$. $\\approx 0.1587$.", "normal-distribution"),
    s("$P(Z < z) = 0.025$, find $z$.", 3, "HARD", "$z \\approx -1.96$.", "normal-distribution"),
  ],
  "confidence-intervals": [
    s("95% CI uses $z =$?", 1, "EASY", "$1.96$.", "confidence-intervals"),
    s("90% CI uses $z =$?", 1, "EASY", "$\\approx 1.645$.", "confidence-intervals"),
    s("$\\hat p = 0.4$, $n = 100$. Find SE.", 2, "EASY", "$\\sqrt{0.24/100} \\approx 0.049$.", "confidence-intervals"),
    s("Margin of error formula.", 1, "MEDIUM", "$z \\cdot \\text{SE}$.", "confidence-intervals"),
    s("$\\hat p = 0.5$, $n = 400$. 95% margin.", 2, "MEDIUM", "$1.96 \\sqrt{0.25/400} = 1.96 \\cdot 0.025 = 0.049$.", "confidence-intervals"),
    s("CI center is at:", 1, "MEDIUM", "$\\hat p$.", "confidence-intervals"),
    s("Construct 95% CI for $\\hat p = 0.6$, $n = 100$.", 3, "MEDIUM", "$0.6 \\pm 1.96(0.049) \\approx (0.504, 0.696)$.", "confidence-intervals"),
    s("To halve margin, multiply $n$ by:", 2, "MEDIUM", "$4$.", "confidence-intervals"),
    s("Min $n$ for 95% CI with margin $\\leq 0.05$, conservative $\\hat p = 0.5$.", 3, "HARD", "$n \\geq (1.96/0.05)^2 \\cdot 0.25 \\approx 385$.", "confidence-intervals"),
    s("Confidence level for $z = 2.576$.", 2, "HARD", "$99\\%$.", "confidence-intervals"),
  ],
  "sample-proportions-and-sampling": [
    s("$E[\\hat p] = ?$", 1, "EASY", "$p$.", "sample-proportions-and-sampling"),
    s("$\\text{Var}(\\hat p) = ?$", 1, "EASY", "$p(1 - p)/n$.", "sample-proportions-and-sampling"),
    s("$\\hat p$ for sample $X$ from $\\text{Bin}(n, p)$.", 1, "EASY", "$X/n$.", "sample-proportions-and-sampling"),
    s("$p = 0.5$, $n = 100$. Find sd of $\\hat p$.", 2, "MEDIUM", "$\\sqrt{0.25/100} = 0.05$.", "sample-proportions-and-sampling"),
    s("$p = 0.3$, $n = 100$. Find sd of $\\hat p$.", 2, "MEDIUM", "$\\sqrt{0.21/100} \\approx 0.0458$.", "sample-proportions-and-sampling"),
    s("As $n$ increases, sd of $\\hat p$:", 1, "MEDIUM", "decreases.", "sample-proportions-and-sampling"),
    s("$\\hat p$ approximately normal for large $n$ by:", 2, "MEDIUM", "CLT (Central Limit Theorem).", "sample-proportions-and-sampling"),
    s("Doubling $n$ changes sd by factor:", 2, "MEDIUM", "$1/\\sqrt 2$.", "sample-proportions-and-sampling"),
    s("$p = 0.5, n = 200$. Find $P(\\hat p > 0.55)$ to 4 dp.", 3, "HARD", "$z = 0.05/\\sqrt{0.25/200} \\approx 1.414$. $P \\approx 0.0786$.", "sample-proportions-and-sampling"),
    s("Sample size to achieve sd of $\\hat p \\leq 0.02$ when $p = 0.5$.", 3, "HARD", "$\\sqrt{0.25/n} \\leq 0.02 \\Rightarrow n \\geq 625$.", "sample-proportions-and-sampling"),
  ],
};

let total = 0;
for (const [slug, items] of Object.entries(SUBS)) {
  fs.writeFileSync(path.join(OUT_DIR, `qset-methods-w4-short-${slug}.json`),
    JSON.stringify({ mcq: [], shortAnswer: items, extendedAnswer: [], extendedResponse: [] }, null, 2) + "\n");
  console.log(`${slug}: ${items.length} SHORT`);
  total += items.length;
}
console.log(`Total: ${total} SHORT across ${Object.keys(SUBS).length} subtopics.`);
