/** Wave 2 batch 4: Data MCQ — 8 subtopics × 8 = 64 MCQ. */
import * as fs from "fs";
import * as path from "path";

const OUT_DIR = "scripts/output";

interface MCQ {
  content: string; optionA: string; optionB: string; optionC: string; optionD: string;
  correctOption: "A" | "B" | "C" | "D"; marks: number; difficulty: "EASY" | "MEDIUM" | "HARD";
  solutionContent: string; subtopicSlugs: string[];
}
const m = (c: string, o: [string, string, string, string], k: "A" | "B" | "C" | "D",
  d: "EASY" | "MEDIUM" | "HARD", s: string, p: string, sec: string[] = []): MCQ =>
  ({ content: c, optionA: o[0], optionB: o[1], optionC: o[2], optionD: o[3], correctOption: k, marks: 1, difficulty: d, solutionContent: s, subtopicSlugs: [p, ...sec] });

const SUBTOPICS: Record<string, MCQ[]> = {
  "probability-rules": [
    m("If $P(A) = 0.4$ and $A, B$ are mutually exclusive with $P(B) = 0.3$, then $P(A \\cup B) =$:",
      ["$0.12$", "$0.6$", "$0.7$", "$1$"], "C", "EASY",
      "Mutually exclusive: $P(A \\cup B) = P(A) + P(B) = 0.7$. **Answer: C**", "probability-rules"),
    m("$P(A')$ equals:",
      ["$P(A)$", "$1 - P(A)$", "$1 + P(A)$", "$P(A) - 1$"], "B", "EASY",
      "Complement rule. **Answer: B**", "probability-rules"),
    m("If $A$ and $B$ are independent with $P(A) = 0.5$ and $P(B) = 0.4$, then $P(A \\cap B) =$:",
      ["$0.9$", "$0.2$", "$0.1$", "$0.4$"], "B", "EASY",
      "Independent: $P(A) \\cdot P(B) = 0.20$. **Answer: B**", "probability-rules"),
    m("If $P(A) = 0.5$, $P(B) = 0.6$, $P(A \\cap B) = 0.2$, then $P(A \\cup B) =$:",
      ["$0.8$", "$0.9$", "$1.1$", "$0.3$"], "B", "MEDIUM",
      "Inclusion-exclusion: $0.5 + 0.6 - 0.2 = 0.9$. **Answer: B**", "probability-rules"),
    m("If $P(B \\mid A) = 0.6$ and $P(A) = 0.5$, then $P(A \\cap B) =$:",
      ["$0.3$", "$0.6$", "$1.1$", "$0.83$"], "A", "MEDIUM",
      "$P(A \\cap B) = P(B \\mid A) P(A) = 0.30$. **Answer: A**", "probability-rules"),
    m("Events $A$ and $B$ are independent if and only if:",
      ["$P(A \\cap B) = 0$", "$P(A) + P(B) = 1$", "$P(A \\cap B) = P(A) P(B)$", "$P(A) = P(B)$"], "C", "MEDIUM",
      "Definition. **Answer: C**", "probability-rules"),
    m("If $P(A) = 0.4$, $P(B) = 0.5$, and $A, B$ are independent, $P(A' \\cap B') =$:",
      ["$0.1$", "$0.3$", "$0.7$", "$0.9$"], "B", "HARD",
      "$P(A') P(B') = 0.6 \\times 0.5 = 0.30$. **Answer: B**", "probability-rules"),
    m("Drawing 2 cards from a 52-card deck without replacement, $P(\\text{both red}) =$:",
      ["$\\dfrac{1}{4}$", "$\\dfrac{25}{102}$", "$\\dfrac{1}{2}$", "$\\dfrac{1}{17}$"], "B", "HARD",
      "$\\dfrac{26}{52} \\cdot \\dfrac{25}{51} = \\dfrac{650}{2652} = \\dfrac{25}{102}$. **Answer: B**", "probability-rules"),
  ],
  "conditional-probability": [
    m("$P(A \\mid B) =$",
      ["$\\dfrac{P(A) P(B)}{P(A \\cap B)}$", "$\\dfrac{P(A \\cap B)}{P(B)}$", "$P(A) + P(B)$", "$\\dfrac{P(B)}{P(A)}$"], "B", "EASY",
      "Definition. **Answer: B**", "conditional-probability"),
    m("If $P(A \\cap B) = 0.2$ and $P(B) = 0.5$, then $P(A \\mid B) =$:",
      ["$0.1$", "$0.4$", "$0.7$", "$2.5$"], "B", "EASY",
      "$0.2/0.5 = 0.4$. **Answer: B**", "conditional-probability"),
    m("If $A$ and $B$ are independent, $P(A \\mid B)$ equals:",
      ["$P(B)$", "$P(A)$", "$P(A \\cap B)$", "$0$"], "B", "EASY",
      "Independence ⇒ $P(A \\mid B) = P(A)$. **Answer: B**", "conditional-probability"),
    m("If $P(A) = 0.3$, $P(B) = 0.5$, $P(A \\cap B) = 0.1$, then $P(B \\mid A) =$:",
      ["$\\dfrac{1}{5}$", "$\\dfrac{1}{3}$", "$\\dfrac{1}{2}$", "$0.6$"], "B", "MEDIUM",
      "$0.1/0.3 = 1/3$. **Answer: B**", "conditional-probability"),
    m("If $P(\\text{rain}) = 0.3$ and $P(\\text{late} \\mid \\text{rain}) = 0.7$, then $P(\\text{rain} \\cap \\text{late}) =$:",
      ["$0.21$", "$0.42$", "$1.0$", "$0.4$"], "A", "MEDIUM",
      "$0.3 \\times 0.7 = 0.21$. **Answer: A**", "conditional-probability"),
    m("In a class, 60% are girls; 30% of girls play sport, 50% of boys play sport. $P(\\text{plays sport}) =$:",
      ["$0.38$", "$0.4$", "$0.5$", "$0.8$"], "A", "MEDIUM",
      "$0.6 \\cdot 0.3 + 0.4 \\cdot 0.5 = 0.18 + 0.20 = 0.38$. **Answer: A**", "conditional-probability"),
    m("If $P(A) = 0.5$, $P(B \\mid A) = 0.4$, $P(B \\mid A') = 0.2$, then $P(B) =$:",
      ["$0.3$", "$0.5$", "$0.6$", "$0.8$"], "A", "HARD",
      "$0.5(0.4) + 0.5(0.2) = 0.30$. **Answer: A**", "conditional-probability"),
    m("With $P(A) = 0.5$, $P(B) = 0.3$ from prior question, $P(A \\mid B) =$:",
      ["$\\dfrac{1}{3}$", "$\\dfrac{2}{3}$", "$\\dfrac{1}{5}$", "$\\dfrac{1}{2}$"], "B", "HARD",
      "Bayes: $\\dfrac{0.5 \\cdot 0.4}{0.3} = \\dfrac{0.20}{0.30} = 2/3$. **Answer: B**", "conditional-probability"),
  ],
  "discrete-random-variables": [
    m("A discrete random variable's pmf values must:",
      ["sum to 0", "sum to 1", "be negative", "be at most 0.5"], "B", "EASY",
      "Probabilities sum to 1. **Answer: B**", "discrete-random-variables"),
    m("If $X$ takes values 1, 2, 3 with probabilities 0.2, 0.5, 0.3, then $P(X \\leq 2) =$:",
      ["$0.2$", "$0.5$", "$0.7$", "$1$"], "C", "EASY",
      "$0.2 + 0.5 = 0.7$. **Answer: C**", "discrete-random-variables"),
    m("$E[X]$ for the distribution above equals:",
      ["$2$", "$2.1$", "$2.5$", "$3$"], "B", "EASY",
      "$1(0.2) + 2(0.5) + 3(0.3) = 2.1$. **Answer: B**", "discrete-random-variables"),
    m("If $\\text{Var}(X) = 4$, then the standard deviation is:",
      ["$1$", "$2$", "$4$", "$16$"], "B", "MEDIUM",
      "Sd = $\\sqrt{\\text{Var}}$. **Answer: B**", "discrete-random-variables"),
    m("$E[2 X + 5]$ equals:",
      ["$2 E[X]$", "$2 E[X] + 5$", "$E[X] + 5$", "$2 E[X] - 5$"], "B", "MEDIUM",
      "Linearity. **Answer: B**", "discrete-random-variables"),
    m("$\\text{Var}(3 X)$ equals:",
      ["$3 \\text{Var}(X)$", "$9 \\text{Var}(X)$", "$\\text{Var}(X) + 9$", "$\\text{Var}(X)$"], "B", "MEDIUM",
      "$\\text{Var}(a X) = a^2 \\text{Var}(X)$. **Answer: B**", "discrete-random-variables"),
    m("$X$ has $E[X] = 5$ and $E[X^2] = 30$. Then $\\text{Var}(X) =$:",
      ["$25$", "$5$", "$30$", "$35$"], "B", "HARD",
      "$30 - 25 = 5$. **Answer: B**", "discrete-random-variables"),
    m("Let $Y = 2 X - 1$ where $\\text{Var}(X) = 3$. Then $\\text{Var}(Y) =$:",
      ["$3$", "$6$", "$12$", "$5$"], "C", "HARD",
      "$\\text{Var}(2 X - 1) = 4 \\text{Var}(X) = 12$. **Answer: C**", "discrete-random-variables"),
  ],
  "binomial-distribution": [
    m("$X \\sim \\text{Bin}(10, 0.5)$. Then $E[X] =$:",
      ["$0.5$", "$5$", "$10$", "$2.5$"], "B", "EASY",
      "$n p = 5$. **Answer: B**", "binomial-distribution"),
    m("$X \\sim \\text{Bin}(20, 0.3)$. Then $\\text{Var}(X) =$:",
      ["$2$", "$4.2$", "$6$", "$14$"], "B", "EASY",
      "$n p (1 - p) = 20(0.3)(0.7) = 4.2$. **Answer: B**", "binomial-distribution"),
    m("For $X \\sim \\text{Bin}(n, p)$, $P(X = k) =$:",
      ["$p^k (1-p)^{n-k}$", "$\\binom{n}{k} p^k (1-p)^{n-k}$", "$\\binom{n}{k} p^n$", "$n p^k$"], "B", "EASY",
      "Binomial probability formula. **Answer: B**", "binomial-distribution"),
    m("$X \\sim \\text{Bin}(5, 0.5)$. Then $P(X = 0) =$:",
      ["$0$", "$0.03125$", "$0.5$", "$0.5^4$"], "B", "MEDIUM",
      "$(0.5)^5 = 1/32 = 0.03125$. **Answer: B**", "binomial-distribution"),
    m("In 10 coin flips, $P(\\text{at least 1 head}) =$:",
      ["$0.5$", "$0.999$", "$1 - (0.5)^{10}$", "$10(0.5)$"], "C", "MEDIUM",
      "$1 - P(\\text{no heads}) = 1 - (0.5)^{10}$. **Answer: C**", "binomial-distribution"),
    m("$X \\sim \\text{Bin}(8, 0.25)$. Sd of $X$ is:",
      ["$\\sqrt{1.5}$", "$\\sqrt{2}$", "$\\sqrt{3}$", "$1.5$"], "A", "MEDIUM",
      "$n p(1-p) = 8(0.25)(0.75) = 1.5$. **Answer: A**", "binomial-distribution"),
    m("If $X \\sim \\text{Bin}(n, 0.2)$ and $E[X] = 4$, then $n =$:",
      ["$10$", "$15$", "$20$", "$25$"], "C", "HARD",
      "$0.2 n = 4 \\Rightarrow n = 20$. **Answer: C**", "binomial-distribution"),
    m("For large $n$, $\\text{Bin}(n, p)$ is approximated by:",
      ["uniform distribution", "exponential distribution", "normal distribution", "Poisson distribution"], "C", "HARD",
      "Normal approximation by the CLT. **Answer: C**", "binomial-distribution"),
  ],
  "continuous-random-variables": [
    m("For a continuous random variable, $P(X = c)$ equals:",
      ["$f(c)$", "$0$", "$1$", "$c$"], "B", "EASY",
      "Continuous: point probability is 0. **Answer: B**", "continuous-random-variables"),
    m("For a valid pdf $f$, $\\displaystyle\\int_{-\\infty}^{\\infty} f(x) dx =$",
      ["$0$", "$1$", "$\\infty$", "any value"], "B", "EASY",
      "Total probability is 1. **Answer: B**", "continuous-random-variables"),
    m("$P(a \\leq X \\leq b)$ equals:",
      ["$f(b) - f(a)$", "$F(a) - F(b)$", "$\\int_a^b f(x) dx$", "$f(a) + f(b)$"], "C", "EASY",
      "Integral of the pdf. **Answer: C**", "continuous-random-variables"),
    m("$E[X]$ for continuous $X$ with pdf $f$ equals:",
      ["$\\int x f(x) dx$", "$\\int f(x) dx$", "$\\int x dx$", "$\\sum x f(x)$"], "A", "MEDIUM",
      "Expectation formula. **Answer: A**", "continuous-random-variables"),
    m("If $f(x) = c$ on $[0, 4]$ is a valid pdf, then $c =$:",
      ["$\\dfrac{1}{4}$", "$1$", "$4$", "$\\dfrac{1}{2}$"], "A", "MEDIUM",
      "$\\int_0^4 c dx = 4 c = 1 \\Rightarrow c = 1/4$. **Answer: A**", "continuous-random-variables"),
    m("For uniform $X$ on $[0, 4]$, $E[X] =$:",
      ["$2$", "$4$", "$\\dfrac{1}{4}$", "$\\dfrac{4}{3}$"], "A", "MEDIUM",
      "Midpoint. **Answer: A**", "continuous-random-variables"),
    m("If $f(x) = 2 x$ on $[0, 1]$ is a pdf, then $E[X] =$:",
      ["$\\dfrac{1}{3}$", "$\\dfrac{1}{2}$", "$\\dfrac{2}{3}$", "$1$"], "C", "HARD",
      "$\\int_0^1 x \\cdot 2 x dx = [2 x^3/3]_0^1 = 2/3$. **Answer: C**", "continuous-random-variables"),
    m("If $X$ has cdf $F$, then the median satisfies:",
      ["$F(m) = m/2$", "$F(m) = 0$", "$F(m) = 0.5$", "$F(m) = 1$"], "C", "HARD",
      "Median splits probability in half. **Answer: C**", "continuous-random-variables"),
  ],
  "normal-distribution": [
    m("For $X \\sim N(\\mu, \\sigma^2)$, $P(X < \\mu)$ equals:",
      ["$0.5$", "$0$", "$1$", "$\\sigma$"], "A", "EASY",
      "Symmetry about the mean. **Answer: A**", "normal-distribution"),
    m("For standard normal $Z$, $P(Z < 0)$ equals:",
      ["$0$", "$0.5$", "$1$", "$0.3413$"], "B", "EASY",
      "Symmetric about 0. **Answer: B**", "normal-distribution"),
    m("Approximately, $P(\\mu - \\sigma < X < \\mu + \\sigma) =$:",
      ["$50\\%$", "$68\\%$", "$95\\%$", "$99.7\\%$"], "B", "EASY",
      "68-95-99.7 rule. **Answer: B**", "normal-distribution"),
    m("If $X \\sim N(50, 100)$, then $P(40 < X < 60)$ is approximately:",
      ["$50\\%$", "$68\\%$", "$95\\%$", "$99.7\\%$"], "B", "MEDIUM",
      "$\\sigma = 10$; range is mean ± 1 sd. **Answer: B**", "normal-distribution"),
    m("If $X \\sim N(0, 1)$ and $P(Z < z) = 0.95$, then $z \\approx$:",
      ["$1.0$", "$1.645$", "$1.96$", "$2.0$"], "B", "MEDIUM",
      "95th percentile of standard normal. **Answer: B**", "normal-distribution"),
    m("$P(Z > 1.96)$ approximately equals:",
      ["$0.05$", "$0.025$", "$0.5$", "$0.975$"], "B", "MEDIUM",
      "Upper tail beyond 1.96 is about 2.5%. **Answer: B**", "normal-distribution"),
    m("Standardise: if $X \\sim N(20, 25)$ and we want $P(X > 27)$, the $Z$-value is:",
      ["$\\dfrac{27}{20}$", "$1.4$", "$\\dfrac{7}{5}$", "Both B and C"], "D", "HARD",
      "$Z = (27 - 20)/5 = 7/5 = 1.4$. **Answer: D**", "normal-distribution"),
    m("If $X \\sim N(\\mu, \\sigma^2)$ and $P(X < a) = 0.16$, then $a \\approx$:",
      ["$\\mu - 2\\sigma$", "$\\mu - \\sigma$", "$\\mu$", "$\\mu + \\sigma$"], "B", "HARD",
      "$P(Z < -1) \\approx 0.16$, so $a = \\mu - \\sigma$. **Answer: B**", "normal-distribution"),
  ],
  "confidence-intervals": [
    m("The standard $z$-value for a 95% CI is approximately:",
      ["$1.645$", "$1.96$", "$2.0$", "$2.576$"], "B", "EASY",
      "$z_{0.025} = 1.96$. **Answer: B**", "confidence-intervals"),
    m("A 95% CI for $p$ is given by $\\hat p \\pm 1.96 \\text{SE}$ where SE =",
      ["$\\hat p(1 - \\hat p)$", "$\\sqrt{\\hat p(1-\\hat p)/n}$", "$\\sqrt{n \\hat p(1-\\hat p)}$", "$1/\\sqrt n$"], "B", "EASY",
      "Standard error of sample proportion. **Answer: B**", "confidence-intervals"),
    m("Increasing $n$ (sample size) makes the CI:",
      ["wider", "narrower", "unchanged", "centred at 0"], "B", "EASY",
      "$\\text{SE} \\propto 1/\\sqrt n$. **Answer: B**", "confidence-intervals"),
    m("A 99% CI vs a 95% CI is:",
      ["narrower", "wider", "the same", "depends on data"], "B", "MEDIUM",
      "Higher confidence ⇒ wider interval. **Answer: B**", "confidence-intervals"),
    m("If $n = 100$, $\\hat p = 0.6$, SE $\\approx$:",
      ["$0.049$", "$0.24$", "$0.6$", "$0.6/100$"], "A", "MEDIUM",
      "$\\sqrt{0.24/100} \\approx 0.049$. **Answer: A**", "confidence-intervals"),
    m("95% CI with $\\hat p = 0.6$ and SE $= 0.05$ is approximately:",
      ["$(0.5, 0.7)$", "$(0.55, 0.65)$", "$(0.50, 0.70)$", "$(0.60 \\pm 0.05)$"], "A", "MEDIUM",
      "$0.6 \\pm 1.96 \\times 0.05 \\approx 0.6 \\pm 0.098$. **Answer: A**", "confidence-intervals"),
    m("Doubling $n$ reduces the margin of error by a factor of approximately:",
      ["$2$", "$\\sqrt 2$", "$4$", "$\\dfrac{1}{2}$"], "B", "HARD",
      "SE $\\propto 1/\\sqrt n$. **Answer: B**", "confidence-intervals"),
    m("The CI does NOT contain the true $p$ with probability:",
      ["$\\alpha$ (e.g. 5%)", "0", "1", "always 50%"], "A", "HARD",
      "For a $1 - \\alpha$ CI, $\\alpha$ is the chance of missing. **Answer: A**", "confidence-intervals"),
  ],
  "sample-proportions-and-sampling": [
    m("The sample proportion $\\hat p$ is calculated as:",
      ["$X/n$", "$n/X$", "$X - n$", "$\\sqrt{X n}$"], "A", "EASY",
      "Number of successes over sample size. **Answer: A**", "sample-proportions-and-sampling"),
    m("$E[\\hat p]$ equals:",
      ["$\\dfrac{p}{n}$", "$p$", "$n p$", "$1 - p$"], "B", "EASY",
      "Sample proportion is unbiased for $p$. **Answer: B**", "sample-proportions-and-sampling"),
    m("Variance of $\\hat p$ is:",
      ["$p(1 - p)$", "$\\dfrac{p(1 - p)}{n}$", "$n p(1 - p)$", "$\\dfrac{1}{n}$"], "B", "EASY",
      "$\\text{Var}(X/n) = \\text{Var}(X)/n^2$ with $X \\sim \\text{Bin}(n, p)$. **Answer: B**", "sample-proportions-and-sampling"),
    m("For large $n$, $\\hat p$ is approximately:",
      ["uniform", "normal", "binomial", "Poisson"], "B", "MEDIUM",
      "CLT. **Answer: B**", "sample-proportions-and-sampling"),
    m("If $n = 400$ and $p = 0.5$, the standard deviation of $\\hat p$ is:",
      ["$0.025$", "$0.05$", "$0.1$", "$0.5$"], "A", "MEDIUM",
      "$\\sqrt{0.25/400} = 0.025$. **Answer: A**", "sample-proportions-and-sampling"),
    m("Quadrupling $n$ changes the SE of $\\hat p$ by factor:",
      ["$1/4$", "$1/2$", "$2$", "$4$"], "B", "MEDIUM",
      "$1/\\sqrt 4 = 1/2$. **Answer: B**", "sample-proportions-and-sampling"),
    m("If true $p = 0.4$ and we observe $\\hat p = 0.45$ in $n = 100$, the $z$-statistic is:",
      ["$0.5$", "$1.02$", "$1.96$", "$5$"], "B", "HARD",
      "SE $= \\sqrt{0.4 \\cdot 0.6/100} = 0.049$; $z = 0.05/0.049 \\approx 1.02$. **Answer: B**", "sample-proportions-and-sampling"),
    m("A simple random sample of size 100 from a large population provides a sampling distribution of $\\hat p$ that is approximately normal with mean $p$ provided:",
      ["the population is normal", "$n p \\geq 10$ and $n(1-p) \\geq 10$", "$p = 0.5$", "$n > 1000$"], "B", "HARD",
      "Standard rule-of-thumb for normal approximation. **Answer: B**", "sample-proportions-and-sampling"),
  ],
};

for (const [slug, mcqs] of Object.entries(SUBTOPICS)) {
  fs.writeFileSync(path.join(OUT_DIR, `qset-methods-w2-${slug}.json`),
    JSON.stringify({ mcq: mcqs, shortAnswer: [], extendedAnswer: [], extendedResponse: [] }, null, 2) + "\n");
  console.log(`${slug}: ${mcqs.length} MCQ`);
}
console.log(`Total: ${Object.values(SUBTOPICS).reduce((s, a) => s + a.length, 0)} MCQ.`);
